### ISSUE TITLE
Saving Quests Doesn't Work

### ISSUE THREAD

**Issue by ungermum** [FlyingPikachu/Quests#1]
When you use the option "Break block" don't save quests(version::Quests-2.8.4). Pls, Fix that

**Comment by FlyingPikachu** [comment]
@ungermum Provide your quests.yml file, or an example quest, for testing.

**Comment by FlyingPikachu** [comment]
@ungermum Version 2.8.6 should resolve this issue. If you still experience issues, you may need to manually add block durability for affected quests. Post your quests.yml if you would like assistance. Thanks!
