### ISSUE TITLE
Remove-item true not working on requirements.

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#100]
I put a custom item requirement and I set it to be removed when you take the Quest, yet the item doesn't actually get removed.

This is my quests config - http://pastebin.com/EDbsi1bw

Update: This only didn't work because when I loaded the item required in the in-game editor, the &6&k* in the name of the paper didn't actually register as that, so I tried it without that symbol and star at the end and it worked. So just an FYI that the Quests Editor doesn't actually recognise the colour and the &k magic symbols.

**Comment by FlyingPikachu** [comment]
I may be able to add support for such special characters in the future, but for now simply avoid those symbols.
