### ISSUE TITLE
Quest won´t Load, no proper location format

### ISSUE THREAD

**Issue by Paddygre** [FlyingPikachu/Quests#100]
_(__Required__) What is your Quests version / build number (do _not_ say "latest")?_
using the Quest 3.0.0-Naomi.jar from Aug 5, 2017

_(__Required__) Please describe the problem and how to replicate it. Any console errors?_
The Quest will not Load in to the Game... although it is created with the inGame editor, the Console error is:

**[01:59:59 ERROR]: [Quests] Neue Welt -3103.0 96.0 -967.0 inside mobs-to-kill: inside Stage 1 of Quest Regeln lesen is not in proper location format!
[01:59:59 ERROR]: [Quests] Proper location format is: "WorldName x y z"**

is it because the world has a space between the two words of the world name? quests are still working in our Farmworld (named: farmworld) 

_(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?_
https://pastebin.com/KAvnFbjv

**Comment by FlyingPikachu** [comment]
You are correct, this is caused by the space within the worldName. The commit that follows (and associated dev build) should fix this. Thanks for the report!
