### ISSUE TITLE
'Talk-To-NPC' Quests giving 'No more Quests available' msg.

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#101]
Basically what the title says, when there is a 'Talk to NPC' Quest stage, when you right click on the NPC, the 'No more quests available.' message pops up in the chat, can just be a bit annoying and maybe confusing for some players, can this be fixed?

**Comment by FlyingPikachu** [comment]
Already fixed in https://github.com/FlyingPikachu/Quests/commit/a7d6ea8885c6eca89c67a438433844a74ffd06ce
