### ISSUE TITLE
Item names in quest editor

### ISSUE THREAD

**Issue by Novy93** [FlyingPikachu/Quests#101]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.0.0-Naomi.jar

(__Required__) Please describe the problem and how to replicate it. Any console errors?
I wanted to add a reward item, by name. In Minecraft it's "Diamond Shovel", but quest editor accept only "Diamond Spade". Not a big deal, but also Lapis Lazuli is as "Inc Sack:4"

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Not really, i am in the middle of create this quest.

**Comment by FlyingPikachu** [comment]
Per the Wiki, this is intentional as we check against the Material enum. There are no plans to add additional checks at this time, but thanks for your report!

https://github.com/FlyingPikachu/Quests/wiki/Item-Formatting
