### ISSUE TITLE
Killing an NPC with a Bow and Arrow not registering.

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#102]
As the title says, I have a Kill NPC quest and it has to be done with a bow and arrow, but when you kill the NPC with a bow and arrow, it doesn't register so this means that I can't do this quest whatsoever. Can you fix this soon please?

**Comment by FlyingPikachu** [comment]
Please explain further. Does the NPC take damage?

**Comment by whoshenry** [comment]
Yes, they take damage and they die but Quests doesn't recognise that you killed the NPC. Only works when you kill an NPC with a sword.

**Comment by Leescar** [comment]
There was a similar issue a while back with kill mob stage issue #10 and was fixed by the PR #15 
The PR might only be listening for entitymobdeath event I think

**Comment by GreenFlagCZ** [comment]
In version 1.9.0 worked fine... After 2.1.0 killing mobs and NPCs do not confirm kill in quest log. In version 2.4.0 only NPCs cant kill with bow.

**Comment by whoshenry** [comment]
Yes, any further information about this issue?

**Comment by FlyingPikachu** [comment]
Please post an example quest for testing.

**Comment by whoshenry** [comment]
Well this is just any NPC-To-Kill Quest... But here's one I just made quickly for you.

http://pastebin.com/vUqv4axb

Just try killing the NPC with a bow, doesn't register.

**Comment by whoshenry** [comment]
Also @FlyingPikachu I guess you're going through the issues now, can you please make sure you look at  #57 please, it's a big issue.
