### ISSUE TITLE
Kill players stage allow suicide

### ISSUE THREAD

**Issue by Novy93** [FlyingPikachu/Quests#103]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.0.0-Naomi.jar

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Stages, Kill Players - this one count suicide as well... Shouldnt work like that.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
Duplicate of #96
