### ISSUE TITLE
Latest Dev Version (#74) Right Click NPC Error

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#103]
Get this error in the console when I right click an NPC to finish a stage.

http://pastebin.com/y6DvQni8

Update: I found that this was an issue with capitalisation with the enchantnemt and the Reward item given. I did enchantment-unbreaking 10 instead of enchantment-Unbreaking 10. 

Maybe this should be pointed out as an error when doing /questsadmin reload, something like incorrect enchantment on item reward? Make it easy for players to configure this properly.

**Comment by FlyingPikachu** [comment]
I see no-one was able to resolve your issue. If this is still a problem, please create a new ticket. Thanks!
