### ISSUE TITLE
Quest bugs and issues

### ISSUE THREAD

**Issue by iMaartennn** [FlyingPikachu/Quests#104]
1. Delivering items to accepting NPCs
When right-clicking an NPC to deliver an item to, the NPC doesn't accept the 
item. Nothing happens. Occasionally works, occasionally doesn't. Sometimes works
when player is crouching, and when player's hunger bar is full. 

2. Delivery brings up quest menu
When giving an NPC items, instead of taking it, the NPC brings up the quest
menu again ( like this: http://gyazo.com/8e28001e60a89b38e4fa3b906ff79468 )

**Comment by Neoblade298** [comment]
This may be because you have 2 quests that both require you to turn items into the NPC. That's what I have anyway. Is it that?

**Comment by FlyingPikachu** [comment]
Please upload your quests.yml and note the quests involved.

**Comment by Formula350** [comment]
Yea, issue 1 sounds just like the "player has 2 quests" bug that so many of us experience.

Not sure about issue 2, but I speculate perhaps to do with the the above issue, which is not recognizing the item as wanting to be delivered; thus, is qualifying it as an attempt at taking one of the other quests that NPC is offering. 
@iMaartennn Doubtful this will help, but perhaps set up the other quests with the Quest Prerequisite of having completed the previous stage first? For example, Part 2 will not show up if Part 1 is not completed, same goes for Part 3.

**Comment by FlyingPikachu** [comment]
Bug #57 (mentioned earlier) may have been related to this issue and has since been resolved. Please update to at least this dev build and check if it resolves the issue.

http://ci.ac3-servers.eu/job/Quests/81/

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
