### ISSUE TITLE
Saving data issue

### ISSUE THREAD

**Issue by Eiffelrose** [FlyingPikachu/Quests#105]
Version: Quests 3.0.0-Naomi 
Whats wrong:
[Quests] Could not save data.​yml to plugins/Quests/data.​yml because data.​yml already exists.​
[Quests] Could not save events.​yml to plugins/Quests/events.​yml because events.​yml already exists.​
[Quests] Could not save quests.​yml to plugins/Quests/quests.​yml because quests.​yml already exists.​

I don't have any quests made yet. Running Minecraft version: Spigot 1.12.1

**Comment by FlyingPikachu** [comment]
This is not an error; simply a notice that those files weren't created because they already exist. They can be ignored.
