### ISSUE TITLE
Getting kicked whenever I accept a quest.

### ISSUE THREAD

**Issue by Legendaryx** [FlyingPikachu/Quests#106]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?

When Accepting a quest from an npc. (happens with every quest)

Getting kicked with this error:
[06:33:08] [Server thread/INFO]: Title command successfully executed
[06:33:08] [Server thread/INFO]: Title command successfully executed
[06:33:08] [Server thread/INFO]: LeGenDaryX lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

This is what is shown in my minecraft client: 
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 63

**Comment by Legendaryx** [comment]
This doesnt happen on Quests 2.9

**Comment by Legendaryx** [comment]
Does Quests 3 use titles on quest accept and quest completion ? Because im having issues with titles kicking players.

**Comment by SXRWahrheit** [comment]
@Legendaryx Yes, by default, titles are enabled. You can disable them in the config.

**Comment by FlyingPikachu** [comment]
@Legendaryx In the event that your quests.yml does not contain the "show-titles" option, simply add it as seen in the link below, or regenerate your config.

https://github.com/FlyingPikachu/Quests/wiki/Configuration

Keeping this open until I determine the reason for kick.

**Comment by Legendaryx** [comment]
Yeah somehow whenever I updated to minecraft 1.12. Title plugins kick my players.

Any suggestions what it could be ?

**Comment by FlyingPikachu** [comment]
You're saying all title plugins kick players? Do you have any anti-cheat plugins, or are you using an alternative like PaperSpigot?

**Comment by SXRWahrheit** [comment]
It looks like this is happening on my server as well; the issue is it causes a timeout. Not sure why. I'm on Spigot.

**Comment by FlyingPikachu** [comment]
Found this - https://www.spigotmc.org/threads/nativeioexception-syscall-read-failed-connection-reset-by-peer.185413/

@Legendaryx Seems it's most likely you're using BungeeCord? It may be possible that the way Quests is sending titles is not compatible with BungeeCord. Waiting on confirmation before I proceed further.

**Comment by SXRWahrheit** [comment]
No BungeeCord here, just Spigot. When I disabled titles we didn't have any more problems.

**Comment by FlyingPikachu** [comment]
@SXRWahrheit Interesting. Suppose it's possible you could have experienced a separate, albeit similar, bug.  Unlikely as that is, I'd like to hear from @Legendaryx before I proceed.

**Comment by Legendaryx** [comment]
I do have bungeecord but it looks like a different issue. 

I do want to make clear that I have this issue with every plugin that sends a title.

**Comment by FlyingPikachu** [comment]
@Legendaryx Caulking this up as a Bungeecord issue. I am unable to assist you further, but have taken the liberty of opening an issue on your behalf - https://github.com/SpigotMC/BungeeCord/issues/2232
