### ISSUE TITLE
Level Requirement

### ISSUE THREAD

**Issue by budopey** [FlyingPikachu/Quests#106]
Not really an issue, more of a request to add level requirement for picking up Quests.

**Comment by FlyingPikachu** [comment]
What sort of level? Enchantment level? McMMO level?

Perhaps you could use Quest Points?

**Comment by budopey** [comment]
Never mind, mcmmo is garbage for lame servers with lazy admins. Servers with it installed are totally lame and a waste of time... Quest points won't work for control of quest level brackets. A server with a class system and dungeons by mob levels would need player level requirements. I assume that would use enchanting level? Yeah forget it.

**Comment by Neoblade298** [comment]
I'm really not sure what kind of tone of voice you have here, but you sound like a dick the way I'm reading it. A simple "enchanting level" would be fine.

**Comment by Leescar** [comment]
There is a way to implement a level system by awards heroes xp to player and using the heroes plugin and just building your quests to ramp with quest points, if you want mobs of varying levels based on number of players there is a plugin called mythicmobs which does this find, however both of those pluins needs a high level or understanding to use to its full potential, you can use it without understanding much but your going to be terrible and unfun.

**Comment by budopey** [comment]
If it were as simple as an enchanting level why would he need to ask? Your useless comment makes you any less of a dick... Heroes? LOL Kainzo is a content stealing twat! His plugin is trash and he takes forever to update it. By the time it gets updated its already obsolete! I already know how to use MythicMobs but that doesn't help with level requirements for Quests. I'm closing this since people like Neo are starting to make useless comments on it and getting butt hurt. I could care less how you read my tone honestly.

**Comment by Neoblade298** [comment]
o wat a rood dood

**Comment by budopey** [comment]
Well dick face, I was only saying forget it because it wasn't that important to begin with, just thought it would make things a lil easier. I'm not trying to bug flyingpikachu with something complicated but not really important compared to other stuff he could be implementing. That is why I said forget it because XP level handling can be done so many different ways it would be a hassle to make compatibility with numerous other plugins that handle the XP leveling system. I am using LegendQuest by the way if you want to look into how it handles the leveling system and possibly add support to Quests for it so Races/Classes of LegendQuest can benefit from Quests.

**Comment by budopey** [comment]
Can you do that Neo? If not why are you commenting on this? You are uselessly interrupting and being a rude twat! End of story. Good day sir!

**Comment by Neoblade298** [comment]
yo bro chiiilll, we got off on the wrong foot
