### ISSUE TITLE
[Request] Re-add quest limit

### ISSUE THREAD

**Issue by Neoblade298** [FlyingPikachu/Quests#108]
Hi, on Blackvein's quest plugin, there was a config option where you could limit the amount of quests a player could have at one time. Could you reimplement that? Or is it already somehow implemented? Because currently my config file shows nothing on that.

(On an unrelated note, I noticed there were various options for quests parties. Is that an upcoming feature or is it already implemented?)

**Comment by Leescar** [comment]
Inside the config.yml file there is a line 
max-quests: 5
Is mine limiting the max at the same time to five.

**Comment by FlyingPikachu** [comment]
As @Leescar noted, this is already present.
