### ISSUE TITLE
Heroes Secondary Class doesn't register.

### ISSUE THREAD

**Issue by dufflad007** [FlyingPikachu/Quests#109]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
2.7.4-b118
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I have a quest that requires you to have a secondary class (alchemist) to take. Even with the secondary class being used on the player, they are denied the quest. I know I've had problems with this in the past, and I can't seem to find a solution to the problem.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/Ah59v06u

**Comment by FlyingPikachu** [comment]
I do intend to look into this, but seeing as I personally know little about the Heroes plugin, this may take me a while. Marking as "help wanted"

**Comment by dufflad007** [comment]
The Primary class works just fine, but secondary doesn't want to work. Thanks for your interest on it!

**Comment by FlyingPikachu** [comment]
@dufflad007 Taking a quick look and have several questions for you:

1. What is your Heroes version?
2. Do you see any Quests warnings/errors when starting your server?
3. Can you provide a quest in which the primary class is working?

**Comment by FlyingPikachu** [comment]
The fix applied just now will be available in a dev build at the link below:

http://ci.ac3-servers.eu/job/Quests/225/

However, it is entirely untested. This issue is being closed due to lack of response from OP and community. Should the problem persist, comment below or open a new issue referencing this one.
