### ISSUE TITLE
Save Quests Not Functioning - Updated

### ISSUE THREAD

**Issue by mecray** [FlyingPikachu/Quests#11]
Hey -

I'm using the Quests plugin on the version **2.8.6-b132** (pictured below).
![quests-version](https://user-images.githubusercontent.com/28368412/27512456-5ede496a-590e-11e7-850a-b22d7d1a1c73.PNG)

When I attempt to save a Quest (that is has all needed arguments filled out), it is unresponsive in-game and gives me this error in the console -
``
24.06 19:02:00 [Server] ERROR Error handling conversation prompt
24.06 19:02:00 [Server] INFO java.lang.NullPointerException: null
24.06 19:02:00 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1036) ~[?:?]
24.06 19:02:00 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1038) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1234) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
24.06 19:02:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
``
In my last issue, you mentioned that I should replicate the issue. Can you please clarify what that means? I'm sorry if I'm being a pain.

Thanks
- meCray

**Comment by FlyingPikachu** [comment]
@mecray Thanks for opening a new issue. By "replicate" I would've meant reproducing the error in the requested version, in this case 2.8.6-b132

So as long as the error you've posted was made in 2.8.6-b132, we can proceed.

**Comment by mecray** [comment]
Yep, the mentioned issue is in the version mentioned above. Is this a bug or or is it something that has to do with my server?

**Comment by FlyingPikachu** [comment]
Uncertain but likely a bug. Which sort of quest were you attempting to make?

**Comment by mecray** [comment]
I was trying to make a quest where a player has to go in a certain area and right click and npc, and then go back and click another npc.

**Comment by FlyingPikachu** [comment]
@mecray I just created a quest with a Talk to NPCs objective and was able to complete it without problem.

Could you precisely detail the steps you're taking to produce the error?

**Comment by mecray** [comment]
Just for this example, I created a test quest. When all of the required fields were filled out, it gave me this error -
`26.06 23:29:08 [Server] ERROR Error handling conversation prompt
26.06 23:29:08 [Server] INFO java.lang.NullPointerException: null
26.06 23:29:08 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1036) ~[?:?]
26.06 23:29:08 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1038) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1234) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
26.06 23:29:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

Here's my configuration -
![sff](https://user-images.githubusercontent.com/28368412/27569843-c4d34698-5ac7-11e7-955e-c8c392844774.PNG)

Am I missing something? It happens with any quest I create.

**Comment by FlyingPikachu** [comment]
@mecray I just created a quest using your configuration without issue (same name, ask/finish msgs, and display item). No errors.

Sorry to ask this, but at this point I need a step-by-step of how you're setting this up. It could be that taking steps in a particular order is causing the issue. If you could, please walk me through your process being as detailed as possible.

**Comment by mecray** [comment]
@FlyingPikachu Do you think there might be some plugin that is causing this?

**Comment by FlyingPikachu** [comment]
@mecray Unlikely, but not impossible.

**Comment by mecray** [comment]
My Plugins -
- AnimationLib
- AutoRestart
- Blacksmith
- ChatEx
- Citizens
- CommandNPC
- CorpseReborn
- CratesPlus
- Essentials
- HolographicDisplays
- PermissionsEx
- PhatLoots
- PhysicsToGo
- PlaceholderAPI
- ProtocolLib
- Quests
- SuperVanish
- UltimateBossBar
- Vault
- VoxelSniper
- WorldEdit & WorldGuard

Sorry for the long list.

**Comment by mecray** [comment]
I just found out my config was corrupted, and thats why it was giving me errors. I reset the config and now the Quests are functioning. Thanks for your help :D
