### ISSUE TITLE
Item name set in various stage goals not working.

### ISSUE THREAD

**Issue by Leescar** [FlyingPikachu/Quests#11]
Under stages the following stage goals will not work and will not accept item names such as dirt stone or item id numbers. 
These stages do not have a load item from hand option either and seemingly are asking for the item name as though you are setting the item goal.

Evidence of the issue is attempting to finish the sample quest "Stone miner" as the quest is asking one to break dirt?
The stages are:
--1 - Break blocks
--2 - Damage blocks
--3 - place blocks
--4 - Use blocks
--5 - Cut blocks
--8 - Enchant items

No errors in console

**Comment by FlyingPikachu** [comment]
What response do you get in chat when submit an item name (do not use id numbers)? A screenshot would be perfect.

**Comment by Leescar** [comment]
Alright got you 
![2015-02-12_04 25 34](https://cloud.githubusercontent.com/assets/10955493/6198154/18d53772-b3ba-11e4-9f61-23d460a53d63.png)
Response when attempting to set up enchantment item names

![2015-02-12_04 25 34](https://cloud.githubusercontent.com/assets/10955493/6198163/3275fa36-b3ba-11e4-8f3d-c8733acb5b50.png)
Response for set name on 1-5
(basically the same each time for break, damage, place, use, cut)

On a side note apologies for submitting so many things,
 I'm just really excited to use this plugin to its fullest extent.
 As well I wanted to ask about the command usage feature in events? 
Limited to vanilla commands or a way to get it to fire off something from another plugin.
Apologies I know its not related to this but I didn't want to add another issue when its my issue not knowing, not the plugin.

**Comment by FlyingPikachu** [comment]
Fixed in Quests 2.2.1. Thanks!
