### ISSUE TITLE
Tip! Scoreboard Requirement

### ISSUE THREAD

**Issue by HrMoritz** [FlyingPikachu/Quests#111]
v: 3.0.0

I dont have any Issue with the plugin. I just wanted to say that a scoreboard requirement would be really usefull!
For example: I want only players, who have the value of the scoreboard "test" on 1 ,to be able to accept a Quest. This could add many different Requirements with not much coding. You could test Players on a specific armor and only with that armor they can accept Quests.
I love this plugin really much and I´d really appreciate it if you could add this Feature as soon as you can. It would make the Plugin the perfect QuestPlugin for me

**Comment by FlyingPikachu** [comment]
This sounds like it could be used intuitively, however not all scoreboards are used to keep score (see mcMMO's level tracking). I feel we may have to account for all the ways in which scoreboards can be used, which is rather challenging. Open to ideas on how to implement scoreboards seamlessly.

**Comment by HrMoritz** [comment]
it would just be awesome if you could have a requirement of a scoreboard as the type dummy. I only want to use the normal scoreboard system by minecraft and not use any scores of other plugins

**Comment by HrMoritz** [comment]
it would just be awesome if you could have a requirement of a scoreboard as the type dummy. I only want to use the normal scoreboard system by minecraft and not use any scores of other plugins

**Comment by FlyingPikachu** [comment]
Restricting a scoreboard to the 'dummy' type sounds easier, but certainly others may wish to use other types. Seeing as there are so many potential uses of scoreboards, it may be best to leave this to custom requirements (see [API](https://github.com/FlyingPikachu/Quests/wiki/Quests-API)). Will leave this open for a bit longer pending more ideas.

**Comment by FlyingPikachu** [comment]
After playing around with scoreboards, it goes without saying that there are near infinite possibilities of what scoreboard values can represent (points, linear order, skill levels, teams, et al.). Furthermore, there are factors like how often is the scoreboard updated, what type of board it is (i.e. 'dummy'), not to mention what the strings say/do, that make this type of requirement endlessly customization.

There is no way, that I can see, to provide the level of configurability that a requirement like this would _need_, so I believe it's safe to say leaving this to custom requirements is the way to go.
