### ISSUE TITLE
Save Issue when edit a quest

### ISSUE THREAD

**Issue by sumdream** [FlyingPikachu/Quests#113]
Hi, Im have problem need your help!
When I save a finished editing quests,the console while output this error:
http://pastebin.com/GSsVEyZt
Im Chinese user,and there a lot of Chinese characters in the quests.yml.
Forgive my poor English.

**Comment by Leescar** [comment]
Can you pastebin both your quests.yml and config.yml please?

**Comment by CarterBradly** [comment]
I have the same issue.

**Comment by sumdream** [comment]
Here is the quests.yml and config.yml
quests.yml http://pastebin.com/ZKtbYMCN
config.yml http://pastebin.com/hAufHS5G
I could editor quests,but I couldn't save the quests.
THX:)

**Comment by Leescar** [comment]
I'm not seeing why it won't let you save. 
Try running the command /questsadmin reload and seeing if any errors come up in console, because I'm not seeing that error

**Comment by sumdream** [comment]
You could edit the quests '[职业]格斗的真谛',add a GUI display or other something ,and save it.You wil see it:)
THX:)

**Comment by Leescar** [comment]
It might be because of the special characters from using Chinese text and having the configuration set to English. Like hello would have to be Ni hao spelled out instead of the characters

**Comment by sumdream** [comment]
All right,I will test it without special characters.And I will report it later.Thanks a lot:)

**Comment by sumdream** [comment]
Hi~I just test something about this error.I find that The color code ''&'' caused this problem.quests does not suppot color code.

**Comment by Leescar** [comment]
Is supposed to support color codes with &, which place did the & symbol cause the error?
Removing which one stopped the error?

**Comment by Leescar** [comment]
Oh wait in the quest name? Yeah that will do it colored names are not yet implemented.

**Comment by sumdream** [comment]
quests name

**Comment by GreenFlagCZ** [comment]
try this § instead of &

**Comment by Leescar** [comment]
Well just a heads up if you color the name you will have to edit the quest in the file. As the system will color the name and not let you edit it properly with 
/quests editor namehere 
because its expecting /quests editor &7namehere 
It will color the name, but you cant edit it with the in game gui anymore, only editing the file, unless you remove the color.

**Comment by FlyingPikachu** [comment]
Closing as issue has been resolved.
