### ISSUE TITLE
java.lang.NullPointerException Error

### ISSUE THREAD

**Issue by CarterBradly** [FlyingPikachu/Quests#114]
Hi. I keep getting this error: http://pastebin.com/bQLWZT9R
Can you please work on a fix? It happens so often, and it greatly hampers the quest-making experience.

**Comment by sumdream** [comment]
Did you use the color code "&" in your quests name?

**Comment by FlyingPikachu** [comment]
Please do not use color codes where not supported. While expanding such functionality is planned, doing so now will cause errors of this nature.

**Comment by CarterBradly** [comment]
Yes, but I didn't use color codes in the named title. Now I get this error: http://pastebin.com/t63EyYcW
