### ISSUE TITLE
Kill dont be detected (video)

### ISSUE THREAD

**Issue by sahudon** [FlyingPikachu/Quests#117]
(__Required__) Quests-3.0.0-Naomi

(__Required__) The solve in ticket #99 dont work, look at this pls : https://youtu.be/oPEl8GlhHYQ

(__Optional__) https://pastebin.com/aggwG4jp

**Comment by FlyingPikachu** [comment]
I see, thank you for the video! This is difficult to test as I do not have a secondary account.

If you would, please try the special test build below and repeat the actions in your video. After killing the player, you'll see many numbers appear in the console. Please post _all_ off those numbers here.

https://www.dropbox.com/s/d8osx16ovgyemxe/Quests-3.0.5.jar?dl=0

**Comment by sahudon** [comment]
Take https://www.youtube.com/watch?v=W0FymPhdeFA&feature=youtu.be

Number in console: 1

The number appear when the player die, but the kill dont count :c

**Comment by FlyingPikachu** [comment]
The visual aid is appreciated, but at this point it isn't necessary if you find it an inconvenience.

It seems that, despite "Player" being an option for the "Kill Mobs" option, it was never designed to accept players as an option. However, the separate "Kill Players" option is under-powered and obviously won't do what you need it to.

I'm debating whether to expand the "Kill Players" option or remove it entirely in favor of making players work with "Kill Mobs". Until I decide, this build below _should_ do the latter. If it doesn't work, post the numbers from console once again.

https://www.dropbox.com/s/tmq76p9ryeyw1lr/Quests-3.0.5.jar?dl=0

**Comment by sahudon** [comment]
Again https://www.youtube.com/watch?v=oc1GbBM6XgQ&feature=youtu.be

Number in console: 1

Dont count. you can doit, i will waiting for your fix

**Comment by FlyingPikachu** [comment]
The 'bug' portion of this issue should be fixed with 33d0fef. Next is to add the ability to count kills in specific locations per #99.

**Comment by FlyingPikachu** [comment]
Upon trying a few different ways to add the aforementioned ability, it dawned on me that just about any quest could utilize this feature. Breaking blocks in a specific area, sheering sheep, taming mobs... completing tasks in a certain location isn't something that should be expanded only to killing players.

The easiest way to add such a feature globally would be via a new Event like the somewhat-recently added Timer events. Until then, I think it's best I just remove the broken "Player" option in "Kill Mobs", which I've done in 143fae7
