### ISSUE TITLE
1.8.4

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#117]
Problem with Spigot 1.8.4
![quests](https://cloud.githubusercontent.com/assets/10450256/7680955/f1996a10-fd6b-11e4-861c-ef56c30aacf8.JPG)

**Comment by SmallSansSerif** [comment]
Yes, please update build for 1.8.4. Thanks!

**Comment by FlyingPikachu** [comment]
I will update the plugin once all dependencies have updated, hopefully in the next few days.

**Comment by 100chilly** [comment]
Spigot is on version 1.8.5 now. Oh the joys of updates. Looking forward to see a release for this version hopefully. :D

**Comment by SmallSansSerif** [comment]
Can this be updated now? I think most things expect worldedit/guard are updated. Citizens updated today.

**Comment by SmallSansSerif** [comment]
Lol now we are at 1.8.6 .. well that was fast. Hoping for an updated version of this soon.

**Comment by FlyingPikachu** [comment]
Supported in v2.5.0
