### ISSUE TITLE
Is it possible to have a quest completed by running a command?

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#118]
I tried to figure out how to do this using chat-events, but it looks like the events system doesn't have a "complete stage" option. I'd like to create a quest that requires players to run the "/sethome" command, because apparently many don't know it exists.

I also created an issue for this rather than a comment on the thread so that others would see it when they search and you could easily link back to it in the future.

**Comment by FlyingPikachu** [comment]
Are you saying the chat-event does not accept commands? Because I figure that should work. Show what you've got?

**Comment by SXRWahrheit** [comment]
No, I didn't see a "complete the stage" option in the list of things to do in quest events. I could just be missing it. :)

I wasn't able to actually test the chat event with commands because I couldn't create the event's outcomes.

**Comment by FlyingPikachu** [comment]
I don't think there is one, as the stage should complete when the user fulfills the chat requirement, assuming it's the only req.

Feel free to request re-open if you experience issues after testing.

**Comment by SXRWahrheit** [comment]
I don't see an option to progress the stage in the event.

![2017-08-29 20_20_45-](https://user-images.githubusercontent.com/774463/29849865-a4900bca-8cf7-11e7-9fd4-d6f778cfd284.png)

**Comment by FlyingPikachu** [comment]
@SXRWahrheit Right, again I don't think there is one. Unless I'm confused, the stage should progress on its own once a requirement is fulfilled.

**Comment by SXRWahrheit** [comment]
Correct, which means that because chat triggers are based on the events system, it appears impossible to have "run a command" be a way to complete a stage/quest.

**Comment by FlyingPikachu** [comment]
@SXRWahrheit What is the current behavior when a command is used the chat event trigger?

**Comment by SXRWahrheit** [comment]
Using the editor, you can't set a command as a trigger - the command just runs.

**Comment by FlyingPikachu** [comment]
Alright. I don't know for sure whether that's a mistake or not, so I'll change this to an enhancement for now.

**Comment by FlyingPikachu** [comment]
The commit pushed just now introduces a Command Event, which is nearly identical to the Chat Event, but is triggered by commands instead. This was simpler and cleaner to add compared to an Objective for running a command. Although this new Event does not inherently end the quest, it can be used to guide the player in doing so (for example, send a "Good job! Now place a chest" message when the player runs /sethome, then finish the quest when the player places a chest).

It can also be used for other things, like redirecting commands. If a player runs _/welp_, the Event could reply with "Did you mean /help?" and then execute the _/help_ command on the player's behalf. Overall, this event adds a lot more functionality than an Objective could offer. I understand this may not be what you were asking for, but hope this is satisfactory for the time being.

**Comment by SXRWahrheit** [comment]
I love you. :D

**Comment by SXRWahrheit** [comment]
If a command objective is still eventually possible, that would be great, but this is an excellent stopgap and I appreciate you explaining examples of how to use it well.

**Comment by SXRWahrheit** [comment]
Could you add some documentation for how to implement this, and maybe for event config options more generally? I tried using the /quests events command and fiddling with it, but didn't get very far.

Thanks for your work on this!
