### ISSUE TITLE
Log back in to server with journal in inventory

### ISSUE THREAD

**Issue by Ironic8b498** [FlyingPikachu/Quests#119]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-2.9.8-B166 and Quests-3.0.5-B185
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I believe when one logs out with the quest journal in your inventory and you log back in the journal don't work right, this last time it stopped the quest from working got many internal errors trying to access the NPC's or running /quests journal or quest stats
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://www.hastebin.com/komucaxuro.vbs

**Comment by FlyingPikachu** [comment]
Thanks for your report, but "I believe" isn't sufficient. Produce the internal errors you speak of.

**Comment by Ironic8b498** [comment]
those errors stopped after I went into creative and trashed the journal

**Comment by FlyingPikachu** [comment]
That's great, but you'll still have to acquire the error(s) from your server log. Otherwise, I'll be closing this issue.

**Comment by Ironic8b498** [comment]
the errors I posted was spamming from the server logs, in chat it said something about fatal internal error

**Comment by FlyingPikachu** [comment]
Closing as OP refused to post error.

**Comment by FlyingPikachu** [comment]
It appears OP posted the error in the _wrong place_ (under "Can you provide an example quest..."). It doesn't look like we'll be needing an example quest, so I'll reopen this.

**Comment by Ironic8b498** [comment]
sorry I read pastebin and posted it there

**Comment by FlyingPikachu** [comment]
Apologies for not getting around to this. The hastebin has expired, so I must close this issue.
