### ISSUE TITLE
Quest Reminder - playerjoinevent

### ISSUE THREAD

**Issue by madtomic** [FlyingPikachu/Quests#119]
Is it possible to add a playerjoinevent that will give current quest status?

Perhaps a delay timer to show up in chat or better yet if this plugin support authme reloaded, quest playerjoinevent fires after player login in using authme reloaded?

madtomic

**Comment by FlyingPikachu** [comment]
I am not looking to support other plugins until the current issues have been resolved. However, feel free to explain your request further so that I might come back to it.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response. Also in hindsight, am I to understand you want /quests stats to be run on login? I'm sure a separate plugin or script can do that, but thank you for your suggestion!

**Comment by madtomic** [comment]
A simple quest checker would be nice. It runs when player joins the server and let the player know if they have an active quest or quests.

**Comment by FlyingPikachu** [comment]
http://dev.bukkit.org/bukkit-plugins/joincommands/
http://dev.bukkit.org/bukkit-plugins/logincommand/
http://dev.bukkit.org/bukkit-plugins/joincommand/

+

/quests stats

**Comment by madtomic** [comment]
Thank you for these suggestions.
