### ISSUE TITLE
Item Deliver problem

### ISSUE THREAD

**Issue by Archious** [FlyingPikachu/Quests#120]
items-to-deliver:
          - name-redstone:amount-3
          - name-glowstone:amount-1

Is there something wrong here
Console said that item-delivery not formatted properly
Using latest Quests version on Spigot 1.7.10
Vault 1.4.1

**Comment by FlyingPikachu** [comment]
Please post the actual Quests version and error ("latest" is not sufficient as you may be using a dev build).

**Comment by Archious** [comment]
Im using Quests 2.4.0

  PotionMaster:
    name: Ren's Dreams 2
    ask-message: <green>* I believe you are here because of Ren? I saw her going back to that old abandoned house again, she always do that whenever she's having those bad dreams. Anyway I'm lacking of ingredients to make the potion that she needed. <br>* Can you go buy 3 redstones and 1 glowstone dust for me?
    finish-message: <yellow>You may now give this potion to Ren.
    npc-giver-id: 29
    requirements:
      quests:
      - Ren's Dreams
      fail-requirement-message: <purple>You need to finish Ren's Dreams quest!.
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-redstone:amount-3
          - name-glowstone:amount-1
          npc-delivery-ids:
          - 18
          delivery-messages:
          - '<npc>: Thanks for the ingredients!'
    rewards:
      money: 0.05
      items:
        - name-potion:amount-1:displayname-Dreamshade


I suddenly got this error after reload
http://pastebin.com/Q9Gzytzf

**Comment by Archious** [comment]
I updated to Spigot 1.8.3

I got this small error instead
http://pastebin.com/n2Ah4zGy

**Comment by FlyingPikachu** [comment]
Sorry for the late response. I would suggest remaking the quest if you haven't already.
