### ISSUE TITLE
Quest no longer exists?

### ISSUE THREAD

**Issue by Ryax75** [FlyingPikachu/Quests#121]
Whenever I reload the quests with /questsadmin reload, it displays the following message:

[Quests] Your active Quest Dragon Hunter no longer exists. You have been forced to quit the Quest.
Quests reloaded.
3 Quest loaded.

The three quests that load are other quests which are working fine.
Is there anything I can do to make it "exist" again?

The quest's code:
http://pastebin.com/L1CCRRFZ

**Comment by FlyingPikachu** [comment]
This seems to be an issue with player data. Open the file named with your UUID in Quests/data and delete and lines that mention "Dragon Hunter" or "null".

**Comment by Ryax75** [comment]
That doesn't seem to be the problem, here's why:
1. It wasn't on my UUID (But when reloading it no longer displays the message)
2. I've tried with multiple players, when they right click NPC 242 it displays: No more quests available.
3. All other quests are still working.

I'm adding a link to the FULL Quests.Yml so you can see. It just simply isn't showing up when I /questsadmin reload.

**Comment by Ryax75** [comment]
Am I allowed to bump this? We'll see.

**Comment by FlyingPikachu** [comment]
Bug #57 (mentioned earlier) may have been related to this issue and has since been resolved. Please update to at least this dev build and check if it resolves the issue.

http://ci.ac3-servers.eu/job/Quests/81/

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
