### ISSUE TITLE
Translation only work after /questadmin reload

### ISSUE THREAD

**Issue by Rio6** [FlyingPikachu/Quests#121]
Version 3.0.0-Naomi

Everytime I reload or restart the server all the messages are in English , I have to do `/questadmin reload` everytime to get the translation back.

[https://pastebin.com/SNUkFuAi](https://pastebin.com/SNUkFuAi)

**Comment by sahudon** [comment]
change the name of the translation a "en" when the server is off maybe work for you

**Comment by FlyingPikachu** [comment]
Fixed in latest dev build, version 3.1.0
