### ISSUE TITLE
Problem with Quests and GadgetsMenu

### ISSUE THREAD

**Issue by topthat177** [FlyingPikachu/Quests#122]
Version: 3.0.0-Naomi

Problem: I installed Quests yesterday and when I first installed it and restarted my server, I tried to start making a quest with help form Koz's video (legend) and I couldn't access the menu at all. Nothing happened when I typed /quests events etc. which generally signals an error of some kind. Looked at the console and sure enough there was one. The plugin was butting heads with GadgetsMenu that was already installed and running which I thought was strange.

Console: https://pastebin.com/avNAtGpF

I temporarily uninstalled Gadgetsmenu to work on adding quests and after I removed it and restarted the Quests worked perfectly? Currently it is still uninstalled as I get my quests set up and I havent tried re-installing. Any Ideas? I would like to run both at the same time eventually although Ill take Quests over the menu. 

Regards,
topthat177

**Comment by FlyingPikachu** [comment]
According to your error, the problem lies solely with GadgetsMenu. Contact the author of that plugin.
