### ISSUE TITLE
1.12 block names not appearing

### ISSUE THREAD

**Issue by silvasky54** [FlyingPikachu/Quests#123]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
No console errors. 1.12 block names are not appearing when delivering blocks to a NPC. Image as evidence https://imgur.com/a/Cq7TP 

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/fNuZvi25

**Comment by FlyingPikachu** [comment]
@silvasky54 What is your Vault version?

**Comment by FlyingPikachu** [comment]
This is caused by Vault being a little behind on item name support for items introduced after 1.9. The next dev build of Quests will provide a less-than-pretty solution for this. Thanks!
