### ISSUE TITLE
How to translate "Counter:"?!

### ISSUE THREAD

**Issue by DonatEW** [FlyingPikachu/Quests#125]
I can not translate this moment! Even in the code I can not find! Tell me ...
![image](https://user-images.githubusercontent.com/23126502/30001675-150d9124-90ae-11e7-8fb3-5fe0201aba9c.png)

**Comment by DonatEW** [comment]
Please help me

**Comment by FlyingPikachu** [comment]
What is the original English text?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
