### ISSUE TITLE
Blacklisting UUID

### ISSUE THREAD

**Issue by nitrostam22** [FlyingPikachu/Quests#127]
Quests-3.0.0-Naomi

I am creating Sentinel npc's to kill mobs as they spawn. whenever an npc kills a mob it spams the consol with there UUID and a mesage about blacklisting it. After adding the UUID's of the npc's to the blacklist the consol spam stops and things run like normal.
 However ALL Players/admins/OP's are now also blacklisted! It does not matter if I enter 1 UUID or 30 a UUID simply being present in the blacklist blacklists ALL Players connected to the server.

  This issue is not terribly game breaking but it means the consol will always be running faster than could possibly be read, especially as the npc count increases.

**Comment by FlyingPikachu** [comment]
Please update to the latest dev build (3.0.5) and post one of the errors from your console.

**Comment by nitrostam22** [comment]
I updated to the latest dev build 3.0.5 Unfortunately there is no change.
I reset the configs and purged all player UUID data as well.
https://pastebin.com/vf20Fz0s   there is the startup but there are no errors other than lore attributes on login which has thus far not impacted any other plugins or performance and the plugin does operate as normal

  For whatever reason the addition of any UUID in the blacklist section blankets the entire server.....its quite strange.

**Comment by nitrostam22** [comment]
The errors I do recieve are strictly Ingame. I recieve the blacklist error please contact an admin message. When ALL of the UUID's are remove from the blacklist the error disapears and ALL players are able to quest as normal. However entering ANY single UUID blacklists the entire server.

 Let me know if there is anything I can do to help with this issue.

**Comment by FlyingPikachu** [comment]
The request to update was to get an accurate console error; not to fix anything.

Since you only have an in-game error, I will have to experiment in my test environment, hopefully later today.

**Comment by nitrostam22** [comment]
If it makes any difference I have been adding the uuid by hand into the config. not with the purge command.

**Comment by FlyingPikachu** [comment]
That likely will make a difference as there is code that runs in the background other than just inserting the line into the config.

**Comment by nitrostam22** [comment]
When I get back in Front of my pc I will try and reproduce the issue by running the uuid through the purge command. 
The only reason i dident do that in the first place the purge command also says it resets the uuid. With an npc uuid I thought there could be a conflict since the npc would have no quest data.

**Comment by FlyingPikachu** [comment]
I believe the command accounts for that, but I'm no position to check atm.

**Comment by nitrostam22** [comment]
Trying to blacklist an NPC with the purge command does not work.  when running the /questadmin purge <name>  command you must use the npc ID (EX 125) when entering /questadmin purge 125   My UUID is sent to the blacklist not the NPC...... I also tried /questadmin purge UUID   with the UUID being the npc assigned uuid. When running the command this way I simply get the error Player not found.

**Comment by nitrostam22** [comment]
https://pastebin.com/0jxTsn6Q      This is what I am trying to avoid using the blacklist

**Comment by nitrostam22** [comment]
Any idea on a fix for this? with several dozen npc's  now killing monster I have to purge my log files daily as they are becoming massive in size due to the constant text spam.
