### ISSUE TITLE
Item Rewards Not Working

### ISSUE THREAD

**Issue by UltimateNetworks** [FlyingPikachu/Quests#127]
When I try to do the "Load Item In Hand" It doesnt appear. When I try to make an item with the options there are (Set ID, Set Amount, Enchantments etc.) I time out. Please Help!

**Comment by FlyingPikachu** [comment]
Unless there is some sort of console error, I don't have a way to diagnose this. Chances are, you just have a bad connection.

Feel free to open a new issue if you get more information.

**Comment by UltimateNetworks** [comment]
Ok, Sorry for the late reply, I have a screenshot 
![2015-06-20_19 44 34](https://cloud.githubusercontent.com/assets/10036904/8269890/350bb450-1785-11e5-9e94-753b7c3088b4.png)

**Comment by UltimateNetworks** [comment]
The item just goes away when I type 8 (Done)
