### ISSUE TITLE
Compass and delay

### ISSUE THREAD

**Issue by Jumpy94100** [FlyingPikachu/Quests#128]
Version : 
Quests 3.0.0-Naomi

I got 2 issues (not sure if it's really an issue but I prefer post it here as an "information" I guess)

First is with the compass, in fact we've got few players in our server who complain that the compass don't indicate the good location of a 'Location to reach' or a NPC (Citizens2).

The second is with the Delay stage. If you have 2 Delay stages in 2 quests and you are doing both quest at the same time the delay are not independent. If you have 2 hours on first quest and 2 hours on the second one, you must wait 4 hours and both stages will be completed at the same time. And it's no really good I guess ^^

Thanks for your help :D

**Comment by FlyingPikachu** [comment]
Compass works fine for me, so you'll need to provide a more specific scenario to test (including a quest from quests.yml would expedite that).

Your second issue was supposedly fixed in #114 - update to the latest dev build

**Comment by Jumpy94100** [comment]
Compass works fine for me too but not for all player which is not normal at all but we've go few permissions' bug on the server and I believe it's the main cause of this bug ^^ (Will see with the permissions' plugin update)

And ... I am a bit lost on Github and I don't find where download the dev build, so can you say me where to find it or a link? It will be really helpful :) 

Thanks for your help :D

**Comment by FlyingPikachu** [comment]
Closing until valid reason to proceed is found.

Dev builds - http://ci.ac3-servers.eu/job/Quests/
