### ISSUE TITLE
The reach location spam many error in console

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#13]
Hello,
I have a problem with the reach location.
I have regenerate all files and set "generate-files-on-join" to 'false'
With the last version of this plugin
![6594a086-b543-11e4-9bd5-d7a37c599056](https://cloud.githubusercontent.com/assets/10450256/6204501/c88b40be-b54d-11e4-82e7-f3be7e5b6717.PNG)

**Comment by Leescar** [comment]
Ive never had an issue with reach location, does the quest complete in game?

**Comment by Mick43** [comment]
Yes when the quest is complete the console spawm error but not every time.
I have create only two quests with reach location, and on quests on two spawn error

**Comment by FlyingPikachu** [comment]
Closed bc duplicate of #4

**Comment by FlyingPikachu** [comment]
Please try this dev build as a potential fix for this issue: http://ci.ac3-servers.eu/job/Quests/34/

**Comment by Mick43** [comment]
Sorry but that's spam error to
![capture](https://cloud.githubusercontent.com/assets/10450256/6319405/91915242-babb-11e4-8cdd-c7aa08f3cc6f.PNG)

**Comment by FlyingPikachu** [comment]
Okay, last one. If this doesn't work, I'll try to duplicate the error and go from there.

http://ci.ac3-servers.eu/job/Quests/37/

**Comment by Mick43** [comment]
Good work, the problem is solved.
