### ISSUE TITLE
locations_to_reach with worldname containing space

### ISSUE THREAD

**Issue by hwathi** [FlyingPikachu/Quests#130]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.05

(__Required__) Please describe the problem and how to replicate it. Any console errors?
World Name contains a space, causes a parsing error.

Our world name is "Towns 1" with a space.    Adding a location to reach of 126.0, 64.0, 98.0 causes a parsing error.

loccations-to-reach:
          - Towns 1 126.0 64.0 98.0

Reloading quests gives the following error:

[20:19:48 ERROR]: [Quests] Towns 1 126.0 64.0 98.0 inside mobs-to-kill: inside Stage 1 of Quest Meet Mag is not in proper location format!

Note; I also filed the bug report for creating events with mob spawners crashing while trying to setup spawn locations, it maybe the same issue as its the same world.

**Comment by FlyingPikachu** [comment]
The fix for #100 should have resolved this issue. Hope to take a look soon

**Comment by FlyingPikachu** [comment]
Related to #124 
Fixed in 1b2eb65a105a34ec18db75b964f8b0fcd4258d7e
