### ISSUE TITLE
Quests disappear and other issues.

### ISSUE THREAD

**Issue by rockindavies21** [FlyingPikachu/Quests#131]
Hi, it seems i'm having many issues with this plugin. For starters Let's say I create a new quest. Now, I realize that I made a spelling error. Then I open the quests editor and change it then I use /questsadmin reload and it says quests reloaded. But, the quest that I edited is not saved/gone. Now, with the other issue it's that whenever I do a quest and then try to do it again it says "No more quests available". None of my quests have redo delays. Thanks.

**Comment by FlyingPikachu** [comment]
Make sure to save when exiting the quest editor (it will ask if you want to save). Unless you add a redo delay, quests are single-use, so that behavior is expected.
