### ISSUE TITLE
Mystic Mobs or other customized Mob mod

### ISSUE THREAD

**Issue by hwathi** [FlyingPikachu/Quests#132]
This is more a question than an issue.

Is it possible to spawn non-vanilla mobs using events?    Or to use them as quest objectives?

**Comment by Formula350** [comment]
MythicMobs Quest Kill module. The JAR goes in the `Quests/modules/` folder.
https://www.spigotmc.org/resources/mythicmobs-quests-module.7261/

I'd assume, with some work, that you could spawn a MythicMob using a command through the events. I mean, if you can issue commands via events, I see no reason why it couldn't work. 
An option might be to have it run the `/execute` command to provide spawn coordinates more easily.
