### ISSUE TITLE
Error on PlayerQuitEvent

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#133]
Getting this error on the PlayerQuitEvent - http://pastebin.com/jG30CUQ5

This doesn't happen all of the time, but it is there. I am unsure how to exactly replicate this at the moment.

**Comment by guyag** [comment]
Do you use /reload?

**Comment by whoshenry** [comment]
No, never.

**Comment by whoshenry** [comment]
Getting it still - http://pastebin.com/uksc7NiD
