### ISSUE TITLE
Feature Request:  Activate Redstone

### ISSUE THREAD

**Issue by hwathi** [FlyingPikachu/Quests#133]
It would be nice if an event could activate a specific redstone switch/lever/button as one of its parameters.

Specifically, I wanted to open a locked iron door after an objective was completed.   I worked around it with teleport, but it'd feel more natural if the door just opened.

**Comment by FlyingPikachu** [comment]
After some digging, it seems this can't be added easily. It is possible to toggle a lever through code, but getting the adjacent redstone or device to become powered is quite challenging - if not impossible - to do without using NMS (a form of coding which would break backwards compatibility with older Minecraft versions and make Quests more difficult to update for future versions as well). Although this would be a great Event to have, it unfortunately cannot be implemented at this time.

Source - https://www.spigotmc.org/threads/set-button-in-world-pressed.122220/#post-1301255
