### ISSUE TITLE
Ask-message Line break.

### ISSUE THREAD

**Issue by Busigbanan** [FlyingPikachu/Quests#135]
Version: 3.0.0-Naomi

I wonder if and how to add a linebreak in the quest ask-message. I have tried "\n" "," without getting desired result.

Pastebin: https://pastebin.com/embed_js/ZtdHzLGe"

//Busigbanan

**Comment by FlyingPikachu** [comment]
Not currently possible, although you might be able to add enough blank spaces to simulate a line break, with some testing on your part. At any rate, this is not a highly requested feature so I will not look into adding it at this time.
