### ISSUE TITLE
Language not loaded when server start

### ISSUE THREAD

**Issue by Fargus5** [FlyingPikachu/Quests#136]
(__Required__) Quest version 3.0.0 Naomi

(__Required__) Hi, I didn't find any errors in the console... but the problem is that when I start the server... the plugin doesn't load automatically the translated language... When server is open if I do the command /questsadmin reload... it will be translate as aspected.

Could u fix this please?

**Comment by Fargus5** [comment]
?

**Comment by FlyingPikachu** [comment]
Duplicate of #121
