### ISSUE TITLE
Client crashes with exception when setting region as "place to go"

### ISSUE THREAD

**Issue by afaik4711** [FlyingPikachu/Quests#137]
In the quest editor at number 7 (Set Region) a OutOfBounds Exeption appears and
the player, who edits the Quest, gets kicked.
Exactly Error: DecoderExeption: java.lang.IndexOutOfBoundsExeption: readerIndex(1) + length(1)

exceeds writerIndex(1): UnpooldesHeapByteBuf(ridx: 1, widx: 1, cap: 1)@
io.netty.handler.codec.ByteToMessageDecoder:278

Error in Serverlog: 
[17:25:16] [Netty Epoll Server IO #2/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 51283 bytes encoded, max 32767)

Using Quests 2.5.1 on Spigot 1.8.3

**Comment by FlyingPikachu** [comment]
This is not typical. I would need your quests.yml as well as the exact steps you took to create that error.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
