### ISSUE TITLE
Give item current doing quest

### ISSUE THREAD

**Issue by DragonHero221** [FlyingPikachu/Quests#137]
(**Required**) Quest version 3.0.0 Naomi

(**Required**) i want to know how do i give item white doing quest i don't know how .-. can someone tell me? (i was doing quest like[Talk to npc[A] and npc[A] give item and Deliver to Npc[B] and Npc[B] Give item and Deliver to Npc[A])

**Comment by FlyingPikachu** [comment]
Closing due to lack or response from community. Maybe try asking on Spigot?
