### ISSUE TITLE
Enchanted books not working as end of quest reward

### ISSUE THREAD

**Issue by thomasdaley2** [FlyingPikachu/Quests#138]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?  
3.0.0

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Enchanted books not working as end of quest reward

Tried using:

give command
tried inputting the book code...... nothing works
cannot use item in hand either

**Comment by FlyingPikachu** [comment]
Duplicate of #107
