### ISSUE TITLE
PlayerJoinEvent、LinkedList issue、IndexOutOfBoundsException

### ISSUE THREAD

**Issue by samueleycw** [FlyingPikachu/Quests#139]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0-Naomi
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Could not pass event PlayerJoinEvent
LinkedList issue
IndexOutOfBoundsException
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/tuUgsFKB

**Comment by FlyingPikachu** [comment]
Please give Quests 3.0.7 a try once available and report back. Include new error if applicable. Thanks!
