### ISSUE TITLE
mythicmobs module

### ISSUE THREAD

**Issue by MastaCraftPLL** [FlyingPikachu/Quests#143]
can you fix this?
Could not pass event MythicMobDeathEvent to Quests v2.5.1-b82
16:21:10 org.bukkit.event.EventException
16:21:10     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot_server.jar:git-Spigot-dbe012b-61ef214]
16:21:10     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-dbe012b-61ef214]
16:21:10     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-dbe012b-61ef214]
16:21:10     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePl

**Comment by FlyingPikachu** [comment]
No, because Quests does not inherently support MythicMobs. You must speak to the author(s) of that module.
