### ISSUE TITLE
PlayerJoinEvent Issue

### ISSUE THREAD

**Issue by CarterBradly** [FlyingPikachu/Quests#144]
Hello, I keep getting this PlayerJoinEvent issue. http://pastebin.com/t63EyYcW
It spams about one error per second. The citizens are the newest version, and so it Spigot and Quests. Any help would be appreciated. Thanks.

**Comment by whoshenry** [comment]
Try the latest Dev Build, b89. This fixed some of the errors associated with this for me. I still get the odd error, but rarely the MoveEvent.

**Comment by CarterBradly** [comment]
Okay, thanks a bunch henry.

**Comment by CarterBradly** [comment]
Still get the error.
