### ISSUE TITLE
/quests Not Working

### ISSUE THREAD

**Issue by Ninja-Jesuz** [FlyingPikachu/Quests#145]
Anytime I try /quests it says

/quests NULL
/quests NULL
/quests NULL
/quests NULL

**Comment by CarterBradly** [comment]
Try updating citizens to the newest version. Also, try restarting the server. I did those two things, and it worked for me.

**Comment by Ninja-Jesuz** [comment]
I have the new version of citizens

**Comment by Ninja-Jesuz** [comment]
16.06 17:12:53 [Server] INFO 0 regions loaded for 'spawn'
16.06 17:12:53 [Server] INFO UUID of player Koda_Lois is 11b04a72-82e0-46c6-aa78-7ddd382e6178
16.06 17:12:50 [Server] INFO No new version available
16.06 17:12:50 [Server] INFO Checking for Updates ... 
16.06 17:12:50 [Server] INFO Loaded 0 NPCs.
16.06 17:12:50 [Server] INFO GroupManager - INFO - Bukkit Permissions Updated!
16.06 17:12:50 [Server] Startup Done (4.719s)! For help, type "help" or "?"
16.06 17:12:50 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
16.06 17:12:50 [Server] INFO ... 13 more
16.06 17:12:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.herocraftonline.heroes.Heroes
16.06 17:12:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at me.blackvein.quests.Quests.onEnable(Quests.java:182) ~[?:?]
16.06 17:12:50 [Server] INFO at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:420) ~[?:?]
16.06 17:12:50 [Server] INFO java.lang.NoClassDefFoundError: com/herocraftonline/heroes/Heroes
16.06 17:12:50 [Server] ERROR Error occurred while enabling Quests v2.5.1-b82 (Is it up to date?)
16.06 17:12:50 [Server] INFO Enabling Quests v2.5.1-b82
16.06 17:12:50 [Server] INFO ... 14 more
16.06 17:12:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
16.06 17:12:50 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.herocraftonline.heroes.Heroes
16.06 17:12:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
16.06 17:12:50 [Server] INFO at net.elseland.xikage.MythicMobs.MythicMobs.onEnable(MythicMobs.java:130) ~[?:?]
16.06 17:12:50 [Server] INFO at net.elseland.xikage.MythicMobs.Compatibility.CompatibilityHandler.Initialize(CompatibilityHandler.java:54) ~[?:?]
16.06 17:12:50 [Server] INFO at net.elseland.xikage.MythicMobs.Compatibility.HeroesSupport.<init>(HeroesSupport.java:25) ~[?:?]
16.06 17:12:50 [Server] INFO java.lang.NoClassDefFoundError: com/herocraftonline/heroes/Heroes
16.06 17:12:50 [Server] ERROR Error occurred while enabling MythicMobs v2.0.4 (Is it up to date?)
16.06 17:12:50 [Server] INFO Loading MythicMobs...
16.06 17:12:50 [Server] INFO Enabling MythicMobs v2.0.4
16.06 17:12:50 [Server] INFO has been enabled.
16.06 17:12:50 [Server] INFO Enabling floAuction v3.1.0
16.06 17:12:50 [Server] INFO version 1.5.5.4-SNAPSHOT-b66 is disabled!
16.06 17:12:50 [Server] INFO Disabling Heroes v1.5.5.4-SNAPSHOT-b66
16.06 17:12:50 [Server] ERROR You are attempting to load Heroes on version v1_8_R3 which is not supported!
16.06 17:12:50 [Server] INFO The detected server mod is SPIGOT. Heroes will use SPIGOT compatibility!
16.06 17:12:50 [Server] INFO You are running Heroes on git-Spigot-3ccbe77-a6a57a9 (MC: 1.8.7)
16.06 17:12:50 [Server] INFO Enabling Heroes v1.5.5.4-SNAPSHOT-b66
16.06 17:12:50 [Server] INFO Enabling Citizens v2.0.16-SNAPSHOT (build 1244)
16.06 17:12:50 [Server] INFO - 0 classes
16.06 17:12:50 [Server] INFO - 0 skills
16.06 17:12:50 [Server] INFO Registration complete
16.06 17:12:49 [Server] INFO Logger => You are 17 version(s) behind
16.06 17:12:49 [Server] INFO Invalid block type "redstone*"
16.06 17:12:49 [Server] INFO Enabling SkillAPI v3.33
16.06 17:12:49 [Server] INFO has been enabled.
16.06 17:12:49 [Server] INFO Enabling WhatIsIt v1.3.9
16.06 17:12:49 [Server] INFO Enabling HolographicDisplays v2.1.10
16.06 17:12:49 [Server] INFO CombatLog v1.8.11-hack Enabled.
16.06 17:12:49 [Server] INFO Factions plugin not found! Safezone untagging will not work.
16.06 17:12:49 [Server] INFO DisguiseCraft plugin not found! Disguise removal will not work.
16.06 17:12:49 [Server] INFO Loading config.yml.
16.06 17:12:49 [Server] INFO Loading messages.properties.
16.06 17:12:49 [Server] INFO Enabling CombatLog v1.8.11-hack
16.06 17:12:49 [Server] INFO Enabling EssentialsSpawn vTeamCity
16.06 17:12:48 [Server] INFO 0 - Portals(s) loaded
16.06 17:12:48 [Server] INFO - Version 2.4-b548 Enabled - By Rigby and fernferret
16.06 17:12:48 [Server] INFO Enabling Multiverse-Portals v2.4-b548
16.06 17:12:48 [Server] INFO Enabling ActionAnnouncer v1.7
16.06 17:12:48 [Server] INFO Enabling EssentialsAntiBuild vTeamCity
16.06 17:12:48 [Server] INFO Enabling EssentialsChat vTeamCity
16.06 17:12:48 [Server] INFO ServerMotd v1.4 enabled correctly!
16.06 17:12:48 [Server] INFO Enabling ServerMotd v1.3
16.06 17:12:48 [Server] INFO Enabling EssentialsProtect vTeamCity
16.06 17:12:48 [Server] INFO Enabled
16.06 17:12:48 [Server] INFO You have an old version of the plugin. Your version: 2.2.1, available version: 2.2.2
16.06 17:12:48 [Server] INFO New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
16.06 17:12:48 [Server] INFO PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix
16.06 17:12:48 [Server] INFO BlocksHub plugin not found.
16.06 17:12:48 [Server] INFO Enabling AsyncWorldEdit v2.2.1
16.06 17:12:48 [Server] INFO Logger => Checking version, please wait...
16.06 17:12:48 [Server] INFO Version: 10807
16.06 17:12:48 [Server] INFO Logger => This server is running CraftBukkit version git-Spigot-3ccbe77-a6a57a9 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
16.06 17:12:48 [Server] INFO Enabling MCCore v1.39
16.06 17:12:48 [Server] INFO 6 - World(s) loaded.
16.06 17:12:48 [Server] ERROR New safe spawn NOT found!!!
16.06 17:12:48 [Server] WARN Original Location: X: 0 Y: 65 Z: 0 P: 0 Y: 0 
16.06 17:12:48 [Server] WARN Spawn location from world.dat file was unsafe. Adjusting...
16.06 17:12:48 [Server] INFO Loaded configuration for world 'spawn'
16.06 17:12:48 [Server] INFO (spawn) Fire spread is UNRESTRICTED.
16.06 17:12:48 [Server] INFO (spawn) Lava fire is blocked.

**Comment by Ninja-Jesuz** [comment]
Anyone help?  That's my console when it's not working

**Comment by Ninja-Jesuz** [comment]
Anyone help?  I just posted my console

**Comment by Ninja-Jesuz** [comment]
Please!!!

**Comment by CarterBradly** [comment]
I had the same issue a while ago. Now /quest isn't working for me...

**Comment by FlyingPikachu** [comment]
@Ninja-Jesuz Make sure you have Vault installed.

**Comment by halowhoflungpoo** [comment]
hello everyone i am brand new to this. i have tried many versions on my server which is 1.8 bukkit . and when i reload my server the folder nor any of the files are created i have citizens 2 ver2.0.14 and vault ver1.5.0-b28 and mcmmo 1.5.00-b3547 . what am i doing wrong that the folder wont create?

**Comment by FlyingPikachu** [comment]
16.06 17:12:50 [Server] ERROR You are attempting to load Heroes on version v1_8_R3 which is not supported!
