### ISSUE TITLE
Commad-Events need a dealy option!

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#145]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Naomi
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When i create an event and use commands-option there is no way to set a delay between two commands. please ad an option so that conflicts wont appear because right now the commands get executed at the same time.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
I think this would be best left to an external plugin like https://github.com/Boosik/boosCooldowns
