### ISSUE TITLE
place objective door

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#146]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? Quests-3.0.0-Naomi (1)

(__Required__) Please describe the problem and how to replicate it. Any console errors? when you make an 
place objective with a door it doesn't work but most other blocks do. is this a bug?

**Comment by FlyingPikachu** [comment]
Confirmed that placing Oak Doors does not work. With a quest created using "wood_door" for the item name, nothing happens when trying to place one. Using "wooden_door" instead results in the following error:

https://pastebin.com/c0spB2UD

**Comment by FlyingPikachu** [comment]
Turns out the "wooden_door" error is a separate issue.

Problem is that the durability of a Wood_Door varies depending on facing direction and state (open/closed). You likely left the durability at its default value of 0, so they doesn't match. Will be looking into a way around this.
