### ISSUE TITLE
NullPointerException Error and /quest not working (internal error).

### ISSUE THREAD

**Issue by CarterBradly** [FlyingPikachu/Quests#146]
Hello.
Here is my error I keep getting in the console: http://pastebin.com/MpYbXWn3
Here is my quests file: http://pastebin.com/5WHMHk4P
Citizens is the newest version, so is Spigot and Quests.

**Comment by Ninja-Jesuz** [comment]
Hey i got it to work.  Theres a lot of stuff I did.  Contact me on skype: Ninja_Jesuz

**Comment by CarterBradly** [comment]
Could you tell me here? That way, we could help others who may have the same issue.

**Comment by whoshenry** [comment]
Yes, please say on here to help others.
