### ISSUE TITLE
Feature Request - Config Requests

### ISSUE THREAD

**Issue by Oskang09** [FlyingPikachu/Quests#147]
![image](https://user-images.githubusercontent.com/15674107/31372257-71b90b5c-adc7-11e7-9e4c-311084aaa2b9.png)
i need a config to remove this message when right clicking npc, i have own plugin to work with right click too but this message is annoying to me.

**Comment by FlyingPikachu** [comment]
Just empty the string in your lang file.

**Comment by Oskang09** [comment]
Not work , it will keep sending blank message. if i remove that line, it generate back to me.
