### ISSUE TITLE
Spawning Mobs for quest

### ISSUE THREAD

**Issue by DovydasAL** [FlyingPikachu/Quests#149]
I made a quest where, when you reach a location, it will spawn 5 Rebels down the hillside with rebel armor and such. Instead, it chooses to spawn only 1 rebel, which does have its name, with no equipment,

**Comment by Leescar** [comment]
You might have to instead put the spawnmob event as the ending event to a stage instead of the starting event,

**Comment by DovydasAL** [comment]
I set the Spawning mob event at the end of reaching a location, but it did not work.

**Comment by Leescar** [comment]
Alright I had this issue a while back, I would suggest redoing the mob spawn event and testing it with each part, are you trying to spawn a disguised mob or a special mob?

**Comment by DovydasAL** [comment]
I completely redid the quest and event. I have a quest that says reach blah blah and finish event as HasselhoffAttack and it spawns 5 zombies in black rebel armor, and rebel swords. But when I reach it, no mobs spawn.

**Comment by Leescar** [comment]
any errors in console?

**Comment by FlyingPikachu** [comment]
@DovydasAL Closing due to lack of response. Feel free to open a new ticket.
