### ISSUE TITLE
Not Issue More Request - Vote Objectives - Getting vote data from when a player votes!

### ISSUE THREAD

**Issue by Vestle** [FlyingPikachu/Quests#149]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Not Issue More Request - Vote Objectives - Getting vote data from when a player votes!
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Not Issue More Request - Vote Objectives - Getting vote data from when a player votes!
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Not Issue More Request - Vote Objectives - Getting vote data from when a player votes!

**Comment by FlyingPikachu** [comment]
What.

**Comment by Vestle** [comment]
Custom quests where users must vote 10 times to get a reward, 100 times for next reward. Allowing Votifier and using a placeholder to read when a player votes.
