### ISSUE TITLE
Says my name does not match the Quest name.. But it does

### ISSUE THREAD

**Issue by Vestle** [FlyingPikachu/Quests#150]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.0-Naomi
Spigot 1.12.2
(__Required__) Please describe the problem and how to replicate it. Any console errors?
ERROR Jungle VII inside quests: Requirement for Quest Jungle VIII is not a valid Quest name!
14.10 09:45:15 [Server] ERROR Make sure you are using the Quest name: value, and not the block name.

- I have all these quests the same but for some reason it wont match this only section. I have all my other log quests setup like this and it works.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/iNcumeMh

**Comment by FlyingPikachu** [comment]
I was unable to replicate the bug in the current version of Quests. Considerable time has passed since it was reported and the bug may have already been fixed. However, I have made the purpose of the error more transparent in the latest commit.
