### ISSUE TITLE
Setstage not working

### ISSUE THREAD

**Issue by Spartankiin** [FlyingPikachu/Quests#151]
Hi i'm new to Quests and am trying to make a fail event where a person has to redo the previous stage. I was going to go about this by having a death event run the command setstage, but am having trouble getting setstage to work. The ingame help says to type /questsadmin setstage [name] [quest] [stage]
I am typing /questsadmin setstage <player> test 4, and it keeps saying that the input must be a number. I switched the quest name with its ID but still nothing. Any help would be fantastic, thanks!

**Comment by FlyingPikachu** [comment]
Are you using Blackvein's Quests. There is no 'setstage' subcommand afaik. You should use the /quests editor.
