### ISSUE TITLE
jenkins server down

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#151]
http://ci.ac3-servers.eu/job/Quests/ is down

**Comment by FlyingPikachu** [comment]
Thanks for the head's up! The Jenkins server is not directly run by me. If the page doesn't come back in a few days, I will contact the maintainer.

**Comment by seema84** [comment]
alright thanks

**Comment by ScuroK** [comment]
@FlyingPikachu 
its still down. could you please contact hom or remove the link from the spigot page?

**Comment by FlyingPikachu** [comment]
A message has been sent.

**Comment by Sprungente** [comment]
Maybe you move to an other jenkins server?

**Comment by Sprungente** [comment]
jenkins are back

**Comment by apolocraft** [comment]
stills down

**Comment by PikaMug** [comment]
@apolocraft This ticket is for an old Jenkins server from nearly three years ago. The current Jenkins server is not down.
