### ISSUE TITLE
Bungeecord Chat accept Quest/Quest editor

### ISSUE THREAD

**Issue by felunka** [FlyingPikachu/Quests#152]
Hi!
With Bungeecord installed you are not able to use the "non command" things of the plugin like write "yes" in the chat to accept a quest...

**Comment by felunka** [comment]
reason: FreeBungeeChat

**Comment by FlyingPikachu** [comment]
That would be an issue with FreeBungeeChat's event priorities, then. Please contact the developer of that plugin.
