### ISSUE TITLE
Data synchronization using symbolic links

### ISSUE THREAD

**Issue by leNicDev** [FlyingPikachu/Quests#152]
Version: 3.0.0-Naomi

When I'm creating a symlink to synchronize the Quests file between two servers, no data is synchronized. Is it possible to add a configuration option to disable possible caching mechanisms?

**Comment by FlyingPikachu** [comment]
Thank you for your interest in Quests! I would be open to a PR for this issue as something like this requires more attention that I can currently provide. As such, I will leave this open with a Help Wanted tag until further notice.

**Comment by FlyingPikachu** [comment]
https://stackoverflow.com/questions/16585798/best-way-to-synchronize-cache-data-between-two-servers

The SO article above leads me to believe that a SQL implementation would the best solution to this issue. Although Blackvein had plans to add SQL support to Quests (evidenced by the old BukkitDev page), no-one has requested it be implemented on this repo to date. Although I'm not against looking into that, I'm striking down the idea of a config option to control caching (unless someone wants to submit a PR for that). Maybe someday I'll have to time to add SQL support myself.

**Comment by FlyingPikachu** [comment]
Closing per last comment. See #312 for a recent request for SQL
