### ISSUE TITLE
Quest Points Save Error

### ISSUE THREAD

**Issue by seanamor** [FlyingPikachu/Quests#153]
Quests Version:
2.5.1 June 5th, 2015

Server Version:
CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Plugins:
(46): CoreProtect, SecretDoors, WorldEdit, ChatColors, FirstJoinPlus, FP, Essentials, GroupManager, ClearLag, CrackShot, Chairs, Lockette, BannerLetters, ProtocolLib, Multiverse-Core, WorldGuard, LibsDisguises, SCreed, EssentialsChat, TeleportSuite, CS-CoreLib, Hats, Vault, ColoredAnvils, EssentialsSpawn, MassiveCore, EnjinMinecraftPlugin, MyPet, Jobs, LiftSign, Werewolf, CreativeGates, KillerMoney, Citizens, Factions, Slimefun, MythicMobs, Quests, ExoticGarden, Denizen, SensibleToolbox, Towny, Sentry, dtlTraders, Magic, ProjectKorra

After creating a quest we began to create quest points required to excel, then attempted to save, after failing to do so this error code appeared in console:

25.06 23:00:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
25.06 23:00:54 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:726) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.util.Waitable.run(Waitable.java:24) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection$5.evaluate(PlayerConnection.java:988) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:54 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1040) ~[?:?]
25.06 23:00:54 [Server] INFO at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:1112) ~[?:?]
25.06 23:00:54 [Server] INFO java.lang.NullPointerException
25.06 23:00:54 [Server] ERROR Error handling conversation prompt
25.06 23:00:00 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
25.06 23:00:00 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:726) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.util.Waitable.run(Waitable.java:24) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection$5.evaluate(PlayerConnection.java:988) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
25.06 23:00:00 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1040) ~[?:?]
25.06 23:00:00 [Server] INFO at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:1112) ~[?:?]
25.06 23:00:00 [Server] INFO java.lang.NullPointerException
25.06 23:00:00 [Server] ERROR Error handling conversation prompt

**Comment by FlyingPikachu** [comment]
Please post the exact steps you took to reach that error.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
