### ISSUE TITLE
Title command successfully executed : Error

### ISSUE THREAD

**Issue by Fancepants** [FlyingPikachu/Quests#153]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 
Quests-3.0.0-Naomi.jar

(__Required__) Please describe the problem and how to replicate it. Any console errors? 
Everytime my users accept a quests it spams Title command successfully executed 2 times in a row. I am unsure how to disable this order get around it. We are on 1.12.2

![image](https://user-images.githubusercontent.com/20112780/31867734-5de7a800-b762-11e7-9735-42237ad9a01c.png)

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/MWEQYv8L

**Comment by mikroskeem** [comment]
`/gamerule sendCommandFeedback false`

**Comment by Fancepants** [comment]
yus! THANKS!

**Comment by FlyingPikachu** [comment]
Duplicate of #98
