### ISSUE TITLE
Quester data[....] not stored. Attempting manual data retrieval

### ISSUE THREAD

**Issue by Jumpy94100** [FlyingPikachu/Quests#154]
Version : 3.0.5-b185

We've got big error with quests. In fact sometimes quests are bugged. When a player finish a quest there is a big Error on the console.
Like ... it's spam the console and the server goes to ... 8 to 12 TPS. So it's unplayable. You can see the error here. The only way to fix it is to reset data of the player. It's not cool ^^'

16:06:56 CONSOLE: WARN]: [Quests] Quester data for UUID "ec72725c-5efd-33f2-b30e-524ba48c629d" not stored. Attempting manual data retrieval... 16:06:56 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to Quests v3.0.5-b185 16:06:56 CONSOLE: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 16:06:56 CONSOLE: Source) ~[?:?]

You can find here the quests.yml with the quests which is problematic.
https://pastebin.com/StPJLmQm

And here you can find the events.yml associated.
https://pastebin.com/aeuQkmHE

Thanks in advance for the help.
Have a good day :)

**Comment by FlyingPikachu** [comment]
Related to #139

**Comment by FlyingPikachu** [comment]
Please give Quests 3.0.7 a try once available and report back. Include new error if applicable. Thanks!
