### ISSUE TITLE
How to remove players from blacklist

### ISSUE THREAD

**Issue by OneBarRouter** [FlyingPikachu/Quests#155]
So I purged myself, because I needed to retest plugins, and it said that that command removed all of a player's quests data... You forgot to mention it blacklists them as well. I tried removing myself from the blacklist in the config.yml, but everytime I reload, it just adds me back. Can you please tell me how to fix this?

**Comment by FlyingPikachu** [comment]
It should not add you back. Stop your server, make sure it's your UUID you're removing, then delete that line and save before starting your server. Make sure to actually /stop your server - a /reload may not be sufficient.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response.
