### ISSUE TITLE
Chat Event not working

### ISSUE THREAD

**Issue by Skeltian** [FlyingPikachu/Quests#156]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0
(__Required__) Please describe the problem and how to replicate it. Any console errors?
No errors
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
CatchFish:
    name: Catch Fish
    ask-message: <yellow>Catch some fish!
    finish-message: <yellow>Good job. Here is some <green>experience<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          start-event: FishingStart
          death-event: DeathFail
          chat-events:
          - RodEvent
          chat-event-triggers:
          - rod
          fish-to-catch: 5
    rewards:
      exp: 250

So the issue I'm having is with the chat events. I'm even using the default quest (Catch Fish - displayed above) and the message says "Type rod in chat to receive a fishing rod" when the quest is taken. However, nothing happens when you say "rod". I've tried creating quests using the event but nothing as well. I'm using skript to handle my chat events, but when I deleted it to test it that was the issue, it still didn't work. Any ideas?

**Comment by Formula350** [comment]
I know that we sometimes experience issues with Quests plugin recognizing/processing chat triggers as well. In my case it's not an Event being used, but the "Password" quest objective. 

The one quest has a player go and find the name of a recipe in a bunker, then come back to that NPC to speak the password.
You return to the NPC and say it, nothing happens.
Say it again, and it is recognized, thereby completing the objective as expected.

That's my only thought, that you may need to say "rod", then say it once more. `*shrug*`
Would be nice not to have to do that, but sometimes to make due, so hopefully that's all it takes for that Event, too.
