### ISSUE TITLE
Quest accepting

### ISSUE THREAD

**Issue by JustinSaenCity** [FlyingPikachu/Quests#158]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.0
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Its no error, just a question. Is there  a way that when clicked on the npc the quests already starts, so not first saying Yes in chat.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Its a question so not needed.

**Comment by JustinSaenCity** [comment]
I can maybe do it with a permission given as default group, but when the quest end I take the perm of that quest so a not matching the needs to start this quest message will show up. 
If you understand it xD should that work?

**Comment by Formula350** [comment]
Oh, yea that should indeed work! Good thinking.

**Comment by JustinSaenCity** [comment]
or just (i use luckperms) add the command as reward
/lp user <player> permission set (perm for quest) false (name of the server cuz i use bungee)\
and just add the perms to the group default
Thanks for reacting and taking time :)

**Comment by Formula350** [comment]
No problem, happy to help :)

*(If this ends up working out for you, I suggest closing this ticket to help out FlyingPickachu, since he has so many open Issues as it is...)*

**Comment by JustinSaenCity** [comment]
I know, thanks :)

**Comment by JustinSaenCity** [comment]
It doesn't work, because I have to accept the quest first
![desktop screenshot 2017 10 31 - 20 12 00 55](https://user-images.githubusercontent.com/31259699/32244130-d4895ac8-be77-11e7-83f0-590f652f0682.png)

**Comment by JustinSaenCity** [comment]
Nvm, I will just not do a custom message
