### ISSUE TITLE
"No More Avaliable Quests"

### ISSUE THREAD

**Issue by Ziden** [FlyingPikachu/Quests#159]
All my players are having "no more avaliable quests" when tryng to get a new quest.

Ive migrated from 2.0.0 to the newest version of Quests, am i missing something ?

Thanks for the attention !

**Comment by FlyingPikachu** [comment]
Make sure you follow this guide:

https://github.com/FlyingPikachu/Quests/wiki/Updating-from-2.0.0

If that doesn't resolve your problem, you may have to recreate some of your quests. Keep an eye in the console for errors. If you find one that you can't fix, please post a new ticket. Thanks!
