### ISSUE TITLE
ERROR Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by sackboyrocks** [FlyingPikachu/Quests#160]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Whenever I create a quest that has anything to do with blocks or delivering, and it's in the npc's GUI, when you click on the item to start the quest you keep in the item in your inventory (ex: a pickaxe named "mining quest" goes into your inventory from the GUI) and it won't show what your objectives are. It just says ----(Quest)---- with nothing below it. If you try to view your progress with /quest, it says and internal error has occured. Here is a pastebin to the console error:
https://pastebin.com/QpvrDf1e

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Example quest: https://pastebin.com/btmw8Kqc

**Comment by FlyingPikachu** [comment]
Your error shows that Vault did not initialize properly, which is likely not the fault of Quests. Also, your Pastebin is missing the data below the InventoryClickEvent, which would be crucial to proceed. For these reasons I'm closing this issue. Feel free to create a new issue with your Vault version, startup log, and the remaining error data if the issue persists. Thanks!
