### ISSUE TITLE
Swipe Objects

### ISSUE THREAD

**Issue by Lucatortuga9** [FlyingPikachu/Quests#162]
(__Required__) What is your Quests version
Quests 2.7.6

(__Required__) Please describe the problem and how to replicate it. Any console errors?

no console errors, sometimes when a player is doing his quests, objects change, for example the quests asks 2 dirt blocks and 1 cobble, sometimes when you deliver the dirt blocks and you do /quest the plugin says: 2/1 cobble and 0/2 dirt.

**Comment by FlyingPikachu** [comment]
Thank you for your report. Without any kind of error or a sample quest to work with, there is little assistance I can provide. If you become able to provide either, please make a new issue including that new information.
