### ISSUE TITLE
Players cannot receive quests by right click.

### ISSUE THREAD

**Issue by TheCrafterian** [FlyingPikachu/Quests#162]
Whenever someone right clicks an NPC they do not get any info about available quests for the NPC. For me it works fine and for other OPs but normal players just uselessy spam their right click and still no result. I hope this plugin doesnt need a permission system so it works for normal players because my server doesnt need one, and if it needs permission system could you please set quest getting and complition automalictty assigned to default permissions?

**Comment by whoshenry** [comment]
Was this the World Guard issue I replied to on Spigot where you needed to add the interact allow flag?

**Comment by FlyingPikachu** [comment]
@whoshenry Possibly, or @TheCrafterian might not have set NPC correctly. Make sure that the desired quests have NPCs set, and that they're the correct NPCs.
