### ISSUE TITLE
Delivery Stage Won't Complete

### ISSUE THREAD

**Issue by RFSMassacre** [FlyingPikachu/Quests#163]
Whenever a player gets to stage of a quest that requires delivering items to an NPC, the quest stays in place even after you completed all the requirements. This happens with whatever kind of quest I make.

I've tried using version of Quests from 2.5.1-b82 to 2.5.1-b89. I'm using the latest version of Spigot 1.8.7. There is no error in the console, either. None of the version seem to be working.

**Comment by SurviveCraft** [comment]
Y i have the same issue. If Deliver or talk to npc is included in a stage it wont pass to the next stage.
Somebody an idea?

**Comment by FlyingPikachu** [comment]
Please create a new issue including your quests.yml if this is still a problem
