### ISSUE TITLE
translation of color is corrupted

### ISSUE THREAD

**Issue by masterstreamer** [FlyingPikachu/Quests#163]
Version: 3.0.0-Naomi

If you translate the colors in the lang/en.yml file or using a new file, e. g. white. If your quest is to shear 1 white sheep, it will not work if in the quests.yml `sheep-to-shear` is set to the translated color. But if you create the quest ingame, the valid colors are shown translated. For example with the german name for white "weiss".
en.yml:
`COLOR_WHITE: "Weiss"`

quests.yml
```
sheep-to-shear:
          - Weiss
```

Inamge editor:
`Weiss`

But after a /questadmin reload it says 0 quests loaded. Log give this:
```
[19:42:03 ERROR]: [Quests] Weiss inside sheep-to-shear: inside Stage 2 of Quest
QUESTNAME is not a valid color!
```
If i manually change the color in quests.yml to the english color "white", it works. But to take the quest ingame it says "Schere white Schaf". So the color is not translated.

**Comment by FlyingPikachu** [comment]
Information in quests.yml cannot be translated. Only your chosen language file can be translated. In other words, `COLOR_WHITE: "Weiss"` is the only necessary step.
