### ISSUE TITLE
Quester Blacklist

### ISSUE THREAD

**Issue by Time6628** [FlyingPikachu/Quests#165]
The console keeps spamming me with "Could not find data for this quester "<insert uuid here>". I'm assuming it's because I run a modded server and it's trying to get fake players data? So I blacklisted those uuids but now no one can quest? xD. 
-Time

**Comment by jusobreira** [comment]
omg, mix moded server with this plugin is a time bomb!

**Comment by FlyingPikachu** [comment]
Please create a new issue if this is still a problem. Thanks!
