### ISSUE TITLE
When my server restarts the quests gets Bug / Has to accept the quest again.

### ISSUE THREAD

**Issue by RaulCto** [FlyingPikachu/Quests#165]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hi, good day. My server it's programmable to do restarts every 5 hours, to avoid lag.
NO CONSOLE ERROR. The issue is the stages in game of a quest. 
Example: **QUEST - Deliver and kill **
- Give 10 stone 
- NextStage: Kill 2 cows
- NextStage: Give dirt 10
- NextStage: Give 2 books 
- FINISH -
PROBLEM: When a player is in the stage 'Give 10 dirt'. And the server restarts the stage and all of the progress that he has, restarts to. He have to accept again the quest- Deliver and kill. And do all agian. 
 
I't it possible to fix it :'c ??

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
No issue here. 
Thanks!

**Comment by FlyingPikachu** [comment]
For this type of issue, having no console error, you will need to provide the related quest from your quests.yml file in order to receive assistance. Thanks!

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
