### ISSUE TITLE
Quest not progressing to next stage

### ISSUE THREAD

**Issue by ForgottenLies** [FlyingPikachu/Quests#166]
The preceding stage ends with an event that triggers a warp. The quest recognizes the end of the stage, and will start the next stage (start messages show) but will not begin the objective, no matter the objective. (Tried location reach, NPC talk to, break block, catch fish, and most other ones)
Stage 3 in the text below works flawlessly, stage 4 will not fire to the objective. 

'3':
          locations-to-reach:
          - world 3617.0 64.0 -9055.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Cabin 7
          start-event: Xephos1
          finish-event: Warp
          chat-events:
          - Player2
          chat-event-triggers:
          - t
          delay: 5
          complete-message: Going to sleep...
        '4':
          npc-ids-to-talk-to:
          - 72
          finish-event: ExampleEvent

**Comment by Neoblade298** [comment]
Can you leave a pastebin of the entire quest from start to finish? pastebin.com so it's easier to copy paste it. I'll see if it works for my server.

**Comment by FlyingPikachu** [comment]
Closed due to lack of response.
