### ISSUE TITLE
Issues with the destorying and using items

### ISSUE THREAD

**Issue by droids18** [FlyingPikachu/Quests#167]
I have attempted to use buttons and levers however when they are used it does not change, does the durability need to be set for breaking/using items? If anyone could give me a rundown that would be great :)

**Comment by FlyingPikachu** [comment]
Please post the data for your quest from your quests.yml (use a site like Pastebin.com).

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. Possibly related to #157
