### ISSUE TITLE
Error Java: java.lang.NoClassDefFoundError...

### ISSUE THREAD

**Issue by Dramine** [FlyingPikachu/Quests#167]
i have error java on my server  because of plugin quests v 2.5.1-b82
![erreur java](https://cloud.githubusercontent.com/assets/13290679/8634548/7821611c-27fd-11e5-8a53-1e2635506d20.png)

my server running on spigot 1.8.

**Comment by DNx5** [comment]
do you have vault installed? if not, add Vault plugin.

**Comment by FlyingPikachu** [comment]
Closed due to lack of response.
