### ISSUE TITLE
Saving quests doesn't work?

### ISSUE THREAD

**Issue by AlHollandiyah** [FlyingPikachu/Quests#168]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests_v3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
When I save a quest it tells me to reload the quests, so I type /questadmin reload, and then it says '0 quests loaded'. However it is in the config as custom1. Why doesn't it load? Am I doing something wrong?

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/SqtNJiSZ

**Comment by masterstreamer** [comment]
Have you translated the quest into another language? If yes, you should use only latin letters.

**Comment by AlHollandiyah** [comment]
Nope, just plain english. What you see in pastebin is exactly what I entered into the Quest editor.

**Comment by FlyingPikachu** [comment]
@AlHollandiyah This means that, although saving the quest may have been successful, there was a problem loading it. If you check your console at the time you run the reload command (or during startup), it should tell you which quest is causing the problem, and perhaps even why.

If you cannot find and resolve the issue, post the relevant portion of your startup log for analysis.

**Comment by AlHollandiyah** [comment]
At the time I was reloading the quests this was the only one in the quests file. There were no others. There was also no message in the console. I have compared this quest meticulously with the stone miner one that is loaded by default, and I couldn't find anything different that I could have changed. I will look into my startup log later today.

**Comment by FlyingPikachu** [comment]
@AlHollandiyah I'm assuming everything went well post-examination of your startup log. Seeing as the load order has changed in version 3.1.2, I'll have to close this and ask that you post a new issue if the problem still exists on 3.1.2. Thanks!

**Comment by AlHollandiyah** [comment]
Will test it later with the newest version, and if it persists I will open a new ticket. Haven't been able to look at it since my last message because of sickness. Thanks!
