### ISSUE TITLE
Quests wont save player progress.

### ISSUE THREAD

**Issue by Wingbeatz** [FlyingPikachu/Quests#170]
I found this big bug right befor i was about to open my server. When i restart my server it seems that it can't save any quests progress on players, therefor resets all player progress in quests.

This is what i get when i stop the server.

http://pastebin.com/5GSeTF1q

And this is what i get when a player starts a quest (Even OP)

http://pastebin.com/3AbdyXyC

Anyone know what the problem is? Or is it the plugin itself? 

NOTE: Server running on Spigot 1.8

**Comment by FlyingPikachu** [comment]
That seems to be a problem with the location it's saving to. Make sure the folder permissions allow new files to be written.
