### ISSUE TITLE
NULL Error

### ISSUE THREAD

**Issue by TinTiger123** [FlyingPikachu/Quests#171]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? **3.1.2**

(__Required__) Please describe the problem and how to replicate it. Any console errors?  **It was added to our server and when doing /quests it just gave a list of "/quests NULL". Not sure if there were any console errors.**

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_? **I cannot.**

**Comment by FlyingPikachu** [comment]
You're either using 3.1.1, are using an incompatible version of Vault, or downloaded an old jar from Bukkit.org

If you have trouble determining which is the case, feel free to provide your startup log for analysis.

**Comment by FlyingPikachu** [comment]
A good review on Spigot by a user named @TinTiger123 indicates the issue has been resolved.
