### ISSUE TITLE
I'm having a issue with Denizen version

### ISSUE THREAD

**Issue by jusobreira** [FlyingPikachu/Quests#171]
Hi, i'm sorry bother you, but i'm having a little issue with denizen, the version you compile the plugin isn't compatible with 1.8.7, could you recompile with the right version? The version which works on 1.8.7 is 0.9.7!

Thank you very much, this plugin is the best!

**Comment by FlyingPikachu** [comment]
Please try the latest version of Quests, 2.5.3 (it has updated Denizen dependency).
