### ISSUE TITLE
Item names will not be translated

### ISSUE THREAD

**Issue by masterstreamer** [FlyingPikachu/Quests#172]
Version: 3.1.2

e.g: you have created a lang.yml to translate into another language, if the quest is to deliver items to a NPC, the quest will say the quest in the translated language, but not the item. The item name is still in english, even if your game is in another language.
The Quest in the image will work, but the translation is a little bit strange.
https://imgur.com/a/XTwgL

**Comment by FlyingPikachu** [comment]
This is because item names are loaded through Vault. Correct me if I'm wrong, but I don't believe Vault provides a workaround?

**Comment by masterstreamer** [comment]
@FlyingPikachu I think not, is there no opportunity to load the item names within your plugin as material? So they should be translated, shouldn't they?

**Comment by FlyingPikachu** [comment]
Loading from the Material enum is what Quests used to do, but was dropped simply because item formatting was unreliable. For example, the enum does not have a name for Lapis Lazuli, which is a variation of INK_SACK. Even more items have names that are not well-known to most players, such as DIODE_BLOCK_ON and DIODE_BLOCK_OFF referring to redstone Repeaters. In both cases, special rules would have to be defined per item. Trimming all this formatting, which would need to be updated for each MC release, cut down on the plugin's footprint and cuts down on headaches.

Source - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by masterstreamer** [comment]
Oh okay, maybe you will find any solution for this?

**Comment by FlyingPikachu** [comment]
Well, here's where we get the item name from Vault. As you can see, it's a single line compared to all that mess I just mentioned:

https://github.com/FlyingPikachu/Quests/blob/14882fb3eddc8402598ff4ec5003942e772085b1/src/main/java/me/blackvein/quests/util/ItemUtil.java#L184

And here's what their API gives us to work with:

https://milkbowl.github.io/VaultAPI/net/milkbowl/vault/item/Items.html

As far as I can tell, there's no way to get a localized name. So unless there's some way to setup Vault to spit out non-English item names, I think we're out of luck. Maybe @Sleaker would know?

**Comment by masterstreamer** [comment]
@FlyingPikachu maybe you can change getName() Tor getDisplayName() ?

**Comment by FlyingPikachu** [comment]
Iirc getDisplayName() retrieves the custom name if one has been set. So a normal Dirt block without a name would return nothing, whereas a Dirt block named "Randy" would return "Randy".

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#getDisplayName--

However, while checking on that I noticed there is a method available called getLocalizedName() which I have never used. I'll have to experiment to see if it does what it sounds like it might do.

**Comment by FlyingPikachu** [comment]
Looks as though getLocalizedName() was introduced in 1.11.2, so there's no point in pursuing it's use for now, unless we want to support only that version and up. Open to suggestions which would support compatibility back to Bukkit 1.7.10 (lowest supported version at time of writing).

**Comment by Sleaker** [comment]
@FlyingPikachu - nah Vault item API is not localized, and people should probably start trying to find replacements for it unless someone wants to update it with all the changes that have happened with item IDs etc.

**Comment by FlyingPikachu** [comment]
A breakthrough has been made in regards to this issue:
https://www.spigotmc.org/threads/get-string-returned-from-tellraw.304767/
