### ISSUE TITLE
Massive player corrupt file issue

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#172]
I am getting this spammed in the console sometimes, I think it's due to a player's file being corrupted - http://pastebin.com/yW3BHX6e

**Comment by Neoblade298** [comment]
Is there any way to trace it to quests? Does disabling it fix it?

**Comment by whoshenry** [comment]
I know it's Quests, there are random Quests error messages alongside this one and other examples like the BlockBreakEvent to Quests.

It's to do with a player's corrupted file. To fix it, I need to go into their file, remove all current active quests and stages. Then it's fixed.
