### ISSUE TITLE
Mobs not counting in kills

### ISSUE THREAD

**Issue by TinTiger123** [FlyingPikachu/Quests#174]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 3.1.2

(__Required__) Please describe the problem and how to replicate it. Any console errors? When you make a quest and include mob killing it does not work. I have tried disabling my mobstacker plugin and slaying the mobs then and it still doesn't count towards the quest at all. Like for example, the quest is to kill 10 pigs and if you kill a pig it doesn't count the kill at all. There are no console errors.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_? https://pastebin.com/Jxi0fn9K

**Comment by alugilak** [comment]
I have the same Problem. You can see it here: https://youtu.be/ERVzHaDclB0
maybe it's just a creation error of us?

**Comment by FlyingPikachu** [comment]
Thanks guys, this is a known bug (#143). I'll take your input into consideration there.

**Comment by TinTiger123** [comment]
Can you give us an estimated time of when the mob killing bug will be squashed?

**Comment by FlyingPikachu** [comment]
@TinTiger123 I’m currently engaged in college finals, so not at this time. Please continue this conversation at the link in my previous comment.
