### ISSUE TITLE
Mob kills / Break Blocks not working

### ISSUE THREAD

**Issue by dcapape** [FlyingPikachu/Quests#176]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.1.3  // Playing via BungeeCord

(__Required__) Please describe the problem and how to replicate it. Any console errors?
The problem happens just setting any quest. No errors in console. 

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/gsMU18we

**Comment by FlyingPikachu** [comment]
Duplicate of #175
