### ISSUE TITLE
simple quest....

### ISSUE THREAD

**Issue by halo7499** [FlyingPikachu/Quests#177]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
quests 3.0.0 naomi
(__Required__) Please describe the problem and how to replicate it. Any console errors?
when i use a vanilla item ,then ok; if i use a custom item (with 0 load item in hand) then don't work
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://one.denizenscript.com/haste/45877

**Comment by FlyingPikachu** [comment]
Thanks for your report! Please give the latest dev build a try and let us know if that doesn't resolve the issue.
