### ISSUE TITLE
Client or server crash while spawning mob in an event!

### ISSUE THREAD

**Issue by Syraleaf** [FlyingPikachu/Quests#177]
Just like it states, it throws out an error while trying to accept the quest;
to give you an idea
1: quest name

you take 1, type yes and then crash :)

Okey, so what error do I get in the console? 
Well, this one :)

07 14:20:36 [Server] ERROR This crash report has been saved to: /./crash-reports/crash-2015-07-20_14.20.36-server.txt 20.07 14:20:36 [Server] INFO ... 4 more 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:724) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:560) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1269) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.World.g(World.java:1398) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1420) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.EntityPlayer.t_(EntityPlayer.java:247) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.EntityTracker.a(EntityTracker.java:243) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:956) ~[?:1.7.0_75] 20.07 14:20:36 [Server] INFO at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922) ~[?:1.7.0_75] 20.07 14:20:36 [Server] INFO Caused by: java.util.ConcurrentModificationException 20.07 14:20:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534) [craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:728) ~[craftbukkit-1.8.3.jar:git-Bukkit-0a645a2] 20.07 14:20:36 [Server] INFO net.minecraft.server.v1_8_R2.ReportedException: Ticking entity 20.07 14:20:36 [Server] ERROR Encountered an unexpected exception

For a server crash, and this one for a client crash :)

20.07 14:14:30 [Disconnect] User Syraleaf has disconnected, reason: Internal Exception: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R1/entity/CraftLivingEntity

We're using Citizens V2.0.15 Snapshot.
We're also using the latest dev version you made :)

Hopefully this helps you fix this bug as it is a very annoying one!

Note: If you need any config files, just ask me :)
~Syra

**Comment by FlyingPikachu** [comment]
This does not appear to be an issue with Quests.
