### ISSUE TITLE
Quests Rewards keeps spamming the reward.

### ISSUE THREAD

**Issue by Legendaryx** [FlyingPikachu/Quests#178]
Suddenly 1 player is getting the quest rewards infinitely.

The items he was getting dropped everywhere. 
His money went up to 1 million.

I had to remove his whole quest data for it to stop.

This is a really game breaking bug.
How can this happen!?

**Comment by Legendaryx** [comment]
Oh btw, no errors in console.

**Comment by FlyingPikachu** [comment]
Post quest data

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
