### ISSUE TITLE
Illegal group reference

### ISSUE THREAD

**Issue by GermanElectronix** [FlyingPikachu/Quests#18]
I think I need your help. If I want to accept a quest, I get this error:
http://pastebin.com/gjPK1LSc
I have no clue what the cause is. It's printing a message, that I accepted the quest, but that's it.

**Comment by FlyingPikachu** [comment]
Cannot reproduce. Try recreating the quest. If that doesn't work, please post exactly how you accepted the Quest (through NPC, commands only, etc.). A copy of your quests.yml would also help.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
