### ISSUE TITLE
Silk Touch/ Block Break Event

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#180]
What is your Quests version / build number (do _not_ say "latest")?
Quest: 3.1.2
Server Version 1.11.2

Please describe the problem and how to replicate it. Any console errors?

-  Problem with the break block event, players are able to replace the block and break them again to finish a quest event, this leads to the quest to be pointless as they can just repeat that enough times to finish a quest.

**Comment by FlyingPikachu** [comment]
There is currently no way in CraftBukkit to differentiate between a naturally-placed block and one that has been user-placed. Furthermore, having Quests track block placement for every block placed by the user would be too costly for memory and, in the case of metadata, would not persist a restart.

You could use plugins like WorldGuard to prevent the placing of certain blocks, either globally or within a region. The same plugin can be used to disable Silk Touch if so desired.
