### ISSUE TITLE
Food items as rewards are automatically consumed

### ISSUE THREAD

**Issue by gtwy** [FlyingPikachu/Quests#180]
Reproduce:
Survival mode
1x fish (display name: "Bill's Catch of the Day") 

When a player is given this reward, he/she hears chewing and the fish is automatically consumed. This should be their decision (consume or keep in inventory until a later date.) In my case, it breaks my quest line because you can trade the fish with another NPC for $$$.

**Comment by FlyingPikachu** [comment]
This is not typical behavior, and as such, I doubt Quests is the culprit. Please check that you do not have any conflicting plugins which would cause this.
