### ISSUE TITLE
mobKill objective don't work

### ISSUE THREAD

**Issue by bigyoor** [FlyingPikachu/Quests#181]
Hello, and sorry for my bad english!

(__Required__) What is your Quests version / build number (do _not_ say "latest")?
**Version 3.1.4 #196** running on a spigot 1.12.2 server
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Sadly, there is no console errors for this bug :/
The objective mob kill don't progress when you try to do it, but no problem to create it in editor.
The other objectives seems to be Ok.

Thanks to you to keep this plugin alive! it's awesome!

**Comment by FlyingPikachu** [comment]
Thanks for your report! Another user has pointed this out to me through video. I will include that below for reference as the issue is being investigated.

https://youtu.be/lIE88jF9p4g

**Comment by FlyingPikachu** [comment]
Quests version 3.1.4 should fix the problem!

http://ci.ac3-servers.eu/job/Quests/197/

**Comment by bigyoor** [comment]
Thanks! that's a really quick bug fixing :) it works perfectly!
