### ISSUE TITLE
PigZombie reverts to "Pig Zombie" on save, which breaks the quest

### ISSUE THREAD

**Issue by gtwy** [FlyingPikachu/Quests#182]
I am using Mob "PigZombie" in one of my quests. If I edit the quest in game, it changes mobs-to-kill from from "PigZombie" to "Pig Zombie." I cannot reload the quests in game (no error message, just shows 1 less quest.)

When I reload the quests in the console, it gives me the error that "Pig Zombie" isn't a valid mob name. So I edit it in the quests.yml file and it's fine. But any time I go back into the Quests editor and make a save (even to an unrelated Stage) it reverts the name back to the incorrect version with the space.

**Comment by bokkers** [comment]
I have run in the exact same issue with CaveSpider and Cave Spider.

**Comment by FlyingPikachu** [comment]
If this is still an issue, please create a new issue with your Quests version number. Thanks!
