### ISSUE TITLE
Mob spawning into solid block throws an un-intuitive error

### ISSUE THREAD

**Issue by gtwy** [FlyingPikachu/Quests#183]
I right clicked on the ground to set a mob spawning position and it kept throwing an error in console (nothing would appear in game.) It turned out that you have to create a block above ground, click on it, add it, then remove that block.

Please add a proper error message or have the game change the spawn location to find an open space.

**Comment by FlyingPikachu** [comment]
Need the error message. If this is still a problem, please open a new issue. Thanks!
