### ISSUE TITLE
Quests plugin not working at all.

### ISSUE THREAD

**Issue by neemyo** [FlyingPikachu/Quests#184]
Build Used: Tried 3.1.2. Just tried 3.1.5 which was uploaded about 20 minutes ago, also doesn't work.

Problem: Quests plugin is not showing up at all. When I type /quests it just pops up with Minecraft's response to unknown commands: "unknown command.", it isn't in the /plugins list either. It's in the server's plugins folder and uploaded properly. Vault is installed as well. 
We also had an issue with version 3.1.2 and while that does not work at all now, it worked a week ago. During that time it also refused to save quests.

**Comment by FlyingPikachu** [comment]
Please post your startup log for analysis.

**Comment by WanderingRaven** [comment]
[2017-12-16-9.log.gz](https://github.com/FlyingPikachu/Quests/files/1584924/2017-12-16-9.log.gz)
Sorry for the delay, was very ill the past week.

**Comment by FlyingPikachu** [comment]
Startup log is spammed with errors like this:

> [04:56:07] [Server thread/ERROR]: [Quests] npc-giver-id: for Quest Stone Miner is not a valid NPC id!

You likely assigned an NPC to a certain quest, then either deleted the NPC or that NPC failed to load.
