### ISSUE TITLE
Some people in my server can't do /quests

### ISSUE THREAD

**Issue by Stephanech** [FlyingPikachu/Quests#186]
Version: 3.1.2
Spigot: 1.12

I don't have the minimum idea of what's happening here. Some of my users just can't use the command /quests, and when they try, this appears in the console:

22.12 04:36:23 [Server] WARN [QuestWorld] Task #332336 for QuestWorld v2.6.7.2 generated an exception
22.12 04:36:23 [Server] INFO java.lang.IllegalArgumentException: No enum constant me.mrCookieSlime.QuestWorld.quests.QuestStatus.REWARD_CLAIMABL
22.12 04:36:23 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_151]
22.12 04:36:23 [Server] INFO at me.mrCookieSlime.QuestWorld.quests.QuestStatus.valueOf(QuestStatus.java:1) ~[?:?]
22.12 04:36:23 [Server] INFO at me.mrCookieSlime.QuestWorld.managers.PlayerManager.getStatus(PlayerManager.java:222) ~[?:?]
22.12 04:36:23 [Server] INFO at me.mrCookieSlime.QuestWorld.managers.PlayerManager.update(PlayerManager.java:182) ~[?:?]
22.12 04:36:23 [Server] INFO at me.mrCookieSlime.QuestWorld.QuestWorld$2.run(QuestWorld.java:186) ~[?:?]
22.12 04:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
22.12 04:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
22.12 04:36:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
22.12 04:36:23 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
22.12 04:36:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
22.12 04:36:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
22.12 04:36:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by FlyingPikachu** [comment]
The error is from QuestWorld. Please look to them for assistance.

If they're unable to resolve your issue, Quests is a great alternative! :)
