### ISSUE TITLE
Ask Message

### ISSUE THREAD

**Issue by Humancraft** [FlyingPikachu/Quests#186]
Hello. Is there anyway you can add more than one line to the ask message?

**Comment by Leescar** [comment]
Edit the .yml directly and you can set messages as long as you desire.

**Comment by Humancraft** [comment]
Okay I will. Thanks! I just wasn't sure that it would bug out or do something weird, but this will be really useful. Once again, thanks.

**Comment by FlyingPikachu** [comment]
Thank you @Leesar
