### ISSUE TITLE
Players get internal errors randomly

### ISSUE THREAD

**Issue by sackboyrocks** [FlyingPikachu/Quests#187]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.0.0 Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Players will randomly get "internal errors" and will be unable to start any new quests. I'm not sure what causes this but it doesn't affect everyone. Most players can still do quests but some started getting errors. And my console is filled with errors like this:
https://pastebin.com/bYPcURFF

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/v111UxZq

**Comment by FlyingPikachu** [comment]
Your Essentials is outdated or corrupted (see error below). I'd say there's a good chance resolving this will also resolve the issue with Quests.

> 23.12 17:04:43 [Server] ERROR Could not pass event PlayerInteractEvent to Essentials v2.0.1-b499
23.12 17:04:43 [Server] INFO ... 17 more

If that doesn't improve the situation, please try updating to the latest release of Quests and post back with the 'new' errors.

**Comment by sackboyrocks** [comment]
That would make sense. I'm downloading the latest version off of EssentialsX jenkins and I'll let you know if that helps.
