### ISSUE TITLE
All quests disappeared

### ISSUE THREAD

**Issue by Bl-unt** [FlyingPikachu/Quests#187]
^Title. quests.yml is still in the plugin folder with all the quests inside. Typing /questadmin reload shows that 0 quests have been loaded, and /quests list returns that no such page exists.

**Comment by FlyingPikachu** [comment]
There is likely an error in your quests.yml. If this is still an issue, try moving the file and letting the plugin generate a new one. Then compare the file structure. You could also try an online YAML parser (use google).
