### ISSUE TITLE
Quests with periods in name cause major issue.

### ISSUE THREAD

**Issue by Formula350** [FlyingPikachu/Quests#19]
After much digging around through player data files of those who were having problems with quests on my server, I was finally able to track down the offending quest, but more importantly the reason why.

If a quest name has a period in it (apostrophe seems fine, more testing needed), for example we had put one to abbreviate "Part 1" down to "Pt. 1", will incorrectly save into the player's data file.

Example:
**currentQuests:**
- Bow of Stars Pt. 1
**questData:**
  Bow of Stars Pt:
    ' 1':
      item-delivery-amounts:
      - 0

The issue is in "questData", where the stored name does not reflect the full quest name. The player can accept the quest just fine, but anything quest-related done after that fact results in an error, effectively breaking that player's ability to utilize quests. Removal of that quest from a player's file while they are logged out resolves the issue and stops errors in the console (even on quit). Unfortunately, each time a player joins who has that issue, it needs to be addressed. 

A way to have it auto-purge a quest that is erroring in the data files of players (not matching anything in the Quests.yml), would be a huge help!

**Comment by FlyingPikachu** [comment]
Thanks for looking into this! This is likely an issue with how YAML reads/write files (with periods often separating each node). While there likely is a workaround for this, it is somewhat intentional, so I ask that you just don't use periods in quest names for the time being.
