### ISSUE TITLE
Question about Events

### ISSUE THREAD

**Issue by Ugikie** [FlyingPikachu/Quests#19]
Hey I am having some trouble with events...I am able to send a player a message in a "Start Event" but nothing happens when i add an event to "Finish Event" not sure if just not working or....

**Comment by FlyingPikachu** [comment]
@Ugikie Were you able to resolve the problem? If not, please post your Quests and Spigot versions, as well as a more detailed description of the issue. Otherwise, I will be closing this soon as no-one seems to have an answer to your question.

**Comment by Ugikie** [comment]
I don't know how, but somehow now we got a Finish Event to work...but I was definitely having the issue before so I will let you know if it comes back up again and try to locate the issue.

Spigot version 1.11.2 and Quests 2.8.6

**Comment by Ugikie** [comment]
Update: We found out the issue...you can't have a start event and a finish event...
Also, you can't have more than 1 start event in a stage..which would be really useful...

Hopefully these aren't difficult issues to fix/implement

**Comment by FlyingPikachu** [comment]
Only having one start event is intentional and I was able to utilize both a start and finish event using the following configuration. At any rate, it seems you were able to resolve your issue.

https://pastebin.com/yaDMZMkd
