### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by Loonytoon1997** [FlyingPikachu/Quests#191]
http://pastebin.com/wW3QQmD3
http://pastebin.com/LTv02vRd
http://pastebin.com/6NZFDapn
http://pastebin.com/1u83X3SJ
http://pastebin.com/XsASxTi0

Been using for a day or two now, here are some errors that I have encountered. 
Please fix them, oh and P.S, love the plugin. :)

**Comment by FlyingPikachu** [comment]
Duplicate of multiple issues, closing as these are best handled individually. Thank you for using Quests!
