### ISSUE TITLE
Getting This error constantly

### ISSUE THREAD

**Issue by PengBread** [FlyingPikachu/Quests#191]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.1.6
(__Required__) Please describe the problem and how to replicate it. Any console errors?
https://pastebin.com/uB6Ffknk
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/dRfvTeXe

Already Tried Updating Vault to the latest version but it's still not working.

**Comment by FlyingPikachu** [comment]
The first line of your Pastebin says:

`26.12 02:53:56 [Server] ERROR This error is caused by an incompatible version of Vault. Please consider updating.`

Update Vault.

**Comment by PengBread** [comment]
I already tried Updating Vault to the latest version but it's still not working before I report this issue.

**Comment by FlyingPikachu** [comment]
@PengBread Is there a chance you're running an older version of Bukkit/Spigot? One that isn't compatible with the latest release?

**Comment by PengBread** [comment]
Using the latest Spigot build and the Quests 3.1.6. After I deleted the quest with money as rewards the console doesn't have the error.

Start up > https://pastebin.com/bykS5hWt

**Comment by FlyingPikachu** [comment]
@PengBread I don't see Quests anywhere in your startup log. Either you don't have it in your /plugins folder or your startup log is incomplete.

**Comment by PengBread** [comment]
posted the wrong startup, i'll repost it agn.

**Comment by PengBread** [comment]
https://pastebin.com/nG5VPXHR

**Comment by FlyingPikachu** [comment]
This error was resolved a few days ago through #146. Dev build 233 or higher should resolve this issue. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/234/
