### ISSUE TITLE
Enchanted books, potions, and commands as rewards.

### ISSUE THREAD

**Issue by pab993** [FlyingPikachu/Quests#192]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.1.6
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I'm trying to give a player a reward after he/she completes a quest. The reward is a enchanted book with silk touch, but the enchanted book is useless, it can't be attached to any pickaxe, axe or weapon. I also tried to give the reward through a command, this one:
/give <player> enchanted_book 1 0 {StoredEnchantments:[{id:33,lvl:1}]}
But the console throw me an error due to the coma between the id an the lvl. Is there any way to put a command with commas?
Thanks for your attention. I love this plugin :)
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by pab993** [comment]
I found a solution. I just put the full command (With the coma) manually into the quest.yml and it works! This probably can be use to give to the players custom potions and enchantments.

**Comment by FlyingPikachu** [comment]
Glad you found a solution! Thanks for using Quests.
