### ISSUE TITLE
Birch Logs Display As Oak Logs For Quests

### ISSUE THREAD

**Issue by Vestle** [FlyingPikachu/Quests#195]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
  | Build ArtifactsQuests-3.1.6.jar |   | Quests-3.1.6.jar

(__Required__) Please describe the problem and how to replicate it. Any console errors?
http://prntscr.com/htybxw
Displays as Oak quest 0/10 when it requires birch logs being cut down. Still need to cut birch trees but it keeps track as Oak 5/10 as an example
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/qsTFVRAG

**Comment by FlyingPikachu** [comment]
Does the number of logs cut increase when you break _any_ type of log block?

**Comment by Vestle** [comment]
For example as I have in the pastebin.com example, I'm using birch log. Players STILL HAVE to break birch log but it is telling the user 9/10 oak log broke. Instead of saying birch. So it's just the language file that should get updated so that the data values are being read as well and not just the item ID then defaulting to its default value of 0 data

**Comment by FlyingPikachu** [comment]
The issue has to do with how Quests looks up item names, or rather, how it _doesn't_.

Currently the ideal way to get the name for a "tangible" item is through Vault (see #172). Even that method isn't perfect, but it was introduced to supersede an older way of getting names which is less accurate, as is the case for you. However, I was too lazy at the time to convert _everything_ over, as noted here:

https://github.com/FlyingPikachu/Quests/blob/746685b583835b1f441da911256084d191b505d1/src/main/java/me/blackvein/quests/Quester.java#L1503

I will now push a commit which updates everything and should resolve your issue. However, Quests is the middle of being localized for languages other than American English. As I'm still hunting for a way to translate item names (and enchantment names) to other languages, which Vault does not natively support, all this may be irrelevant in a matter of days.

**Comment by FlyingPikachu** [comment]
Fix available in this dev build - http://ci.ac3-servers.eu/job/Quests/219/

**Comment by Vestle** [comment]
Latest dev build causes this to happen. Glitch https://imgur.com/a/TGfhN

**Comment by FlyingPikachu** [comment]
@Vestle I don't understand what you're trying to tell me in that image. If this is unrelated to the titular problem, please open a new issue.
