### ISSUE TITLE
hello no files are created when i restart my server i am new to this plugin

### ISSUE THREAD

**Issue by halowhoflungpoo** [FlyingPikachu/Quests#195]
hello everyone i am brand new to this. i have tried many versions on my server which is 1.8 bukkit . and when i reload my server the folder nor any of the files are created i have citizens 2 ver2.0.14 and vault ver1.5.0-b28 and mcmmo 1.5.00-b3547 . what am i doing wrong that the folder wont create?

**Comment by TheMeq** [comment]
Does the account the server is running on have enough permission to create new directory's and files?

**Comment by FlyingPikachu** [comment]
Closed due to lack of response.
