### ISSUE TITLE
ISSUE: Quest will not complete even after advancing though last stage

### ISSUE THREAD

**Issue by james8470** [FlyingPikachu/Quests#196]
After accepting an certain quest on my server and completing all stages on it (there is only one) by talking to another NPC besides the start NPC, it simply declares "Stage Complete: Talk to (NPC" or whatever it says for completing a objective, but it does not finish the quest for the player and award the rewards. 

This quest used to work perfectly, but not anymore. I even tried removing the quest and remaking it, but it still fails to work correctly. Am I doing something wrong or is this some kind of glitch?

Thank you for reading!

Regards, James

**Comment by TheMeq** [comment]
open your quests.yml file look at the differences between that quest and another quest.

**Comment by FlyingPikachu** [comment]
Please create a new issue if this is still a problem. Thanks!
