### ISSUE TITLE
Amelioration stage: Talk to NPC

### ISSUE THREAD

**Issue by Lemrigue** [FlyingPikachu/Quests#197]
After a player finish a quest where he had to talk to a NPC, and he click another time to the NPC after finish the quest, it will displays that the NPC doesn't have any other quests available. Even if the NPC was not the NPC who give the quest. 
Is it possible to disable the message ? 
Not for the NPC who give the quest but for the NPC to which one had to talk

**Comment by FlyingPikachu** [comment]
As I recall this is intentional and cannot be disabled. However, you can change the message in your Quests/lang folder.
