### ISSUE TITLE
Reinforced Spawner "is not formatted Properly!"

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [FlyingPikachu/Quests#198]
I get this error:
name-MOB_SPAWNER:amount-1:displayname-bReinforced Spawner:lore-7Type:bPig inside items-to-deliver: inside Stage 1 of Quest Ultra Breeding I is not formatted properly!

Here is the quest:

custom19:
    name: Ultra Breeding I
    npc-giver-id: 241
    ask-message: Hello!, I saw a New Breeding Method, Can you Craft me a Pig Spawner?
    finish-message: Thanks!, heres some Cash
    requirements:
      quests:
      - Farming I
      - Farming II
      - Farming III
      - Farming IV
      - Farming V
      fail-requirement-message: You need to Complete Farming I-V First!
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-MOB_SPAWNER:amount-1:displayname-§bReinforced Spawner:lore-§7Type:§bPig
          npc-delivery-ids:
          - 241
          delivery-messages:
          - You Delivered the Spawner!
    rewards:
      money: 500

**Comment by dmulloy2** [comment]
The plugin religiously splits item stack inputs using the : (colon), so your issue is here: ````:lore-§7Type:§bPig````

**Comment by xH3LLRAIZ3Rx** [comment]
ok thats fixed, now when I try to deliver it, it shows Reinforced Spawner (Mob Spawner) x 1 is not a required item for this Quest! how can i fix that?
