### ISSUE TITLE
Quest will not complete after killing mobs

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [FlyingPikachu/Quests#199]
When someone kill the good amount of monsters in the location nothing happens. On  the chat i can see "(Complete) You have killed zombie 25/25", but not "**Complete**" and it doesnt give me rewards. In the dictionary and after typing /quest I can see  25/25. When i'm removing the location it works.

My quest:
  custom1:
    name: Szybki zombie
    npc-giver-id: 150
    ask-message: §eW jednej z odnog kopalni zyja niezwykle smierdzace Zombie! Prosze, pozbadz sie ich. Tylko uwazaj! Szybko biegaja..
    finish-message: §eUdalo Ci sie! Porozmawiaj z ludzmi w wiosce lub przyjdz do mnie po kolejne zadania!
    requirements:
      quests:
      - Co tutaj sie dzieje?
      fail-requirement-message: §cUkoncz najpierw questa §5Co tutaj sie dzieje?§c.
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 25
          locations-to-kill:
          - Dungeony -327.0 48.0 231.0
          kill-location-radii:
          - 15
          kill-location-names:
          - legowisku §bSzybkich zombie§a

**Comment by FlyingPikachu** [comment]
You don't have any rewards set up.
