### ISSUE TITLE
Item names are bugged

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#2]
After i finished creating the quest and complete the stage my item name is bit buggy
http://prntscr.com/60v8m0

**Comment by FlyingPikachu** [comment]
Is this on Quests 2.1.3? If not, please retry and check for console errors.

**Comment by SimbaZockt** [comment]
Yes with complete regeneratet files..

**Comment by FlyingPikachu** [comment]
Fixed in Quests 2.1.4. Thanks!
