### ISSUE TITLE
Quests errors

### ISSUE THREAD

**Issue by Aimon94** [FlyingPikachu/Quests#20]
I've been using this plugin for a long time, and it does not work much, why is not the corrective work performed? From the very first versions and up to the last few mistakes were corrected, I can describe everything that does not work (if you fix it)

**Comment by GregZ123** [comment]
This is not really an issue report, you need to say what the issues that you are experiencing are and how they can be reproduced. If applicable you should also include console logs and the quests config.

**Comment by FlyingPikachu** [comment]
@Aimon94 Greg is correct, please describe each problem in new issues (preferably one per problem). Be as detailed as possible.

It should be noted that only bugs in the most recent versions of Quests are of interest at this time.
