### ISSUE TITLE
Sponge and Quests future

### ISSUE THREAD

**Issue by n0ct** [FlyingPikachu/Quests#201]
First of all, This is not really an issue but it's more a question:
I am a sysadmin for a minecraft players community. We have a long term project and in this project we would like to use quests. But we also would like to use some mods and in a long while we will probably use sponge in order to do that. (Or should we use Forge ?)
**Will Quests be continued on Sponge when it will be released ? Will it be possible to have a quests configuration portability ?**

I ask this question now to avoid telling later to my players: "Sorry, all the quests you already created will be deleted now we start using sponge to add the custom classes and other mods."

**Comment by ShepherdJerred** [comment]
It's not even supported on Spigot.Bukkit anymore.

**Comment by n0ct** [comment]
It still work on the last spigot version.

**Comment by ShepherdJerred** [comment]
Yes, but it isn't supported.

**Comment by oddare** [comment]
Any words on this?

**Comment by ShepherdJerred** [comment]
Once again, the project was abandoned by the developer.

**Comment by FlyingPikachu** [comment]
I have no plans to continue development on Sponge. Pull requests are still accepted here and anyone interested in continuing development can PM me on Spigot. Thanks!
