### ISSUE TITLE
"/questadmin purge" blacklisted everyone?

### ISSUE THREAD

**Issue by bdr498** [FlyingPikachu/Quests#205]
I wanted to clear someone's quest data so I used /questadmin purge [name], which worked, however it also appears to have blacklisted everyone. No normal players or even ops are able to use and /quest commands and are greeted by the message that they are blacklisted and should contact a server admin if it is in error. How can I un-blacklist everyone from this "blacklist" and prevent this from happening in the future?

**Comment by FlyingPikachu** [comment]
Remove their UUIDs from config.yml

**Comment by JohOply** [comment]
Same bug

**Comment by FlyingPikachu** [comment]
Closed due to lack of response from OP. If this is still an issue, feel free to create a new ticket with more information.

**Comment by ScuroK** [comment]
@FlyingPikachu  i just have the same issue in latest version

**Comment by FlyingPikachu** [comment]
@ScuroK Please see my last comment where I said to make a new ticket if this is still an issue.
