### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#206]
Hello,

I want to create a race horse!

So I use the "reach location" and "delay", I just far?
The problem and the delay is not working, instead of having to complete the journey from one point to another in a time allotted, it gives the reward several seconds after you finish the race!
the console gives several error also ...

Thank's for your great job, FlyingPikachu.

![capture](https://cloud.githubusercontent.com/assets/10450256/9758493/419049ba-56e7-11e5-8cfe-a91968d51d51.JPG)

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
