### ISSUE TITLE
is there any ways to using a colon: in item lore?

### ISSUE THREAD

**Issue by muska104** [FlyingPikachu/Quests#207]
i cannot using : in the give item lore event
this mean i cannot using the giving event to give player a "Item Lore Stats" item or some quest information that having a colon

just like this
  test:
    items:
    - name-STONE:amount-1:displayname-testing:lore-Quest:testing:lore-information2:go!

**Comment by muska104** [comment]
i tried using %COLON% not working

**Comment by FlyingPikachu** [comment]
Not at this time.
