### ISSUE TITLE
Plugin complete shutdown with NULL on all messages

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#208]
Server Spigot Version: 1.12.1 snapshot R.1
Quest Version: 3.1.6

Issue.
Nothing would work, none of the commands and all the npcs that were originally set on quests stopped working.
![image](https://user-images.githubusercontent.com/23487437/34468363-02d7c152-eebc-11e7-8221-059ef098725a.png)

EDIT: I restarted the server a couple more times and it brought back the npc quests, but it was not GUI instead it was written in typing for the list of quests. 

I end up editing one of the quests from all npcs and it was back to normal again with GUI icons. Problem solved, but in case of it happening again, i would greatly appreciate to know what the problem was to prevent it happening again. Thanks!

**Comment by FlyingPikachu** [comment]
Does not occur for me on 3.1.6. Most likely an incompatible version of Vault or you've accidentally downloaded an old jar from Bukkit.org

If you have trouble determining which is the case, feel free to provide your startup log for analysis.

**Comment by FlyingPikachu** [comment]
Another possibility is you haven't added permissions. See https://github.com/FlyingPikachu/Quests/wiki/Commands-&-Permissions
