### ISSUE TITLE
2 quests with same required items 

### ISSUE THREAD

**Issue by Tetdoss** [FlyingPikachu/Quests#209]
Hello ! I got an issue :/

When a player has 2 quests with the same required items, only one quest takes the items, so he often has to /quests quit <quest> to give items.

Thank you ! Merci d'avance !

**Comment by FlyingPikachu** [comment]
I don't quite understand. Can you give an example?

**Comment by FlyingPikachu** [comment]
Closed due to lack of response from OP.
