### ISSUE TITLE
Quests Journal not working

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#21]
I use version 2.2.0

If I do /quests journal i get a book but there is only 1 line of text "*invalid book tag*"

**Comment by FlyingPikachu** [comment]
This seems to only happen when the player does not have any accepted quests. Minecraft applies this text when something is invalid, such as in this thread: http://www.spigotmc.org/threads/essentials-invalid-book-tag.29903/

My guess is that Minecraft requires text be set in the book at all times, but Quests only does so when the player has a quest. Attempting to verify this now.
