### ISSUE TITLE
Quests not saved.

### ISSUE THREAD

**Issue by BlueFoxx** [FlyingPikachu/Quests#21]
My quests are not saved to the server or plugin reload..

I love this plugin and would really like to use it on my server.
A solution ? There is no error in the console...
My server is in 1.11.2

**Comment by FlyingPikachu** [comment]
What is your Quests version and can you describe this in greater detail?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. If this problem persists through Quests v2.8.7, please create a new issue with the requested information. Thanks!
