### ISSUE TITLE
Can't get myself out of purge? [HELP]

### ISSUE THREAD

**Issue by Venman** [FlyingPikachu/Quests#212]
Q: So as an Owner, I "purged and blacklisted" myself and I can't seem to find a way/command to get myself out of of blacklist? I tried doing the command again and deleting my data UUID file in the files.

Q: Is there a way to get rid of the "Accept Quest: Yes / No" option? I want to make it so when a player clicks/types (/quests take <quest>) that it just accepts it right away. A lot of my players are getting confused with the typing option to confirm with they want to take it.

Overall, I want to get myself out of "purge" and I can't figure out how too. I also want to get rid of the Accept Quest option and I can't seem to find it anywhere, if possible?

**Comment by FlyingPikachu** [comment]
A: You must also delete your UUID from the blacklist in config.yml

A: Not as far as I know but there are unfortunately no plans for one.
