### ISSUE TITLE
[Server thread/WARN]: [Quests] Task #80

### ISSUE THREAD

**Issue by mewter** [FlyingPikachu/Quests#213]
I'm getting these errors every 15 seconds in the console:
http://pastebin.com/rhxJXz9X

**Comment by AdminZero** [comment]
I too seem to be getting similar errors when players quit the server or timeout:  

Example #1: http://pastebin.com/PCR2ee5k
Example #2: http://pastebin.com/rSATqtjw
Example #3: http://pastebin.com/uK5fLrLs

Is there and easy fix for this or something that perhaps configured wrong?

Hope this helps. Thanks,
AdminZero

**Comment by mewter** [comment]
i removed the plugin completly, i didnt get any answers on it so i
disbanded the quests project.
