### ISSUE TITLE
Quest's Moduels

### ISSUE THREAD

**Issue by TheGreaTGamester** [FlyingPikachu/Quests#216]
So I have many games on my server.
I have tnt run for example. I want to make a quest when a player wins 3 games they win cash. Is their any way to set this up? And I would also want to know if I can setup certine quests to be done in certine worlds.

**Comment by FlyingPikachu** [comment]
That would require integration with your tnt run plugin, which unfortunately is not planned. As for certain worlds, just use permissions.
