### ISSUE TITLE
Redundant Quest Accept Prompt

### ISSUE THREAD

**Issue by RealmShift** [FlyingPikachu/Quests#218]
This plugin is by far the best quests plugin I have found for my spigot server, and it works pretty well. However, everywhere I have seen this plugin used (the tutorial video on the site, and other servers), when a player right clicks an NPC with a quest attached, all they have to do is type either "Yes" or "No" to accept or reject the quest. However, on my 1.8 server with this plugin a player has to first type "1" or "0" to accept or cancel, and then "Yes" or "No" to accept, which seems a bit redundant. Is there any way to disable the 1 / 0 prompt?
   Thanks.
(Sorry if this is not the place to ask this, I am new to GitHub).

**Comment by FlyingPikachu** [comment]
I have never heard of having to do that before. Are you sure you're not using a different plugin?

**Comment by RealmShift** [comment]
As far as I know, no. Omcolorful's AngelBeats server has the same method (1/0 then Yes/No). But their SwordArtOnline server has the just Yes/No, just as the tutorial video on the plugin page has. It's basically this format:
~Select one~
0. (Quest Name)
1. Cancel

Then the Yes/No option (which is the only thing required almost everywhere else I have seen it).  Is it possible there is a unique version? I downloaded the latest version from the Spigot site.

**Comment by FlyingPikachu** [comment]
I agree that it's probably in case you have more than one quest per NPC. That said, I'm unsure whether it can be disabled or not.

**Comment by RealmShift** [comment]
Well there is an option to set how many quests per NPC in the yml file. I set it to 1, but only after noticing the 1/0, so it still is showing the same format. I will probably try a fresh install and configure that before creating quests.

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
