### ISSUE TITLE
Multiple messages on stage start/finish (question)

### ISSUE THREAD

**Issue by triagonal** [FlyingPikachu/Quests#219]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Edge Build #219 (but it doesn't matter)

No errors - just wondering if there's a way to send multiple messages on stage start/finish to the player instead of just one. Can't seem to find a solution in the wiki (or perhaps i'm just blind).

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from community. You may have better luck asking these types of questions on the Spigot forums. Personally, I would suggest looking at the _/quests events_ menu to see if it can do what you're trying to accomplish.
