### ISSUE TITLE
quests dupe

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#22]
Apparently a player of mine was able to dupe a quest even though it had a redo delay of 24 hours (1 day) he said he was able to click on the quest multiple time or something https://images.discordapp.net/attachments/263548298361569280/330333514153328653/2017-06-30_23.06.03.png?width=1027&height=531

**Comment by FlyingPikachu** [comment]
@ozm8 I'm closing this. We need actual evidence of a bug, or at least the means to try and recreate it. Some guy on your server claiming he duped something doesn't cut it. You also didn't provide any server details like Quests version, Spigot version, errors or config settings.

Feel free to post a new issue IF you get more information and thanks for using Quests.
