### ISSUE TITLE
Kill mobs PigZombie

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#22]
on Quest. Kill PigZombie doesnt work.

Quest says: No Vailid mob Type

**Comment by FlyingPikachu** [comment]
Are we talking about the quest editor? More details, please.

**Comment by SimbaZockt** [comment]
Yes. On the Latest version of quest in the Quest editor on Stages Kill mobs: PigZombie dont work

**Comment by FlyingPikachu** [comment]
Looks like mob names that consist of 2 words don't work (PigZombie, EnderDragon, IronGolem, et al.). Workaround for now is to use "Pig_Zombie" instead (with the underscore).
