### ISSUE TITLE
Could not pass event EntityDeathEvent to Quests v3.1.8-b222

### ISSUE THREAD

**Issue by NevendyND** [FlyingPikachu/Quests#221]
so.. I'm here again :x 

Quests v3.1.8-b222

I testet the new Version but i can't talk to him he gives me no answer and the quest freeze (No error in console) (https://github.com/FlyingPikachu/Quests/issues/220)

oh and here the EntityDeathEvent (He gives me the reward but don't the permission i set)
![deathevent](https://user-images.githubusercontent.com/28860034/34508727-d5480bec-f042-11e7-8081-1bff7bf0b2d6.png)

**Comment by NevendyND** [comment]
Found out the Quest will complete without permission reward. (no error)
The error shows only when i set as reward a permission. (for example: clickwarp.warp.* )

with the new build http://ci.ac3-servers.eu/job/Quests/222/
I can't talk to him when i set a stage to talk to him again.

**Comment by FlyingPikachu** [comment]
@NevendyND Looking into this now. Could you please reply with the following?

- Spigot version
- Vault version
- Permission plugin name and version

**Comment by NevendyND** [comment]
spigot-1.12.2
Vault (Version: 1.5.6-b49
GroupManager+ (GroupManagerX) (Version: GMBuildVer (Phoenix)+1 ) 

(but i think i change it to : https://www.spigotmc.org/resources/groupmanager-working-1-7-1-12-builds.38875/history )

ok i test the other GroupManager but i can't talk to him to finish the Quest with Permission reward.
with the new GroupManager the permission reward works.

but can't talk to him in a stage to finish the quest.

hope you understand me :s

**Comment by FlyingPikachu** [comment]
Cool. So to conclude, this EntityDeathEvent issue was likely caused by your setup between Vault and GroupManager. That's not something Quests can fix, so I'm glad you made things work. If at any point you want to seek further help with this, contact the authors of Vault or GroupManager and link them to this bug.

As for the not being able to talk to the NPC, it looks like the fix for #220 didn't work. I'll reopen that issue while I work on a fix.

**Comment by NevendyND** [comment]
I downloaded a new Vault and delete the folder.

Can't talk to him to finish the quest 
![htfhth](https://user-images.githubusercontent.com/28860034/34542412-c0dab1f6-f0dc-11e7-9387-248bc863fa6c.png)

jep the only thing is when i want that the player must talk again to a npc to finish the quest the npc ignore the rightclick, but jea i create a Stage 2 its only a startmessage and talk to npc.
Here is the Quest: https://pastebin.com/WHHbYYyn

no errors :o
