### ISSUE TITLE
Deliver Task doesnt complete

### ISSUE THREAD

**Issue by ModdyLP** [FlyingPikachu/Quests#223]
Hello

we have on our server the issue,that the Deliver Task as last stage or as middle stage doesnt complete the quest or the stage. In the console is no error apearring. Sometimes is the Deliver Task working but only for short time.

Please help, we need this feature as soon as possible.

Best regards
ModdyLP

**Comment by ModdyLP** [comment]
My Server Version Minecraft Spigot 1.8.8 
Citizens build 1267
Quest build q92
Which information do you need also?

**Comment by FlyingPikachu** [comment]
Post your quests.yml

**Comment by ModdyLP** [comment]
here the quest.yml

I have seen some yaml syntax mistakes, i correct these errors and now i will try it but you can take a look if you see something else.

http://pastebin.com/5d5C1ANc

**Comment by FlyingPikachu** [comment]
Looks alright to me. If you're still having the problem even with fixing those syntax mistakes, then post back here and say which quest in particular isn't working.

**Comment by ModdyLP** [comment]
It hadn't fixed after i correct the mistakes. http://pastebin.com/7b0uLP6D

Here the quests they dont work:
custom12
custom2
custom9
custom10
custom1

One delivery quest is working: 
custom15

I hope you have a solution for me, becouse i think it is really weird.

**Comment by FlyingPikachu** [comment]
I looked at each of them and I don't see anything particularly wrong. Unfortunately, there's not much else I can do without a console error. Perhaps you could backup then delete those quests, just to see if that solves the problem?

**Comment by ModdyLP** [comment]
I had delete all quests for a while but that didnt solve the issue. It is really Bad that this didnt work becouse we had member they want to use it. :(
