### ISSUE TITLE
Spacing Issues with GUI

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#224]
This is just a simple example of trying to figure another alternative to make things easier for people who uses GUI to accept quests. 

Issue: The current GUI system is not as user-friendly, as the default line is &5 aka purple color code and it does not have an option in the GUI to do line skipping
![image](https://user-images.githubusercontent.com/23487437/34644555-afadcb80-f2ed-11e7-9c18-8766f036aa79.png)

**Comment by FlyingPikachu** [comment]
It is indeed possible to start a new line, althought I can’t recall how. Once you do it’s simply a matter of putting a color code first in the new line. See this old ticket
https://github.com/Blackvein/Quests/issues/56

Leaving this open until I can give this more attention.

**Comment by johnsoncui02** [comment]
I made and went through the mess to count the exact spacing when 2 color codes are invovled and this is the exact spacing. As for future reference for those who consider the same issue. copy paste this link

    ask-message: '&e&m-                       &r            &aObjective: &b                           &b- Kill 50 Chickens                      &b- Kill 20 Cows &b                       &e&m-                       &r            &aReward: &b                              &b$800    &b                              &d               &a                      &dCooldown :                             &3 * 24 Hrs                 &r            '

![image](https://user-images.githubusercontent.com/23487437/34645259-7dea1986-f2fd-11e7-9266-3ae7ae990a29.png)

But with the chestcommands fix it would be much better off.

**Comment by FlyingPikachu** [comment]
Closing as OP was able to work out a solution.
