### ISSUE TITLE
Quick Question about NPC responses.

### ISSUE THREAD

**Issue by Durtturbine** [FlyingPikachu/Quests#226]
Is there anyway I could edit the text an NPC says to have it include the questers Name? For instance on completion of the quest the NPC says  "Thanks '@playername' for killing those pesky mobs for me.'
![2015-11-13_22 55 45](https://cloud.githubusercontent.com/assets/15843729/11162516/1a6980da-8a5a-11e5-87ce-4d111b99a5b1.png)

**Comment by Durtturbine** [comment]
Also, Anytime I try and set an initial event, save the quest and do a reload. It clears the initial event.

**Comment by FlyingPikachu** [comment]
That is the "finish message" if I'm not mistaken. You can either edit via commands or go to your quests.yml file.

Please create a new issue with more information for your other problem.
