### ISSUE TITLE
Entire commands

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#228]
Hi

I love GUI system to create quests ! :p 
But there is a "problem" : i can't automate actions or commands to change quests from console.

So, please can you add entire commands in addition to GUI ?

English isn't my native language, so if you don't understand something, tell me please ! 

Thanks !

**Comment by FlyingPikachu** [comment]
Please provide a list of commands that you would like added.

**Comment by JohOply** [comment]
Thank you for your answer !

- all commands related to requirements
- set NPC start

**Comment by FlyingPikachu** [comment]
I tried doing this and it proved cumbersome because of how Quests handles commands. And since the only commands that could benefit from the change are /quests top, /quests editor, and /quests info, I have chosen not to proceed. Sorry, but thank you for the suggestion and your interest in Quests!

**Comment by JohOply** [comment]
Is it possible to do something like that : " /quests editor 1 4 5 2 1 1 3 exit " to simulate gui ?
