### ISSUE TITLE
Suggestion for a Placeholder API Update

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#228]
Suggestion: This request seems to be troublesome when it comes to coding it. By adding a placeholder of sorts to track the quest progress would be a very nice addon to the plugin feature. So say when i kill a pig or broke a block that the quest requires it would show some sort of progress in either on the scoreboard, action bar, etc.. Rather than using the command /quest every time a player is concerned with how much progress they have made.

Suggestion 2: Setup some sort of a timed quest event for players to compete. So say a quest to whomever kills the most zombies within a 3 day timeframe or whatnot, and reward players from 1st to 3rd. Yeah... this sounds like you might have to actually recode the whole plugin. anyways, food for thought. Just a suggestion.

Edit: Hopefully all these threads from me aren't bothersome. Let me know if it needs to be eased down.

**Comment by FlyingPikachu** [comment]
Although a scoreboard or action bar for it could be interesting, the first suggestion implies that quest tracking does no exist, which it does, in /quests journal. Unless an issue is created to specifically explore new types of tracking, I'm counting this as already implemented.

The second suggestion can likely be accomplished through a Timer Event which was added in Quests 3.0.0, however expanding upon this functionality is already being explored in #93. As such, I'm counting this suggestion as a duplicate.
