### ISSUE TITLE
Players have choice : 1 question, 2 (or more?) answers

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#229]
Hi guys !

I have an idea to improve this very nice plugin (I hope dev isn't really inactive :/)

Can you add a question/answer system, with differents actions possible for each choice
For instance, NPC asks to player "Do you want help me?"
Player can say "Yes" or "No".
If "yes", there is a particular action and story, if "no", another action and story.

If you don't understand something, please tell me !

Thanks in advance :)

**Comment by xH3LLRAIZ3Rx** [comment]
I agree, add this :D

**Comment by xxmarijnw** [comment]
This would be terrible to add this to the starting NPC, as you can't deny the quest if you accidentally click it. This would be better suitable if you are already in a quest.

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
