### ISSUE TITLE
You can remove items from quest gui with shift + rightclick

### ISSUE THREAD

**Issue by i9hdkill** [FlyingPikachu/Quests#23]
Open a quest gui and shift + rightclick on a questicon.
You now have that item in your inventory.

spigot 1.12
https://pastebin.com/tKVSFDpx

**Comment by ghacproductions** [comment]
This occurs when one of your quests has (one/multiple?) dot(s) (".") in their name as the name is used for creating a config-section and the path may not contain multiple dots following each other.

**Comment by FlyingPikachu** [comment]
@ghacproductions appears to be correct. Using the latest build, I was able to shift + right-click to accept a quest without any issues.

It should be noted that the in-game Quest Editor does not allow periods or commas to be used in names (in any amount).
