### ISSUE TITLE
null null null

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#230]
(__Required__) What is your Quests version / build number Quests-3.2.0

(__Required__) Please describe the problem and how to replicate it. Any console errors? When you do a command any quests command it says:

/quests NULL
/quests NULL
/quests NULL
/quests NULL
/quests NULL
/quests NULL
/quests NULL
/quests NULL
/quests NULL
/quests NULL

[img]https://i.imgur.com/0K0aSYQ.png[/img]

and there are no errors in the log
I also tried restarting the server a few time and still no lunk
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_? I just started a new server so its the default https://pastebin.com/z1F6wSdj

**Comment by FlyingPikachu** [comment]
You either have an incompatible version of Vault, have accidentally downloaded an old jar from BukkitDev. or did not give yourself the proper command permissions.
