### ISSUE TITLE
Chat Triggers And Events (Kind of)

### ISSUE THREAD

**Issue by BakProject** [FlyingPikachu/Quests#231]
# Objective Password / Chat Triggers (Events)

I have another thread going about the GUI and suggestions. And as the plugin is updating and changing I needed to learn about the events so I started exploring them. On chat Triggers the chat is spammed if a player is not spelling or repeating it exactly as the trigger is. There should be a multiple entry on the chat event using pipes, same as the Password Objectives. But the problem with both of these is chat is not muted when chatted correctly/incorrectly. I think there could be a little mute timer for 20 seconds or a close detection.

The mute could be kind of like how the ask confirmation is. When the Player types "Yes" or "No" the message does not show up in the chat. A 20 second grace period, or shorter by 5-10 seconds. But this "grace period" is only activated when the event is noticed in a stage.

 # Multiple Entries on Chat Trigger Events

On the chat entries there is only an option to have 1 selection of text. But say the player adds a " . " at the end when the chat trigger does not! The trigger is not activated and it is useless. Maybe I am just over looking something? 

Thank you for reading
- BakProject (MCForest.net)

**Comment by FlyingPikachu** [comment]
This feature has been tweaked slightly over the past year and I'm unsure if this is still a problem. If so, please comment below or make a new issue and I'll take another look.
