### ISSUE TITLE
Addon to the chestcommand suggestion

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#232]
When the stage for talk-to-npc event after the quest is fulfilled, a player has to go back to the NPC to talk to him in order to finish the quest fully. It works fine as it is, but it spams alot of messages such as the following image due to adding the turn in stage to one of NPCs. Is it possible to fix the issue?

EDIT: I'm using chestcommands to fulfill the quest GUI.

![image](https://user-images.githubusercontent.com/23487437/34712400-94113420-f4d7-11e7-9269-3581d39c464a.png)

**Comment by FlyingPikachu** [comment]
Does this only occur when using ChestCommands or can I replicate this without it?

**Comment by johnsoncui03** [comment]
It's replicatable by selecting a talk to event. Say after you finish a quest and your second stage is to talk to some other box. That "some other npc" that was selected is the one having this issue.

Talk-to-event

**Comment by FlyingPikachu** [comment]
Fairly certain this was resolved some time ago. If not, comment below with an example quest to test with and I'll re-open the issue.
