### ISSUE TITLE
Console spam when a player joins the server.

### ISSUE THREAD

**Issue by RandomGaming** [FlyingPikachu/Quests#233]
Hello,
Whenever a player joins my server, I get spammed with something about Quests. Anyway to fix it?

18.11 15:40:08 [Multicraft] RandomMC ran command Message of the Day
18.11 15:40:08 [Connect] User RandomMC, IP XXXXXXXXX
18.11 15:40:08 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:813) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
18.11 15:40:08 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
18.11 15:40:08 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
18.11 15:40:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
18.11 15:40:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
18.11 15:40:08 [Server] INFO at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:784) [Quests.jar:?]
18.11 15:40:08 [Server] INFO at me.blackvein.quests.Quester.loadData(Quester.java:2507) [Quests.jar:?]
18.11 15:40:08 [Server] INFO at me.blackvein.quests.Quester.hardClear(Quester.java:3398) [Quests.jar:?]
18.11 15:40:08 [Server] INFO at java.lang.Class.getMethod(Class.java:1665) ~[?:1.7.0_65]
18.11 15:40:08 [Server] INFO java.lang.NoSuchMethodException: me.blackvein.quests.Quester$1.hardClear(java.lang.Object)
18.11 15:40:08 [Server] ERROR null

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
