### ISSUE TITLE
Problem with new Language system

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#233]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.0
(__Required__) Please describe the problem and how to replicate it. Any console errors?
in the latest version on german some editor messages create problems. its unclear if we should type "cancel" or "Abbrechen" for example. It would be better to have a placeholder for key-words like this and translate those words seperately. otherwise the plugin tells me to type "cancel" but expects "Abbrechen"

**Comment by FlyingPikachu** [comment]
This does not surprise me as translations are provided by the community. I will attempt to correct this myself in the future, but if you cannot wait, feel free to submit correct strings yourself:

https://crowdin.com/project/translate-quests

**Comment by FlyingPikachu** [comment]
Quests version 3.2.1 includes updated German strings which should resolve this issue.
