### ISSUE TITLE
/questadmin reload broken

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#234]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.0
(__Required__) Please describe the problem and how to replicate it. Any console errors?
i use de-DE language. If i do /questadmin reload it tells me this is an unknown command. no errors in the console. can you fix this pls?

**Comment by FlyingPikachu** [comment]
This does not surprise me as translations are provided by the community. I will attempt to correct this myself in the future, but if you cannot wait, feel free to submit correct strings yourself:

https://crowdin.com/project/translate-quests

**Comment by ScuroK** [comment]
@FlyingPikachu The crowdin translation already contains translations wich cause editors not to work.
Therefor i would prefere to translate the whole .yml file myself so that everything will work fine. Will you accept a finished file? And how can i send it to you?

**Comment by FlyingPikachu** [comment]
Note there's a chance this may be fixed in Quests 3.2.1

Feel free to translate the entire file and upload it on Crowdin (there should be an option called "Upload Translations). Note that a user named "Enterih" just submitted translations for the last few strings hours ago, so it not might be worth the effort to translate anything besides what you find to be erroneous.

**Comment by Sprungente** [comment]
enterih is here :)

Wäre echt cool, wenn du später bei der Optimierung behilflich sein kannst. Ein Problem ist derzeit, dass das ganze nicht einheitlich ist. So ist der /questsadmin reload derzeit zu /questsadmin neuLaden übersetzt, wofür ich bereits eine Änderung zum klassischen "reload" Befehl vorschgeschlagen habe. 

Warum es nun im Detail trotzdem nicht geht, ist mir ein Rätsel

**Comment by Sprungente** [comment]
@FlyingPikachu use Electro Ball to crowdin 

i have translated some commands into German and i think "neuLaden" doesnt exist, Please checkup Suggestions or change itself back to "reload". Many commands are involved in this issue,

**Comment by FlyingPikachu** [comment]
I have resolved this on Crowdin and the change will be included in the next major release of Quests. You may have to let the plugin regenerate your strings.yml for the update to take effect.

For future issues like this, please don't hesitate to resolve the issue yourself by correcting the translation on Crowdin - https://crowdin.com/project/translate-quests
