### ISSUE TITLE
Errors with reload

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#234]
Hi,

Last time i want to reload quests, i have this error : http://pastebin.com/gEfLgXBh

**Comment by Flynnftw** [comment]
I am having the same issue. http://pastebin.com/ezyAR7WD

**Comment by FlyingPikachu** [comment]
That looks like an error within your quests.yml file. Perhaps if you post it someone can take a look for you.

**Comment by JohOply** [comment]
Others errors : http://pastebin.com/fBxqaEj9 (the plugin doesn't work after these errors)

events (seems be buggy: IG, there isn't any events even if there is default config) http://pastebin.com/GgZTXxwk
quests http://pastebin.com/AYPjPM1f

**Comment by JohOply** [comment]
I have another error (when server start), i don't know if there is a link : http://pastebin.com/tzDd61JU

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
