### ISSUE TITLE
Missing messages file

### ISSUE THREAD

**Issue by JustDJplease** [FlyingPikachu/Quests#235]
I would like to inform you about the following thread on the spigot forums:
https://www.spigotmc.org/threads/quests-plugin-null-error-please-help.295951/#post-2832521

Kind regards,
JustDJplease / TheBlockBender

**Comment by FlyingPikachu** [comment]
Thanks for bringing that to my attention. Once available, the following dev build contains a fix:
http://ci.ac3-servers.eu/job/Quests/234/

**Comment by Patfreeze** [comment]
Hello,

Got the same Issue but for fr-QC, I'm on Windows. [ I know, not the good place for testing 😄 ]

Code I use in my own plugin to bypass this problem :
`getDataFolder()` <--- give me the /plugins/MY_FOLDER_PLUGIN
`File.separator` <--- change the / or \ depend on plateform.

**CODE:**
`
File file = new File(   getDataFolder() +  File.separator +  "Players",   "playerMario.yml" );
`

Hope this will help. But Linux is the BEST!! 😆

**Comment by PikaMug** [comment]
@Patfreeze The solution you've proposed is unrelated to the original issue, which has already been fixed.

Currently, fr-QC is not a supported language. You may request it by contacting me on [Crowdin](https://crowdin.com/project/translate-quests).

The plugin already uses File#separator for language files, shown here:
https://github.com/PikaMug/Quests/blob/39a1c3edc7cdfb09ee78c0a3cf88ee011fb906b5/main/src/main/java/me/blackvein/quests/util/Lang.java#L130-L133

If you're having issues with files not generating, please see https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting
