### ISSUE TITLE
Dev Request

### ISSUE THREAD

**Issue by TheCheatCode** [FlyingPikachu/Quests#236]
We have found some small bugs with the plugin on our server and I DLed the source code and believe I can fix them, but my eclipse is being annoying. never used it for minecraft coding before.

If you can tell me how to get past the red lines in my imports I can commit the bug fixes I do if you'd like. Currently looking at the items dropping from GUI inventory and the redo timer reset on relog, pretty sure i already fixed the GUI one, but with my imports failing i can't be sure.

my imports for org.craftbukkit.v1_8_2, v1_8_1, etc that don't have their own jar won't read them from the 1.8.3 jar (or I don't know how to make them do it). If you can help me solve this I can help you bug-fix.

Thanks

**Comment by FlyingPikachu** [comment]
You must also have those versions of CraftBukkit. Either obtain them the official way by following

https://www.spigotmc.org/wiki/buildtools/

or visit http://getspigot.org/

**Comment by TheCheatCode** [comment]
hm, the buildtools say they can only be used for 1.8, 1.8.3, and 1.8.6. I have those, but what do I do about the in-between imports? I've included a screenshot of the 1.8.2 import redlines and my lib can be seen on the left.

Thanks for the quick reply to my first comment!

**Comment by TheCheatCode** [comment]
https://gyazo.com/ff838ee6adbbdbb8f692109aa064dd48

**Comment by FlyingPikachu** [comment]
Those are examples, using the "--rev 1.8.2" flag should compile that version for you.

Unfortunately, I can't help you obtain a jar beyond that advice for legal reasons. If you manage to acquire a build and need further assistance, make a new issue. Thanks!
