### ISSUE TITLE
Reset Objective

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#236]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.0

(__Required__) Please describe the problem and how to replicate it. Any console errors?
if the player re-enters the server, the "break block" task is reset and duplicated in / quest

https://pastebin.com/KGEqARHJ

**Comment by FlyingPikachu** [comment]
This error was resolved a few days ago through #146. Dev build 233 or higher should resolve this issue. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/234/
