### ISSUE TITLE
New requirements and stages

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#237]
Hi guys

I have some ideas (i didn't see it, so if i'm wrong, please tell me where i can find this)

- Add a requirement: have less than X quest's points (a bit like have at least X quest's points)
- Add a count for quests (per day?). Thats allow some new options :
  - Add a "requirement" (it is more a limit): a player can do MAX Z times "Y" quest each day (For instance : a player can do (and succeed) 10 times farmer quest each day, not more)
  - Add a requirement: Done X times Y quest (for instance : to be able to do librarian's quest, player have to done 5 times farmer's quest)
- Add stages : Crafting, Smelting (in furnace), Potions brewering
- Add a general message for the quest (in addition to a starting stage message) : because, currently, if i use NPC Gui, the first message is into the Gui, and not in the chat.
- Add an option to remove progression messages (like "----(QUEST NAME)----", "Talk to...", "*QUEST COMPLETE: QUEST NAME*", etc. Except for rewards :)

English isn't my native language, so if you don't understand something, please tell me :)

Thanks!

**Comment by FlyingPikachu** [comment]
Since players cannot lose quest points, I feel the first bullet is counter-intuitive
The "count for quests" can already be done with a redo-delay.
Adding stages has already been look at (see #24).

Not sure I understand what you mean about a general message?

Most messages can be configured in strings.yml. So you could probably change all of those to an empty string (" ").

**Comment by JohOply** [comment]
- The first bullet can be useful for "tutorial quest" for instance, if some quests give some items but i want that only for new players (or in this case, player who have less x points)
- I'm not sure understand your answer for the second bullet, can I create the two requirement which follow?
- Okay, I seen it. But i think there is a big difference between craft (for instance), and deliver : with craft, player MUST do an action. With deliver only, the player can take items in his chests and take less time to do the quest :)
- I'm not sure about it, but if i understand the plugin, the first message is the first stage, because the first message of the quest is into the desc in GUI of NPC
- If i put an empty string, is there an empty line in the chat ?

If something is not clear, tell me please i will try to explain more ^^

**Comment by FlyingPikachu** [comment]
Good point, a point cap could be useful for that.

There is already an option to make a player wait X amount of time before they can redo the quest.

You are correct about crafting, but I feel it is up to the quest maker to set delivery that cannot be easily obtained.

For the last bullet, yes there will probably be an empty line in the chat. Try it and see!
