### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#238]
Hello again!

- Can i add an "enter" (like " \n "), to have two lines in 1 message ? :)
- Can i use an order for stages ? (Stage 1 must before Stage 2, etc)

Thanks in advance

**Comment by FlyingPikachu** [comment]
For a line break use %br% (http://dev.bukkit.org/bukkit-plugins/quests/pages/main/translations/).

Not sure what you mean about order for stages.

**Comment by JohOply** [comment]
I want to know if stages are ordered or not. For instance : 
- Stage 1 : talk to NPC n°1
- Stage 2 : delivrer 3 dirt to NPC 1
- Stage 3 : talk to NPC n°2

A player who do this quest, what happen? He must done stage 1, then stage 2 and finally stage 3. Or he can done stage 3, then 1 and finally stage 3 (or any other sequence)

**Comment by FlyingPikachu** [comment]
They are ordered.
