### ISSUE TITLE
Error show objective

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#238]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1
(__Required__) Please describe the problem and how to replicate it. Any console errors?

12.01 08:31:17 [Server] WARN at java.lang.Thread.run(Thread.java:745)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
12.01 08:31:17 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12.01 08:31:17 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
12.01 08:31:17 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
12.01 08:31:17 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
12.01 08:31:17 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
12.01 08:31:17 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12.01 08:31:17 [Server] WARN at me.blackvein.quests.Quests.onCommand(Quests.java:659)
12.01 08:31:17 [Server] WARN at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1696)
12.01 08:31:17 [Server] WARN at me.blackvein.quests.Quests.showObjectives(Quests.java:1856)
12.01 08:31:17 [Server] WARN java.lang.NullPointerException

**Comment by FlyingPikachu** [comment]
Is this related to your previous issue?

Please describe the steps you took to encounter this error.

**Comment by SwimUp29** [comment]
I delete quests 3.2.0, stopped server, download quests 3.2.1 --> start server 
and sometimes I see this error in the console

+ my players sometimes can not refuse the quest, they get a message that the job does not exist, although through /questsadmin quit I can reject the quest

**Comment by FlyingPikachu** [comment]
I'd say this is likely the cause of the other errors you've posted. Please give this dev build a try:

http://ci.ac3-servers.eu/job/Quests/243/

Once the error occurs, you will see it mention the name of a particular quest. Post that quest from quests.yml AND the new error here to receive further assistance.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
