### ISSUE TITLE
Quest Chains not working. (quests requiring previous quests)

### ISSUE THREAD

**Issue by SpiffyLich** [FlyingPikachu/Quests#239]
pretty much, as the title says, quests that have the requirement that you have completed a different, listed quest, do not work / launch.

immediately the "requirement failed" message will display upon attempting to start the quest.

a better explanation: if I have 2 quests, A , and C-   

and to Start quest A, I must have completed quest C...

 even after having completed and received the rewards from C, quest A still will display the "requirements not met" message.

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
