### ISSUE TITLE
Issue with 'mobs-to-kill' event...

### ISSUE THREAD

**Issue by Ugikie** [FlyingPikachu/Quests#24]
When making a quest and using the kill mob objective, I choose a mob like Elder Guardian for example and then upon saving and reloading the plugin, I get this error in console

_## ERROR Elder Guardian inside mobs-to-kill: inside Stage 7 of Quest Captain Kent is not a valid mob name!
and then my quests doesn't show up in the list of quests..._

I went to the quests.yml and changed
mobs-to-kill:
**Elder Guardian**

to

mobs-to-kill
**Elder_Guardian**

and performed a /questadmin reload and it worked, the quest appeared in the list...but then editing the quest and saving and reloading the plugin again, **reverted the "Elder_Guardian" back to "Elder Guardian"** and broke it yet again...

Quests version 2.8.6 Spigot 1.11.2

**Comment by FlyingPikachu** [comment]
Probably never added as a supported mob. Will likely be fixed alongside #18

**Comment by FlyingPikachu** [comment]
I was wrong, all mobs are supported for mobs-to-kill and this is unrelated to #18 

When first creating a quest, mobs are saved correctly (in your case as "EnderGuardian"). However, upon going back to edit the quest, mobs will be incorrectly saved by their display name ("Ender Guardian").

While underscores are accounted for, spaces were not. A fix will be pushed shortly. Thanks @Ugikie
