### ISSUE TITLE
Feature Request: Craft & Smelt Tasks

### ISSUE THREAD

**Issue by Grasty** [FlyingPikachu/Quests#24]
Other Quest plugins (EpicQuest) have the ability to make players craft or smelt an item, but Quests does not. It would be nice if these could be added to Quests. Currently I just use the Deliver Items Task to have the players deliver the items to an NPC, but i cant stop them from just taking the items out of their inventory ... Not a big deal, but it would be nice if i could make them smelt or craft as it would let me force players to go find ore to smelt or the materials for something.

Granted i can work around it with other tasks like Mine x iron ore, deliver x iron ingots to x NPC. But it would be nice if i could make them smelt it too.

Not terribly important, would just be nice if it was added.

Thanks!

**Comment by Gummibrallan** [comment]
/sign. Love to see this too

**Comment by Leescar** [comment]
It would also be nice to have a player fail a quest if they smelt or craft a certain item as well.

Though epic quests looks like it has a vastly different Boolean structure,(Which is why in my personal opinion I prefer this plugin over that one, praise Pikachu)  I'm not the best at coding though and wouldn't know how to convert/inject into quests.

**Comment by FlyingPikachu** [comment]
Would the quest complete upon crafting/smelting the item or after obtaining it from the Table/Furnace? And is okay for players to craft from their inventory?

Here's EpicQuest's events for crafting and smelting:
https://github.com/Akumasama/EpicQuest/blob/17a3655352ed26f71b41dde97714c5fc9252273a/src/main/java/randy/questtypes/TypeCraftItem.java
https://github.com/Akumasama/EpicQuest/blob/17a3655352ed26f71b41dde97714c5fc9252273a/src/main/java/randy/questtypes/TypeSmelt.java
https://github.com/Akumasama/EpicQuest/blob/e352900e13b9909487c8066411718ef06a2167b7/src/main/java/randy/listeners/InventoryDragListener.java

**Comment by Grasty** [comment]
I could go either way, im not terribly picky. Upon Crafting/Smelting would probably be preferable as I would imagine you could just loot some already smelted ore instead ... but that wouldnt really bother me that much.

I would think it would be ok to allow crafting from inventory, actually i think that if it wasnt allowed players might get confused why they arent getting credit. Again though, im not picky.

**Comment by FlyingPikachu** [comment]
I began work on this but have decided not to proceed. I thought about everything one could do to an item - craft it, smelt it, brew it, rename it, use it, toss it, break it, repair it, destroy it, et al. It would be great to cover each of those individually, but I feel as though delivering an item covers most, if not all of these , so long as the player's environment is controlled (including enchanting?). And considering how crowded the Stage editor is already, this just doesn't seem feasible.

Thank you for your suggestion! :)
