### ISSUE TITLE
Gui-display: custom name & colors don't work

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#240]
Hi guys!

Here a part of my quests. I want to change color and name of the item in the gui (so the "name" of the quest), but here, the name stay "Visite" and not "Carte de visite". I use only ingame commands :)

>  custom1:
    name: Visite
    npc-giver-id: 148
    ask-message: '&eQui sont ces gens ?...'
    finish-message: Bienvenue dans le village de Noël 2015, créé tout spécialement pour vous divertir.
    gui-display: name-EMPTY_MAP:amount-1:displayname-Carte de visite

**Comment by Armystich** [comment]
custom8:
    name: '&2Sell some Drugs...'
    npc-giver-id: 14
    ask-message: '&6So you want to Help Push Product...'

you can do that and it will solve your issue
