### ISSUE TITLE
Events not sticking?

### ISSUE THREAD

**Issue by Raeras** [FlyingPikachu/Quests#242]
I created an Event to use as the initial Event for one of my quests. I put it in and saved the quest. When I reloaded the quest and went back in to the editor to look the event was gone.  The Event was originally the 'Give Item' but then I thought that was the issue so I changed it to a command event. It still did not stick. I then tried with one of the built in events but that did not stay either.

Is this a regular issue and is there any way to fix it? I really like this plugin and would like it even better if there was a way to keep the Events in place. 

(Maybe it has to be done manually from the config instead of through the server commands?)

Any help is appreciated. Thank you!

**Comment by DanyBv** [comment]
Go to the config and replace "initial-event" with "event" and it will work.

**Comment by FlyingPikachu** [comment]
Fixed by #252, download latest dev build. Thanks @DanyBv
