### ISSUE TITLE
Quest Journal not working

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#243]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1 b234
(__Required__) Please describe the problem and how to replicate it. Any console errors?
12.01 16:19:10 [Server] INFO ... 15 more
12.01 16:19:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:661) ~[?:?]
12.01 16:19:10 [Server] INFO at me.blackvein.quests.Quests.questActionsCommandHandler(Quests.java:1300) ~[?:?]
12.01 16:19:10 [Server] INFO at me.blackvein.quests.Quests.questsJournal(Quests.java:1483) ~[?:?]
12.01 16:19:10 [Server] INFO at me.blackvein.quests.Quester.updateJournal(Quester.java:268) ~[?:?]
12.01 16:19:10 [Server] INFO at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:365) ~[?:?]
12.01 16:19:10 [Server] INFO Caused by: java.lang.NullPointerException
12.01 16:19:10 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
12.01 16:19:10 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
12.01 16:19:10 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v3.2.1-b234
12.01 16:19:10 [Server] ERROR null

**Comment by FlyingPikachu** [comment]
Note that this is error is likely the result of another issue regarding objectives, and not inherently a fault of the Quests Journal. However, I will push a commit that should make this known to the console rather than produce an error.
