### ISSUE TITLE
Duplicate objective still

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#244]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Objectives still duplicate
https://pastebin.com/KGEqARHJ

if re-connected then the task of "break block" is duplicated

**Comment by PengBread** [comment]
I'm having the same issue too. As stated above.

**Comment by FlyingPikachu** [comment]
Should be fixed in 01cad69706e6969c0da71e3d16d8abb5f0c7c664

Counting as duplicate of #242
