### ISSUE TITLE
permission dont work

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#244]
the permission "- -quests.info" dont work - please fix

**Comment by FlyingPikachu** [comment]
Working fine for me. Perhaps it's an issue with your permissions setup?

**Comment by seema84** [comment]
I think no. Other permissions works fine ("- -quests.stats" and "- -quests.take")

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
