### ISSUE TITLE
Quests Not Ending - Loops required task couple times. 

### ISSUE THREAD

**Issue by Vestle** [FlyingPikachu/Quests#245]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 
Build #235 (Jan 11, 2018 8:33:06 PM)
	Build Artifacts
	Quests-3.2.1.jar	

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Target wood cutting is 200. User gets to 200. It starts a new 200.the player cuts 200 more down. It then says cut 210 wood. All within the same quest. Before the update the user cut down 200 wood they completed the quest. Now they do what I said above. 
https://imgur.com/a/TGfhN
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
This is going to be difficult to diagnose without an example quest. Would you mind giving the dev build below a try? If that doesn't resolve the issue, please provide an example quest.

http://ci.ac3-servers.eu/job/Quests/237/

**Comment by FlyingPikachu** [comment]
Fixed in #247
