### ISSUE TITLE
[Suggestion] Quest Tracker GUI

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [FlyingPikachu/Quests#245]
I Think you should add a Quest Tracker GUI, maybe change the Journal so it opens a GUI which shows Quests in Categories where you can look at for each Quest just like Quest World here http://dev.bukkit.org/bukkit-plugins/quest-world/

**Comment by FlyingPikachu** [comment]
Interesting but we are currently focusing on bug fixes at this time.
