### ISSUE TITLE
NPC Issue

### ISSUE THREAD

**Issue by SamB440** [FlyingPikachu/Quests#246]
I have an issue where OPPED players can use the NPC GUI but de-OPPED players can't.

**Comment by FlyingPikachu** [comment]
What permissions do you have set?

**Comment by SamB440** [comment]
There are no permissions for it I believe, I believe it's an issue  with world guard. I'm using a different plugin for protection and it works fine! Issue with world guard or Quests?

**Comment by FlyingPikachu** [comment]
Impossible to know without knowing which permissions are set. If this is still an issue, please open a new ticket with more information.
