### ISSUE TITLE
Blacklist Lock

### ISSUE THREAD

**Issue by RealmShift** [FlyingPikachu/Quests#247]
Recently I have been having problems with Quests, so I recreated some of the existing ones. However, I could not take the new quests because they are named the same as the older ones, so I purged my UUID of all Quests data. However, now I am blacklisted and not even console commands or deleting my UUID in the config will change anything. As I am the server owner, this is definitely not good. Any suggestions? I am running a patched Spigot that implements 1.8 via Carbon and I have one of the latest versions of Quests installed.

**Comment by xxmarijnw** [comment]
You need to remove your UUID in the Config.yml under 'quester-blacklist:'.
