### ISSUE TITLE
Npc deliver Issue

### ISSUE THREAD

**Issue by agronaque512** [FlyingPikachu/Quests#249]
Hi,
When i use the deliver system to finish a stage or a quest it doesn't work, players and op's can't deliver the item to the NPC, when you right clic to deliver it, they just purpose the other quests or saying "no more quest available"....

**Comment by Armystich** [comment]
Have you tried right-clicking with the item?

**Comment by agronaque512** [comment]
Sure sometime it will work, sometime it just give me others available quests.

**Comment by FlyingPikachu** [comment]
If this is still an issue, please create a new issue with your Quests version number. Thanks!
