### ISSUE TITLE
Quests question

### ISSUE THREAD

**Issue by WanderingRaven** [FlyingPikachu/Quests#25]
Hello,

I am hoping you can help with a few questions about your plugin, Quests.

1.  I have recently come into ownership of a server that already has this plugin installed and I want to upgrade.  I'm concerned there may be some incompatibilities though.  The server is still running MC 1.8.8.  If I upgrade to the current version will that cause any issues?  And what is the best way to upgrade?
2.  Is it possible to only have a player able to do a quest once they've completed another quest? 
3.  Is it possible for players to be given specific permissions (from various plugins) as rewards for completing a quest?
4.  How do you access the GUI?

I may have more questions.  So sorry.  We have been brainstorming some ideas but just can't seem to wrap our head around making this plugin work for them, altho theoretically it seems possible.  Alternatively, what would the cost be to come to my server and set up some quests?

Thank you!

**Comment by FlyingPikachu** [comment]
@WanderingRaven To answer question 1, no, there should be no issues upgrading (unless you are coming from version 2.0.0 or below, in which case [click here](https://github.com/FlyingPikachu/Quests/wiki/Updating-from-2.0.0)).

For all other questions, I feel it is best to link you to the English video tutorial - https://www.youtube.com/watch?v=0EZ6yv4MVBM

**Comment by WanderingRaven** [comment]
Thank you, I will attempt an upgrade soon.  I did watch that video tutorial as well as another one and I still can't seem to make heads or tails of it.  Do you have time for a paid project?

**Comment by WanderingRaven** [comment]
@FlyingPikachu Sorry to bother you again.  I rewatched those videos and still can't seem to figure out how to make a more advanced quest that requires some of the above settings.  Can you help via Discord or would you be willing (for a fee) to help me set some up?  Thanks!

**Comment by FlyingPikachu** [comment]
@WanderingRaven Unfortunately I do not have the time for a paid project, but thanks for your offer. I encourage you to seek help building your server on the Spigot forums. Thanks!
