### ISSUE TITLE
Hide quests that i can't take in NPC GUI

### ISSUE THREAD

**Issue by JohOply** [FlyingPikachu/Quests#250]
Hi,

Currently, even if a player can not take a quest, he can see the quest into the NPC GUI and the note above the NPC.

Is it possible to hide both things if the player can't take the quest given by a NPC ?

Thanks in advance

**Comment by FlyingPikachu** [comment]
If I recall correctly, those are indicators that an NPC has a quest, but not necessarily one that the player can take. So that is intentional.

Perhaps the requested behavior could be added in the future.

**Comment by FlyingPikachu** [comment]
Closing due to apparent lack of interest by the community.
