### ISSUE TITLE
lang Using zh-CN causes all commands to not be valid

### ISSUE THREAD

**Issue by Xiazihong** [FlyingPikachu/Quests#250]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2-b245
(__Required__) Please describe the problem and how to replicate it. Any console errors?
lang Using zh-CN causes all commands to not be valid
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
No

**Comment by FlyingPikachu** [comment]
This does not surprise me as Chinese Simplified has not yet been completed. Translations are provided voluntarily on Crowdin and it's possible the commands do not match the help menus. These sort of issues are only resolved once all language strings are completed.

If you'd rather not wait, feel free to correct the translations at:
https://crowdin.com/project/translate-quests
