### ISSUE TITLE
PermissionsEX permissions as stage trigger.

### ISSUE THREAD

**Issue by oldquestman** [FlyingPikachu/Quests#252]
Hello!
I have setup a denizen-powered dialogue with an NPC (let's call him Bob). I want to have a quest STAGE to be completed when you reach a certain spot in the conversation with Bob.
I figured it would be easy to have the denizen script give the player a flag or a permission like "befriend.bob" at the right moment of the conversation. Then the quests plugin would check for a permission before it can move the player to the next stage. Preferably the list of requirements could have custom names like "Befriend Bob" instead of "have permission befriend.bob"
Is something like this possible? Or is the same result achievable by some other techinque that I have overlooked?

Best Regards
OldQuestMan

**Comment by FlyingPikachu** [comment]
To my knowledge, there is no way to give anything, let alone a permission, in the middle of a conversation. However, you might be able to do something crafty with Events in between stages. Like using a chat-triggered Event to give the player a permission when they type a keyword in chat.

You can explore this in the _/quests events_ menu.

If this isn't satisfactory, try asking on the Spigot forum as there's a limited chance of someone here knowing an alternative. However, I'll mark this as a question for if someone might know a trick.

**Comment by oldquestman** [comment]
Hey, thank you for your quick reply!
So basically my goal is to have a player complete a stage only when certain
command has executed. The permissions would work if there was an option to
have permissions as stage requirement. The script just has to run something
like:
- execute as_op "pex user <player.name> add befriended.bob"

As the plugin already is able to check for permission before starting a
quest, would it be possible to check for permission before starting next
stage of the quest?
Best regards
oldquestman

2018-01-22 6:52 GMT+02:00 FlyingPikachu <notifications@github.com>:

**Comment by oldquestman** [comment]
I figured a way to make it work so i'm closing the issue. Thank you for your help.

If someone else is interested, I just had a denizen script to check if the player has the permission node through an IF statement that executes the "/questsadmin nextstage" command to forcefully complete the stage.
