### ISSUE TITLE
Issue with Quests all command options are NULL

### ISSUE THREAD

**Issue by DrCreo** [FlyingPikachu/Quests#253]
so I just came across this issue and I have no idea what caused it but every command option or command description is "NULL" is data missing? http://puu.sh/m9Qxa/fc5f82a647.jpg

**Comment by FlyingPikachu** [comment]
Make sure you have the latest version of Quests from Spigot as well as Vault installed.

**Comment by meegamax** [comment]
I'm having the same issue.

**Comment by FlyingPikachu** [comment]
Make sure you are using the latest version from Spigot and NOT the old version from Bukkit. https://www.spigotmc.org/resources/quests.3711/

If you're still having an issue after updating please create a new ticket along with your Quests version.
