### ISSUE TITLE
Reach Location trouble

### ISSUE THREAD

**Issue by oldquestman** [FlyingPikachu/Quests#253]
Hey.
Currently the "reach location" objective doesn't work if your world name has a space in it (for example world called Biome Bundle).
Putting " " or ' ' around the world name leads to an error.
I can't change the world name anymore. Is there a way to work around this, so that the plugin accepts "Biome Bundle" as the world name?

Oldquestman

**Comment by FlyingPikachu** [comment]
What is your Quests version?

**Comment by oldquestman** [comment]
I'm still on 3.2.1.

2018-01-23 5:31 GMT+02:00 FlyingPikachu <notifications@github.com>:

**Comment by oldquestman** [comment]
I'm sorry for bothering, but is this an easy bug to fix? Can I expect this bug to be removed soon, or should I drop my hopes of location based quests and think off something else?
Thank you a lot for your time!
