### ISSUE TITLE
PlayerDeathEntity Error

### ISSUE THREAD

**Issue by PengBread** [FlyingPikachu/Quests#254]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2

(__Required__) Please describe the problem and how to replicate it. Any console errors?
I don't know what caused this. But its spamming my console. https://pastebin.com/2xv2v1WB

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
Please post the complete error; your Pastebin is missing the last half or so. It is impossible to diagnose this without it.

**Comment by PengBread** [comment]
ah my bad, 
https://pastebin.com/nV7eSCqW

**Comment by PengBread** [comment]
Any ideas what caused it?

**Comment by FlyingPikachu** [comment]
Not as of yet.

Does your error truly end with "23.01 22:52:17 [Server] INFO Caused by: java.lang.NullPointerException" ? Typically the lines immediately following that one would contain the necessary info to figure this out.

**Comment by PengBread** [comment]
Yes , also I got another error which is PlayerDeathEvent
https://pastebin.com/t2TBNRS4

**Comment by FlyingPikachu** [comment]
I'm confident that #283 may have fixed this. If the issue persists, please open a new ticket. Thanks!
