### ISSUE TITLE
Setting a quester's stage still not functional

### ISSUE THREAD

**Issue by mrequinox3** [FlyingPikachu/Quests#255]
/questadmin setstage [Quester_Name] [Quest] [Stage] is still unfunctional .
The same problem as here: https://github.com/FlyingPikachu/Quests/issues/151
This command sets a quester's stage on a Quest, so it doesn't set the stage of a Quest.

**Comment by FlyingPikachu** [comment]
If this is still an issue, please create a new issue with your Quests version number. Thanks!
