### ISSUE TITLE
giving Dialogue

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [FlyingPikachu/Quests#256]
How do I give my Quests Dialogue, so for example, right click npc, select quest, then the npc talks to you, and you talk to him (using preset coversation, so you don't actually talk to him) and then it goes to the next task

**Comment by xxmarijnw** [comment]
You can set more than one 'start message' in the 'Edit Stages' menu. 

Typ 1 (add a new stage)
Typ 22 (Start Message (None set))
Typ in a start message.

And repeat this for any sentence of dialogue you want.

**Comment by xH3LLRAIZ3Rx** [comment]
ok, no need, installed ZQuest instead :D
