### ISSUE TITLE
First Run of Plugin do not generate lang files...

### ISSUE THREAD

**Issue by JGamesexe** [FlyingPikachu/Quests#256]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2-b246

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Just run server without lang files...
https://paste.ubuntu.com/26460032/

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
quest.yml, events.yml are fine... but config.yml has nothing...

[Sorry for bad english]

**Comment by JGamesexe** [comment]
#

**Comment by FlyingPikachu** [comment]
Is it safe to assume you are hosting your server on Ubuntu?

**Comment by JGamesexe** [comment]
Local hosting =V (Windows 10)

**Comment by FlyingPikachu** [comment]
The following dev build should resolve this issue. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/249/

**Comment by JGamesexe** [comment]
** Lang files are still not generating on first run

**Comment by FlyingPikachu** [comment]
This should do the trick once available - http://ci.ac3-servers.eu/job/Quests/250/

**Comment by JGamesexe** [comment]
Still without lang files ;-;

same with the same error
```
[06:01:02 INFO]: [Quests] Enabling Quests v3.2.3-b250
[06:01:02 ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US
[06:01:02 INFO]: [Quests] Loaded language en-US. Translations via Crowdin
```

**Comment by JGamesexe** [comment]
Now without NULL on commands...

**Comment by FlyingPikachu** [comment]
Great! As for the lang files not generating, I haven't been able to replicate that on a Win7 machine. It's possible your folder permissions aren't set properly. Does the /lang folder generate, but not the .yml files? Or is it nothing at all?

**Comment by JGamesexe** [comment]
Only, /lang folder don`t generate, everthing else is fine

**Comment by FlyingPikachu** [comment]
Given that a lot has changed with recent versions of the plugin, I'm going to close this as likely resolved. If you're still experiencing the issue on the latest version of Quests, feel free to open a new ticket.
