### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by ThunderGemios10** [FlyingPikachu/Quests#257]
When typing /quests. It gives a NULL message.

Preview:
http://imgur.com/F2hlRta

**Comment by ZeeKingEpic** [comment]
idk if i have permission to help you or not
But U need to have Newest Quest Version And Vault Installed

**Comment by ThunderGemios10** [comment]
@ZeeKingEpic I am already using the latest version of Quests (Specifically Spigot) and have Vault installed.

**Comment by ZeeKingEpic** [comment]
@ThunderGemios10  OK i had the same problem i just fixed it yesterday i ll give u both Jars

https://www.dropbox.com/s/2u2t7hl1kkug865/Quests%20%281%29.jar?dl=0 ( QUESTS JAR )
https://www.dropbox.com/s/o424d8ipgmbfujv/Vault%20%281%29.jar?dl=0 ( VAULT JAR )

**Comment by meegamax** [comment]
I'm having the same issue.

**Comment by FlyingPikachu** [comment]
@meegamax Make sure you are using the latest version from Spigot and NOT the old version from Bukkit. https://www.spigotmc.org/resources/quests.3711/

If you're still having an issue after updating please create a new ticket. This one is closed.
