### ISSUE TITLE
Broken - Trying to create a quest in game

### ISSUE THREAD

**Issue by MGxEMAN** [FlyingPikachu/Quests#258]
Hello, whenever i tried to create a quest in game, i could fill out all the options. However when i came down to saving the quest. This error came up in console:

06.01 14:22:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
06.01 14:22:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:728) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
06.01 14:22:59 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1040) ~[?:?]
06.01 14:22:59 [Server] INFO at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:1112) ~[?:?]
06.01 14:22:59 [Server] INFO java.lang.NullPointerException
06.01 14:22:59 [Server] ERROR Error handling conversation prompt

**Comment by FlyingPikachu** [comment]
If this is still an issue, please create a new issue with your Quests version number. Thanks!
