### ISSUE TITLE
Can scoreboard tags be a factor in checking if the quest is available to a player or not?

### ISSUE THREAD

**Issue by CostDeathYT** [FlyingPikachu/Quests#260]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? Any

(__Required__) Please describe the problem and how to replicate it. Any console errors? I just wanted to ask if scoreboard tags could be used as triggers for if the quest is doable by a certain player. I wanted this feature because I am trying to make a minecraft MMORPG where there are 4 races all with different quests.
If you could provide aid, it would be much appreciated :).
Regards,
Cost

**Comment by FlyingPikachu** [comment]
No. However, you could use permission requirements if, for example, each player has some permission unique to their class. Otherwise, you could have someone familiar with Java look at building you a Custom Requirement - https://github.com/FlyingPikachu/Quests/wiki/Quests-API#requirements-api
