### ISSUE TITLE
Problems with quests

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#261]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Version - 3.1.6

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello! We really like your plugin. Recently encountered a small problem: daily quests are multiplied and if not executed, then after a certain time this quest can not be executed. Thank you in advance

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Quest: https://pastebin.com/t3KwxR31
Screen: https://imgur.com/a/kTAHV

**Comment by FlyingPikachu** [comment]
This was resolved in Quests 3.2.2 - update your Quests version.
