### ISSUE TITLE
GUI can take item

### ISSUE THREAD

**Issue by Armystich** [FlyingPikachu/Quests#263]
Hello When I make a quest and I test them B4 i allow any players to do it I find that the item in the GUI can be taken by the player. I noticed that it only happens when it is the 2nd quest the NPC gives too.

**Comment by Volkenstein666** [comment]
Just as an aside- I had a similar issue with being able to pull items out of  the GUI but it only ocurred when I was running the server off my home computer and my computers memory was almost maxxed out- so for me it was a lag / memory issue that allowed the items to be dragged out of the GUI

**Comment by FlyingPikachu** [comment]
If this is still an issue, please create a new ticket including your Quests version number. Thanks!
