### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#264]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2 latest on spigot.org 
(__Required__) Please describe the problem and how to replicate it. Any console errors?
27.01 18:39:17 [Server] INFO at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:379) ~[?:?]
27.01 18:39:17 [Server] INFO at me.blackvein.quests.Quester.getObjectives(Quester.java:530) ~[?:?]
27.01 18:39:17 [Server] INFO Caused by: java.lang.NullPointerException
27.01 18:39:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
27.01 18:39:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
27.01 18:39:17 [Server] INFO org.bukkit.event.EventException: null
27.01 18:39:17 [Server] ERROR Could not pass event InventoryClickEvent to Quests v3.2.2-b246

**Comment by FlyingPikachu** [comment]
Please describe how to replicate the issue.

**Comment by SwimUp29** [comment]
Sorry, idk. Sometimes I check the console for errors and noticed this error.

**Comment by FlyingPikachu** [comment]
Seeing as the crucial part of the error is missing (the lines following `27.01 18:39:17 [Server] ERROR Could not pass event InventoryClickEvent to Quests v3.2.2-b24`) and you cannot provide a way to replicate the issue, I must close this ticket as there is insufficient material for me to investigate.
