### ISSUE TITLE
Talking npc

### ISSUE THREAD

**Issue by Zeuscp1** [FlyingPikachu/Quests#265]
Hello, how can i have the npc to have a chat interaction with the player, or maybe just the npc talking to you?

**Comment by FlyingPikachu** [comment]
If you are asking whether it's possible to hold an extensive conversation with an NPC through quests, the answer is 'no'. The most an NPC can communicate is the ask-message, complete-message, and anything you've set up via stages. Citizens has a built-in methods for conversing with NPCs. Seek out their documentation for more info.

For your additional question, the answer is 'maybe'. Try using <player> or %player%. If neither works, then I'm afraid you out of luck. Once again, however, there may be methods for this when you approach an NPC within the Citizens plugin itself.

**Comment by Zeuscp1** [comment]
Yes i know citizens has a built in methods for conversing but how can i pull out the msg in the mission? you know? anyway i will search for it on the citizens plugin but if you know it will make my life easier. Anyway thanks for your help!
