### ISSUE TITLE
Needing some modules to be made

### ISSUE THREAD

**Issue by zDrakon** [FlyingPikachu/Quests#265]
I wonder if you would recommend anyone or would take up to a task to develop some custom modules for my upcoming server. 

I really want a "Timer" module so that I can set a quest to expire after a certain amount of time.

I also want a module to act like a "First Time/Vanilla Minecraft Achievement" quest module. So if a player does something, this event will be triggered and the quest will have been completed. These would be accepted as soon as the player joins by default. 

I am willing to pay for this development, and many have suggested I come to you developers on this plugin to do this. Sorry if not right place.

**Comment by FlyingPikachu** [comment]
@NathanWolf has been contributing actively, perhaps he would be interested. But I think you'd have better luck asking on the Spigot forums. Thanks!
