### ISSUE TITLE
Dupe with / quests journal

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#266]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Version - 3.2.2

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello! Thank you for helping with previous problems. Our player found another problem. When you receive journal with quests, you write /book and erase the text in the book, then save. So how many times you can do. Thanks in advance

**Comment by FlyingPikachu** [comment]
In what way does this duplicate something? Sounds like he's just erasing the contents of the Journal. If you'd like to avoid that, just disable whatever the permission is for _/book_.

**Comment by AIphaDragon** [comment]
Thank you, we will do it.
