### ISSUE TITLE
Talking NPC

### ISSUE THREAD

**Issue by Zeuscp1** [FlyingPikachu/Quests#268]
Hello, anyone here that can help me? Im still trying to figure out how can i make an npc say a solid text for the mission...NPC talking to you in the quest is so simple yet i dont see any way i can get it to do it..

**Comment by FlyingPikachu** [comment]
You question has already been answered in your previous issue, #265. "The most an NPC can communicate is the ask-message, complete-message, and anything you've set up via stages." There is no other functionality available within Quests itself.

Please do not create duplicate tickets. If you still want further assistance, a better place to ask is the Spigot discussion forum - https://www.spigotmc.org/threads/quests.47772/
