### ISSUE TITLE
Farming

### ISSUE THREAD

**Issue by mattias1172** [FlyingPikachu/Quests#268]
Is it possible to make quests about farming? Specifically breaking wheat and replanting seeds? I tried setting it up to "break" 9 wheat and "place" 9 seeds, but when I do so, the counter stays at 0/9 when I break wheat or plant seeds.
(Also tried using the "use" and "cut" options. Still no effect.)

Also, to avoid double posting, is there a way in the requirements section to allow multiple items and not all of them together? As in (using my example above) if I wanted a hoe to be a requirement, I want a player to be able to use any hoe; wooden, stone, gold, iron, and diamond. Not just a specific one and not all of them. 

Thanks,
-Mattias

**Comment by FlyingPikachu** [comment]
Sorry for the late response, but this seems like 2 questions better suited for the Spigot forums. Thanks!
