### ISSUE TITLE
Interaction error

### ISSUE THREAD

**Issue by ImZeta** [FlyingPikachu/Quests#269]
I have a problem with the plugin, some users on my server can not interact with .. but have permissions says "error" This error began with 1 user, but now are 5 ... I've noticed in the quests, but all are well configured .. any idea why? I'm using version 2.5.1

**Comment by FlyingPikachu** [comment]
Please post the full error. I suspect it could be a conflict with another plugin such as WorldGuard. Also, try updating to the latest version of Quests.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
