### ISSUE TITLE
Problems with custom-objectives

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#269]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Version - 3.2.2

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello. Sorry to trouble you again. There was a problem with the counter of mobs created through MythicMobs. Thanks in advance for your help.
Error: https://pastebin.com/2AUSpw7V

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Quest: https://pastebin.com/WsZpjHZv

**Comment by FlyingPikachu** [comment]
This is an error within the MythicMobs module; not Quests itself. Please bring this to the attention of the module authors.
