### ISSUE TITLE
null

### ISSUE THREAD

**Issue by TaylorPigman** [FlyingPikachu/Quests#27]
Whenever I type in any command I get this.
(/quests)
![2017-07-03_07 16 00](https://user-images.githubusercontent.com/29876113/27810811-8628fdae-6024-11e7-9fe1-cecb1f4fd24f.png)

**Comment by FlyingPikachu** [comment]
@TaylorPigman What is your Quests version (don't say "latest")?
Do you have Vault installed?

**Comment by TaylorPigman** [comment]
ohh... 2.0.0

**Comment by FlyingPikachu** [comment]
Spigot page for latest version :)

https://www.spigotmc.org/resources/quests.3711/
