### ISSUE TITLE
Problems with the names of flowers

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#270]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Version - 3.2.2

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello! Faced a problem with the names of flowers in the quest. The quest is executed as before, the screenshots show the difference in the name of flowers. Thanks in advance.
Screenshots: https://imgur.com/a/fW9Bt

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/uTLKYVvH

**Comment by FlyingPikachu** [comment]
I'm not sure I understand the issue. Is the problem that item names are not always translated? This is to be expected per #172

**Comment by AIphaDragon** [comment]
In the quest there are 3 different flowers. In the quest for the player, 3 times is written to bring the poppy instead of 3 different flowers.

**Comment by FlyingPikachu** [comment]
Looking at your quest, they appear to be the same flower, just with different data tags:

>items-to-deliver:
          - name-RED_ROSE:amount-5:data-5
          - name-RED_ROSE:amount-5:data-6
          - name-RED_ROSE:amount-5:data-1

Here is a objective I just created with a Rose, Dandelion, and Lilac respectively. If you're ever uncertain, use the "0 - Load item in hand option" when adding items :)

> items-to-deliver:
          - name-RED_ROSE:amount-1
          - name-YELLOW_FLOWER:amount-1
          - name-DOUBLE_PLANT:amount-1:data-1
