### ISSUE TITLE
Adding support for item ID's and 'Load from hand'

### ISSUE THREAD

**Issue by 1mRAAAH** [FlyingPikachu/Quests#272]
Hey.

I've encountered an issue in the setup of the quests as a functionality.
You know the "0. load from hand" when adding items to the rewards list?
I am desperate for that function to be implemented into the "break blocks" etc part.
I can not let players break blocktypes suchs as 159:14 (red stained clay).

It blocks me in creating more and unique / harder challenges!?
Thanks for looking into this!

KindReg
1mRAAAH

**Comment by 1mRAAAH** [comment]
Next issue.
I've added 15 quests so far.. When I loaded 14, I could do /quests list 2.
With the 15th quest added, when I do /quests list 2 It gives an error:

02.02 22:42:44 [Server] INFO 1mRAAAH issued server command: /quests list 2
02.02 22:42:44 [Server] ERROR null
02.02 22:42:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v2.5.3-b92
02.02 22:42:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
02.02 22:42:44 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
02.02 22:42:44 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: toIndex = 16
02.02 22:42:44 [Server] INFO at java.util.SubList.<init>(AbstractList.java:622) ~[?:1.8.0_66]
02.02 22:42:44 [Server] INFO at java.util.AbstractList.subList(AbstractList.java:484) ~[?:1.8.0_66]
02.02 22:42:44 [Server] INFO at me.blackvein.quests.Quests.listQuests(Quests.java:2563) ~[?:?]
02.02 22:42:44 [Server] INFO at me.blackvein.quests.Quests.questsList(Quests.java:2187) ~[?:?]
02.02 22:42:44 [Server] INFO at me.blackvein.quests.Quests.questActionsCommandHandler(Quests.java:1651) ~[?:?]
02.02 22:42:44 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:781) ~[?:?]
02.02 22:42:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
02.02 22:42:44 [Server] INFO ... 15 more



All quests are perfectly fine.
Check quests markup here: http://pastebin.com/FKj3SXcT

**Comment by 1mRAAAH** [comment]
Can you please help me in this matter? I'm trying to create 100 quests prior to 10th of feb and open the server... But if this doesn't work I can't use it...

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
