### ISSUE TITLE
Suggestion for modules or extend API

### ISSUE THREAD

**Issue by zDrakon** [FlyingPikachu/Quests#273]
I have a suggestion for this quest plugin to allow quests that expire after a certain time if a player hasn't completed it. 

So if a player accepts a timed quest for 10 minutes but fail to complete it within 10 minutes, the quest expires.

Also I'd like to have the plugin hook into the FactionsUUID plugin to create "Faction quests"
These faction quests will allow faction leaders to take a quest for the entire faction. No time expiration.

Thanks I hope these become a reality.

**Comment by FlyingPikachu** [comment]
While that may leave a cleaner interface, I feel like that would be the only real benefit as there would be no effect (i.e. punishment). Of course one could be though up, but in that case please create a new, updated ticket if that is still of interest. We are not looking to hook into other plugins at this time. Thanks!
