### ISSUE TITLE
Add ability to receive quest items and rewards with full inventory

### ISSUE THREAD

**Issue by SullyTheUnusual** [FlyingPikachu/Quests#276]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
v3.1.2-b192
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Doing quests with a full inventory prevents you from receiving quest items and rewards.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
This is likely intended, as there is currently no queue system for unacquired rewards. Implementing one would likely require a new subcommand and changes to way Quests stores player data. Although that’s entirely possible to do, there are other tasks on my plate at the moment.

Until then, I highly recommend updating to the latest version of Quests.

**Comment by SullyTheUnusual** [comment]
Instead of a queue system, how about just cancelling the right-click event with an error message?  In other words, you can't start/continue/complete the quest with a full inventory.

**Comment by FlyingPikachu** [comment]
That's a splendid idea, although it may take a bit more tweaking than that (for example, Reach Location events would likely spit an error message with every step taken after reaching the zone).

**Comment by SullyTheUnusual** [comment]
I suppose instead of triggering it on right-click, you could trigger it when certain objectives are run (those that give items), not sure how hard that would be.

In the meantime, I'll just make sure my players know to always keep some room in their pack when questing.  Thanks for an awesome plugin!

**Comment by Midnight9746** [comment]
You could also make it work with plugins such as the backpack one. That way your sending it to that instead, or to an ender chest.

Or (even though there's coding) make it put it in quest's own GUI.

**Comment by FlyingPikachu** [comment]
A quick glance shows me that Quests actually drops item rewards at the player's location, rather than add them to inventory:

https://github.com/FlyingPikachu/Quests/blob/fc494bad7573902b3c5d7143566215f11b607431/src/main/java/me/blackvein/quests/Quests.java#L3727

So if inventory is full, the item will just float on the ground.
