### ISSUE TITLE
User can pick up items from Quest-GUI

### ISSUE THREAD

**Issue by H4ZEL** [FlyingPikachu/Quests#276]
Hey,
I have a MMO-RPG Server with some quests. The problem is that my user click on the quest-npc, its open an GUI, they choose/click on the item to select the quest and than thy can take the item and using it. quest is working but they shouldn't get the GUI-item :(

Hope you can help...

**Comment by FlyingPikachu** [comment]
Post Quests version and Spigot version.

**Comment by Aceakita** [comment]
I have the same issue, and i'm currently using Spigot 1.8.8 with Quests 2.5.5

**Comment by Volkenstein666** [comment]
I have had this issue in the past-- please check to make sure your server memory is not peaking when this behavior occurs. Whenever this became an issue with me it was because of lag created by maxxed out or close to maxxed out memory usage

**Comment by FlyingPikachu** [comment]
Closed due to lack of response from OP. If anyone else experiences this problem, please create a new issue with you Quests version, Spigot version, and an example of the quest. Thanks!
