### ISSUE TITLE
MythicMobs Module error

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#280]
(Required) What is your Quests version 3.2.4/ build 255 ?

(__Required__) I am not sure why but sometimes the console is getting filled with this:https://pastebin.com/es11j2TK

(__Optional__) This module installed: https://www.spigotmc.org/resources/mythicmobs-quests-module.7261/

**Comment by Vestle** [comment]
https://pastebin.com/XifuhVeQ
Duplicate issue

**Comment by FlyingPikachu** [comment]
Duplicate of #265

Use the latest dev build, released today.
