### ISSUE TITLE
API Issues / Denizen support

### ISSUE THREAD

**Issue by Fortifier42** [FlyingPikachu/Quests#281]
Hi,

I'm using Quests as a depend of a plugin, to add the ability to retrieve information from Quests in Denizen. I was hoping you would be able to add this, otherwise I can add it and send in a PR.

However, it would be nice to see more informational methods of Quester.

**Comment by Fortifier42** [comment]
Methods I'd like to see.
`Quester.getQuestPoints();`
`Quester.setQuestPoints(int);`

**Comment by FlyingPikachu** [comment]
Duplicate of #87
