### ISSUE TITLE
commands reward

### ISSUE THREAD

**Issue by shaun246** [FlyingPikachu/Quests#284]
I want to give players a kit when they finish a quest as a reward in the config i've done.

rewards:
    quest-points: 1
    commands:
    - kit drugs ""

but when i finish the quest it does /kit drugs "" in console instead of getting the name of the player.

**Comment by Aceakita** [comment]
You could try /sudo <player> kit drugs
This will execute a console command that forces the player who completed the quest to run the command /kit drugs
Assuming he has the perms to the kit, he should be able to get it. If he doesn't you will have to make another command reward that adds said permissions to the player that completed the quest.

**Comment by FlyingPikachu** [comment]
Aceakita's answer seems best. Please create a new, updated ticket if this is still an issue. Thanks!
