### ISSUE TITLE
Kill Mob stage not working

### ISSUE THREAD

**Issue by IzzyKap** [FlyingPikachu/Quests#284]
(__Required__) What is your Quests version / build number ("3.2.4-b255")?

(__Required__) Please describe the problem and how to replicate it. Any console errors?
No matter what I do the Kill Mob stage (#12) does not work. I kill the mobs and nothing happens, it does not register it. I tried with a bow, a sword, my fist, spells, nothing works. I also tried on two separate servers (my actual server and my test server) to see if the issue was just based on the servers setup. There are no console errors of any sort available.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/D1edskDx

**Comment by Midnight9746** [comment]
The stage works for me and my friend. Are you running the correct server version? Sometimes code changes throughout versions and that can mess things up.

**Comment by IzzyKap** [comment]
My server is on the  newest spigot and the Quest build is the one I just specified. I killed like 100 horses nothing happened. If you want to come on the server I can show you what I mean, the ip is mc.amscraft.co.

**Comment by IzzyKap** [comment]
![image](https://user-images.githubusercontent.com/20936658/36065211-ad47a0c6-0e65-11e8-8903-24cb86040e37.png)
![image](https://user-images.githubusercontent.com/20936658/36065217-bcc45012-0e65-11e8-906d-602e4512f62d.png)

**Comment by FlyingPikachu** [comment]
It seems this is caused by the fix for #257. Will push an alternative solution.
