### ISSUE TITLE
getting spammed with errors in console

### ISSUE THREAD

**Issue by MatrixKhan** [FlyingPikachu/Quests#285]
some of the errors are not from quests but i also see some from quests i believe http://pastebin.com/MfimW6Nv

**Comment by MatrixKhan** [comment]
i also have this glitch where players sometimes get glitched out and the rewards from a quest spam on them here is a log: http://pastebin.com/pgBvSPE8

**Comment by FlyingPikachu** [comment]
You are correct that Quests is mentioned but I see a number of errors from other plugins in both of your error logs (including an error from PhatLoots which is a dependency and may affect how Quests performs).

I suggest starting with fixing your PhatLoots error and then a fresh install of the latest version of Quests. If your issue persists, please create a new ticket.
