### ISSUE TITLE
Problem with delays

### ISSUE THREAD

**Issue by bigyoor** [FlyingPikachu/Quests#286]
Hello and sorry for my bad english, i think there is an issue with delays in quest objectives:

**(__Required__) What is your Quests version / build number (do _not_ say "latest")?**

256 (254 and 255 tried before)

**(__Required__) Please describe the problem and how to replicate it. Any console errors?**

When i create an objective with a delay, the next stage of the quest does not start fully after the defined delay, it's shows the header "--{Quests}--" with "start-message" but no objectives , and the quest stay freeze on the stage with no objectives. 

**(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?**

**https://pastebin.com/fmtMkB7g** (sorry for the french)

in this example , (delay is in the stage 2) the objective to talk to the npc n°20 is freezing on "start-message" of stage 3 and the objective "talk to npc" don't appears. It's just launch the message: "message de debut" and If i look on quest journal , it says the name of the quest with no objectives

have I misunderstood the functioning of delays Or is it a bug ?

**Comment by FlyingPikachu** [comment]
Once all objectives have been completed, the Delay is how long the plugin will wait until telling the player the quest is complete and dishing out rewards.

As a side note, I noticed the Delay expects milliseconds (even though it asks for seconds). I will keep this ticket open until I have time to investigate that.
