### ISSUE TITLE
Spam from Console

### ISSUE THREAD

**Issue by WonderWizard** [FlyingPikachu/Quests#286]
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:39 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:39 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:39 [Server] Server thread/WARN *someRegex* in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:39 [Server] Server thread/WARN *someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:39 [Server] Server thread/WARN somePrefix* in config.yml is not a valid UUID for quester-bla

**Comment by FlyingPikachu** [comment]
What is your Quests version? And have you tried regenerating config.yml?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
