### ISSUE TITLE
/questadmin setstage

### ISSUE THREAD

**Issue by vjaszczurv** [FlyingPikachu/Quests#287]
The "/questadmin setstage" command doesn't seem to work poroperly. When i use it, it tells me, that the quest hasn't been found. I put the quest name correctly, i've tried on different quests, reseting the server and plugin etc.

**Comment by Aceakita** [comment]
try putting the quests name using '' So lets say the quest is named: Quest Number 1
You would put: /questsadmin setstage Aceakita 'Quest Number 1' 2

This would put user Aceakita on the second stage of said quest.

**Comment by FlyingPikachu** [comment]
Aceakita's suggestion should work. Closing due to lack of response.
