### ISSUE TITLE
Second stage doesn't show objective after delay

### ISSUE THREAD

**Issue by bigyoor** [FlyingPikachu/Quests#289]
Hello,

Just a suggestion:

**Add a delay section in execution of stages** , example:

You have an objective to give a book to a NPC that will traduce it , and the next objective is recover the traduced book after the defined delay.

Bye!

**Comment by FlyingPikachu** [comment]
Stage delays are already available. Look towards the bottom of the list when editing a stage. It's literally called "Delay".

**Comment by bigyoor** [comment]
we do not understand each other well i think ,

**I know that** but it don't works beetween objectives....... 

In a recent request #286 you said to me:
"Once **all objectives** have been completed, the Delay is how long the plugin will wait until telling the player the **quest is complete and dishing out rewards**."

What i suggest it's a delay **between** objectives. So if it's supposed to be available, it don't works as i said before in my request:

_"in this example , (delay is in the stage 2) the objective to talk to the npc n°20 is freezing on "start-message" of stage 3 and the objective "talk to npc" don't appears. **It's just launch the message**: "message de debut" and If i look on quest journal , **it says the name of the quest with no objectives**"_ 


So , if i don't explain myself properly , please tell me ( my english is bad).

**Comment by Midnight9746** [comment]
This is where I swoop in and clearify....

Number 4 (THIS is the delay before you can redo the quest)
https://imgur.com/a/O0YTU

Number 17 (THIS is the delay before the next stage)
https://imgur.com/a/2denc

Side notes: Yes I'm on my phone, and sorry if the pictures fail to work.

**Comment by bigyoor** [comment]
Here is some screens and the config to illustrate my problem:
https://pastebin.com/Q1KE4NXb

after take the quest: Ok
https://www.noelshack.com/2018-07-4-1518695711-quest-taked.png

do the obj1: Ok
https://www.noelshack.com/2018-07-4-1518695725-after-kill-zombie-obj1.png

after delay , no objective displayed , quest is frozen:
https://www.noelshack.com/2018-07-4-1518695730-no-obj2-displayed.png
https://www.noelshack.com/2018-07-4-1518695737-no-obj2-displayed-2.png

I hope that will help you to understand my problem :/ , i don't want to waste your time.....

**Comment by bigyoor** [comment]
@Midnight9746  thanks , i know that and understand the difference beetween them , but it don't works for me... ( the delay before next stage) :/

**Comment by Midnight9746** [comment]
Huh, odd. I'll go make a test quest later... right now it's late for me. (Well really 6am and I haven't slept yet XD)

**Comment by bigyoor** [comment]
Lol Ok , have a good night xD

**Comment by Midnight9746** [comment]
What version is your server and quests?

Mine (/version) says "CraftBukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)" <- It's just Spigot 1.12.2 server however the server's host has bukkit mixed with the code as it was the original server.jar (But that shouldn't matter, only that it's Spigot 1.12.2 now)

And quests (/Versions Quests) says "Version 3.2.4-b255"

This is what I did for the quest as well, It's similar to yours just without the rewards and ask messages:

custom26:
    name: Tester
    npc-giver-id: 745
    ask-message: test ask
    finish-message: test finish
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 745
          delay: 1
          delay-message: blep
        '2':
          npc-ids-to-talk-to:
          - 745

Result: It works!

**Comment by bigyoor** [comment]
oh... strange, i've tried to reset the language by default ,just in case, it don't works too. I'll do some deeper tests this night if you want.

**Server version:**
CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 

**Quests version:**
3.2.4-b261

**Comment by FlyingPikachu** [comment]
@bigyoor I see now that you also created #286 about the same issue a few days ago. The result of #286 was that I changed the Delay in-game to accept seconds rather than milliseconds (as is the case with redo-delays AKA number 4 in @Midnight9746 's example). This change is present in the latest dev builds.

HOWEVER, even though the Delay in-game asks for seconds now, _it still saves the delay in milliseconds within your config_. So, looking at your config, you currently have the delay set at 10 _milliseconds_. A value this small is bound to cause problems.

Try changing the value to 10000 (which is 10 seconds in milliseconds). I'm confident that will resolve this issue. I have tested this myself and, although the quest _appears_ "frozen" for a moment, it WILL take action after 10 seconds.

If you still experience an issue, please request for this to be reopened rather than creating a new issue. Thanks!

**Comment by Midnight9746** [comment]
Yeah my version used seconds in the stages.

**Comment by bigyoor** [comment]
Thanks for your reply

sorry, the conversation has drifted on my old issue #286 

I've tried to put "10000" in the config , it don't works, and the delay is still running in seconds, because when i define 10 , it takes 10 seconds to execute...

 do you want to reopen the #286 to talk about it on the right topic ?

**Comment by FlyingPikachu** [comment]
@bigyooor Don't worry about reopening #286 

It seems I was mistaken about it still using milliseconds in the config, so do leave it at 10. You say that "it takes 10 seconds to execute", so I'm assuming it is in fact working now? I'm confused.

**Comment by bigyoor** [comment]
Sorry, I expressed myself badly when I talked about "objectives", i wanted to say "stages", but forget that , in reality the plugin have what i want : delay on stages, but it don't works for me and i I think I have misdescribed it since the beginning in my 2 topics.

So,I will repeat my explanation more simply because my english is bad....

after delay-message in stage1 and delay itself,  the start-message of stage2 appears but not the objective you have to do , quest is blocked, you can't finish it.


https://pastebin.com/Q1KE4NXb

https://www.noelshack.com/2018-07-4-1518695730-no-obj2-displayed.png
https://www.noelshack.com/2018-07-4-1518695737-no-obj2-displayed-2.png

Hope you'll understand me xD , sorry for the mess!

**Comment by FlyingPikachu** [comment]
@bigyoor Does the objective appear 10 seconds after the start message?

**Comment by bigyoor** [comment]
nope, the objective (Kill Creeper: 0/1) never appears, but the start-message of stage 2 appears after 10 seconds , as it appears on the screenshots i posted.

**Comment by FlyingPikachu** [comment]
I see. In that case I'll reopen this and clarify the title.

**Comment by Worlfy** [comment]
Still on-going. /quest becomes empty (objective disappears?) upon having the delay. Nothing else happens, even after time passes, there's nothing delay-related that happens. The delay-message shows up the moment it's triggered, rather than when interacted with on the npc or anything like that (Unsure of when that has to trigger). I hope it's okay for me to bump this up

**Comment by FlyingPikachu** [comment]
@Worlfy Perfectly fine for you to bump an open issue. For the record, what version of Quests are you using? Thanks.

**Comment by Worlfy** [comment]
3.3.4

**Comment by FlyingPikachu** [comment]
I was just able to replicate the issue, using the following quests file:
https://pastebin.com/PWvYfUK3

![test](https://user-images.githubusercontent.com/2267126/49324544-c3949d00-f4fd-11e8-98c0-062e6ddc991d.png)

The second stage shows its start message after 10 seconds, but show the complete message when 1 Creeper is killed (nor does the quest end as it should). Hope to find a solution soon.

**Comment by FlyingPikachu** [comment]
Happy to report that this issue has been fixed. Use the following dev build once available:
http://ci.ac3-servers.eu/job/Quests/519/
