### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#29]
When you have time, think you could add a teleport feature during a quest? I've tried going around it, using one quest to tp a player to a dungeon world. But get this error: https://pastebin.com/r0Jp4EPN

This is the quest I'm trying to make: https://pastebin.com/L5kzjTqF

**Comment by FlyingPikachu** [comment]
Can be accomplished by controlling your environment (warp signs, telepads, command blocks, etc.)?

**Comment by FlyingPikachu** [comment]
Looking closer, this appears to be an error in Multiverse (perhaps your command isn't formatted properly?). At any rate, this doesnt look like Quests bug so I suggest trying the Spigot forum for help with what you're trying to accomplish.
