### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by iJoeyMonster** [FlyingPikachu/Quests#290]
I have multiple issues with the plugin where it's not working. I'm using the 1.8 version on my server.

1. It's not live updating. I watch a tutorial video (the video does seem a bit outdated though)
2. It won't let me turn in the items for the quest. It keeps saying it's not a required item for the quest.
3. I created another npc to make a totally separate quest, but it won't let me use the editor command at all. Nothing happens. I don't imagine you have to use only one npc for every single quest you make...
4. I tried to make a stage where the user was supposed to break sugarcane blocks, but it wasn't updating it and telling them what to do next. 

Edit: This was supposed to be for breaking blocks.

Edit 2:
Okay.. so I deleted my previous quests and started over. I did a kill mob quest, and it worked up until I tried to deliver the items to the NPC. The first two stages worked flawlessly. It updated live and told me it was completed and what to do next. I put three stages. First stage, kill mobs. Second stage, talk to NPC. Third stage, deliver items to NPC. When I try to right click the NPC with items in my hand it tells me the items are not required for the quest. The first two stages worked flawlessly. It updated live and told me it was completed and what to do next.

Here's a screenshot of the response: [http://i.imgur.com/7Mtblmk.png](url)
Here's a screenshot of what I entered in the editor: [http://i.imgur.com/Ee0zTPL.png](url)

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if these are still issues. Thanks!
