### ISSUE TITLE
EntityDeathEvent error

### ISSUE THREAD

**Issue by frendlyZ** [FlyingPikachu/Quests#290]
Quests version 3.2.4-b255

I have this error spamming all over my console, help would be appreciated. I know, there is something about MythicMobs, but I don't know what to do about it.

> ```
> [11:29:52 ERROR]: Could not pass event EntityDeathEvent to Quests v3.2.4-b255
> org.bukkit.event.EventException: null
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1114) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.EntitySkeletonWither.die(EntitySkeletonWither.java:48) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
> at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
> Caused by: java.lang.NoSuchFieldError: currentQuests
> at com.gmail.berndivader.questsMythicMobsKillObjective.QuestMMKillObjective.onMythicMobDeathEvent(QuestMMKillObjective.java:68) ~[?:?]
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-4bd94dc-1c40a81]
> ... 22 more
> ```

Here is the Quests.yml
https://pastebin.com/xpbq0zA0

**Comment by FlyingPikachu** [comment]
@frendlyZ Would you please give this dev build a try? It contains a recent fix for how mobs are handled. It may or may not resolve the issue:

http://ci.ac3-servers.eu/job/Quests/259/

In the event it does not, please post the new error (even if it looks identical) and we'll go from there (:

**Comment by frendlyZ** [comment]
looks like it's fixed, thank you.
