### ISSUE TITLE
Permissions problems

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#291]
3.2.4

Players don't have access to quests' journal even having quests.journal permission node

PermissionsEx 1.23.4

**Comment by FlyingPikachu** [comment]
Doesn't seem to be an issue on my test server, which uses PEX. Permissions are handled through Vault, so you try seeking help from them, but its more likely an issue with your PEX setup. Regardless, without an error or some kind of lead to go on, this is beyond my ability to assist you.
