### ISSUE TITLE
Could not pass event BlockBreakEvent to Quests v3.2.4-b261

### ISSUE THREAD

**Issue by zippoking** [FlyingPikachu/Quests#292]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.2.4-b261
(__Required__) Please describe the problem and how to replicate it. Any console errors?

Hey Guys, 
this error keeps appearing in my console. Can you tell me what this is about? 

https://pastebin.com/mcmafrd8

**Comment by Sprungente** [comment]
please use hastebin or pastebin

Thanks :)

**Comment by FlyingPikachu** [comment]
@zippoking I have updated your original post to use a Pastebin link instead.

One of you Break Block objectives is causing the errors. It'd be helpful if you could post your quests.yml file (on Pastebin).

**Comment by zippoking** [comment]
Hi,

thanks for the quick reply and sorry for not using pastebin.

Here is the story to the error:
I just installed the plugin, tried the default quests and then created my own quest ingame.
Just a very simple one. It was about breaking sugarcane. Unfortunately sugarcane didn´t work (i think i used ID 338, which is not the sugarcane block, so my mistake).
However i edited the quest ingame, changed the name and the goal to break 4 wood blocks.

This worked for me as a very simple test. A second player joined the server and then the error kept appearing in my console.

Here is the requested quests.yml file: https://pastebin.com/VWWFeeYA

Hope you guys can help me =)

Thhanks in advance.
Best regards
Zippokino

**Comment by zippoking** [comment]
So it seems that the issue is fixed for me.
I didn´t get the error messages again.

**Comment by FlyingPikachu** [comment]
@zippoking Sorry for the late reply. Glad it seems to be resolved. I don't see anything inherently wrong with your quests.yml, but if this comes up again, just comment here and I'll take another look.
