### ISSUE TITLE
/questadmin reload (Internal Error) v. 2.55

### ISSUE THREAD

**Issue by Legendofmcpc** [FlyingPikachu/Quests#293]
This was my 4th quest added so I added it it told me to do /guest admin reload when I did it said Internal error has occurred while attempting to perform this command. and thats it! I can No longer add any quests.

**Comment by Cilicou** [comment]
Hey, I've encountered a similar error recently and I found out that if you add an Item reward it automatically creates a "- null" item which creates an error when you reload OR try to edit the quest. Try going in the config folder of the plugin and opening the quests.yml with notepad++ and removing all the "- null" items in the files.

Hope it helps !

**Comment by FlyingPikachu** [comment]
Please update to the latest dev build. If the issue persists, create a new ticket with the full error message. Thanks!
