### ISSUE TITLE
Quests keeps deleting itself

### ISSUE THREAD

**Issue by Aceakita** [FlyingPikachu/Quests#294]
Players with quests that takes a long period of time to complete are getting their quest reset randomly. There is no death penalty, there is nothing. The player should be able to fully finish his/her quest during long periods of time with no problem. But they just randomly reset and delete it's progress.

Currently using Quests 2.5.5
Spigot 1.8.8

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
