### ISSUE TITLE
Events - spawning multiple mobs

### ISSUE THREAD

**Issue by Cilicou** [FlyingPikachu/Quests#295]
I would like to know if I did something wrong because I created an event that triggers at the start of a killing quest. Using the in game event builder I specified a spawn point for 5 zombies to spawn at the start of the quest but only 1 spawns.

Here's my event and quest folder.
Thks in advance !

[events.txt](https://github.com/FlyingPikachu/Quests/files/181364/events.txt)
[quests.txt](https://github.com/FlyingPikachu/Quests/files/181365/quests.txt)

**Comment by Volkenstein666** [comment]
here is how I wrote a mob spawning event and the last time I checked it worked

  Ambush1:
    message: <red>you're under attack!
    effects:
    - GHAST_SHRIEK
    effect-locations:
    - Gorgoroth -581 84 -638
    commands:
    - /summon Zombie -581 84 -638
    - /summon Zombie -588 86 -636
    - /summon Zombie -584 86 -636
    - /summon Zombie -582 84 -647
    - /summon Zombie -582 85 -643

(note each mob is given its own spawn coords and for whatever reason the world does not have to be specified as with the seperate sound effects command (I use multiworld and have seceral world going))

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
