### ISSUE TITLE
Suggestion: Dynamic Waypoints

### ISSUE THREAD

**Issue by Sprungente** [FlyingPikachu/Quests#295]
Hello Everyone! Hello Pikachu

Today i have a second idea (i think it's a good idea). 
My idea should be additional to the compassfeature:
- particle to the goal (it can be automatically or with placed waypoint, who can be placed as objective from an admin or other staffmember). It should be optional. 

I like the second idea. What do you think about waypoints or a compassusing?

I'm thanksfull when it comes to the plugin.

**Comment by Sprungente** [comment]
hmmm sure. it can limit it and in which radius particles are spawning. 

Automatically generated waypoints will use to much ressources but when it's handling like the citizens path feature?

**Comment by FlyingPikachu** [comment]
By "citizens path," you mean wayfinding? I didn't know that used particles?

**Comment by Sprungente** [comment]
i does use "flowers" in the debug-pathfinding . 
but normally don't. But when waypoint for special quests works similary like the path feature from citizens with the difference that per block one particle will generate in radius from maybe 16 blocks. player can follow them. so it's my idea

**Comment by FlyingPikachu** [comment]
I see, wasn't aware of the flower thing either. I'll have to take a look at how Citizens does that and get back to you.

**Comment by Prowco** [comment]
Well maybe a solution for that is use compass so the compass guide you

**Comment by Sprungente** [comment]
you don't read complete @Prowco 

> My idea should be additional to the compassfeature

**Comment by FlyingPikachu** [comment]
Rather than implement particles or flowers for helping the player find their way, I've decided to add support for the purpose-built [GPS](https://www.spigotmc.org/resources/gps-1-9-1-13-2-the-first-ever-minecraft-global-positioning-system.53672/) plugin.

Available in http://ci.ac3-servers.eu/job/Quests/576/
