### ISSUE TITLE
Suggestion: Healing Objective

### ISSUE THREAD

**Issue by Sprungente** [FlyingPikachu/Quests#296]
hello everyone, hello Pikachu

Today i have my third (great???) idea. i created a quest as the idea was comming. 

an example:
Quest is handling about a bird who broke his wings. 
"Please heal my bird!"
You throw 3 Healpotion to the bird 
finish 

What do you think about this idea? 
Thanks for reading

**Comment by FlyingPikachu** [comment]
I'm going to proceed under the assumption you want a Throw Potion objective, as only healing potions is far too narrow.

The main problem I see with a Throw Potion objective is _what_ to throw at. Mobs are obviously the first thought (like your bird), but there's also NPCs and other players. Also, what should happen if the thrower hits nothing? They still _threw_ it, so should they be rewarded? On that note, what about throwing at particular blocks? Or into the Void?

I'm not saying a Throw Potion objective wouldn't be useful, but given the potential variety of uses, I believe this would be better left to a custom objective. Furthermore, any work on this time of objective right now would likely have to be recoded when Minecraft 1.13 comes out. So although this is an interesting suggestion, I'm going to pass at this time.

**Comment by Sprungente** [comment]
good argument.  yes the 1.13 -.- . I marked this issue to talk about after the hard recoding :)
