### ISSUE TITLE
Tame

### ISSUE THREAD

**Issue by CorporalBruno** [FlyingPikachu/Quests#298]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 3.2.4

(__Required__) Please describe the problem and how to replicate it. Any console errors? Create new quest, add stages. In the stage pick tame a mob. Fill out how many mobs (i picked 1). Then try to save the quest. The quest fails to load with /questsadmin reload but the yaml shows its in the quests.yml file.  You also cant use questseditor  to edit the quest further because it wont load to edit. After manually removing that stage or changing it to a method that works properly such as talk to npc, the quest then loads again properly.

So it seems like taming mobs is broken in quests at the moment.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
Not all of the mobs in that list are tameable. The only tameable mobs in Minecraft are Horses, Parrots, Ocelot, Wolves, and Llamas (although looking at the code, llamas hadn't been enabled in Quests yet).

I will now push an update which removes all non-tameable mobs from the list, as well as allow Llamas. The fix will be available soon here - http://ci.ac3-servers.eu/job/Quests/263/

**Comment by CorporalBruno** [comment]
`
  custom1:
    name: Taming Wolves
    npc-giver-id: 292
    ask-message: Avicii<white>:<yellow> Find and tame 5 wolves. When you accomplish
      that, come back and see me.
    finish-message: Avicii<white>:<yellow> Great job. Now I know I can trust you with
      this egg. Walk 2500 meters with it in your off hand.
    gui-display: name-BONE:amount-1
    requirements:
      quests:
      - Brunomon
      fail-requirement-message: <purple>Avicii<white>:<yellow> Please complete the
        Brunomon quest first.
    stages:
      ordered:
        '1':
          mobs-to-tame:
          - Wolf
          mob-tame-amounts:
          - 5
        '2':
          npc-ids-to-talk-to:
          - 292
    rewards:
      money: 5
      quest-points: 1
      commands:
      - rpgpets give <player> egg
`
