### ISSUE TITLE
NPC No Redo Quest but AngryVillager Symbol

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#299]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
DevBuild 261
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Gave Quests to NPC.
If a Player finished his Quest, the NPC got the "Angry Villager" Symbol over his Head. But the Quest was not redoable. NPC has no other Quests.

Thought, this should only be, if the NPC has a Redo Quest?

**Comment by FlyingPikachu** [comment]
Unable to reproduce. Please provide an affected quest from your quests.yml for testing.

**Comment by Regnak85** [comment]
An Example Quest.
There is no Redo.
But the NPC show the Symbol.
Every other NPC after Quest too.

[quests.txt](https://github.com/FlyingPikachu/Quests/files/1735200/quests.txt)

**Comment by FlyingPikachu** [comment]
Thanks, I was able to reproduce it with your example quest. Fix will be available soon at:
http://ci.ac3-servers.eu/job/Quests/264/
