### ISSUE TITLE
Can't save quests

### ISSUE THREAD

**Issue by trycpr** [FlyingPikachu/Quests#299]
Hey there,

I don't seem to be able to save/exit when using /quests editor. The console shows some text about saving quests. Also, It'd be great if it was upgraded to 1.9, so I can use my server on the highest version.

Thanks.

**Comment by FlyingPikachu** [comment]
Please post your Quests version.

**Comment by trycpr** [comment]
Latest version on Jenkins, Quests-2.5.5.jar

**Comment by FlyingPikachu** [comment]
The latest version on Jenkins is 2.6.0, give that a try and post back with any errors.
