### ISSUE TITLE
Mob spawn event dont work

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#3]
Error: 
http://pastebin.com/a4dXq7St

**Comment by FlyingPikachu** [comment]
Is this on Quests 2.1.3? If not, please retry and check for console errors.

**Comment by SimbaZockt** [comment]
Yes with complete regeneratet files..

**Comment by FlyingPikachu** [comment]
I need more information about what steps you took to create this error.

**Comment by SimbaZockt** [comment]
1. /quests editor
http://prntscr.com/62up3t
2. Set mob Spawns
http://prntscr.com/62up8q
3. Set mob Type
http://prntscr.com/62upe8
4.Zombie
http://prntscr.com/62upih
5. Set spawn location
http://prntscr.com/62upky
6. ADD 
http://prntscr.com/62upoz
7.Set amount
http://prntscr.com/62upri
8.Finish - Done
http://prntscr.com/62upwr
9. Error
http://prntscr.com/62uq1e

hopefully it helpes

**Comment by FlyingPikachu** [comment]
How did you reach step 2? I cannot find how to get there after creating a quest.

**Comment by SimbaZockt** [comment]
oh sorry i mean /Quests events

**Comment by FlyingPikachu** [comment]
Apparently this issue was carried over from Quests 2.0.0. Fixed in Quests 2.1.5. Thanks!
