### ISSUE TITLE
Events mob spawning index out of bounds

### ISSUE THREAD

**Issue by AnthonyD4X** [FlyingPikachu/Quests#30]
When setting up mobs to spawn in the events you can successfully get 1 set to spawn but if you want to add some more mobs to spawn it will give an index out of bounds when you hit done.

**Comment by FlyingPikachu** [comment]
@AnthonyD4X Please provide your Quests version, the error, and the quest from quests.yml for testing.

**Comment by FlyingPikachu** [comment]
Closing due to lack of information and response from op. If this is still a problem, please create a new issue with the requested details. Thanks!
