### ISSUE TITLE
SkillApi Module is not working

### ISSUE THREAD

**Issue by Prowco** [FlyingPikachu/Quests#301]
What is your Quests version / build number (do _not_ say "latest")?
Quests 3.2.4
Please describe the problem and how to replicate it. Any console errors?
Skillapi module is not working the requeriments and rewards are not displayed.

**Comment by FlyingPikachu** [comment]
Please provide an example quest from quests.yml for testing. Use Pastebin.

**Comment by FlyingPikachu** [comment]
Closing due to lock of response from OP.
