### ISSUE TITLE
Unknown issue...

### ISSUE THREAD

**Issue by Rookie-G** [FlyingPikachu/Quests#302]
When I create a quest I can fill in all the boxes perfectly, no problem there. The only issues are when I made a quest I now get spammed with the letter 'a' in chat... Also there apparently is an internal error when I do ./questadmin reload. It's quite a vital command as you probably know. We on FlameSurvival RPG use quests a lot and consider it one of our main plugins, the reload issue only appears when we attempt to save a quest and reload them. Exiting the quest without saving has no error.
We currently use [this] (https://www.spigotmc.org/resources/quests.3711/) version of Quests, and we're running 1.9 Minecraft.
With the reload issue we get an NPE in console [logs.] (http://pastebin.com/gPAELr9p)
Any advice would be appreciated,
-Rookie
@FlyingPikachu

**Comment by FlyingPikachu** [comment]
One of your NPCs is invalid or there is an issue with Citizens. Make sure Citizens is setup properly and all of your NPC ids in quests.yml are correct.

**Comment by Rookie-G** [comment]
Thanks, I removed a bunch of quests that could only be found in 'quests.yml' for some reason. The commands ./questadmin reload still won't execute correctly but I do have a hunch like yours that the problem is in the Citizens plugin.

**Comment by FlyingPikachu** [comment]
Here is a thread with a similar error: https://www.spigotmc.org/threads/citizen-2-0-17-plugin-cant-work-on-1-9.132505/

The current suggestion seems to be updating Spigot, then Java. Since this problem is outside the scope of Quests, I must close this issue. If the problem persists after updating, please open a new ticket. Thanks!

**Comment by Rookie-G** [comment]
Thanks @FlyingPikachu, you've been a great help. :3
