### ISSUE TITLE
If used Timed Quest (Event: TimerStart) Chatoutput buggy

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#303]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
DevBuild 261
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Tried Timed Quest.
Used TimerStartEvent
Got this:

![quests](https://user-images.githubusercontent.com/1340357/36401818-619a719a-15da-11e8-91af-0429384fa8c7.jpg)

**Comment by FlyingPikachu** [comment]
If you're referring to the English text, that has already been resolved on Crowdin. Either update that line manually in your lang/de-DE/strings.yml or have the latest version of Quests (3.2.5 atm) regenerate the file.
