### ISSUE TITLE
Question! High Timing PlayerQuitEvent

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#304]
What is your Quests version / build number (do _not_ say "latest")?
DevBuild 264 (Quests 3.2.5)

After installing new Version, got some "Lags" with Quests.
Looked for timings:

![qu1](https://user-images.githubusercontent.com/1340357/36438551-95a6a57c-166a-11e8-896b-a1f55150dfeb.png)

Plugin Problem? Or maybe something else?

**Comment by FlyingPikachu** [comment]
Have you compared this to previous Quests versions? Not much has changed as far as the PlayerQuitEvent, which is what your report mentions. I'd imagine all versions take a bit of time to process that event, as player data needs to be checked and saved to disk.

If you come across any evidence to the contrary, I'll reopen this.
