### ISSUE TITLE
Suggestion: Hide Quests, if you dont meet the requirements

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#305]
Would it be possible to make an option to Hide Quests, where you dont meet the requirements?

Example:
Got NPC with Quests A, B, C and D

Without doing A, you cant do B, C, and D. 
To do so, thats no Problem, Quest Requirement A, and it works fine.

But Users, dont know that they must fullfill A first.
So they look and see "Oh, A, B, C and D" ... They taking A... then want B.. they see "Oh, Requirement"... C the same, D the same.
Why not only "Show" Quest A? 
And then, if the have done it, they will see "Ah, there is now another Quest" ?

**Comment by FlyingPikachu** [comment]
Sorry to have this sit on the back burner for so long.

I believe you want to set `ignore-locked-quests: true` in config.yml
