### ISSUE TITLE
Issue with quest points

### ISSUE THREAD

**Issue by Neoblade298** [FlyingPikachu/Quests#306]
So on my server, a death loses you 2 quest points through the command /questadmin takepoints 2. Works fine, however, the plugin allows you to go into negative numbers. This wouldn't be a problem, but when a player hits -1 or below, they're unable to do ANY quests, regardless of what quest point requirement I have them set at. I've tried setting a quest point requirement to a negative number but it doesn't allow it.

Whether this is an intended feature or not, it'd be nice if it were possible to set the minimum quest point value to 0.

**Comment by FlyingPikachu** [comment]
Please create a new ticket if this is still an issue.Thanks!
