### ISSUE TITLE
Can't change language 

### ISSUE THREAD

**Issue by TommyVic** [FlyingPikachu/Quests#306]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
323-b254 UNSTABLE
(__Required__) Please describe the problem and how to replicate it. Any console errors?
There's no console error but when i change the config file to vi ( Vietnamese) it doesn't work 
Do i have to set it vi-VI like en-EN ? or just vi cus vi is not working
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/uEQVet62

**Comment by Leomelonseeds** [comment]
Go into the lang folder of the quests plugin, and copy one of the file names as your language from there (eg. en-US = english)

**Comment by FlyingPikachu** [comment]
Please don’t use the builds marked “UNSTABLE”. Update to a newer, stable version! That build also doesn’t contain all translations for Vietnamese.

Once you’ve updated, just “vi” should work.

**Comment by TommyVic** [comment]
Can you link me to the lastest version ? for server 1.11.2 ? 
Also does this plugin link with mythicmobs ?

**Comment by Leomelonseeds** [comment]
The latest version works with 1.11.2 I think.
You need to download a module (link on spigot page) and then place it in the modules folder for MythicMobs compatibility.

**Comment by FlyingPikachu** [comment]
@TommyVic It will work for 1.11.2 - http://ci.ac3-servers.eu/job/Quests/264/

For MythicMobs, this is the module you'd need - https://www.spigotmc.org/resources/mythicmobs-quests-module.7261/
