### ISSUE TITLE
1.9 items-to-deliver Dosen't Work

### ISSUE THREAD

**Issue by Sollitude** [FlyingPikachu/Quests#307]
My quest have this stage
```
        '1':
          items-to-deliver:
            - name-cobblestone:amount-10
          npc-delivery-ids:
            - 2
```
But when i loads the mission the mission is not there. If i remove the stage and put some other stage in it works.

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
