### ISSUE TITLE
Some weird things...

### ISSUE THREAD

**Issue by Leomelonseeds** [FlyingPikachu/Quests#307]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.5
(__Required__) Please describe the problem and how to replicate it. Any console errors?
So I'm really confused about 2 things here:
1. For the break blocks type stage, it seems like a silk touch pickaxe breaking the specified block will not count as the block being broken. Any reason for this?
2. Mob killing type stage does not seem to work. When I started my "Kill 10 zombies" quest, I went and killed some zombies, with no result. I tried using an enchanted sword, a normal sword, taking off custom enchanted armor, with no avail. The counter stayed at 0/10.

There are no console errors. 

Also, you should add an option to notify a player each time he gets a part of the stage done (eg. When zombie killed, notify "1/10").

Thanks :)

**Comment by Leomelonseeds** [comment]
Sorry, heres my quests.yml:
`quests:
  Miner:
    name: 'Miner'
    ask-message: '<yellow>Mine a series of blocks and ores. Rewards: 1500 Mokens, 500 exp, 6 quest points, and a chat tag.'
    finish-message: '<yellow>Well done. Here are 1500 Mokens, 500 exp, 5 quest points, and a chat tag!'
    redo-delay: 86400
    stages:
      ordered:
        1:
          break-block-names:
            - STONE
          break-block-amounts:
            - 64
          break-block-durability:
            - 0
          finish-event: NiceFinish
        2:
          break-block-names:
            - COAL_ORE
          break-block-amounts:
            - 32
          break-block-durability:
            - 0
          finish-event: NiceFinish
        3:
          break-block-names:
            - IRON_ORE
          break-block-amounts:
            - 16
          break-block-durability:
            - 0
          finish-event: NiceFinish
        4:
          break-block-names:
            - GOLD_ORE
          break-block-amounts:
            - 10
          break-block-durability:
            - 0
          finish-event: NiceFinish
        5:
          break-block-names:
            - DIAMOND_ORE
          break-block-amounts:
            - 8
          break-block-durability:
            - 0
          finish-event: NiceFinish
        6:
          break-block-names:
            - EMERALD_ORE
          break-block-amounts:
            - 1
          break-block-durability:
            - 0
          finish-event: NiceFinish
    rewards:
      money: 1500
      exp: 500
      quest-points: 6
      permissions:
        - deluxetags.tag.miner
  Hunter:
    name: 'Hunter'
    ask-message: '<yellow>Kill a series of passive mobs! Rewards: 500 Mokens, 200 exp, 2 quest points, and a chat tag.'
    finish-message: '<yellow>Good job! Here are 500 Mokens, 200 exp, 2 quest points, and a chat tag!'
    redo-delay: 7200
    stages:
      ordered:
        1:
          mobs-to-kill:
            - Cow
          mob-amounts:
            - 10
          finish-event: NiceFinish
        2:
          mobs-to-kill:
            - Sheep
          mob-amounts:
            - 10
          finish-event: NiceFinish
        3:
          mobs-to-kill:
            - Pig
          mob-amounts:
            - 10
          finish-event: NiceFinish
        4:
          mobs-to-kill:
            - Chicken
          mob-amounts:
            - 10
          finish-event: NiceFinish
    rewards:
      money: 500
      exp: 200
      quest-points: 2
      permissions:
        - deluxetags.tag.hunter
  Slayer:
    name: 'Slayer'
    ask-message: '<yellow>Kill a series of monsters! Rewards: 1000 Mokens, 500 exp, 5 quest points, and a chat tag.'
    finish-message: '<yellow>Good job! Here are 1000 Mokens, 500 exp, 5 quest points, and a chat tag!'
    redo-delay: 86400
    stages:
      ordered:
        1:
          mobs-to-kill:
            - Zombie
          mob-amounts:
            - 10
          finish-event: NiceFinish
        2:
          mobs-to-kill:
            - Skeleton
          mob-amounts:
            - 10
          finish-event: NiceFinish
        3:
          mobs-to-kill:
            - Spider
          mob-amounts:
            - 10
          finish-event: NiceFinish
        4:
          mobs-to-kill:
            - Creeper
          mob-amounts:
            - 10
          finish-event: NiceFinish
        5:
          mobs-to-kill:
            - Enderman
          mob-amounts:
            - 10
          finish-event: NiceFinish
    rewards:
      money: 1000
      exp: 500
      quest-points: 5
      permissions:
        - deluxetags.tag.slayer
  CatchFish:
    name: 'Catch Fish'
    ask-message: '<yellow>Catch 10 fish!'
    redo-delay: 300
    finish-message: '<yellow>Good job. Here is some <green>experience<yellow>.'
    stages:
      ordered:
        1:
          fish-to-catch: 10
    rewards:
      exp: 100
      quest-points: 1
  SleketanHunter:
    name: 'Skeleton King Hunter'
    ask-message: '<yellow>Kill the Skeleton King!'
    finish-message: '<yellow>You did it! Have <green>1000 Mokens <yellow>, some <green>experience<yellow>, and a chat tag (use /tags)!'
    redo-delay: 172800
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data: 
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: 'false'
                Notifier msg: Killed %c% out of %s%
                Objective Name: Kill a Skeleton King
                Internal Mobnames: SkeletonKing
    rewards:
      money: 1000
      exp: 250
      quest-points: 5
      permissions:
        - deluxechat.tag.kslayer`

**Comment by Leomelonseeds** [comment]
Oh , and here's my quests.yml:
`
quests:
  Miner:
    name: 'Miner'
    ask-message: '<yellow>Mine a series of blocks and ores. Rewards: 1500 Mokens, 500 exp, 6 quest points, and a chat tag.'
    finish-message: '<yellow>Well done. Here are 1500 Mokens, 500 exp, 5 quest points, and a chat tag!'
    redo-delay: 86400
    stages:
      ordered:
        1:
          break-block-names:
            - STONE
          break-block-amounts:
            - 64
          break-block-durability:
            - 0
          finish-event: NiceFinish
        2:
          break-block-names:
            - COAL_ORE
          break-block-amounts:
            - 32
          break-block-durability:
            - 0
          finish-event: NiceFinish
        3:
          break-block-names:
            - IRON_ORE
          break-block-amounts:
            - 16
          break-block-durability:
            - 0
          finish-event: NiceFinish
        4:
          break-block-names:
            - GOLD_ORE
          break-block-amounts:
            - 10
          break-block-durability:
            - 0
          finish-event: NiceFinish
        5:
          break-block-names:
            - DIAMOND_ORE
          break-block-amounts:
            - 8
          break-block-durability:
            - 0
          finish-event: NiceFinish
        6:
          break-block-names:
            - EMERALD_ORE
          break-block-amounts:
            - 1
          break-block-durability:
            - 0
          finish-event: NiceFinish
    rewards:
      money: 1500
      exp: 500
      quest-points: 6
      permissions:
        - deluxetags.tag.miner
  Hunter:
    name: 'Hunter'
    ask-message: '<yellow>Kill a series of passive mobs! Rewards: 500 Mokens, 200 exp, 2 quest points, and a chat tag.'
    finish-message: '<yellow>Good job! Here are 500 Mokens, 200 exp, 2 quest points, and a chat tag!'
    redo-delay: 7200
    stages:
      ordered:
        1:
          mobs-to-kill:
            - Cow
          mob-amounts:
            - 10
          finish-event: NiceFinish
        2:
          mobs-to-kill:
            - Sheep
          mob-amounts:
            - 10
          finish-event: NiceFinish
        3:
          mobs-to-kill:
            - Pig
          mob-amounts:
            - 10
          finish-event: NiceFinish
        4:
          mobs-to-kill:
            - Chicken
          mob-amounts:
            - 10
          finish-event: NiceFinish
    rewards:
      money: 500
      exp: 200
      quest-points: 2
      permissions:
        - deluxetags.tag.hunter
  Slayer:
    name: 'Slayer'
    ask-message: '<yellow>Kill a series of monsters! Rewards: 1000 Mokens, 500 exp, 5 quest points, and a chat tag.'
    finish-message: '<yellow>Good job! Here are 1000 Mokens, 500 exp, 5 quest points, and a chat tag!'
    redo-delay: 86400
    stages:
      ordered:
        1:
          mobs-to-kill:
            - Zombie
          mob-amounts:
            - 10
          finish-event: NiceFinish
        2:
          mobs-to-kill:
            - Skeleton
          mob-amounts:
            - 10
          finish-event: NiceFinish
        3:
          mobs-to-kill:
            - Spider
          mob-amounts:
            - 10
          finish-event: NiceFinish
        4:
          mobs-to-kill:
            - Creeper
          mob-amounts:
            - 10
          finish-event: NiceFinish
        5:
          mobs-to-kill:
            - Enderman
          mob-amounts:
            - 10
          finish-event: NiceFinish
    rewards:
      money: 1000
      exp: 500
      quest-points: 5
      permissions:
        - deluxetags.tag.slayer
  CatchFish:
    name: 'Catch Fish'
    ask-message: '<yellow>Catch 10 fish!'
    redo-delay: 300
    finish-message: '<yellow>Good job. Here is some <green>experience<yellow>.'
    stages:
      ordered:
        1:
          fish-to-catch: 10
    rewards:
      exp: 100
      quest-points: 1
  SleketanHunter:
    name: 'Skeleton King Hunter'
    ask-message: '<yellow>Kill the Skeleton King!'
    finish-message: '<yellow>You did it! Have <green>1000 Mokens <yellow>, some <green>experience<yellow>, and a chat tag (use /tags)!'
    redo-delay: 172800
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data: 
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: 'false'
                Notifier msg: Killed %c% out of %s%
                Objective Name: Kill a Skeleton King
                Internal Mobnames: SkeletonKing
    rewards:
      money: 1000
      exp: 250
      quest-points: 5
      permissions:
        - deluxechat.tag.kslayer
`

**Comment by Leomelonseeds** [comment]
Oh, and here's my quests.yml:
https://pastebin.com/AybqUH7p

**Comment by FlyingPikachu** [comment]
Thanks for using Quests!

1. Looking at the code, this appears to be intentional for players that wish to break blocks without progressing a quest. Seeing as there are no similar conditions for placing or damaging blocks, I'm open to removing this "feature" if need be.
2. Your Slayer quest worked just fine for me, incrementing the number of Zombies killed. Could another plugin be stopping the EntityDeathEvent from being passed on to Quests?

I feel notifying players every time a player breaks a block would likely be considered annoying. However, feel free to request that feature as a suggestion in a _separate_ issue, if you please.

**Comment by Leomelonseeds** [comment]
Thanks for replying!
I dunno about the silktouch pickaxe "feature", maybe you shoudn't remove it as people don't really go mining with a silktouch pickaxe xD
Here's some plugins that might be causing the Slayer problem:
- Mcmmo
- CrazyEnchantments
- MythicMobs
- Mcore Factions?
- CombatlogX?
- Compat NoCheatPlus?
(? means possible, but not that possible)
Could you please give a suggestion on which I should remove?

**Comment by FlyingPikachu** [comment]
Frankly, it could be any of those plugins, or none of them. Without some kind of lead, your guess is as good as mine. I suppose I'd start with MythicMobs since that undoubtedly tweaks the death event.
