### ISSUE TITLE
Lore error on saving

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#309]
3.2.4 b261

Create an item with ':' in lore and try to use it for quests

[Fri, 23. Feb 2018 12:55:58 CET ERROR] [Quests] Make sure you aren't using the config section idetifier.
[Fri, 23. Feb 2018 12:55:58 CET ERROR] [Quests] name-MAP:amount-1:data-860:displayname-Чертёж Кирки Дормхеймского Каменщика:lore-**_Тип:_**:lore-Разное:lore----===]]=Описание=[[===---:lore-Используйте у мастера кузнечного дела,:lore-чтобы научиться создавать предмет чертежа. inside items-to-deliver: inside Stage 1 of Quest Орудие Каменщика is not formatted properly!
[Fri, 23. Feb 2018 12:55:58 CET ERROR] [Quests] name-MAP:amount-1:data-860:displayname-Чертёж Кирки Дормхеймского Каменщика:lore-Тип::lore-Разное:lore----===]]=Описание=[[===---:lore-Используйте у мастера кузнечного дела,:lore-чтобы научиться создавать предмет чертежа. inside items-to-deliver: inside Stage 1 of Quest Поиск чертежа дормхеймской кирки is not formatted properly!

**Comment by FlyingPikachu** [comment]
Because ':' is used to separate data, this cannot be used in lore (or any other item property). You must remove the ':' from your lore. I will look into preventing people from accidentally adding ':' but there will be no work-around.

**Comment by ScuroK** [comment]
@FlyingPikachu  latest version broke most of my quests because of ':'

You didnt give any informations how we should change our quest files. pls help

**Comment by FlyingPikachu** [comment]
@ScuroK Simply remove the ':' you have added to your item lore from quests.yml
