### ISSUE TITLE
Right Clicking on my "Quests Merchant"

### ISSUE THREAD

**Issue by Biscoot1** [FlyingPikachu/Quests#310]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.4-b255
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When I rightclick on the npc it just prompts to tell me the npc id in chat and not the gui.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
This is not an error. There is currently no way to enter an NPC ID through a GUI.
