### ISSUE TITLE
Possibility to run an event when timer runs out?

### ISSUE THREAD

**Issue by oldquestman** [FlyingPikachu/Quests#313]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.5
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When you create a timed event, it fails the quest when the timer runs out like expected. But there doesn't seem to be a way to run an event when that happens (like you can have death event and logout event). Have I overlooked something or is this really the case?

**Comment by FlyingPikachu** [comment]
This is not possible because you'd be running an event for a Quest which is no longer being taken.

**Comment by oldquestman** [comment]
Well you can run a death or a logout event even if they have fail-quest set
to true.
That way when someone for example dies during the quest, they fail the
quest and also a bunch of commands can be run through the death event to
"reset" everything back to how it was at the start.

Now the timer timeout does fail the quest automatically but there is no way
to run an event

sunnuntai 25. helmikuuta 2018 FlyingPikachu <notifications@github.com>
kirjoitti:
