### ISSUE TITLE
Could not pass event PlayerDeathEvent to Quests v3.2.5-b264

### ISSUE THREAD

**Issue by PortGasMC** [FlyingPikachu/Quests#314]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Build 3.2.5 

(__Required__) Please describe the problem and how to replicate it. Any console errors?
im using : spigot 1.12.2 latest build
               : infernal mobs
               : custombosses
error : https://pastebin.com/cLpFWtt2

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Using the default quest.yml
https://pastebin.com/q7dgpj2M

**Comment by FlyingPikachu** [comment]
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.
