### ISSUE TITLE
Quests not saving

### ISSUE THREAD

**Issue by t0xic1** [FlyingPikachu/Quests#315]
Using the newest plugin Quests 2.6.0
Sometimes when i save quests the plugin doesn't save them then i have to delete all the files and reinstall the plugin.
This happens everyday usually.

Here is some error it might be related to the problem : http://pastebin.com/ysaQVtsi

**Comment by FlyingPikachu** [comment]
Please update to the latest build and create a new ticket if this is still an issue. Thanks!
