### ISSUE TITLE
Really Important Question.

### ISSUE THREAD

**Issue by durson54** [FlyingPikachu/Quests#316]
Version: 3.2.5-b264
So I have a question. My server is RPG based and I use SkillAPI for classes,skills. And there's the feature to have many "accounts" so you can change accounts and have another class. But there's a problem with it. When I changed my acc, Quests didn't "reset" so I'm continuing. If you know what I mean. So I want to separate it for each account. How can I do this? Is it possible? Please it's really important, otherwise I can't have more accounts.

**Comment by durson54** [comment]
Also I saw on one server that when they talk to Quest NPC It will open book for them and There'll be title if you want to accept the quest and down below it will be ✔Yes ✘No. How can I do this?

**Comment by FlyingPikachu** [comment]
Unfortunately, Quests is not account-bound for SkillAPI.

As for the book, I'd have to see it. Perhaps they coded their own module for that.

**Comment by durson54** [comment]
But couldn't you make a update for it? :/
