### ISSUE TITLE
Using colons breaks most of my quests!!!

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#318]
For example:

22:16:27 CONSOLE: ERROR]: [Quests] 6[Quests] "cname-TRIPWIRE_HOOK:amount-1:enchantment-Infinity 1:displayname-9TardisKey6" inside a items: 6inside Event 5Tardis16 is not formatted properly!

What have you done?? Can you please fix this?

**Comment by ScuroK** [comment]
22:12:36 CONSOLE: ERROR]: [Quests] name-DIAMOND_AXE:amount-1:enchantment-Unbreaking 3:displayname-Försterhacke in items: Reward in Quest Förster is not properly formatted!
22:12:36 CONSOLE: ERROR]: [Quests] name-LEATHER_BOOTS:amount-1:enchantment-DepthStrider 3:displayname-Wasserläufer in items: Reward in Quest Hexe in Not is not properly formatted!
22:12:36 CONSOLE: ERROR]: [Quests] 6[Quests] "cname-TRIPWIRE_HOOK:amount-1:enchantment-Infinity 1:displayname-9TardisKey6" inside a items: 6inside Event 5Tardis16 is not formatted properly!
22:12:36 CONSOLE: ERROR]: [Quests] finish-event: in Stage 2 of Quest Der Doktor failed to load.
22:12:36 CONSOLE: ERROR]: [Quests] 6[Quests] "cname-TRIPWIRE_HOOK:amount-1:enchantment-Infinity 1:displayname-9TardisKey6" inside a items: 6inside Event 5Tardis16 is not formatted properly!
22:12:36 CONSOLE: ERROR]: [Quests] Failed to load Event "Tardis1". Skipping.

**Comment by ScuroK** [comment]
Since Quests dont have any options to run multiple delayed commands i HAVE to use conditionalcmds.

Example Event:
Tardis10:
message: '&9&oWir treffen uns bei der Tardis!'
commands:
- 'ccmd <player> if -perm:essentials.spawn-=1 do /0/ npc select 391 /40/ sentinel
guard /80/ sentinel respawn'

I HAVE to use ":". All my quests (hours of work) are broken now!

why cant we use something like ' to fix it? 
'command:with:colons'


i HAD TO downgrade. otherwise quests is worthless on my server because i use it for nice complex quests. there is a need to use ":" within the bukkit/spigot system. for example if different plugins share commands or if i need to use conditionalcommands to make quest run multiple commands with a delay in between...

**Comment by ScuroK** [comment]
pls help :( @FlyingPikachu

**Comment by FlyingPikachu** [comment]
I am not currently at a computer from which I can assist you. Since you’re a longtime user, feel free to post your quests.yml via Pastebin and I will attempt to remove the problematic colons for you once I’m available.

**Comment by ScuroK** [comment]
@FlyingPikachu
I think not only quests.yml is the problem but also some of my important command events. 

https://pastebin.com/WtB3w5t6
https://pastebin.com/BS4d6yCf

**Comment by FlyingPikachu** [comment]
I've removed every invalid instance of ":" (colons) I could find. Note that your give commands will likely no longer work. Use the Give Items option instead. If any errors occur on startup, just post them here and I'll take another look.

https://pastebin.com/eQ6aG5U2
https://pastebin.com/vg4aWGcL

[events.txt](https://github.com/FlyingPikachu/Quests/files/1759423/events.txt)
[quests.txt](https://github.com/FlyingPikachu/Quests/files/1759426/quests.txt)

**Comment by ScuroK** [comment]
thx alot! i will test it out as soon as i have some time. im pretty busy this week.

**Comment by ScuroK** [comment]
how about ehe events.yml? i see there are alot of colons in commands left. Is this ok?

**Comment by FlyingPikachu** [comment]
I don't see any that shouldn't be there, but the best way to known is to just try loading it.

**Comment by ScuroK** [comment]
@FlyingPikachu It seems to work now but the letter "ä" doesnt work anymore.

**Comment by ScuroK** [comment]
it shows a ? kind of symbol instead.

could you fix this?

**Comment by ScuroK** [comment]
@FlyingPikachu same goes for letter "ö"

it doesnt work

**Comment by FlyingPikachu** [comment]
That sounds like a separate problem. I’d appreciate if you could open a new issue for that.
