### ISSUE TITLE
Multi Delivery

### ISSUE THREAD

**Issue by Roy416** [FlyingPikachu/Quests#318]
I am trying to make a quest where the player kills mobs in one stage, and in the second stage returns some of the remains. Blaze rods, nuggets, and spider eyes. I get the error the item list and npc list are not equal in size. Thanks in advance!

**Comment by Liphius** [comment]
Not sure how i'd fix that, but I'd go around it by making multiple stages that asks for each of the items.

So Stage 2 would ask for Blaze Rods
Stage 3 would ask for nuggets
and Stage 4 would ask for the spider eyes.

However, it may not be ideal in your situation but a temporary fix until the author or someone with more knowledge helps you out.

**Comment by Roy416** [comment]
I found out a bit later just by reading what it was saying. I just had to repeat the NPC ID the same amount of times as the number of items I had. So if the NPC ID was 11 and I had 3 items, I would do ' 11 11 11 ', for choosing the npc.

**Comment by FlyingPikachu** [comment]
If I understand correctly, this issue has been resolved. Otherwise, please create a new ticket. Thanks!
