### ISSUE TITLE
Can i ask how to make custom requirement

### ISSUE THREAD

**Issue by hichay** [FlyingPikachu/Quests#319]
In my server have Ecoin = Credits
it mean member use real money to buy Ecoin and then use Ecoin to buy item in server.
So i want ask how i can make ecoin requirement to accept a quests from npc. i can only see Money requirment and other no Credits

**Comment by Liphius** [comment]
Is it a virtual currency or item currency?

**Comment by FlyingPikachu** [comment]
Closed to due lack of response from OP.
