### ISSUE TITLE
lanuage de-DE does not work for me

### ISSUE THREAD

**Issue by zippoking** [FlyingPikachu/Quests#320]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.6-b266 from 25.02.2018

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hey,

so i got this issue with the language files.
On first plugin load no lang folder and files are generated.
After setting manually the folder and files, it still does not work.

See Console and Folder structure: 
[Console output and folder structure](https://imgur.com/secllru.png)

Windows 7 x64
I really want to use the plugin in german, especially after people put effort in the translation!
Thanks a lot.

**Comment by FlyingPikachu** [comment]
Are you sure all subfolders have read/write permission? You can check/apply this in Win7 by right-clicking on the folder and selecting Properties -> Security -> Advanced

**Comment by zippoking** [comment]
I checked it a couple of times and since all other plugins are able to write data to their files....i think everything is fine.

But take a look for yourself:
Windows folder permission: [Quest/lang/de-DE](https://imgur.com/krgmh8D.png)

Hope you can figure it out =)
Best regards
Zippoking

**Comment by FlyingPikachu** [comment]
Assuming "Vollzugriff" means "full access," everything looks good. I'm stumped.

Try unpacking this Zip folder into your /plugins/Quests directory. It's the language strings downloaded straight from Crowdin, de-DE included.
[lang.zip](https://github.com/FlyingPikachu/Quests/files/1768354/lang.zip)

**Comment by zippoking** [comment]
Correct, "Vollzugriff" means "full access".
I really tried everything, putting the lang files in every folder :-D

Unfortunately it still doesn´t work. "Failed loading lang files...." in the console.

Also the default language strings are implemented right into the plugin, aren´t they? 
There is no strings file for those? Cause i would just copy the text from the german file into the english file and hope that it works :-D

**Comment by FlyingPikachu** [comment]
Yes, the files exist within the plugin and are supposed to be generated into the /lang folder whenever they're missing.

I'd like to take a look at your full startup log. Can you post a link to your SpigotMC profile and I'll send you a PM? Since you blacked out part of your first image, I assume you'd rather not post it here.

**Comment by zippoking** [comment]
Sure. Here is my profile link:
https://www.spigotmc.org/members/zippolino.183883/

Actually i dont know why i blacked out the part of my first image :-D. However if you need the full startup log lets switch over to SpigotMC PM.

**Comment by ScuroK** [comment]
i dont like the totally translated lang file in terms of commands. i made my own trasnlation for important things like "Yes" and "No" and stuff. but i kept the commands in english. thats pretty normal with plugins

**Comment by FlyingPikachu** [comment]
@ScuroK That is entirely unrelated to this ticket. Please create a new issue if you'd like to discuss that.

**Comment by Sprungente** [comment]
But @ScuroK have right :)

Any commands should work. If not tell us the command ! Try to remove the lang folder and restart the server. It helps me a lot when the lang-file don't load.

**Comment by ScuroK** [comment]
@Sprungente  thx mate. my suggestion was to leave the commands in english and only add translated descriptions. just like most other multi lingual plugins out there.

**Comment by FlyingPikachu** [comment]
This ticket seems to be getting off-track. I'm already in touch with @zippoking on SpigotMC regarding this issue, so I'll go ahead and close this.

@ScuroK You might want to check out the new `translate-subcommands` settings in Quests 3.2.7
