### ISSUE TITLE
Cannot view quests

### ISSUE THREAD

**Issue by LoreCase** [FlyingPikachu/Quests#321]
I right click a questing npc and this happens.

  
    02.05 06:50:43 [Server] INFO [06:50:43 INFO]: Saved the world
    02.05 06:50:43 [Server] INFO [06:50:43 INFO]: Saving...
    02.05 06:50:43 [Server] INFO [06:50:43 INFO]: Saving is already turned on.
    02.05 06:50:43 [Multicraft] Skipped 4 lines due to rate limit (30/s)
    02.05 06:50:43 [Multicraft] Auto-saving world...
    02.05 06:50:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source) ~[?:?]
    02.05 06:50:36 [Server] INFO at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:128) ~[?:?]
    02.05 06:50:36 [Server] INFO at me.blackvein.quests.Quester.interactWithNPC(Quester.java:1180) ~[?:?]
    02.05 06:50:36 [Server] INFO Caused by: java.lang.NullPointerException
    02.05 06:50:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
    02.05 06:50:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1532) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    02.05 06:50:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    02.05 06:50:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
    02.05 06:50:36 [Server] INFO at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:394) [citizens-2.0.17-SNAPSHOT.jar:?]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
    02.05 06:50:36 [Server] INFO org.bukkit.event.EventException
    02.05 06:50:36 [Server] INFO [06:50:36 ERROR]: Could not pass event NPCRightClickEvent to Quests v2.6.0-b99

**Comment by Zalakoth** [comment]
Have you tried to re-install the plugin? (Back-up your quests.yml before doing this!)

**Comment by FlyingPikachu** [comment]
@LoreCase Also, post your Spigot version.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. Please update to the latest build and create a new ticket if this is still an issue. Thanks!
