### ISSUE TITLE
Letters like Ää Öö dont work anymore

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#323]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.5
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Letters like Ä Ö Ü inside quests dont work anymore. it shows a "?" symbol instead.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/vg4aWGcL

**Comment by FlyingPikachu** [comment]
Did those letters work previously outside of lang files? I'm thinking it's probably because of the quests.yml file encoding, which hasn't changed lately.

**Comment by FlyingPikachu** [comment]
To elaborate on my last comment, your quests.yml file needs to be in UTF-8 format. If you're on Windows, shut down your server and open the quests.yml in Notepad. Go to Save As and, at the bottom of the window, you'll see "Encoding:". Make sure it's set to UTF-8 and overwrite the old file.

https://github.com/FlyingPikachu/Quests/commit/220e0c0e6763ac99845cbba7f95d5f45f430b2b1 should help make this more evident in the future.

**Comment by ScuroK** [comment]
@FlyingPikachu still broken. not it shows something like "^" instead of "?"
https://imgur.com/a/E6PbM

**Comment by FlyingPikachu** [comment]
That doesn't happen for me. Make sure the character is actually 'ö' in your quests.yml


![forster](https://user-images.githubusercontent.com/2267126/36939518-d746e72e-1eff-11e8-82d5-a4fd0d6fc501.png)

**Comment by ScuroK** [comment]
sry i had to fix my files now it works
