### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Vilican** [FlyingPikachu/Quests#324]
I encountered this bug: [https://sufix.cz/res/files/quests-bug.png](https://sufix.cz/res/files/quests-bug.png)
It appears when someone is online. Could you fix this?

**Comment by FlyingPikachu** [comment]
Please try the 1.9.4 test build once it's out:
http://ci.ac3-servers.eu/job/Quests/100/

**Comment by Vilican** [comment]
Ok, fixed. Thank you
