### ISSUE TITLE
Talking to NPC in stages

### ISSUE THREAD

**Issue by norghloS** [FlyingPikachu/Quests#325]
Quests Version 3.2.5

As second stage of a quest I have set it to require you "talk" to 3 NPCs. When I right click on any of those 3 NPCs I get the message "No more quests available". Can not complete quest as a result.

**Comment by FlyingPikachu** [comment]
Unable to replicate in my test environment. Please upload your quests.yml for review.

**Comment by norghloS** [comment]
As per your request:


[quests.zip](https://github.com/FlyingPikachu/Quests/files/1782009/quests.zip)

**Comment by Sprungente** [comment]
I have this issue too, but longer time ago as i tried out

**Comment by FlyingPikachu** [comment]
@norghloS Stage 3 of your quest doesn't contain any objectives other than a Complete Message (which is meant to be send upon completion of a real objective). Looking into preventing confusion in the future, but for now just delete Stage 3 of your quest and add the Complete Message to Stage 2.
