### ISSUE TITLE
Commands with colons broken?

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#326]
@FlyingPikachu You recently fixed my quests.yml and events.yml

Here is my problem in events.yml:
It seems like you changed this command event:
- ccmd <player> if -perm:essentials.spawn-=1 do /0/ npc select 391 /40/ sentinel
      guard /80/ sentinel respawn

to

- ccmd <player> if -essentials.spawn-=1 do /0/ npc select 391 /40/ sentinel
      guard /80/ sentinel respawn

wich makes the command not working.

could you tell me why this is and if i can revert or fix it. because since quests is unable to execute commands in a scheduled/delayed way i am depending on "conditionalcommands"

**Comment by FlyingPikachu** [comment]
I removed the colon in #318 simply so your events.yml would load. Formatting for whatever plugin's command that is is unrelated to Quests and it's up to you to find an alternative, if one exists. You could try a plugin [like this](https://www.spigotmc.org/resources/%E2%99%9B-commanddelay-%E2%99%9B-1-8-8-1-12-x-%E2%9C%94.40014/) for delaying certain commands.

Please discuss future support for colons in #275, where @SXRWahrheit suggested an alternative
