### ISSUE TITLE
Console Error with Spigot 1.9.4

### ISSUE THREAD

**Issue by sleite** [FlyingPikachu/Quests#328]
3:18:05 PM [WARN] [Quests] Task #1712 for Quests v2.6.0-b99 generated an exception
3:18:05 PM java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/Packet
3:18:05 PM at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread.java:134) ~[?:?]
3:18:05 PM at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:79) ~[?:?]
3:18:05 PM at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
3:18:05 PM at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
3:18:05 PM Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet
3:18:05 PM at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
3:18:05 PM at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
3:18:05 PM at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
3:18:05 PM ... 10 more

**Comment by sleite** [comment]
Note:  Server / Plug-In still seems to work (so far), even with the occassional server spam.

**Comment by FlyingPikachu** [comment]
Use this dev build http://ci.ac3-servers.eu/job/Quests/100/
