### ISSUE TITLE
Enchanting items rewards not working

### ISSUE THREAD

**Issue by PTsandro** [FlyingPikachu/Quests#33]
http://pastebin.com/1431f7Ku

My config of the items with enchant rewards:

- name-WOOD_SWORD:amount-1:enchantment-Sharpness 1:enchantment-Durability 2:displayname-Porkinator:lore-Faca de Cozinha para Matar Porcos

**Comment by FlyingPikachu** [comment]
Sorry for the late reply. Rename "Durability" to "Unbreaking". Thanks!
