### ISSUE TITLE
Tame Mob Quests wont work

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#330]
What is your Quests version / build number (do _not_ say "latest")?
3.2.5-b264
Please describe the problem and how to replicate it. Any console errors?

I created two Quests, to tame mobs. Tried them, another User tried them, everthing worked fine.
After a normal Server restart, another User tried to do the Quest. He accepted it, and then: Error in Console.

Can you provide an example quest from quests.yml _using Pastebin.com_?

Quest: https://pastebin.com/82TSskD6

Error, started with User coming Online: https://pastebin.com/UKsebMaG

Same, with another Quest with Lamas: https://pastebin.com/SEFvaaTH

**Comment by FlyingPikachu** [comment]
Worked just fine for me:

![wolf](https://user-images.githubusercontent.com/2267126/37378266-e3eb873e-2704-11e8-9c86-bc68d6e685c2.png)

Are you running any mods which might modify the EntityType enum? You could also try a newer dev build of Quests. I'm currently running http://ci.ac3-servers.eu/job/Quests/281/

**Comment by FlyingPikachu** [comment]
@Regnak85 I was able to encounter the error after restarting my test server. The latest commit (and thus, latest dev build) fixes this issue. Thanks for using Quests!
