### ISSUE TITLE
Mobkill doesnt count

### ISSUE THREAD

**Issue by Sefreneth** [FlyingPikachu/Quests#331]
3.2.4-b255
 
I have normal mobkill quests (like kill 5 pigs, kill 15, skeletons) that worked ALL THE TIME, and stopped working, basicly, it doesn't count kills. Its like players didn't kill anything. Not even new created quests.
Any idea?

**Comment by FlyingPikachu** [comment]
Unless you changed versions recently, it's likely another plugin is interfering with the entity death event. Have you added/changed anything like WorldGuard or anti-cheat plugins lately?

**Comment by Fortepsai** [comment]
We have Spartakus Anti Cheat for quite few months and its seems doing its thing but havent noticed something got broken, nevertheless we have addons for Quests and BetonQ for MM kill, thats all i can tell . 
With world guard there is nothing i can come with, which would interefere with quests .

**Comment by FlyingPikachu** [comment]
@Fortepsai tells me via Spigot chat that he and @Sefreneth are on the same server.

Anti-cheat plugins and WorldGuard could certainly be interfering. The best way to test that is to simply disable the plugins for a moment and see then if the kill-mob quest works.

If one of you can provide a sample quest from quests.yml, I can try to replicate the problem.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response.
