### ISSUE TITLE
Quests journal multiply

### ISSUE THREAD

**Issue by Sefreneth** [FlyingPikachu/Quests#332]
3.2.4-b255
No console errors, bug occurs quite often, like 2 from 10 players time to time randomly. They run /quests journal command and when they run it again, Instead of putting journal away it creates new one completely empty. And as you cant throw it away its messy. Even i cant remove it from players inventory, except of running /clear . Any ideas?

**Comment by FlyingPikachu** [comment]
This typically happens whenever there is either 1) a server/plugin reload, or 2) the Quests Journal's title or lore is modified in some way that the plugin cannot recognize. The former is most likely. What is preventing your players from throwing the old Journal away?

**Comment by Fortepsai** [comment]
Not even OP can throw that journal away, and there was actualy no reload of any sorts, and that was the issue .

**Comment by FlyingPikachu** [comment]
I've just added the permission "quests.admin.drop" to Quests. Any player that has this permission (including OPs) will be able to drop their Quests Journal.

Once available, use the following dev build to make use of this feature:
http://ci.ac3-servers.eu/job/Quests/283/

**Comment by FlyingPikachu** [comment]
By the way, the above build of Quests will likely break the MythicMobsQuestModule. If need be, use this custom build to restore functionality:
https://www.dropbox.com/s/2pq695oqodtpgb1/MythicMobsQuestModule_custom.jar?dl=0

**Comment by Fortepsai** [comment]
Thank you very much  @FlyingPikachu  !
