### ISSUE TITLE
/quests NULL ?

### ISSUE THREAD

**Issue by GizaRoho** [FlyingPikachu/Quests#333]
I am running the latest version on this plugin and the latest version of Spigot, however when I try to use any of the commands it just responds with "NULL" and when just typing "/quests" it shows each command ending in "NULL" also. 

I am unsure how to fix this, please help.

**Comment by meegamax** [comment]
I am having the same issue and would also like support as well.

**Comment by meegamax** [comment]
Wait nevermind im all good now. Make sure you have vault on your server. http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/

**Comment by GizaRoho** [comment]
Yeah I've got vault. The plugin was working fine it's just not working now

**Comment by Zalakoth** [comment]
It helped for me to just reinstall the newest version

**Comment by GizaRoho** [comment]
Hmm I just tried that and it didn't work.. 

This is what I'm getting if I type /quests


![2016-06-01_20 08 28](https://cloud.githubusercontent.com/assets/19664721/15722253/b4b40fb6-2834-11e6-9303-551d6aa604d5.png)

**Comment by Zalakoth** [comment]
I dunno, originally what I did when I had that issue was this:

Delete Plugin.
Run server without it one time.
Install Vault.
Install newest version of Plugin.

*BAM* It worked.

Try it out, and if it doesn't work, comment the Error logs that appear in your console.
(I'm not an Admin to this plugin or anything, but I can usually figure out the problem by reading the issue.)

**Comment by GizaRoho** [comment]
I tried that. I tried a few times. I tried going back to the previous version also. I deleted it totally, ran, reinstalled, restarted, reinstalled Vault...

The Jar seems to be only making a "Data" file. Here is the only error in the console:

[Server] ERROR Error occurred while enabling Quests v2.6.1-b100 (Is it up to date?)

I'm running the latest version of this plugin and Spigot 1.9.4

**Comment by Zalakoth** [comment]
I'm not sure, there isn't much I could do. The next best guess I would have is to try to run the server with vault on it, without the quests plugin. Stop the server, and *then* reinstall quests. There is not much I can do on this end unfortunately :/

**Comment by FlyingPikachu** [comment]
Make sure you're not running an older version of Quests (pre-Spigot) alongside the latest version.

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!

**Comment by GizaRoho** [comment]
This is still an issue.
