### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by AshourAziz** [FlyingPikachu/Quests#335]
Hello, you can drop an item out of a GUI and it'll be placed into your inventory.

**Comment by AshourAziz** [comment]
PlayerListener line 179 evt.getWhoClicked().closeInventory(); according to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html
We should not be using the entity that invoked the method, could this be the problem.

**Comment by FlyingPikachu** [comment]
Please update to the latest build, then copy and paste the error in its entirety.

**Comment by AshourAziz** [comment]
I will try this again soon, but we added a few checks to disable drops and it worked. I could make a PR but I don't think it's a 'standard' way to fix the issue, it was more of a hot fix.

I'll try the latest one shortly though.

**Comment by FlyingPikachu** [comment]
@AshourAziz I believe this could have been fixed in #343. If this is still an issue after updating to Quests 2.6.4, paste the new error in a new issue along with your quests.yml file. Thanks!
