### ISSUE TITLE
/quests list not working

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#336]
Hi.

I do use "translate subcommands" but for some reason /quests list dows not work in english. but i also doesnt work in german (quests liste) . It tells me command not found..

**Comment by ScuroK** [comment]
the german lang file must be so messed up. for example the help page (on /quests) tells me i can use /quests quit if i do so it recomends me to to / quests NULL ...

**Comment by FlyingPikachu** [comment]
Have you tried regenerating the language file?

**Comment by ScuroK** [comment]
@FlyingPikachu i just. regenerated all lang files and the problem is still there.
/quests list doesnt work and /quests liste doesnt work 

can you fix this pls?

**Comment by ScuroK** [comment]
Maybe its caused by this:
20:51:42 ERROR]: [Quests] The enchantment name 'Unbreaking' is invalid. Make sure quests.yml is UTF-8 encoded
[20:51:42 ERROR]: [Quests] The enchantment name 'DepthStrider' is invalid. Make sure quests.yml is UTF-8 encoded
[20:51:42 ERROR]: [Quests] The enchantment name 'Infinity' is invalid. Make sure quests.yml is UTF-8 encoded
[20:51:42 ERROR]: [Quests] The enchantment name 'Infinity' is invalid. Make sure quests.yml is UTF-8 encoded
[20:51:42 ERROR]: [Quests] name-TRIPWIRE_HOOK:amount-1:enchantment-Infinity 1:displayname-&9TardisKey inside items-to-deliver: inside Stage 3 of Quest Der Doktor is not formatted properly!
[20:51:42 ERROR]: [Quests] The enchantment name 'Infinity' is invalid. Make sure quests.yml is UTF-8 encoded


i will try to fix it and see if it works after

**Comment by ScuroK** [comment]
@FlyingPikachu i cant fix this error message. the file IS in UTF-8 and the enchentments seems to be ok actually. Any idea?

**Comment by ScuroK** [comment]
Weird: Now i reloaded quests and the errors about enchentments are gone.

But "/quests list" and "quests liste" still doesnt work when using the german language. so his is a bug for sure.

**Comment by FlyingPikachu** [comment]
I’m currently at work and will be able to assist you in about an hour.

**Comment by ScuroK** [comment]
thx alot ;) its just the /quests list. 
ignore the rest 

cu later

**Comment by FlyingPikachu** [comment]
What version of the plugin are you on? On 3.2.7, _/quests liste_ worked just fine for me.

**Comment by ScuroK** [comment]
3.2.7 latest snapshot. did u try with german lang file?

**Comment by FlyingPikachu** [comment]
Correct. This is the response I get:

![de](https://user-images.githubusercontent.com/2267126/37560638-af3db2e4-2a12-11e8-9a61-a375ebc1fb05.png)

**Comment by ScuroK** [comment]
what command?

**Comment by FlyingPikachu** [comment]
_/quests liste_

**Comment by ScuroK** [comment]
weird. i do the same but i get "Unbekannter befehl...." (unknown command...)
from quests

and no errors in console.

can you try with quest-titles containing ÄÖü characters?

**Comment by ScuroK** [comment]
accept-timeout: 60
allow-command-questing: true
allow-command-quests-with-npcs: false
allow-quitting: true
ask-confirmation: true
convert-data-on-startup: false
generate-files-on-join: true
ignore-locked-quests: false
kill-delay: 600
language: de-DE
max-quests: 0
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: angry_villager
show-requirements: true
show-titles: true
translate-subcommands: false
use-compass: true
quester-blacklist:
- UUID
- UUID
- UUID
debug-mode: false
show-npc-effects: true
npc-effect: note

**Comment by ScuroK** [comment]
@FlyingPikachu or do you wanna join my server so i can show u?

**Comment by ScuroK** [comment]
still there? :(

**Comment by FlyingPikachu** [comment]
I see you have `translate-subcommands` set to `false`. Doing so means we should use _/quests list_ (not _liste)_. However, testing it like that still doesn't show any issues for me.

Could you upload or Pastebin your _/lang/de-DE/strings.yml_ file?

**Comment by ScuroK** [comment]
sure just wait a moment

**Comment by ScuroK** [comment]
@FlyingPikachu 
https://pastebin.com/1gF1p8fd

**Comment by ScuroK** [comment]
@FlyingPikachu found anything?

**Comment by ScuroK** [comment]
I just found /quests quit is not working aswell :S

**Comment by FlyingPikachu** [comment]
Think I found the problem. I highly recommend backing up your quests.yml before using the following dev build. (There's a new feature in development which could break something, although unlikely.)

http://ci.ac3-servers.eu/job/Quests/285/

**Comment by FlyingPikachu** [comment]
Think I found the problem. I highly recommend backing up your quests.yml before using the following dev build. (There's a new feature in development which could break something, although unlikely.)

http://ci.ac3-servers.eu/job/Quests/286/

**Comment by ScuroK** [comment]
works! thank you so much!

**Comment by ScuroK** [comment]
@FlyingPikachu But how can i set he redo delay in this version??
