### ISSUE TITLE
accept timeout option not working

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#337]
the config option "accept timeout" does not work. whatever i set there doesnt matter. the timeout is always after arround ~30s.

could you fix this pls? its very important because i make long and nice intro texts

**Comment by FlyingPikachu** [comment]
Assuming you're now on dev version 3.2.8

What value are you trying to set the option for? As in, what number?

**Comment by ScuroK** [comment]
i tryed to put in 100
