### ISSUE TITLE
Redo delay option missing

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#339]
3.2.8 SNAPSHOT

The editor option "Redo delay" is missing in this version. Its not possible to set the redo delay.

**Comment by FlyingPikachu** [comment]
This is not a bug. Option has been moved to the WIP section for that dev build.

**Comment by ScuroK** [comment]
So the redo delay will return in a later version?

**Comment by FlyingPikachu** [comment]
It's still in-game under Planner (WIP) -> option 4, but shows up as NULL because it's a dev build. That said, all of the existing redo-delays still work and can be edited in the config under 'planner.cooldown'
