### ISSUE TITLE
GUI is not working

### ISSUE THREAD

**Issue by NathanTheDragon** [FlyingPikachu/Quests#34]
Hi there! :)

 I've attempted to make a GUI with the quests system, and it hasn't worked. So here's what I did:

○ I first CREATED my NPC and did the usual stuff to set it up.
○ I got to the ADD GUI item part, I added an item that has a colored name and lore.
○ I then added stages, rewards, ect. and reloaded the plugin after finishing the creation process.

Afterwards, when I right clicked the NPC it only showed TEXT not a GUI allowing me to click on something. I did restart the server, but to no avail there was no success. I tried to look for errors, but there weren't any.

Hope you can help me,
○ Nathan ○

**Comment by NathanTheDragon** [comment]
To add on, I do get these errors when the server is done loading:

[20:30:01] [Server thread/WARN]: [Quests] An error occurred removing old data from the snooper database!
[20:30:01] [Server thread/WARN]: [Quests] An error occurred inserting data into the snooper database!

Do they mean anything?
Thanks!

**Comment by FlyingPikachu** [comment]
Will look into this soon. Those errors are unrelated and can be removed with the latest dev build.
