### ISSUE TITLE
finish event cannot use

### ISSUE THREAD

**Issue by ChenyangLin-J** [FlyingPikachu/Quests#34]
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
2.9.0
- Description of problem & console errors
in the stage event, I set that finish event is to give some items to the player, but when the stage finish, no giving. (the start event is available)
- An example quest from quests.yml for testing, if applicable

Failure to provide the first 2 bullets may result in your issue being closed!

**Comment by FlyingPikachu** [comment]
I was able to complete the default Catch Fish quest, which uses a finish event, no problem.

Perhaps there is an issue with your event? You'll have to post your configuration to get help.

**Comment by ChenyangLin-J** [comment]
ok

**Comment by ChenyangLin-J** [comment]
events :
  新手任务送你鱼:
    items:
    - name-RAW_FISH:amount-3
quests:
     '7':
          items-to-deliver:
          - name-BOW:amount-1
          - name-ARROW:amount-4
          npc-delivery-ids:
          - 3
          - 3
          delivery-messages:
          - 成功递交
          - 成功递交
          start-event: 新手任务弓箭
          finish-event: 新手任务送你鱼
          complete-message: 啊呀呀呀呀，老夫真的是感激不尽啊，你既然帮了我的帮，我就给你下个任务上交的东西吧～快去找向导五吧。
 I set the finish event but it doesn't work

**Comment by FlyingPikachu** [comment]
Is that your events.yml? It looks more like config.yml.

Events.yml format should look like this - https://pastebin.com/XngWp6TP

If you still need help, upload the file itself rather than copy/paste.

**Comment by FlyingPikachu** [comment]
Your format looks ok. Give this build a try:
https://www.dropbox.com/s/qwwgixcj5oo9a43/Quests-2.9.1.jar?dl=0

**Comment by ChenyangLin-J** [comment]
it still cannot use

**Comment by FlyingPikachu** [comment]
Closing as dead end.
