### ISSUE TITLE
Trying Editing Requirements, broke QuestEditor

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#340]
What is your Quests version / build number (do _not_ say "latest")?
Quests-3.2.8.jar 
Build #287

Please describe the problem and how to replicate it. Any console errors?

Tried to create New Quest.
Everything in the Editor worked, till i tried to set Requirements.

Send 9 for Requirements -> Nothing happens
Tried again to send 9 -> 9 Appears in Chat. No Editor.
Quest was lost.
Opended Quest Editor again, tried 9 again -> Nothing happens, no Quest Editor anymore, any Input
goes to Chat.

**Comment by FlyingPikachu** [comment]
Thanks for bringing that to my attention! Note that the build you're using isn't particularly stable, and unless you're experimenting with recent changes, I recommend you use one of the stable SpigotMC builds for public server environments.

**Comment by FlyingPikachu** [comment]
Fixed in http://ci.ac3-servers.eu/job/Quests/288/
