### ISSUE TITLE
I have question

### ISSUE THREAD

**Issue by jomjonejame** [FlyingPikachu/Quests#341]
Can Enable / Disable per world ?

**Sample:**
//Blacklist Plugin Quests per world
Blacklist:
   - world_Nether
   - world_End

**Comment by FlyingPikachu** [comment]
Blacklist if for players only. If you which to disable features per-world, use a permissions plugin.

**Comment by jomjonejame** [comment]
For example: 
a player get quests Kill Player in world name: Survival and When player teleport to world name: minigame. and a player play the Bedwars Game. When player kill other player in Bedwars Game so Quests Kill Player still running

I must use permission ??

Sorry for My English is not good

**Comment by FlyingPikachu** [comment]
@jomjonejame Ah that makes sense. I believe revoking Quest permissions in the minigame world should fix the problem. If not, open a new Github issue with a sample quest (from the quests.yml file).
