### ISSUE TITLE
Quests Issue: /questadmin reload NPE

### ISSUE THREAD

**Issue by Rookie-G** [FlyingPikachu/Quests#345]
Hello, I am writing on behalf of the Flame Survival team.

We have been experiencing an issue on our server with one of the main admin commands from the Quests plugin. ./questadmin reload creates an NPE in console again [-.-], this time the issue has nothing to do with the Citizens plugin I believe.
We are running the latest version of Spigot and Quests for 1.9.4, but we dont understand the cause of the exception with the NPE. We have the NPE in a pastebin [here](http://pastebin.com/9dEXgXDU), if anybody *cough* @FlyingPikachu *cough*  could reply with a possible solution to our query this would be much appreciated.

Thank you for reading,
-Rookie

**Comment by SteveTheDog** [comment]
I'd like to add that we're using this version of Citizens on Spigot 1.9.4 http://ci.citizensnpcs.co/job/Citizens2/1371/

**Comment by FlyingPikachu** [comment]
Your error does not seem to be Citizens-related. Please upload your quests.yml file.

**Comment by Rookie-G** [comment]
[Quests.yml](http://www.filedropper.com/quests)

**Comment by Rookie-G** [comment]
Theres a lot of quests btw. I use the plugin for GUI shops, welcome tutorials and inventory bins.

**Comment by FlyingPikachu** [comment]
@Rookie-G The last quest in your config, "custom42", has a null rewards value. Removing that line fixed the issue in my tests, so I suggest you do the same. I will update the plugin to spit out a warning in similar situations.
