### ISSUE TITLE
Error when trying to "Save" a Quest ingame

### ISSUE THREAD

**Issue by ParadiseRealms** [FlyingPikachu/Quests#346]
Please see attached error report when trying to save a quest through the In Game Editor - 

http://pastebin.com/vG4FNuPv

If you need any more information, please let me know.

**Comment by FlyingPikachu** [comment]
@ParadiseRealms Can you please provide an example of the quest you are trying to save?

**Comment by ParadiseRealms** [comment]
Yeah! Just a simple, speak to an NPC to get the quest, catch 15 fish, deliver the 15 fish to the NPC, and get a cash/mcmmo reward.

**Comment by FlyingPikachu** [comment]
@ParadiseRealms I modified the default Catch Fish quest to work similarly and was able to complete it with no problems (except that the NPC wouldn't take pufferfish, but that's intentional) and no errors. Unless you want to upload the exact quest from your quests.yml, I don't know what else to try.

  custom2:
    name: Catch Fish
    npc-giver-id: 4
    ask-message: Â§eCatch some fish!
    finish-message: Â§eExcellent. Here is some Â§aexperienceÂ§e.
    requirements:
      money: 1
      fail-requirement-message: Â§cComplete Â§5Stone MinerÂ§c first.
    stages:
      ordered:
        '1':
          fish-to-catch: 5
          items-to-deliver:
          - name-RAW_FISH:amount-3
          npc-delivery-ids:
          - 4
          delivery-messages:
          - thx
          start-event: FishingStart
          death-event: DeathFail
          chat-events:
          - RodEvent
          chat-event-triggers:
          - rod
    rewards:
      money: 100
      exp: 250
      mcmmo-skills:
      - Herbalism
      mcmmo-levels:
      - 1

Proof of completion - http://i.imgur.com/921ac1U.png

**Comment by ParadiseRealms** [comment]
It was more letting you know than anything, I have been writing the Quests manually from the Config and loading them in :) I love the plugin, so I just wanted to let you know incase anyone else was having the problem

**Comment by FlyingPikachu** [comment]
@ParadiseRealms I wish you had mentioned that earlier. See if creating the quest through the in-game menus will resolve your issue. Thanks for your interest in Quests.
