### ISSUE TITLE
Quest objective that split

### ISSUE THREAD

**Issue by BrinDeNuage** [FlyingPikachu/Quests#346]
Build number : Quests 3.2.7

Please describe the problem and how to replicate it. Any console errors?
Some players have their objectives (most of time it is place or break blocks) which split everytime the server restart. Since it has been bugging for a while most of my players have now huge list of objectives and can't complete their quest. 

Here is some example:
https://media.discordapp.net/attachments/331054029478166538/428654169256230912/2018-03-28_22.37.04.png?width=1767&height=1006
https://cdn.discordapp.com/attachments/354625490696536064/428653921800552448/unknown.png

Can you provide an example quest from quests.yml _using Pastebin.com_?
Example of one of the bugged quest: https://pastebin.com/Ze0NGjUd

**Comment by FlyingPikachu** [comment]
Looking at your quests.yml, I notice that you’re using item IDs for block names, which is not supported. How you were able to get the plugin working at all with them is beyond me. I’m confident replacing the IDs with proper block names should resolve the issue (you may need to reset player data afterward).

**Comment by FlyingPikachu** [comment]
Nothing immediately stands out as wrong for that quest. Do you get any errors?

**Comment by BrinDeNuage** [comment]
Maybe that error: 
[13:59:45] [Server thread/ERROR]: [Quests] currentStage was null for e385f65d-0d6a-4d2a-9ee9-d7baaca415bb on command

**Comment by FlyingPikachu** [comment]
Have you tried resetting that player's data? I mentioned you may need to do that. If that doesn't help, please post the _entire_ error.

**Comment by BrinDeNuage** [comment]
Sorry I had some exams. Is there a way to reset every player's data about one quest?

**Comment by FlyingPikachu** [comment]
@BrinDeNuage Not at this time.
