### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by ElementalRealm** [FlyingPikachu/Quests#347]
Hello,
I don't know why but some quests do not give me any reward. To be more precise there are 2 NPC's that don't give me anything, they need to give a stone sword and the other needs to give 20 wood planks. What going on? What's the problem?

**Comment by AshourAziz** [comment]
I seem to be having this issue with all my quests running 2.5.5-b95 running the latest 1.8.8 snapchat, git-Spigt-e4d4710-e1ebe52


No money is being given out by the quests.


@ElementalRealm what version spigot & Quests?

**Comment by ElementalRealm** [comment]
I'm running 1.8.3 spigot

**Comment by ElementalRealm** [comment]
I believe that I'm using quests 2.6.4

**Comment by ElementalRealm** [comment]
I believe that I'm using quests 2.6.4

**Comment by FlyingPikachu** [comment]
@ElementalRealm _Make sure_ that's what version you're running so we're not going on a wild goose chase. Also, please post the data in quests.yml on the problematic quests.

**Comment by AshourAziz** [comment]
http://pastebin.com/CJqXgjhj

**Comment by AshourAziz** [comment]
Happening for all my quests though, I create my quests through the ingame commands.

**Comment by ElementalRealm** [comment]
The version of the plugin is 2.6.1. My spigot is 1.8.3. The problem is with all the quests besides "Fishing Rod" and "Bring me some Fish".
Here is my .yml file.

> quests:
  Miner:
    name: Stone Miner
    ask-message: <yellow>Could you mine <purple>10<yellow> blocks of <purple>Stone<yellow>, and deliver the <purple>10<yellow> pieces <yellow>of <purple>Cobblestone<yellow> to me?
    finish-message: <yellow>Well done. Here is your reward.
    redo-delay: 1800
    requirements:
      items:
      - name-wood_pickaxe:amount-1
      remove-items:
      - false
      fail-requirement-message: <red>You must have a <purple>Wooden Pickaxe<red> first.
    stages:
      ordered:
        '1':
          break-block-names:
          - stone
          break-block-amounts:
          - 10
    rewards:
      money: 1000
      quest-points: 1
  Hunter:
    name: Mob Hunter
    ask-message: <yellow>Kill an assortment of Mobs.
    finish-message: <yellow>Excellent. Here is a <purple>Diamond Sword<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          death-event: DeathFail
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: GoodJob
        '2':
          death-event: DeathFail
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: GoodJob
        '3':
          death-event: DeathFail
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
    rewards:
      items:
      - name-diamond_sword:amount-1
      exp: 100
      quest-points: 1
  CatchFish:
    name: Catch Fish
    ask-message: <yellow>Catch some fish!
    finish-message: <yellow>Excellent. Here is some <green>experience<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          start-event: FishingStart
          death-event: DeathFail
          chat-events:
          - RodEvent
          chat-event-triggers:
          - rod
          fish-to-catch: 5
    rewards:
      exp: 250
  custom1:
    name: Bring me some Fish
    npc-giver-id: 88
    ask-message: I am out of bait. I need 3 regular fishes! Tell to my wife Ana "Fishing" she's at home behind you.
    finish-message: Thanks for the fish. I cannot eat salmon so have those. Here you have some money. Coming home now...
    stages:
      ordered:
        '1':
          fish-to-catch: 3
    rewards:
      items:
      - name-COOKED_FISH:amount-5:data-1
      money: 100
      quest-points: 1
  custom3:
    name: Fishing Rod
    npc-giver-id: 90
    redo-delay: 1800
    ask-message: What did my husband (the Fisher) told you to tell me?
    finish-message: That man! Here is his fishing rod. Tell him to bring the fish right now!
    stages:
      ordered:
        '1':
          password-displays:
          - 'Enter here what my husband said:'
          password-phrases:
          - Fishing
    rewards:
      items:
      - name-FISHING_ROD:amount-1
  custom2:
    name: Bring me some Fish
    npc-giver-id: 91
    ask-message: 'Please get me 3 regular fishes. Tell Ana: "Fishing" she lives behind
      you and will give you a rod.'
    finish-message: Thanks very much. I cannot eat salmon so have those. Now i need to cook the dinner for Ana.
    stages:
      ordered:
        '1':
          fish-to-catch: 3
    rewards:
      items:
      - name-COOKED_FISH:amount-5:data-1
      money: 100
      quest-points: 1
  custom8:
    name: Delivery this Letter (Start)
    npc-giver-id: 64
    redo-delay: 5
    ask-message: Please delivery this letter to the guard on the other side of this mine. He's wainting for it.
    finish-message: Thanks, now go. The other guard needs this letter!
    stages:
      ordered:
        '1':
          password-displays:
          - Enter the word "Letter" on the chat to recive the letter.
          password-phrases:
          - Letter
    rewards:
      items:
      - name-PAPER:amount-1:displayname-Mine Guard's Letter
  custom4:
    name: Bring me some logs
    npc-giver-id: 66
    ask-message: I need 10 logs to finish my job for today. Cut them from the trees that have redstone arround please
    finish-message: Thanks friend! Take your reward, it's not much but it's what I have.
    stages:
      ordered:
        '1':
          break-block-names:
          - log
          break-block-amounts:
          - 10
    rewards:
      items:
      - name-WOOD:amount-20
      money: 75
      quest-points: 1

**Comment by FlyingPikachu** [comment]
@ElementalRealm First, please update to 2.6.4 and see if that resolves your issue.

Second, am I understanding you correctly that "Delivery this Letter (Start)" and "Bring me some logs" are the problematic quests? Because the other ones that aren't fish-related are default quests.

**Comment by ElementalRealm** [comment]
Yes those are the problematic ones. Okay, i'll update

**Comment by ElementalRealm** [comment]
Okay, I have already updated but when I created 2 more quests they do not give the rewards. You can complete them but they will not reward you. No items, no quest points and no money.

Here is the quests.yml

> quests:
  Miner:
    name: Stone Miner
    ask-message: <yellow>Could you mine <purple>10<yellow> blocks of <purple>Stone<yellow>, and deliver the <purple>10<yellow> pieces <yellow>of <purple>Cobblestone<yellow> to me?
    finish-message: <yellow>Well done. Here is your reward.
    redo-delay: 1800
    requirements:
      items:
      - name-wood_pickaxe:amount-1
      remove-items:
      - false
      fail-requirement-message: <red>You must have a <purple>Wooden Pickaxe<red> first.
    stages:
      ordered:
        '1':
          break-block-names:
          - stone
          break-block-amounts:
          - 10
    rewards:
      money: 1000
      quest-points: 1
  Hunter:
    name: Mob Hunter
    ask-message: <yellow>Kill an assortment of Mobs.
    finish-message: <yellow>Excellent. Here is a <purple>Diamond Sword<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          death-event: DeathFail
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: GoodJob
        '2':
          death-event: DeathFail
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: GoodJob
        '3':
          death-event: DeathFail
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
    rewards:
      items:
      - name-diamond_sword:amount-1
      exp: 100
      quest-points: 1
  CatchFish:
    name: Catch Fish
    ask-message: <yellow>Catch some fish!
    finish-message: <yellow>Excellent. Here is some <green>experience<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          start-event: FishingStart
          death-event: DeathFail
          chat-events:
          - RodEvent
          chat-event-triggers:
          - rod
          fish-to-catch: 5
    rewards:
      exp: 250
  custom1:
    name: Help us againts the Warlock!
    npc-giver-id: 130
    redo-delay: 86400
    ask-message: Thank to the gods! Some one sended help! Kill 50 zombies and 20 skeletons. Help me please!
    finish-message: Thank you for your help! Maybe now I can leave this cave without dieing. Take this reward...
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - zombie
          - skeleton
          mob-amounts:
          - 50
          - 20
    rewards:
      items:
      - name-DIAMOND_SWORD:amount-1:enchantment-Sharpness 3:enchantment-Unbreaking 3:displayname-Royal Guard's Sword
      money: 1500
      quest-points: 1
  custom2:
    name: Bring me some wood please!
    npc-giver-id: 66
    redo-delay: 1800
    ask-message: I need 10 more logs from the trees that are marked with redstone. May you bring them to me?
    finish-message: Thanks! Now I may create more axes to the Lumber Cutters. Here is your reward.
    stages:
      ordered:
        '1':
          break-block-names:
          - log
          break-block-amounts:
          - 10
    rewards:
      items:
      - name-IRON_AXE:amount-1:enchantment-Unbreaking 2:displayname-Wood Cutter's Axe
      money: 150
      quest-points: 1

**Comment by ElementalRealm** [comment]
Is that any problem with the enchantments?

**Comment by ElementalRealm** [comment]
Can you help me?

**Comment by FlyingPikachu** [comment]
@ElementalRealm I just tested your "Delivery this Letter (Start)" and "Bring me some logs" quests. Both worked fine without any issues. Here is proof of the latter quest, where I receive the wood planks.

http://i.imgur.com/c6FuzF8.png

Unless there is an error log or more information to work from, I can't fathom what the problem is. This is a public repo, so perhaps someone else can provide some ideas.

**Comment by ElementalRealm** [comment]
Hmm i doesn't aperar the reward to me.
Is there any plugin that may do that to the Quests? Like an plugin that is incompatible with yours?

**Comment by FlyingPikachu** [comment]
@ElementalRealm Not that I am aware of, but feel free to post your plugin list and maybe someone will notice something.

**Comment by ElementalRealm** [comment]
I've updated to the last version (2.6.5) i was using 2.6.4.
I really need this plugin. It works fine the only problem is just the rewards.
Here is my 38 plugins list:
PlayerHeads
WorldEdit
ChatColors
ArcaneEnchants
Essentials
ClearLag
TuxTwoLib
Buycraft
Modifyworld
Lockette
PlayerRider
Votifier
WorldGuard
RewardVoting
iConomy
PermissionEx
SimpleCommandSigns
NickOfPlayer
Lottery
Vault
PlayerParticles
LandLord
GriefLog
ChestShop
McJobs
PlotMe
AutoAnnouncer
Multiverse-Core
Citizens 2
Quests
Spawners
Multivere-SignPortals
MoneyThief
ChatEx
Multiverse-Portals
MyPet
Prison
HolographicDisplays

**Comment by ElementalRealm** [comment]
I have already deleted the folder and the .jar file and replace it but doesn't work. The most strange thing is that at first it was working just fine!

**Comment by ElementalRealm** [comment]
And I need this plugin urgently

**Comment by ElementalRealm** [comment]
And the other quests plugins don't work with citizens so well as yours.

**Comment by FlyingPikachu** [comment]
@ElementalRealm I don't personally see anything that raises an alarm. You could also try test-running your server with just Citizens and Quests.

**Comment by ElementalRealm** [comment]
Sorry but I can't do that. I can't close the server for that. Do you have a debug version or something like that?

**Comment by FlyingPikachu** [comment]
@ElementalRealm I would have to have an error message to write any debug code. My only other idea then would be to make a copy of your server and run that instead. Of course there's no guarantee it's a plugin conflict, but without more information to go on, I'm personally stuck.

**Comment by ElementalRealm** [comment]
Well, now it's working. I guess it is a problem with money rewards. Because when I removed the money rewards all the quests started to work

**Comment by FlyingPikachu** [comment]
@ElementalRealm Interesting. Glad you've got things working. If you uncover more information, feel free to let us know. Thanks!
