### ISSUE TITLE
Found a little bug when i close my game and a event is active

### ISSUE THREAD

**Issue by NevendyND** [FlyingPikachu/Quests#348]
04:14:23 [INFO] *player* lost connection: Internal Exception: java.io.IOException:

04:14:23 [ERROR] Could not pass event PlayerQuitEvent to Quests v3.2.7-b284
04:14:23 org.bukkit.event.EventException: null
04:14:23 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:405) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1102) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:319) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
04:14:23 Caused by: java.lang.NullPointerException
04:14:23 at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:695) ~[?:?]
04:14:23 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
04:14:23 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
04:14:23 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
04:14:23 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
04:14:23 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-aa25568]
04:14:23 ... 12 more

**Comment by FlyingPikachu** [comment]
What do you mean by an Event being "active"? Is this exclusive to the timer Event?

**Comment by NevendyND** [comment]
I think it was when a Events in a Quest is active and a player log out so it gives this error

**Comment by FlyingPikachu** [comment]
I'll assume you mean a timer Event is active. The dev build in my next post should resolve this issue.

**Comment by FlyingPikachu** [comment]
http://ci.ac3-servers.eu/job/Quests/302/
