### ISSUE TITLE
Mending while using the quest editor

### ISSUE THREAD

**Issue by j2ther** [FlyingPikachu/Quests#348]
Quests 2.6.4

Using the quest editor it appears I am not able to apply the Mending enchant to items (tools, armor, books) and the Mending enchant does not show up in the list of available enchants.

**Comment by FlyingPikachu** [comment]
Confirmed. Looking into it.

**Comment by FlyingPikachu** [comment]
@j2ther http://ci.ac3-servers.eu/job/Quests/104/

**Comment by j2ther** [comment]
Thanks!

**Comment by Fargus5** [comment]
dear, what about updating the saving quest editor?

you cannot save quests...
