### ISSUE TITLE
Another problem with german

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#349]
When i setup a quest where players have to shear sheeps it always resets the quest or sometimes makes it not load properly. the reason are the wool colors. both generate issues: using german color names and english ones aswell.

[17:21:11 ERROR]: [Quests] Grau inside sheep-to-shear: inside Stage 2 of Quest Schäfer is not a valid color!

and if i put in the english color name it gets set back to german everytime i edit the quest and save it..

**Comment by FlyingPikachu** [comment]
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.
