### ISSUE TITLE
Question: Commands, colors and initial events quests.

### ISSUE THREAD

**Issue by Leescar** [FlyingPikachu/Quests#35]
I hate to be a bother but I've been really digging deep into this plugin (making a personal guide as well)

I haven't been able to find a guide anywhere as far as the acceptable text colors and commands it will accept. 
       On text colors:
I checked the en.yml and saw that colors like silver and etc were used however when using them inquest text prompt "<silver>wordshere <magenta>words here"
 Some refuse to work, others do but from testing; Brown, Gray, lime, magenta, silver, orange, cyan and lightblue so far will not work.

 I've juggled between minecraft text color codes and <color>.

As well it seems text color codes absolutely do not work with objective display override. 
I am fine with it being green just unsure if text codes are supposed to work there.

  
     On commands:
 I am just completely lost on how to get command events to work.
 Are they limited to only vanilla commands? 
Some way to extend into other plugins commands?

       On initial events:
 Every time I've set up a quest and inserted an 'initial event' it somehow gets removed and I am left with attaching the event to stage 1 instead.

Thanks for the time and work.

**Comment by FlyingPikachu** [comment]
If it's text then here are the acceptable colors: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html

Perhaps you were looking at this, which is used for particles and dyes: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Color.html

As for the other questions you'll need to detail the steps you took.

**Comment by Leescar** [comment]
Ah ok so the second link is indeed what I was looking at for chat colors and thought maybe quests plugin extended acceptable chat colors. Though I know better now apologies and thank you.

The steps I use for commands on events and quests are as follows. 
/quests events
2-edit events
-eventname-
17-set commands to execute

Then during the commands prompt I've attempted using slash(/) and without slash and cannot get it to run some special commands.
.
I had wanted to possibly have quests run a ranking command to rank a player with bpermissions or similar. As well I wanted to have it possibly run the spawn command for mythic mobs. 
Another command would be when the player triggers the event it would do a server announcement via broadcast command. "player has done xxx" or another.
A command to perhaps /press button /toggle lever
Of course these would rely on quests being able to prompt into other plugins commands.

Internally allowing an event to force a player into a quest, like a event that would use questsadmin @p or <player> and force them into another quest or progress the current quests stage. 
The applications are immense if I could given the event triggers.

Those are just a few command options among others I can possible think of applying. I haven't been able to get anything like above to actually work. 


As far as the other question I follow this process to insert a simple initial event that prompts text and gives the player a boat.
/quests editor
2-edit a quest
-questname-
8-set initial event
-eventname-
13-save
1-yes
/questsadmin reload
 
At this time quests are reloaded. Upon using /quests editor and going into the quest I just saved with an initial event the initial event is now (none) despite actions formerly took registered the initial event with (eventnamehere)

Speaking of events and the way they work I might ask why on a stage is each event trigger limited to one event, it would be very interesting to affix a specific event to specific chat words instead of one event for any of the chat words. Allowing for a multitude of effects, in example a user says fuck they get slowness triggered, a user says shit they get blindness. Combine the multiple chat event triggers with commands and the outcomes get interesting and endless.

I apologize to unload such a huge wall of text.

**Comment by Leescar** [comment]
Sorry to put another small wall of text but I had forgotten to add the portion of text colors for the override objective portion. 
/quests editor
1-create new quest
-named-
11- edit stages
1-add new stage
20- custom objective ----------Here is where I've attempted to use color codes only to have it display as:
![test1](https://cloud.githubusercontent.com/assets/10955493/6460360/46110c8e-c15c-11e4-8807-479462b5965a.png)

As you can see option 22- set start text- Will display proper color codes as does 23-set finish test
I wasn't sure if custom objective display was locked at only green or if this was an issue.


However I have found an issue it is in regards to using color codes for a quests name.
 Unfortunately the quest you see above I can no longer edit!
 As after the quest is saved it applies the color codes and removes them, but they are still a part of the name.
The gui seems to think Color Code Test is an invalid name I even tried Color_Code_Test and with &4Color &3Code &2Test with no success. 
The fate is the same for & color coding and <> Color coding.
Which leaves me to forcibly go into the quests.yml to edit the quest or remove the color coding.

**Comment by FlyingPikachu** [comment]
For your first question regarding commands, I cannot duplicate that on my test server. I used "/bcast success!" as my test command. In the event editor (/quests events), I created a new eventIn the stage editor (inside /quests editor), I added a start event for my quest

**Comment by FlyingPikachu** [comment]
Sorry about the close/re-open, accident.

For your first question regarding commands, I cannot duplicate that on my test server. I used Essentials' */bcast success!* as my test command. In the event editor (*/quests events*), I created a new event and Set commands to execute as "bcast success!" without the / (using the / just runs the command). Then, in the stage editor (inside */quests editor*), I set the start event for my quest as the event I just made. Upon taking the quest, I saw "[Broadcast] success!" in-chat.

For your second question about colors, quest names are not intended to support that. This is evident in your picture by the ")---" following your quest name keeping the green color instead of staying gold. If you would like to request this feature, please open a new Issue with that information and I'll get to it once the remaining bugs have been ironed out. For now, avoid using colors in quest names.

On that note, I actually will close this as your original question has been answered. Gracias! :)
