### ISSUE TITLE
Kill angry wolf (sentinel) -quest errors

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#350]
Please see this issue linked:

https://github.com/mcmonkey4eva/Sentinel/issues/240

**Comment by ScuroK** [comment]
what i can say is that the errors start to pop up after i safed the quest.

**Comment by FlyingPikachu** [comment]
Quests does not modify the max health of wolves. Looking at the list of plugins you posted, my first suspicion would be MyPets. Good luck!

**Comment by FlyingPikachu** [comment]
Unless you have evidence that Quests is causing the issue, the matter is now closed.
