### ISSUE TITLE
How can I add a quest to a sign?

### ISSUE THREAD

**Issue by Coolkc456** [FlyingPikachu/Quests#350]
I am running a Pixelmon 3.5.1 on a 1.7.10 Cauldron server using version Quests 2.0.0 ALPHA. Citizens NPCs do not work on my server so I was wondering how can I add a quest to a sign if possible? If not, do you know a plugin that is 1.7.10 Cauldron compatible that can do this? I really want to have quests for players on my Pixelmon server.

**Comment by FlyingPikachu** [comment]
That version of Quests is not supported. Cauldron is not supported either, so if the latest version available on Spigot does not work, try an older version.

A quick Google search for "minecraft command signs" should yield helpful results.
