### ISSUE TITLE
Quests resseting on server restart

### ISSUE THREAD

**Issue by kamziksvk** [FlyingPikachu/Quests#351]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? Quests 3.2.7

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello there are no console errors, the problem is that some players who have an active quest gets bugged, during the schedulled night server restart. When they login back, the situation is that they do not have active quest, and they can not take another one, until administrator forcibly didnt finish or quit the previous quest.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

It usually happens within this quests:

custom36:
    name: Problem s vlkmi
    npc-giver-id: 14
    redo-delay: 1209600
    ask-message: Podarilo sa nam zistit, preco ma Rybar Galon pre nas nalovit dostatok
      ryb! Nedaleko pristavu sa usidlili v Dungeone vlci Calu, ktori lovia nase ryby.
      Zabi ich 50 a ziskas vzacnu odmenu! Vyhni sa ale BESNEMU Calu!
    finish-message: Vyborne! Snad aspon na chvilu bude od vlkov pokoj. Tu je tvoja
      odmena!
    gui-display: name-GOLD_SWORD:amount-1
    requirements:
      quest-points: 40
      fail-requirement-message: Musis mat alespon 40 questovych skusenosti, aby si
        mohol prijat tento quest! Nemozem ho predsa dat ziadnemu novacikovi!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 50
              data:
                Mob Level: '0'
                Objective Name: Calu
                Internal Mobnames: Calu

**Comment by FlyingPikachu** [comment]
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.

**Comment by Nericu** [comment]
I am currently getting this issue in 3.6.7 and past 3.6.6. It only seems to be none cooldown quests having this issue.

Example,
I have a quest to dig 1000 dirt and another to break 100 of each wood log and if you log out while this is being done and the server restarts the quests lose their objectives in the quests journal and /quests stats. It still shows that they have the quest just nothing to do to finish the quest.
