### ISSUE TITLE
Cannot Spawn Moore Than One Mob

### ISSUE THREAD

**Issue by xRiftx** [FlyingPikachu/Quests#353]
So, I'm trying to make a mob arena on my private server using Quests. I've created an event to spawn the first wave of mobs, which should be 30 Zombies. However, when I start the Arena Quest when the event triggers only one Zombie will spawn. I'm currently using Quests 2.6.5, and this has halted development of the Arena.

**Comment by FlyingPikachu** [comment]
Upload the related quest from quests.yml

**Comment by xRiftx** [comment]
custom1:
    name: Beginner Arena
    npc-giver-id: 132
    ask-message: So you want to do the Beginner Arena? This should be a piece of cake for a warrior like you!
    finish-message: Good job, this is only the first step in the road to becoming a legend!
    event: ArenaStart
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 20
          locations-to-kill:
          - Le_Monde 4316.0 33.0 -3478.0
          kill-location-radii:
          - 23
          kill-location-names:
          - The Arena
          start-event: BasicArenaWave1
          death-event: DeathFail
          start-message: Kill the Zombies Eon has released into the Arena!
          complete-message: Good job, get ready for the next wave!

And this is the related event that is supposed to spawn the 30 Zombies:

  BasicArenaWave1:
    mob-spawns:
      '0':
        spawn-location: Le_Monde 4315.0 34.0 -3478.0
        mob-type: ZOMBIE
        spawn-amounts: 30

**Comment by FlyingPikachu** [comment]
@xRiftx Please be aware that this fix will cease working with the next Spigot/Minecraft update. Hopefully, a more permanent solution will have been thought up by then.

**Comment by FlyingPikachu** [comment]
Permanent solution introduced in ef239ba4f541ac8335e80dfcda3bb4280a02748
