### ISSUE TITLE
How to set scoreboard + quest rotation

### ISSUE THREAD

**Issue by PikaCF** [FlyingPikachu/Quests#354]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.24-b255
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello,
It states in the features
Delicious rewards! Give items, experience, permissions, and/or perks from other plugins! **Leaderboards are available should you decide to hand out Quest Points.**
How do I set these leaderboards?

Q.2
Is it possible to create like 50 quests that rotate.
To elaborate.
Day 1: Quest no.1 only
At 12am, the quest disappears and a new one appears
Day 2: Quest no.2 only
Day 3: Quest no.3 only
Day 50: Quest no. 50 only
Day 51: Quest no 1. only
and so on.

Thank you in advance!

**Comment by FlyingPikachu** [comment]
"Leaderboards" refers to the _/quests top_ command, not the GUI scoreboards you're thinking of.

The ability to time Quests will be available in the next release (see #93).
