### ISSUE TITLE
quest timer messages wrong in german

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#357]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
pls see screenshot. i use german.

![2018-04-06_23 44 38 kopie](https://user-images.githubusercontent.com/10480144/38445683-d0ba3f0e-39f4-11e8-91f0-7697ef3c2056.png)

**Comment by Regnak85** [comment]
Ist kein Bug, liegt an veraltetem Format in dem Übersetzungsfile. Zieh dir mal nen DevBuild oder ähnliches, und sieh dir dort das Format an. 

Soweit ich weiss ist es nun so: 
timerMessage: "%green%Zeit, die Quest zu schaffen:%red% <time> Sekunden"
timerStart: "%green%Du hast noch%red% <time> Sekunden%green% um die Quest zu schaffen"

Und nicht mehr mit <green>

**Comment by FlyingPikachu** [comment]
Thanks, this will be resolved in the next release of Quests. For future translation issues, please contribute directly to Crowdin at https://crowdin.com/project/translate-quests
