### ISSUE TITLE
I made a quest, but it's not showing available

### ISSUE THREAD

**Issue by Devillion** [FlyingPikachu/Quests#358]
After creating my quest it said I need to reload the plugin for my new quest to show up. I did "/questsadmin reload" however it only shows that there's 3 quests in the file. (the default quests  that are there when you first load the plugin)

When I open the file, my quest is there that I created, however if I try to edit the quest in game it doesn't show up in the list.

When I click on the npc that I setup for the quest, it just say's no more quests available.

I'm using your latest dev build and the latest spigot that I just ran build tools on today.

Here's my quest info: http://pastebin.com/0t0BiLEe

**Comment by FlyingPikachu** [comment]
When you start the server, Quests will output some information, including how many Quests were loaded from the file. Does the info say Quests loaded 3 or 4? There may even be error messages telling you what the problem is.

**Comment by Devillion** [comment]
There were no errors, but what I figured out is it didn't like all the custom name & lore stuff. I did an item without all that and it loaded up fine.

**Comment by FlyingPikachu** [comment]
Interesting. Anyway, glad you resolved your issue.
