### ISSUE TITLE
Spam from Console

### ISSUE THREAD

**Issue by misaka9090** [FlyingPikachu/Quests#359]
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:42 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN someSuffix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN somePrefix in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN SomeGuy12345 in config.yml is not a valid UUID for quester-blacklist
21.02 19:38:40 [Server] Server thread/WARN someRegex in config.yml is not a valid UUID for quester-blacklist

Woh...

Quests Ver Quests-2.6.5.jar

**Comment by FlyingPikachu** [comment]
Regenerate your config.yml
