### ISSUE TITLE
Rewards Issue

### ISSUE THREAD

**Issue by budopey** [FlyingPikachu/Quests#36]
I cant seem to get phat-loot: and command: rewards to work properly. Can you give me an example of each that works or look at my examples that I have tried and maybe figure out what I did wrong?

command: loot give {player} Gremlins
command: loot give <player> Gremlins
command: loot give player Gremlins
phat-loot: Gremlins

**Comment by FlyingPikachu** [comment]
Are you using PhatLoots v3.8.1 or v4.0.0? And what's your Quests version?

**Comment by FlyingPikachu** [comment]
Closed due to lack of response from OP.
