### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#36]
Quests 2.8.8 test2 (keeping until updated :P and spigot 1.11.2

In the middle of a long quest questline and boom, server is restarted. I come back and still on the quests but compass leads to last bedspawn. Anyway you can fix that for the next update? Maybe implement the quests journal to link with the compass so we can click which quest to follow?

**Comment by FlyingPikachu** [comment]
This behavior is intentional, probably in-case the player loses interest in the quest after logging out - https://github.com/FlyingPikachu/Quests/blob/abd696aed665c66c29ae744c96dfbcb4d97afabd/src/main/java/me/blackvein/quests/Quester.java#L2563

Please elaborate on how the Quest Journal would allow the player to point the compass.

**Comment by QueenKisaki** [comment]
Well it's definately a problem for players who log out wanting to return to questing or that get disconnected but come back and have to find their way without the compass. I was thinking if you were able to make the journal entry for the quest clickable and the players can choose which quest they want to follow. If that is not possible, maybe have the entry show the location coordinates that was put in during the making of the quest? (Most of my quests have reach location stages to help them)

**Comment by FlyingPikachu** [comment]
Is it possible to execute code from a book link? Afaik they can only open your browser, but I'd love to be proven wrong.

Coords might not sit well with users that aren't familiar with them. And we'd have to note the world as well. Open to other suggestions

**Comment by QueenKisaki** [comment]
That's true.. hmm. I guess will have to implement the command to accept quests that way if they come back and are not on the quest then they'll have to re-accept it that way. Was worth a shot but you're right.

**Comment by FlyingPikachu** [comment]
Closing until a better solution is proposed, ideally via PR.
