### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#362]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests - 3.2.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
PlayerJoinEvent - https://pastebin.com/KX5f7uXe
NPCRightClickEvent - https://pastebin.com/MLE1685R
BlockDamageEvent and BlockBreakEvent - https://pastebin.com/aeaK70iP
InventoryClickEvent - https://pastebin.com/5rEWh6ha
PlayerMoveEvent - https://pastebin.com/vys410yh

**Comment by FlyingPikachu** [comment]
Looks like one of the enchantments in your quests.yml is invalid. Can't tell which one without looking at the file.

**Comment by AIphaDragon** [comment]
Here is our quests.yml pastebin: https://pastebin.com/teE7fEGv
config.yml: https://pastebin.com/heKnfWci

Also, we have discovered, that errors are connected with such thing, that data files for new players do not create. Now, we have 9998 data files for our players, and new players come, so they are supposed to have new data files in "data" folder, but the don't. New files for new players simply do not create

**Comment by AIphaDragon** [comment]
Sorry for problem with absence of new data files. It was from our side.
So we send you only quests.yml and config.yml pastebins

**Comment by AIphaDragon** [comment]
Thank you, we will try.

**Comment by AIphaDragon** [comment]
Errors disappeared. There are new ones, but they are rare: https://pastebin.com/KmQHiUD0.

**Comment by FlyingPikachu** [comment]
@AIphaDragon It's technically the same error, but I had changed the code to show detailed output when it happens. That said, this build should resolve the issue:

http://ci.ac3-servers.eu/job/Quests/301/
