### ISSUE TITLE
Player can pick the Gui item and when do...

### ISSUE THREAD

**Issue by DevinderFTW** [FlyingPikachu/Quests#363]
Player can pick the GUI item setted in the quest,  and when do the command /questsadmin reload more then once i get a reset in the plugin. The quest i just made get lost, it desapears.

Using the version for 1.7.10 its a cauldron server

**Comment by FlyingPikachu** [comment]
Cauldron is not supported.

**Comment by DevinderFTW** [comment]
even though is not suported your plugin isn't working well i need to be fixed by the way!
