### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by MooshroomStatus** [FlyingPikachu/Quests#364]
I was testing the new quests commands, (making sure it worked because Citizens2 is broken and I uploaded both plugins at the same time) and managed to add myself to the **blacklist**. I read through all your pages and there is **no explanation** on how to remove yourself from it, only _how to add to it_. I tried removing myself from the files and reloading which inevitably lead to my console spamming itself saying _"could not find player for blacklist ID."_ So I ask, how can I remove myself from the blacklist without having to remove the plugin and all it's files and reuploading them all?

**Comment by FlyingPikachu** [comment]
Remove your uuid from the 'quester-blacklist' list in config.yml

**Comment by MooshroomStatus** [comment]
Id appreciate you reading all of my post here. I told you what happens when i do. It spams console. And not only does it spam console when i do that, it continues to tell me im blacklisted. Removing myself does not fix the issue.

**Comment by FlyingPikachu** [comment]
@MooshroomStatus I did read that part, but the "could not find player for blacklist ID" implies that your did _not_ properly remove the id. Please post the console error in its entirety. Thanks!

**Comment by MooshroomStatus** [comment]
Im not sure how to remove the UUID then, because deleting it from the blacklist and saving the file + restarting didnt work.

"Could not find player for 'UUID' (it says the full code) please consider adding them to the blacklist."

Thats the only thing it kept saying. It spams my console with that. Not only did it continue to spam my config, I was still unable to access any commands. Perhaps you could add an admin command that removes players from the blacklist?

**Comment by FlyingPikachu** [comment]
@MooshroomStatus Again, I need the error in its entirety. What is "the full code"?

Your command suggestion is not a bad idea.

**Comment by MooshroomStatus** [comment]
This is the easiest way I can show you. I made a video demonstration.

[](https://youtu.be/6Kibm_XYLNM)

**Comment by FlyingPikachu** [comment]
Quests should not have added your UUID back to the file after reload. I will look into it.

**Comment by FlyingPikachu** [comment]
This will be fixed in the version 2.6.7 release. Thanks!
