### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by kamziksvk** [FlyingPikachu/Quests#366]
Hello, after the update of the Quests a strange bug started to appear in the console and the Player Event "/mv tp world_dungeon" is not executed. IDK because in the last version it was working despite the console error.

(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.0

(__Required__) Please describe the problem and how to replicate it. Any console errors?
https://pastebin.com/6ctW1aeH

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Example from Events.yml - https://pastebin.com/kugnaSNg

Please link to this error - https://github.com/FlyingPikachu/Quests/issues/355

**Comment by FlyingPikachu** [comment]
This dev build should resolve the issue:

http://ci.ac3-servers.eu/job/Quests/303/

**Comment by kamziksvk** [comment]
Will try on today night restart, I will let you know tomorow! Thank you in advance :)

**Comment by kamziksvk** [comment]
It is working well! thank you!
