### ISSUE TITLE
Particles Missing 2.

### ISSUE THREAD

**Issue by dadee971** [FlyingPikachu/Quests#367]
Hi,

You have closed my first topic and it wasn't an invalid Label.
I said that Particles are missing TILL 2.6.0.
I have update, that is why i said "TILL", may be "SINCE" would be better.
Sorry i'm not english.

I'm have installed each update since April and none of them have particle.
I'm actually using 2.6.7.
Version 2.6.2 was supposed to bring back particles, but it did not.

You are fast making invalid Label, before reading and trying to understand what i'm talking about.

Spigot version: CraftBukkit version git-Spigot-3996d7d-6b843d9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Was not working on 1.10 either.

**Comment by FlyingPikachu** [comment]
Referencing #366 

"Til" or "till" means "until", so you were saying particles were missing in versions before 2.6.0. Thank you for clarifying, but don't blame me for your mistake.

Particles work just fine for me. Do you have "show-npc-effects" set to "true" in config.yml? And does your Minecraft client have particles set to "All" in the settings?

**Comment by dadee971** [comment]
Sorry, my mistake.
I had disable them because they were spamming on 1.10.
Everything is working.
Thanks.
