### ISSUE TITLE
Duplicating quests on relog

### ISSUE THREAD

**Issue by Archests** [FlyingPikachu/Quests#368]
Version : 3.3.0 - b300

Problem : When you take a quest and relog it replicates the quest and it's not just visual because you have to redo the quest per each time it's there. I am using quests from NPC's. There is no console errors

quests.yml : https://pastebin.com/iXczYFK0

**Comment by FlyingPikachu** [comment]
Was able to replicate the problem with your Coal Miner I quest and my default Stone Miner quest. Duplication occurs whenever player leaves the server with an active quest (not just when the server restarts). Not sure what's causing this, but I'll continue looking.

**Comment by FlyingPikachu** [comment]
This build should resolve the error:

http://ci.ac3-servers.eu/job/Quests/303/

You may need to manually remove dupes from the player data, located in /Quests/data. For each file you would need to change anything this:

```  Coal Miner I:
    blocks-broken-names:
    - COAL_ORE
    - COAL_ORE
    - COAL_ORE
    blocks-broken-amounts:
    - 0
    - 0
    - 0
    blocks-broken-durability:
    - 0
    - 0
    - 0
```

to

```  Coal Miner I:
    blocks-broken-names:
    - COAL_ORE
    blocks-broken-amounts:
    - 0
    blocks-broken-durability:
    - 0
```

Alternatively, you could just delete the affected file(s) and start anew.
