### ISSUE TITLE
Once I edit a quest I get disconected

### ISSUE THREAD

**Issue by pumphage** [FlyingPikachu/Quests#369]
As soon as I edit a quest it would disconnect me while saving.

**Comment by pumphage** [comment]
`05.07 00:21:53 [Disconnect] User pumphage has disconnected, reason: Internal Exception: java.lang.NullPointerException
05.07 00:21:37 [Server] ERROR Make sure you are using the Quest name: value, and not the block name.
05.07 00:21:37 [Server] ERROR Stone Miner inside quests: Requirement for Quest Catch Fish is not a valid Quest name!
05.07 00:21:37 [Server] ERROR Make sure you are using the Quest name: value, and not the block name.
05.07 00:21:37 [Server] ERROR Stone Miner inside quests: Requirement for Quest Mob Hunter is not a valid Quest name!`

This is the error that it gives me

**Comment by pumphage** [comment]
This is another error I get sometimes when I try to save it, it won't disconnect me but it just won't do anything and I get this error. http://pastebin.com/vQSfgAH1

**Comment by pumphage** [comment]
This is my quest.yml haven't finished it since I can't edit the quests anymore. http://pastebin.com/mtbzDwrB

**Comment by FlyingPikachu** [comment]
The first thing that jumps out at me is many of your Quests are named '&4<-----'. Try renaming those quests in your quests.yml to something else.

**Comment by pumphage** [comment]
Originally I didn't have those but still had the same problem, I'm not using them as quests but simply place holders, to make it look better and neater.

**Comment by FlyingPikachu** [comment]
Regardless, that formatting may not be allowed by Quests (I don't have time to test that personally). Please backup your config and remove or replace the "place holders".

**Comment by pumphage** [comment]
New quest.yml http://pastebin.com/7mq7qy6k same problem same error

**Comment by FlyingPikachu** [comment]
@pumphage I was able to replicate your error and am working on a solution.

**Comment by FlyingPikachu** [comment]
Fixed in today's dev build. Once installed, you can restore your quests.yml to its original state (with your place holders).

**Comment by pumphage** [comment]
Alright thanks

**Comment by james8470** [comment]
Thank goodness, I've had this bug as well, thanks Pikachu :)
