### ISSUE TITLE
Problems with required item

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#375]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.1-b301
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello. Found a problem with the quests, where you need to bring things. Sometimes it is impossible to deliver the required item, as shown in the video: https://youtu.be/ulmjgYFmh94.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Quest: https://pastebin.com/nNCqEdPA

**Comment by FlyingPikachu** [comment]
Will have to test this myself sometime. Thanks for the report!

**Comment by AIphaDragon** [comment]
Thanks for the answer :)

**Comment by AIphaDragon** [comment]
The problem is repeated. May need to provide more information for you?

**Comment by FlyingPikachu** [comment]
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.
