### ISSUE TITLE
I dont have permissions

### ISSUE THREAD

**Issue by haruh09** [FlyingPikachu/Quests#379]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.1

I dont have permissions all commands, as Operator my users can´t use /quests with permissions

**Comment by ScuroK** [comment]
same here: after updating to 3.3.1 all users (regardless of permissions) cant use commands anymore and get a "no permission" message. even me @FlyingPikachu  can you please fix this?

**Comment by FlyingPikachu** [comment]
@haruh09 @ScuroK Believe I found the issue and should be fixed in this build:

http://ci.ac3-servers.eu/job/Quests/311/

I'd appreciate if you'd both comment back here to let me know if the issue's resolved. Thanks!

**Comment by haruh09** [comment]
is okay and works

**Comment by haruh09** [comment]
Thanks
