### ISSUE TITLE
Quest GUI cant read the text.

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#38]
Hey. 
Can you do something that i can read the quest text?
Maybe to edit the place in the GUI there the item is

http://prntscr.com/6bepka

**Comment by FlyingPikachu** [comment]
You can edit this in your quests.yml, search for "gui-display".

**Comment by SimbaZockt** [comment]
But my Gui-display looks like this...
http://prntscr.com/6bhvw9

**Comment by FlyingPikachu** [comment]
Isn't that for a different quest than the one in the image? You can edit or remove the lore.

**Comment by SimbaZockt** [comment]
Thats my Quest.yml

http://hastebin.com/osebapagef.sm

**Comment by FlyingPikachu** [comment]
So it's showing you the ask-message instead? Strange. I'll re-open this and load up your config later.

**Comment by FlyingPikachu** [comment]
Apparently this is intentional. To get around this, the next dev build will check if there's any lore on the item when a GUI is displayed. If there *is* lore, it will show that lore instead of the ask-message. Thanks!
