### ISSUE TITLE
Error on 3.3.2

### ISSUE THREAD

**Issue by PengBread** [FlyingPikachu/Quests#381]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.2
(__Required__) Please describe the problem and how to replicate it. Any console errors?
This error has been spamming in my console. I don't know what caused it.
https://pastebin.com/U1eN4hX9
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/2Z7GKXCH

**Comment by FlyingPikachu** [comment]
Need the portion of the error following the last line in your Pastebin. In other words, everything after

`27.04 05:31:19 [Server] INFO Caused by: java.lang.NullPointerException`

**Comment by mercurialmusic** [comment]
Just to confirm, I'm getting the same: [https://pastebin.com/UvGkvd9U](https://pastebin.com/UvGkvd9U)

Using Quests 3.3.2b311 on Spigot 1.12.2 (latest).

**Comment by FlyingPikachu** [comment]
@mercurialmusic Your error stops there, too? Will try to replicate this.

**Comment by PengBread** [comment]
Not fixed. Still having the same issue
https://pastebin.com/ArmAFVzz

For the last part, i can't find the 25 more messages.

**Comment by FlyingPikachu** [comment]
My mistake, I posted the wrong link. Should've been:

http://ci.ac3-servers.eu/job/Quests/312/

**Comment by mercurialmusic** [comment]
Sorry, missed the emails, but yes, my error did cut off there as well. Initial tests of that build seems like it's been solved, at least for me. Thanks!

**Comment by PengBread** [comment]
The previous error was solved.
This time a new error came to console instead.
https://pastebin.com/uaP2W3kN

**Comment by PengBread** [comment]
Even when downgraded to 3.27, it now cause the same issue. Have to temp disable quests from my server.

**Comment by FlyingPikachu** [comment]
@PengBread Original error has been solved. If you are still experiencing that second error, please make a new ticket.
