### ISSUE TITLE
Grant access to Quests#getQuester() ?

### ISSUE THREAD

**Issue by Eternirya** [FlyingPikachu/Quests#387]
What is your Quests version / build number (do _not_ say "latest")?

3.2.2

Please describe the problem and how to replicate it. Any console errors?

I need to get quester data for my plugin, the old version of plugin i can easy get with Quests#getInstance()#getQuester(player), but now i can't access Quests#getInstance() anymore.

Sorry if this issue was exist but i cant find any issues related to this.

**Comment by FlyingPikachu** [comment]
Thanks for integrating Quests! For the latest versions, use something like:
`private static Quests quests = (Quests) Bukkit.getServer().getPluginManager().getPlugin("Quests");
Quester qp = quests.getQuester(p.getUniqueId());`
