### ISSUE TITLE
Quest Plugin + Magic Plugin

### ISSUE THREAD

**Issue by McJoker123** [FlyingPikachu/Quests#388]
Hello, I need the support of Magich plugin! I download the add-on module specified by you in the links for Magick, but unfortunately it does not install on my core spigot 1.12.2! And when I hit the magic, I do not count the monsters that I kill. Is it possible to fix this? With the plug-in magic many players farm mobs with magic and not with a sword this creates some kind of convenience when complaints are received that magic does not count the quests and kill the mobs

**Comment by FlyingPikachu** [comment]
Firstly, it's not for "Magich" or "Magick", this is for NathanWolf's "Magic" plugin.

Secondly, that module is not developed by me. Seek help from NathanWolf here:
https://github.com/elBukkit/MagicPlugin/issues
