### ISSUE TITLE
Problem on 3.3.2 build 312

### ISSUE THREAD

**Issue by favorit5503** [FlyingPikachu/Quests#389]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.2 build 312
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I have this problem this error is spamming my console.
https://pastebin.com/NHX7uAeR
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/pWNawkr8

Thank you :)

**Comment by FlyingPikachu** [comment]
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.
