### ISSUE TITLE
Problem while formating an item.

### ISSUE THREAD

**Issue by MetalGearDaner** [FlyingPikachu/Quests#39]
With the new formating syntax of Quests, the parameter "name-" is used twice on a format for an object with custom name. E.g:

I want to rename a FLOWER_POT, "Taza de Café". So, on the formating, I would use name-FLOWER_POT_ITEM:amount-1:name-Taza de café:...

This makes an error because you use "name-" twice.

**Comment by FlyingPikachu** [comment]
Change the second "name-" to "displayname-".
