### ISSUE TITLE
Deliver Items can't add more than one 

### ISSUE THREAD

**Issue by Seff300** [FlyingPikachu/Quests#391]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.2
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When I'm creating the stage and I choose Deliver Items and try to add multiple items to be delivered to one NPC it says The item list and the NPC list are not equal in size! (I don't know if it is really a bug but I think that you should be able to add more than one item) No errors.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/bA8TzHJN

**Comment by FlyingPikachu** [comment]
Thanks for submitting this issue and sorry I wasn't able to get to it. Chances are the issue has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.
