### ISSUE TITLE
Error this afternoon (Could not pass event PlayerMoveEvent)

### ISSUE THREAD

**Issue by BrinDeNuage** [FlyingPikachu/Quests#392]
Build: Quests-3.3.2

Good afternoon everybody. I don't really know for the moment how the error happened but I'll tell you soon if I figure out. Here is the error: https://pastebin.com/pS6uEPHU

**Comment by FlyingPikachu** [comment]
Use this build once available - http://ci.ac3-servers.eu/job/Quests/520/
