### ISSUE TITLE
Quests and Magic Error work!

### ISSUE THREAD

**Issue by McJoker123** [FlyingPikachu/Quests#397]
Dear developer! You vkurse that your plugin does not work in conjunction with the Magic plug-in! The fact is that the magazine does not count the use of combat spells! Although in fact he thinks! Also when I put the module into compatibility with the magic plugin! Faced with the same trouble, he does not count in the magazine fighting magic such as fireball! Thus, you can give the task to use 15 magic fireball! He counts only the first blow, after that he will not display an account in the log, but if you do it all the same, you will execute it! It's very sad it needs to be corrected! It seems that the plugin does not consider the effects of the bottles or finds them very crooked! (Without a magazine it's absolutely deplorable)

**Comment by FlyingPikachu** [comment]
Your translator has failed; I do not understand.

The module for Magic is not mine. Proper place to request help is here:

https://github.com/elBukkit/MagicPlugin/issues
