### ISSUE TITLE
Problem with deleting NPC and Quests

### ISSUE THREAD

**Issue by Fargus5** [FlyingPikachu/Quests#4]
good morning,

I do not understand why no one has reported this serious problem.
All you have noticed is that after months and months of quests work, when the time comes when you need to remove an NPC (doing / npc remove), if you do not notice that a quest was tied to it, Quest then begins to bribe.

There is a fundamental rule I understood over time ... never remove the npc first and then the quest. Always delete the quest first and then remove the npc.

If you miss this, you can start saying goodbye to all the quests you create. This is because the quest related to the npc you have removed can no longer be deleted. There will always be mistakes, one after the other, until the file explodes.

Can you solve this problem?

There is no particular version ... this problem persists for a long time, years. Do not ask me for log console, I do not have it and I can not start all my quests again. Just try it on your server and you will see the problem.

**Comment by FlyingPikachu** [comment]
@Fargus5 Hello. Firstly, I do not appreciate a potential bug being described as a bribe. I believe most server administrators that spend "months and months" working on a server have the foresight to backup files in the event something goes wrong, and suggest you do the same.

Secondly, this may not be a bug. Removing one part of a quest typically does not delete the entire quest. For example, if I delete 1 stage out 3 from a quest, should the entire quest be deleted? The answer is _no_.

That said, removing an NPC from a quest does not necessarily mean that the quest should be deleted. As for the "file explod[ing]", what is stopping you from deleting the Quest? Is there an error message? Does the quest vanish? I may or may not be able to replicate your problem, so I'd appreciate you taking a moment to be more descriptive.

**Comment by FlyingPikachu** [comment]
Closing due to lack of reponse from OP.
