### ISSUE TITLE
Bunch of Errors on 3.3.4

### ISSUE THREAD

**Issue by PengBread** [FlyingPikachu/Quests#403]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
https://pastebin.com/YacQ0Ke6 > Error 1
https://pastebin.com/dFz2E8pm, https://pastebin.com/vcJkcP3a > Error 2
https://pastebin.com/qGz7nhyy > Error 3
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by PengBread** [comment]
Any ways to solve these issues?

**Comment by FlyingPikachu** [comment]
Similar to your last issue (#381) it is difficult to pinpoint the exact issue seeing as all of your errors "cut off", so to speak. Hoping to find a solution in time

**Comment by PengBread** [comment]
Does this caused by plugin conflicts or config issues? From what I think, i'll show you my config.

Quest.yml
https://pastebin.com/vuRQKeZE

**Comment by PengBread** [comment]
Still haven't found whats the issue?

**Comment by PengBread** [comment]
@FlyingPikachu is it possible that it's caused by mythicmob related quests?

**Comment by FlyingPikachu** [comment]
Frankly, there's no way for me to tell. Given the variety of errors, I would think the issue has to do with your server or another plugin, rather than Quests. That's merely speculation, though.

**Comment by FlyingPikachu** [comment]
If you find any errors that have more data after the `NullPointerException` line, please post them here.
