### ISSUE TITLE
Add a group to the player in PermissionsEx after completing the quest.

### ISSUE THREAD

**Issue by MarZonPro** [FlyingPikachu/Quests#406]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Can I give the player a certain group in PermissionsEx after completing the quest? If Yes, how to do it, if not, then advise me, please, something. This is necessary in order to prohibit most players to visit privates on the territory, provided that they have not passed the quest. For example, if a player has not reached a certain point in the story, he will not be able to approach the boss. Ie you kill a boss he will not be available.
Thanks in advance!
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
In the _/quests editor_, create or edit a quest and then chose 12 - Edit Rewards. You may either set a permission reward directly, or set a command reward for /pex
