### ISSUE TITLE
Error after creating long quest

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#41]
In your issue, please include:
I created a 4 stage quest, here: https://pastebin.com/SLZQ9FG8

and after saving I tried to reload and got this: https://pastebin.com/sYZ2aVVN

**Comment by QueenKisaki** [comment]
I removed the ore breaking stage and it works. Did I have too much for them to do?

**Comment by FlyingPikachu** [comment]
Closing due to lack of Quests/Spigot version. Please follow the issue template.
