### ISSUE TITLE
Denizen Loading Failure

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#41]
https://gist.github.com/SXRWahrheit/58fe2b0ab84d26f5e58d

Unless you're ahead of me on Denizen versions (I'm a few weeks behind), Quests needs its Denizen hook updated. This has been an issue since 1.9.

**Comment by SXRWahrheit** [comment]
Of note, this also causes /questadmin reload to fail:

https://gist.github.com/SXRWahrheit/bbf569387b98dc90a4c7

**Comment by SXRWahrheit** [comment]
Just updated Citizens, Denizen, and Spigot, am using Quests 2.2.5. Issue persists.

**Comment by FlyingPikachu** [comment]
This may be related to #40 in that the class exists but Quests cannot find it. Either Quests is loading them incorrectly or the same issue is affecting both Denizen and Heroes'. At this point the former is more likely, so I'll post back when I have more info.

**Comment by SXRWahrheit** [comment]
Let me know what I can do to help. Additionally, #denizen-dev is a great resource on EsperNet!
