### ISSUE TITLE
Take Item Event

### ISSUE THREAD

**Issue by BakProject** [FlyingPikachu/Quests#410]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4-b316

Is there an event to take items from somebody? I am trying to make a quest were a player has to catch fish and when they finish catching the amount of fish I want it to be take from their inventory without clearing the whole inventory. I would use the run commands but we have a confirmation and it will just NULL our console.

Main Question: Is there an event to take a certain 'item(s)' from a players inventory?

**Comment by FlyingPikachu** [comment]
Sorry for not being able to reply sooner.

There are quests to deliver items to NPCs, not to receive items from either NPCs or players. However, I believe there is a remove-items requirement which can clear certain items from a player's inventory. You could simply add that requirement to a second quest.
