### ISSUE TITLE
Bug that may had my server crashed 

### ISSUE THREAD

**Issue by BrinDeNuage** [FlyingPikachu/Quests#411]
Bug on Quests-3.3.4

I don't reeally know how the error happened but just four seconds later my server crashed and it is the only error that could have caused the crash. Here is the error : https://pastebin.com/bvWCjgce

**Comment by FlyingPikachu** [comment]
Likely fixed in https://github.com/FlyingPikachu/Quests/commit/87edb98c3e815a7e8b23446d217477dfff7c8c64 so try using the latest dev build. Once installed, post the new error here if it happens again. Thanks!
