### ISSUE TITLE
"NULL" when typing /quests and/or /questsadmin

### ISSUE THREAD

**Issue by meisjuan** [FlyingPikachu/Quests#413]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

I'm using Quests 3.3.4 running on a Spigot 1.12.2 server with Vault installed

i got "NULL" error when typing /quests or /questsadmin

![2018-05-31_21 56 05](https://user-images.githubusercontent.com/26559321/40789829-8f882420-651d-11e8-9de8-aef7b5886cc6.png)
![2018-05-31_21 56 11](https://user-images.githubusercontent.com/26559321/40789830-8fc9731c-651d-11e8-9e59-75df6e5bb850.png)

(__Required__) Please describe the problem and how to replicate it. Any console errors?

No Console errors..
![screenshot 27](https://user-images.githubusercontent.com/26559321/40789973-e7095f20-651d-11e8-904b-d93ca4e75a04.png)

**Comment by FlyingPikachu** [comment]
Firstly, I see you have Vault installed. Which version number?

Secondly, your plugin list has Citizens labeled in red, which means it isn't working properly. You may want to fix that before proceeding here, as it could be related to the cause of your issue.
