### ISSUE TITLE
Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#416]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.1 - b301
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello. After rebooting the server, this error will flood the logs without stopping. Thank you in advance for your help.
Error: https://pastebin.com/is3aJ86M

**Comment by Sprungente** [comment]
Are vault installed? 

try again with the newest build

**Comment by AIphaDragon** [comment]
I will try. Vault is installed.
