### ISSUE TITLE
Start Up Error 

### ISSUE THREAD

**Issue by SoraShiunin** [FlyingPikachu/Quests#418]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Start up the server. https://hastebin.com/sefabusadu.vbs
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://hastebin.com/inupapawil.sql

**Comment by FlyingPikachu** [comment]
Sorry for the wait, but your Hastebins have expired. Please use Pastebin with no expiry date next time!

**Comment by FlyingPikachu** [comment]
@SoraShiunin That error is not for this plugin. You're looking for https://github.com/fatpigsarefat/Quests
