### ISSUE TITLE
Break Blocks Stage

### ISSUE THREAD

**Issue by ElementalRealm** [FlyingPikachu/Quests#419]
Using Quests 2.7.3 b116

Hello. I'm having a problem. I'm trying to create a quest where i need to break some log blocks and qhen I type 1 (to select the "Break Block" stage) it selects the Place Block instead the Break Block.

Can you help me?

Best regards,
Epic Realms Team

**Comment by ElementalRealm** [comment]
I've updated to the 3.3.4 version and the problem presists

**Comment by ElementalRealm** [comment]
I've arranged a way to fix it. But there is no way to put the redo delay. How can i place it?

**Comment by FlyingPikachu** [comment]
Break block issue was only present with older builds such as 2.7.3.

Redo delay has been moved to 10 - Edit Planner and is now called Cooldown
