### ISSUE TITLE
After the server restarts BUG

### ISSUE THREAD

**Issue by LK520** [FlyingPikachu/Quests#42]
spigot-1.12-R0.1-SNAPSHOT-b1349
Quest2.8.7
This BUG has been around for a long time.It exists almost every version.
Players do not complete the quest after receiving the quest, and then I restart the server, the count of the quest count will be reset.
Such as digging 100 stones, I have dug 20, after the restart, it becomes 0.
The console does not have any error, it's just a BUG.

**Comment by FlyingPikachu** [comment]
This does not happen for me when tested with the default Stone Miner quest.

Given the number of stones in your example (100), this could be related to #40

**Comment by FlyingPikachu** [comment]
Closing as dead end and likely duplicate.

**Comment by LK520** [comment]
In the latest version of the current issue of such a problem, players out of the game and then add a more of the same quest goals, and when the quest is reached, the quest will not be completed.
