### ISSUE TITLE
Mob stage issue

### ISSUE THREAD

**Issue by Chikafusa** [FlyingPikachu/Quests#421]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
                              Quests-3.2.1
(__Required__) Please describe the problem and how to replicate it. Any console errors?
                              I made a quest for fighting mobs and I can start the quest. When I try defeating the mob however, it did not count the kill. The count is still 0/1

**Comment by FlyingPikachu** [comment]
Thanks for using Quests! I was unable to replicate the issue, so unless you can provide a particular quest where this is happening, there isn't much I can do. You may use a site like Pastebin to post the data from your quests.yml file.
