### ISSUE TITLE
 Unhandled exception executing command 'quests' in plugin Quests v3.3.4-b316

### ISSUE THREAD

**Issue by kamziksvk** [FlyingPikachu/Quests#425]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Version 3.3.4-b316

(__Required__) Please describe the problem and how to replicate it. Any console errors?
The problem occurs when player gets a new quest.  Error included in Pastebin.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/HaAKUJmr

**Comment by FlyingPikachu** [comment]
Sorry I never got around to closing this. This should be resolved in recent builds of Quests.
