### ISSUE TITLE
Wrong skull show

### ISSUE THREAD

**Issue by Angelty** [FlyingPikachu/Quests#426]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I am try put Wither Skeleton Skull in the Gui, but is come as regular Skeleton Skull.  i try setting with set name
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
example Quest
https://pastebin.com/TW3txLKG

![image](https://user-images.githubusercontent.com/3494357/41881066-240757fa-78a7-11e8-9da8-070f42058e9a.png)
![image](https://user-images.githubusercontent.com/3494357/41881121-7c09bfec-78a7-11e8-9658-d47bf499adfb.png)
![image](https://user-images.githubusercontent.com/3494357/41881154-999a59b8-78a7-11e8-9115-bddb477183cc.png)
![image](https://user-images.githubusercontent.com/3494357/41881205-dda36df2-78a7-11e8-913e-411e45b3130d.png)

**Comment by FlyingPikachu** [comment]
This is because the GUI doesn't consider a Wither skull any different from a normal one, because it's the same item number/id. Although you posted first, let's continue this discussion in #430
