### ISSUE TITLE
Take quest using command with internal quest names

### ISSUE THREAD

**Issue by madtomic** [FlyingPikachu/Quests#427]
Take quest using command with internal quest name and not the actual quest name.

If you use another language for quest names. It is impossible to take a quest in that language.

**Comment by madtomic** [comment]
Any news?

**Comment by FlyingPikachu** [comment]
I'm afraid I can't do this. If I named a quest like...

> Internal name: MyQuest, actual name: DerpQuest

...and then had another quest like...

> Internal name: DerpQuest, actual name: MyQuest

...which quest would get called if I issue _/quests take MyQuest_? Obviously some logic could be applied to prioritize one quest over the other, but that opens a whole new can of worms and config options. It's far simpler (and safer) to only expose a singular name per quest.

**Comment by madtomic** [comment]
I don’t think the server owner would do something like this. I am certain that I won’t do this. The request is because there is no way to take a quest written in Chinese so this method was thought of.

**Comment by FlyingPikachu** [comment]
Unfortunately, I have to consider that someone else would do that, even if you wouldn't. It would be much easier to just make quest names compatible with Chinese characters. If you would like to have that considered, please request it in a new issue.
