### ISSUE TITLE
Can force quest finish whether the player activated it or not

### ISSUE THREAD

**Issue by EscolarProgramming** [FlyingPikachu/Quests#435]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?
The command "/questadmin finish" finishes the quest whether the player has activated it or not. We have some bosses on our server which run the finish-command after dieing. The issue is that actual everybody get the rewards of the quest.
There are no console errors.

**Comment by EscolarProgramming** [comment]
Okay, I see it's not a bug, it's a feature (pull request #110).

So can you add a bool flag, that you can toggle for each quest which handels the beheaving of the finish-command?
E.g. if it's set it true the quest can only be finished if the player already has accepted the quest and if it's set to false (standard) you can finish it whether you have accepted it or not.

**Comment by FlyingPikachu** [comment]
Apologies for only getting around to this ticket now.

That command should outside of the plugin's scope. In other words, you should have a Kill Mob as the final stage in your quest, rather than ending the quest externally.
