### ISSUE TITLE
Quest fails to advance

### ISSUE THREAD

**Issue by WanderingRaven** [FlyingPikachu/Quests#439]
VERSION:
3.3.4-b316

PROBLEM:
I have a quest that provides a brief walkthru for my server.  This quest is required and is the only option to advance from the spawn point on my server.  When a new member joins, it seems like they all have the same issue with the quest - even though it starts, the first step (take this quest? yes/no) doesn't allow them to advance even if they type yes.  So then they log in and out and nothing seems to fix it except doing /questsadmin reset [playername] and then it allows them to advance.  I haven't tried any other options to reset their data and fortunately this is the first one so resetting doesn't wipe anything else.  None of the other quests seem to have this issue.

QUESTS.YML PASTEBIN:
https://pastebin.com/iu0fbM5x

**Comment by FlyingPikachu** [comment]
Sounds like you might have another plugin blocking the player's input before it can reach Quests. Many servers do not allow players to use chat until they get permission.

**Comment by WanderingRaven** [comment]
I don't believe that is it.  A new player can chat just fine.  It seems like it is one quest in particular (the most important one, the one that grants them default permissions).  By doing /questadmin reset that doesn't change/add/remove any permissions.  Could it be anything else?

**Comment by FlyingPikachu** [comment]
Apologies for only getting back to this ticket now. Please try the latest version of Quests and, if the issue is still present, post any new errors generated by that version. Thanks!
