### ISSUE TITLE
All quests commands give "Unknown Quests command. Type /questsadmin for help.

### ISSUE THREAD

**Issue by ErenBlack** [FlyingPikachu/Quests#44]
All quests commands give "Unknown Quests command. Type /questsadmin for help.

- Version: 2.8.7

- As the title says, when i try to type a command from Quests, it gives me this error.

- There are no quests, because i cannot create one.

I am attaching all my Quests files so you can sift through them just in case you need to.
[Quests Files.zip](https://github.com/FlyingPikachu/Quests/files/1146861/Quests.Files.zip)

**Comment by FlyingPikachu** [comment]
Thank you. Please try running version 2.9.0 and post your startup log

**Comment by ErenBlack** [comment]
Heres the log. Same error. Running version 2.9.0

**Comment by FlyingPikachu** [comment]
Do you have anything in the /modules folder? If so, what?

**Comment by ErenBlack** [comment]
Yes. I have "Questsmodulemythicmobs".
[Questsmodulemythicmobs.zip](https://github.com/FlyingPikachu/Quests/files/1148913/Questsmodulemythicmobs.zip)

I have attached a zip with the module inside of it.

**Comment by FlyingPikachu** [comment]
The module you're using is outdated (tested myself, same result). You will need to remove or update the module in order for things to function properly.

Since this is not an issue with Quests itself, I must close this. Thanks for using Quests!
