### ISSUE TITLE
Cannot make block break event for any kind of wood but oak.

### ISSUE THREAD

**Issue by MamaBeau** [FlyingPikachu/Quests#441]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.4-b255

(__Required__) Please describe the problem and how to replicate it. Any console errors?
No console errors, go in game, create a quest, create a block break event, enter in Log:1, 17:1 or use the block durability. Save quest, select quest to complete, see that the Item durability does not work for wood of any sort

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?  custom5:
    name: LumberJack Quest 1
    npc-giver-id: 9
    redo-delay: 604800
    ask-message: Can you chop me some wood?
    finish-message: Thank you for your time!
    stages:
      ordered:
        '1':
          break-block-names:
          - Log
          break-block-amounts:
          - 1
          break-block-durability:
          - 2

**Comment by FlyingPikachu** [comment]
Apologies for only getting around to this ticket now. Please try the latest version of Quests and, if the issue is still present, post the new error generated by that version. Thanks!

P.S. Quests does not support item IDs, so don't use "17:1"
