### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by JTGgamer** [FlyingPikachu/Quests#445]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.6
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When typing any commands such as /quests or /questsadmin it comes up with all commands being null.

![image](https://user-images.githubusercontent.com/27565081/43628047-18bc46aa-968c-11e8-9ad2-a262c2f583e7.png)

There are no errors in console concerning this issue.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
No as /quest create is null and the plugin only loaded in the data file, not the quest file.

**Comment by FlyingPikachu** [comment]
Do you have Vault installe? If so, what version?

**Comment by RetroRed** [comment]
If I was to use quests version 1.9.0, what would be the best version of vault to use?

**Comment by RetroRed** [comment]
> Do you have Vault installed? If so, what version?

If I was to use quests version 1.9.0, what would be the best version of vault to use?

**Comment by FlyingPikachu** [comment]
@FlyingPikachu Quests 1.9.0 was produced by Blackvein, so I wouldn't know. Please use a modern version of the plugin from Spigot.

Closing due to lack of response from OP.
