### ISSUE TITLE
Players can't access /quests 

### ISSUE THREAD

**Issue by Zenful1828** [FlyingPikachu/Quests#447]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 2.0.8

(__Required__) Please describe the problem and how to replicate it. Any console errors? No console errors, players can't do /quests even though i  gave permissions quests.quest, quests.quests, quests.questinfo, and others that should be default.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_? No

**Comment by Worlfy** [comment]
Are you using LuckPerms by any chance?

**Comment by Zenful1828** [comment]
I am using GroupManager

**Comment by Zenful1828** [comment]
I am using GroupManager

**Comment by FlyingPikachu** [comment]
You are using an old Bukkit version of Quests. Please download a current version off Spigot:
https://www.spigotmc.org/resources/quests.3711/
