### ISSUE TITLE
Big error with Quests

### ISSUE THREAD

**Issue by Spartan9802** [FlyingPikachu/Quests#452]
What is your Quests version ?
3.3.4-b316

Please describe the problem and how to replicate it. Any console errors?
Some players receive an interal error and can no longer do anything related to quest, it doesn't really have a pattern for the error, I have errors in the console I pass this to you

Errors:
https://pastebin.com/MaEJa2Tf
https://pastebin.com/9xanP0ed

My Quest.uml
https://pastebin.com/ZJDaVRXE

**Comment by FlyingPikachu** [comment]
Apologies for only getting around to this ticket now. Please try the latest version of Quests and, if the issue is still present, post the new error generated by that version. Thanks!
