### ISSUE TITLE
Could not pass event EntityDeathEvent to Quests v3.3.7-b482

### ISSUE THREAD

**Issue by kamziksvk** [FlyingPikachu/Quests#453]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.3.7

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Could not pass event EntityDeathEvent to Quests v3.3.7-b482
Console errors included in the pastebin log

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/U6EbVssj

**Comment by FlyingPikachu** [comment]
The following build should fix the issue once available. If not, please post back with the new error via Pastebin.

http://ci.ac3-servers.eu/job/Quests/483/
