### ISSUE TITLE
BUG VERY DANGEROUS

### ISSUE THREAD

**Issue by robimoli** [FlyingPikachu/Quests#456]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

Hi, my players are trying to deliver items to the npc, and they get this message no more quest available, and in the console i get:
Message not found: crate.cooldown

What is the error?

Other problem, when the players logout and login, they get the reward of the quest all the times...

And they hasn´t finished the quest never.

Is a loop of errors...

My version is:
version: 3.0.0-Naomi-b${env.BUILD_NUMBER}

I hope a answer and a fix, because i cant create more quests if i have this errors :(

**Comment by FlyingPikachu** [comment]
Update to the latest Spigot version; 3.0.0 is outdated.

If the error persists, upload your quests.yml file

**Comment by robimoli** [comment]
Ok, thanks i will try it.

**Comment by FlyingPikachu** [comment]
@robimoli I'm going to assume a newer version resolved the issue for you. Please consider updating your review on Spigot. Thanks!
