### ISSUE TITLE
Can not do /quests commands, even op with admin.* permission.

### ISSUE THREAD

**Issue by NerdyBirder** [FlyingPikachu/Quests#457]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
version 3.3.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?
I can not do any quests commands even though I have the quests.admin.* permission and OP. I know there has been another issue recently with a different permissions plugin that was resolved but we use BungerPermBukkit.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

I do not have any quests created because I can not access the commands to make one..

![2018-08-13_17 18 22](https://user-images.githubusercontent.com/32281657/44058694-f8199116-9f1c-11e8-9fe2-cd83d61dbf13.png)

**Comment by FlyingPikachu** [comment]
This was fixed in a recent dev build. Please try the latest build and post back if that doesn't resolve the issue.

**Comment by NerdyBirder** [comment]
Thank you. I am not the best at navigating github yet, where can i go to download the lastest build? I downloaded the newest version from spigot earlier today but that was not the right one.

**Comment by FlyingPikachu** [comment]
@NerdyBirder http://ci.ac3-servers.eu/job/Quests/
