### ISSUE TITLE
Non-opped players can not complete quests with Block-break or location tracking events

### ISSUE THREAD

**Issue by NerdyBirder** [FlyingPikachu/Quests#459]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When making quests that include "go to location" or "block break" the quest will not complete even when the player has completed the stage needs. There are no console errors with this problem or any messages in chat. The quest will complete fine for opped Admins. I have not removed any permissions from the default true list but no one can do /quests even with quests.quest and other default permissions.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/jyAqzYSS

**Comment by FlyingPikachu** [comment]
Apologies for not being able to reach this ticket until now. This sounds like a permissions issue independent from Quests. If you're still affected, try removing the permissions plugin temporarily to see if that resolves the issue. Updating to the latest version of Quests may also fix the problem. Feel free to comment if you'd like this ticker re-opened. Thanks!
