### ISSUE TITLE
Event error?

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#46]
Quests 2.9 and spigot 1.11.2

I had this issue before but it fixed itself and now its starting again: https://pastebin.com/iqtNzKn5
This is the quest with the issue: https://pastebin.com/sh753Ae6

When completing the quest, it actually completes and shows in chat the region greeting of the dungeon but I'm still standing in front of the quester. If this is not something to do with Quests would you be able to tell me how to fix it?

**Comment by FlyingPikachu** [comment]
This appears to be an issue with some sort of compatibility layer in BetonQuest, not Quests.
