### ISSUE TITLE
"hashCode not designed"

### ISSUE THREAD

**Issue by caseif** [FlyingPikachu/Quests#460]
Several classes have stub hashCode overrides. I'm not really sure why, as they're _clearly_ being used in collections elsewhere in the codebase, and it causes AssertionErrors when the VM has assertions enabled.

**Comment by FlyingPikachu** [comment]
Those overrides were in the plugin when I took it over from Blackvein. Although I remember tweaking them at some point, you're right that they don't serve any clear purpose. Feel free to submit a pull request to remove them. Otherwise, I'll get around to it eventually.

**Comment by FlyingPikachu** [comment]
Decided to remove the hashCode from Event.java and then investigate with the FindBugs plugin, which reported the following:

> Bug: me.blackvein.quests.Event defines equals and uses Object.hashCode()

> This class overrides equals(Object), but does not override hashCode(), and inherits the implementation of hashCode() from java.lang.Object (which returns the identity hash code, an arbitrary value assigned to the object by the VM).  Therefore, the class is very likely to violate the invariant that equal objects must have equal hashcodes.

> If you don't think instances of this class will ever be inserted into a HashMap/HashTable, the recommended hashCode implementation to use is:
public int hashCode() {
  assert false : "hashCode not designed";
  return 42; // any arbitrary constant will do
 }

Correct me if I'm wrong, but I can't find anywhere that Quests checks equals() on any of the affected classes (Quest.java, Stage.java, QuestMob.java or Event.java). Although I could maybe see deep comparison of inventory items being useful in QuestMob, I doubt this will see any real usage externally from other plugins. Use of Object.equals() should be sufficient, so I'll clean this up shortly.
