### ISSUE TITLE
Help: NULL

### ISSUE THREAD

**Issue by NotSoSe** [FlyingPikachu/Quests#461]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 2.0.0 ALPHA
(__Required__) Please describe the problem and how to replicate it. Any console errors?
If I write /quests it will appear a list of NULL
![null](https://user-images.githubusercontent.com/42919000/44961302-8e34df00-af0f-11e8-9ede-6e74609c45a6.PNG)
And the plugins have no problems.
![pl](https://user-images.githubusercontent.com/42919000/44961303-90973900-af0f-11e8-9741-afddc4eb81ca.PNG)

And I have the latest version both of Vault and Citizens

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by Sprungente** [comment]
really? You use Alpha 2.0? Thats years ago dude xD

The good old time 
Use the newest version from https://www.spigotmc.org/resources/quests.3711/
or 
http://ci.ac3-servers.eu/job/Quests/483/

**Comment by FlyingPikachu** [comment]
As @Sprungente stated, use one of the new Spigot builds. Thanks!
