### ISSUE TITLE
reward in hand -> spawn_egg

### ISSUE THREAD

**Issue by Ju27930** [FlyingPikachu/Quests#462]
What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.4-b316

Please describe the problem and how to replicate it. Any console errors?
I would like to give a "chicken_spawn_egg" as a reward but the player receives a "pig_spawn_egg"
I create the reward with the egg on my hand
but in the quests.yml file, i have an other name

Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/iwbXnDYm

Thanks ! :)

**Comment by FlyingPikachu** [comment]
Related to #107 

Should now be possible with this dev build - http://ci.ac3-servers.eu/job/Quests/484/
