### ISSUE TITLE
line break and other questions

### ISSUE THREAD

**Issue by BobbyMere** [FlyingPikachu/Quests#467]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?

I placed the custom reward module from your download in the 'module folder' and it says it's not loaded when I try to do a custom reward. Am I missing something?

Also, custom named and lore items don't save through a server restart or /questadmin reload.
It also seems to not support color codes at all using the in-game editor, even when using the auto item loader, on items or messages. &c ,§c, <red> doesn't work.  What does it support?

Is there a way to have the display name on the npc and the display name in the gui differently?
My npc in game name is 'bob' but I want the gui display name to be the quest name

Is there a way to force a new line in text? Or display the reward separately from the asking message? /n ; | don't work

Is there a discord?

**Comment by FlyingPikachu** [comment]
The API jars are not modules, they are used to _create_ modules such as https://www.spigotmc.org/resources/mythicmobs-%E2%9A%94-quests-add-on-%E2%9A%94.7261/

Please create a new issue about the reload thing if that's still a problem in recent builds.

As for a new line in text, I assume you mean in the lore section. There is no way to do that at this time.

Link to Discord is available on the main Spigot page.
