### ISSUE TITLE
Bug with vault update

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#468]
Hello, and thank you for keeping this great plugin updated :)

I have Quests version 3.3.4 and Vault 1.7.1.

Since vault has been updated my bug mining quest (before the update worked without problems), and the console error is as follows:
https://pastebin.com/8m32d1Sp

And here is the quest in question:
https://pastebin.com/bCszzJZ5

**Comment by DrOreo002** [comment]
Seems like this is a problem with the build, try to build this plugin by ur own

**Comment by aglarcz** [comment]
Tried to build on my own, still bugged.

**Comment by aglarcz** [comment]
Answer from vault dev https://github.com/MilkBowl/Vault/issues/742

**Comment by FlyingPikachu** [comment]
http://ci.ac3-servers.eu/job/Quests/489/

If desired, one can enable the item/mob/enchant translation by adding translate-items: true to one's config.yml. Note the language is determined by the client. Please report bugs in new tickets.
