### ISSUE TITLE
Blocks and extensions

### ISSUE THREAD

**Issue by Fractvival** [FlyingPikachu/Quests#47]
Hi!
Please, will add extend for block ids ?

example:
Block STONE, now is only STONE (diorite,granite,andesite...)
I would like to only broken DIORITE
ids-1:3

we sometimes add extensions for these particular blocks?
Thanks and sorry for my bad english

**Comment by FlyingPikachu** [comment]
Sorry, this is no longer supported as Minecraft (and thus, Spigot) will cease using block ids in the near future.

http://www.reddit.com/r/Minecraft/comments/1yt5wi/numerical_block_ids_will_be_removed_completely/?utm_source=Reddit&utm_medium=twitter

**Comment by Fractvival** [comment]
Hmm, thanks, good.
Quests for Spigot 1.8 not for Spigot 1.8, because can not categorize STONE to stone, andesit or diorite.
Goog Job. Bay

**Comment by FlyingPikachu** [comment]
I'm sorry to hear about your passive aggressive attitude, hope it's treatable.

If you'd bother to have read the documentation, there is a 'data' field for that:
http://dev.bukkit.org/bukkit-plugins/quests/pages/main/item-formatting/
