### ISSUE TITLE
Wheat doesnt count.

### ISSUE THREAD

**Issue by lizzardboy912** [FlyingPikachu/Quests#471]
(3.3.7-b483) What is your Quests version / build number (do _not_ say "latest")?

(No console errors.) Please describe the problem and how to replicate it. Any console errors?

(https://pastebin.com/zxiWShdz) Can you provide an example quest from quests.yml _using Pastebin.com_?

I'm trying to create a farming quest and whenever I break the wheat it doesn't add to the counter.

![javaw 2018-09-16 16-44-19-99](https://user-images.githubusercontent.com/41771054/45600756-ed92f480-b9cf-11e8-90a2-a3678d5ac6d3.jpg)
![javaw 2018-09-16 16-44-28-09](https://user-images.githubusercontent.com/41771054/45600757-ee2b8b00-b9cf-11e8-9e9a-d38cf8cc82b1.jpg)

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP
