### ISSUE TITLE
Issues when using /quest

### ISSUE THREAD

**Issue by beavurus** [FlyingPikachu/Quests#473]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Whenever I join a quest, it does give me info about what I should do, and when I do /quest it says "An internal error..."
I also get some console errors that won't stop spamming: 
[console error.pdf](https://github.com/FlyingPikachu/Quests/files/2389602/console.error.pdf)

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/AVjP6sKD

**Comment by FlyingPikachu** [comment]
Please submit your console error in a basic text filetype (not PDF), or use Pastebin.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
