### ISSUE TITLE
GC mem over limit, due to Quest mem leaks.

### ISSUE THREAD

**Issue by Kainzo** [FlyingPikachu/Quests#474]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4-b316
(__Required__) Please describe the problem and how to replicate it. Any console errors?
https://paste2.org/44Adzawk
https://paste2.org/5kF6Wyc6

**Comment by FlyingPikachu** [comment]
Commit should fix the first error, however the second paste appears to be caused by your server failing to provide Quests with various player-related events. Possibly fault of ViaBackwards?
