### ISSUE TITLE
NULL problem

### ISSUE THREAD

**Issue by RetroRed** [FlyingPikachu/Quests#479]
Version 1.9.0

Every command just gives the result Null, I have seen a few people with this problem so I wondered if I am using quests version 1.9.0, what version of vault should I use

![image](https://user-images.githubusercontent.com/28838354/45929168-c6937000-bf45-11e8-98de-ba51ffd23560.png)

**Comment by FlyingPikachu** [comment]
That is an old version of Quests is from Bukkit, which is not supported. Please use a current build from Spigotmc.org
