### ISSUE TITLE
Quest requirement items not taken when you have more than 1.

### ISSUE THREAD

**Issue by jk526** [FlyingPikachu/Quests#48]
Spigot 1.12
Quests 2.9.0 (And has been the same for previous versions)

Hey! I absolutely love this plugin. One thing that is irking me somewhat is when there's a requirement for an item to start a quest, I use quest tokens. Like, you need 1 quest token to take a quest, and when you take it the token is taken off you. If you have 1 token it is taken fine. But if you have 2 or more, it doesn't take the token and you get the quest anyway. Have tried on a couple of my servers with the simplist quests etc and it always happens...

No errors showing in Console

- An example quest from quests.yml for testing, if applicable

name: The Daily News
    npc-giver-id: 3
    redo-delay: 86400
    ask-message: Greetings Traveller. Please go around all the Major towns and Gather information for my Newsletter. Thankyou.
    finish-message: Great. This issue will be a real humdinger.
    gui-display: name-BOOK_AND_QUILL:amount-1
    requirements:
      items:
      - name-IRON_NUGGET:amount-1:displayname-Quest Token:lore-Can be used to accept Daily Quests
      remove-items:
      - true
      fail-requirement-message: In order to accept this quest you need a Quest Token. Go to /warp Quests to get your daily allowance.
    stages:
      ordered:
        '1':
          locations-to-reach:
          - survival2 -1105.0 90.0 675.0
          reach-location-radii:
          - 10
          reach-location-names:
          - Spawn by typing ./spawn
        '2':
          npc-ids-to-talk-to:
          - 13
          complete-message: Super Secret Mage's guild news is Super Secret. Read my Blog for more.
        '3':
          locations-to-reach:
          - survival2 -17785.0 69.0 -4018.0
          reach-location-radii:
          - 10
          reach-location-names:
          - Inishmore through the Portal on ./warp ship
        '4':
          npc-ids-to-talk-to:
          - 23
          complete-message: The Grass is Green, the Birds are Chirping and all is well on our wonderful island thankyou.
        '5':
          locations-to-reach:
          - survival2 1252.0 64.0 16015.0
          reach-location-radii:
          - 10
          reach-location-names:
          - Roanoke through the portal on ./warp ship
        '6':
          npc-ids-to-talk-to:
          - 98
          complete-message: The Creaking of the trees is keeping us all awake at night and vicious monsters prowl the boundaries of our town. Apart from that, all is well.
        '7':
          locations-to-reach:
          - survival2 17077.0 63.0 -6600.0
          reach-location-radii:
          - 10
          reach-location-names:
          - The Keep through the portal on ./warp ship
        '8':
          npc-ids-to-talk-to:
          - 91
          complete-message: The Mead flows free and our Training Continues. We will be ready should a worthy adversary show up.
        '9':
          locations-to-reach:
          - survival2 16573.0 72.0 1390.0
          reach-location-radii:
          - 10
          reach-location-names:
          - Droughtstone through the portal on ./warp ship
        '10':
          npc-ids-to-talk-to:
          - 129
          complete-message: I am the only person to remain in this deserted settlement. We have the odd passerthrough, but I am lonely. Hold me?
        '11':
          locations-to-reach:
          - survival2 -13496.0 228.0 11044.0
          reach-location-radii:
          - 20
          reach-location-names:
          - Highwater through the Portal on ./warp ship
        '12':
          npc-ids-to-talk-to:
          - 122
          complete-message: Well, since our town uprooted and floated up to the sky our engineering has improved greatly. As has our quality of life. Now the Sky is the Limit.
        '13':
          npc-ids-to-talk-to:
          - 3
          complete-message: Well, It seems like everything is going smoothly, apart from Roanoke, That doesn't sound good.
    rewards:
      items:
      - name-TRIPWIRE_HOOK:amount-1:enchantment-Knockback 1:displayname-§aBasic Key:lore-§cOpen the Basic Crate!
      - name-GOLD_NUGGET:amount-2:displayname-Questicle:lore-Use this to trade for Loot
      money: 250
      mcmmo-skills:
      - Woodcutting
      mcmmo-levels:
      - 5

**Comment by FlyingPikachu** [comment]
Afaik this is intentional and losing the 1 token is likely a bug. Think of tokens functioning more like levels in an RPG - they only go up in order to indicate your experience and are not taken away. That is my recollection and I will leave this issue open pending investigation.

You are the second person to want the plugin to charge for taking quests as of late (see #47). Although custom requirements is currently your only option, if this trend continues I'll consider it as a built-in feature for future versions.

**Comment by jk526** [comment]
Oh, no I don't think so. There's an option when you make the quest of whether to allow the player to keep the required item or to take it away. I have to take it away selected. 😊 the remove items- true above is that part.

**Comment by jk526** [comment]
The tokens are a custom item I made. I just give players 10 a day so they can only do 10 of my daily quests each day. But I can fix this by making it a "deliver 1 quest token" sort of objective in the quest. Just thought it might not be too hard a fix to have it recognise stacks and multiples of the item. 😊

**Comment by FlyingPikachu** [comment]
Forgive me, I was thinking of Quest points; not tokens. I do see the `remove-items` option. Hoping to look into it shortly.

**Comment by jk526** [comment]
Ha no worries, I thought you might have been. Love the plugins. It's my favourite. Do have another occasional error when players become corrupted, but can't for the life of me find the error or duplicate it. I'll keep a look out for it.

**Comment by FlyingPikachu** [comment]
@jk526 Will be fixed in this dev buld once available:

http://ci.ac3-servers.eu/job/Quests/144/

Thanks!
