### ISSUE TITLE
Redo Delay

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#48]
When the redo delay to a quest is completed, the "(Completed)" after the name of the quest is not removed and the show-npc-effects does not wake up.

![2015-03-10_07 12](https://cloud.githubusercontent.com/assets/10450256/6570152/ddf44a9a-c6f5-11e4-91e1-0ba63105b996.jpg)

**Comment by FlyingPikachu** [comment]
I think this is intentional as it is to indicate that the quest has been completed at least once. I'll look into making the effect come back, though.

**Comment by FlyingPikachu** [comment]
After some experimenting, it looks as though having the effect come back after a quest is completed is not feasible due to how Quests handles the redo-delay.
