### ISSUE TITLE
Forced Timeout

### ISSUE THREAD

**Issue by Natalbee** [FlyingPikachu/Quests#480]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.3.7

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Starting the server produces a console error. You can accept quests, and you get the title message saying that you have, but the timeout function abandons the quest 20s later even if it's in progress (w/ console error). You can't choose it again because it still thinks you're in the quest, but it's already made you quit. This is with the default Stone Miner quest.

Console Log:
[latest (for Quests).log](https://github.com/FlyingPikachu/Quests/files/2408900/latest.for.Quests.log)

Log covers the server startup, player login, quest accept, involuntary quest abandonment, quest requirement completion (with no result), then player leave.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
It's the default Stone Miner quest automatically generated by the plugin.

**Comment by FlyingPikachu** [comment]
Closing as recent builds of Quests should not be affected by this issue.
