### ISSUE TITLE
"Tame Mobs" Stage Bug

### ISSUE THREAD

**Issue by MooshroomStatus** [FlyingPikachu/Quests#482]
Quests V:3.3.4

Whenever you add a "Tame Mobs" stage to a quest, upon doing /questadmin reload, any quest with this stage automatically gets deleted. I created a new quest and set up all the required stuff for a quest. I set the first stage to Tame Mobs (14) and set it to tame cows x2, and pigs x2. Upon saving and reloading, the quest was deleted. I decided to try and edit a pre-existing quest to add this stage. Same steps, tame mobs, cow x2/pig x2, save, /questadmin reload. This caused the other quest to get deleted as well. There are no console errors that I have found so far.

Found the issue. Any sort of normal mobs are not listed as tamable mobs.
![screenshot 29](https://user-images.githubusercontent.com/20261414/46202143-a19f5400-c2db-11e8-95cc-3706d6aac1d1.png)

These are the only mobs that work:
![2018-09-28_04 20 04](https://user-images.githubusercontent.com/20261414/46202193-c72c5d80-c2db-11e8-8d67-dcea893488b9.png)

**Comment by FlyingPikachu** [comment]
That's because cows and pigs are not tamable mobs. How were you able to add them? Did the in-game menu accept "Pig" even though it's not in the list, or did you edit the config?

**Comment by MooshroomStatus** [comment]
I guess I confused tamable with breedable, but to answer your question, it did allow me to input cow in the in-game editor. If I had an animal already set, then switched it to cow, it would automatically switch back, but if I added the stage for the first time and picked cow, it would accept the input then automatically delete the quest upon saving.
