### ISSUE TITLE
Alternate Blocks Unrecognized

### ISSUE THREAD

**Issue by MooshroomStatus** [FlyingPikachu/Quests#483]
Quests V:3.3.4

I'm trying to make a quest to place down every flower. The only working flowers are roses and dandelions. All other flowers, either by ID or enum name are not valid names. Had the same issue with blocks like wood. Quests only allows for oak logs or planks to be placed/broken. All other types are "Not a valid material name."

I'd HIGHLY recommend support for specific block ID's, i.e. 38:1 38:2 38:3.
Recreated by attempting to add this stage to a quest.

![2018-09-28_04 53 36](https://user-images.githubusercontent.com/20261414/46201856-d363eb00-c2da-11e8-9d51-ae0b84ff998f.png)

**Comment by FlyingPikachu** [comment]
Is this still an issue with Quests 3.4.3?

**Comment by FlyingPikachu** [comment]
Closing as this should no longer be an issue. Feel free to request re-open with proof to the contrary.

**Comment by Klawdek** [comment]
This is still an issue with 3.6.1

**Comment by FlyingPikachu** [comment]
@Klawdek Thanks for pointing that out. However, the offer to re-open _with proof_ was directed at the original poster. Feel free to open a new ticket for your situation.
