### ISSUE TITLE
Spigot 1.13.1 + particles.

### ISSUE THREAD

**Issue by dadee971** [FlyingPikachu/Quests#484]
Hi.

**Spigot**: version git-Spigot-f6a273b-1cf8b5d (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
**Quests**: version Quests v3.3.7-b483

My console is spamming each second (it is about particules may be the note above npc head):
[https://pastebin.com/xWVqd0fT](url)
When i disable npc-effect, there are no messages at all in console .

`npc-effects:
  enabled: false
  new-quest: note
  redo-quest: angry_villager`

Bests regards

**Comment by FlyingPikachu** [comment]
Try http://ci.ac3-servers.eu/job/Quests/489/
