### ISSUE TITLE
Quests editor freezing up during attempted delivery quest.

### ISSUE THREAD

**Issue by Archaie** [FlyingPikachu/Quests#485]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4-b316
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When attempting to make a delivery quest using a Citizens 2 NPC, after defining the item and amount of it to deliver and selecting 8. done, the quests CUI freezes up, and stops responding. The only way out is to Re-Log.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
No, because the problem prevents the quests from being created.

**Comment by neox91120** [comment]
Got the same issue please help :/

**Comment by FlyingPikachu** [comment]
@Archaie What version of Spigot are you on?

**Comment by neox91120** [comment]
1.12.2
but i fixed it its ok
just vault outdated version i had
