### ISSUE TITLE
Setting coords for reach location error

### ISSUE THREAD

**Issue by pentlock1** [FlyingPikachu/Quests#486]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.7 B483
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When setting a block for reach location it does not show the block coords in chat but gives this error in console https://pastebin.com/vgDJYLFY Still able to type add and it adds the location though.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/gHNNmjGt

**Comment by FlyingPikachu** [comment]
Closing as recent builds of Quests should not be affected by this issue.
