### ISSUE TITLE
Issue with GUI item selection

### ISSUE THREAD

**Issue by pentlock1** [FlyingPikachu/Quests#487]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.7 B483
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Enter the GUI item selection menu. select 0 to load item in hand. editor freezes and starts sending following error in console repeatedly until I log out. https://pastebin.com/MxpxXEA1
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
due to the nature of the bug I am unable to save the quest to generate it in the quests.yml

**Comment by pentlock1** [comment]
Update: every time I log in the error begins running in console again, every second.

**Comment by arenmarsden** [comment]
You can't use the latest version of Vault due to the fact Quests uses the 1.6 version of which had an ItemAPI, which is now removed because it was unnecessary.

@FlyingPikachu - Should probably look into this.

**Comment by FlyingPikachu** [comment]
Closing as recent builds of Quests should not be affected by this issue.
