### ISSUE TITLE
Cant tame horses for a quest. 

### ISSUE THREAD

**Issue by Snoogles** [FlyingPikachu/Quests#49]
When creating a quest in 2.2.2 using tame mob you get the following error. 

[22:47:36] [Server thread/ERROR]: [Quests] Horse inside mobs-to-tame: inside Stage 1 of Quest New Horses is not a valid tameable mob!

**Comment by FlyingPikachu** [comment]
First, try using the latest version of Quests (2.3.0).

**Comment by Snoogles** [comment]
This continues to be a problem in 2.3.0. No errors in console of any kind until /questsadmin relog and the same error. 

Here is the quest from quests.yml for your reference:

  custom1:
    name: New Horses
    npc-giver-id: 34
    redo-delay: 604800000
    ask-message: I always need horses for my stable. Can you tame me 5?
    finish-message: Thank you. Come back next week. Here are some apples, hay and 250 ozonebucks.
    stages:
      ordered:
        '1':
          mobs-to-tame:
          - Horse
          mob-tame-amounts:
          - 5
    rewards:
      items:
      - name-GOLDEN_APPLE:amount-2:data-1
      - name-HAY_BLOCK:amount-3
      money: 250
      quest-points: 1
