### ISSUE TITLE
how to use wither skeleton skull after 1.13

### ISSUE THREAD

**Issue by PhantomXN** [FlyingPikachu/Quests#494]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
after 1.13, there are no durabillty for skulls, wools, potions, etc... they are seperated as a single item. how can i use them as quest requirement?
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
example: SKULL_ITEM:1 doesn't means wither skeleton skull. It means skeleton skull at always

**Comment by FlyingPikachu** [comment]
Resolved in Quests 3.4.0
