### ISSUE TITLE
Quest-Reward: Set item name doesnt work [2.1.5]

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#5]
Set name dont work.

Error: http://pastebin.com/zepUXLdM

**Comment by FlyingPikachu** [comment]
Try dev build #18 and let me know if that resolves the issue (no guarantee).

http://ci.ac3-servers.eu/job/Quests/

**Comment by SimbaZockt** [comment]
Still error cant change the name from items

**Comment by FlyingPikachu** [comment]
Fixed in Quests 2.1.6. Thanks!
