### ISSUE TITLE
permission and command reward problem.

### ISSUE THREAD

**Issue by neemyo** [FlyingPikachu/Quests#50]
Hi there,

When I try to give a permission it doesn't do anthing. I'm trying to give a bending plugin permission which is:
bending.player

I put that into the permission reward section, save, and reload. The person completes the quest but it doesnt come up as a reward and when they try to use commands related to the permission, it doesnt work. I've also tried giving "/bending choose water" as a command [as thats what bending.player gives them] and that also doesnt come up as a reward or work.

**Comment by FlyingPikachu** [comment]
Closing due to lack of adherence to issue guidelines (no Spigot/Quest version). Given the nature of the problem, please provide the appropriate data from quests.yml if you choose to make a new issue. Thanks!
