### ISSUE TITLE
not giving rewards

### ISSUE THREAD

**Issue by Castiella** [FlyingPikachu/Quests#501]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3,3.8

(__Required__) Please describe the problem and how to replicate it. Any console errors?

28.10 11:27:40 [Server] ERROR [Quests] currentStage was null for 63fff657-115c-41b7-b53b-ec513ef1a297 on command
28.10 11:27:42 [Server] INFO Deth_Glitch issued server command: /bal
28.10 11:27:42 [Server] ERROR [Quests] currentStage was null for 63fff657-115c-41b7-b53b-ec513ef1a297 on command

When we run a quest with a password it wont give the command reward set. Instead, we get this console error.

**Comment by FlyingPikachu** [comment]
Thanks for the report and sorry for not being able to get to it until now. Without the quests file, or the player file for that UUID, that was in use at the time the bug occurred, there's no way to diagnose this. Feel free to open a new issue if the problem happens again.
