### ISSUE TITLE
Can't deliver items if not crafted in same world

### ISSUE THREAD

**Issue by neox91120** [FlyingPikachu/Quests#502]
It's all in the title

Basically, a player cannot give (for example) a full iron armor if it isnt crafted in the same world as the npc.
If he crafts the iron armor in world spawn (and npc is in world spawn) then it works. But if he is in nether or other mv world then it says that he can't deliver that item.
thx in advance

**Comment by FlyingPikachu** [comment]
Are you sure the player has permission in that world?

https://github.com/FlyingPikachu/Quests/wiki/Commands-&-Permissions

**Comment by neox91120** [comment]
Yes thay do, because they can do /quest  and /quests in worlds on my server

**Comment by FlyingPikachu** [comment]
https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/NpcListener.java#L59

@neox91120 Looking at that code, which runs when a player right-clicks an NPC, there are no checks for which world the player or NPC is in. What is the specific error message you get, word for word?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
