### ISSUE TITLE
BUG: Event dissapears when it gives an enchanted item.

### ISSUE THREAD

**Issue by SirMario11** [FlyingPikachu/Quests#512]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.4.0; minecraft 1.8.8
(__Required__) Please describe the problem and how to replicate it. Any console errors?

When you make a event that gives the player an enchanted item, the event will dissapear in the /quests events. You also can't use the event anymore. 

It does show up in the events.yml file tho. I have found a workaround by making the event execute a command that gives the player the enchanted sword instead.

I hope you can fix this, because making the commands do the trick isn't that nice to work with.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
 events.yml:
EnchantmentBUGevent:
    items:
    - name-DIAMOND_SWORD:amount-1:enchantment-Sharpness 2:meta-type-UNSPECIFIC:enchants-{DAMAGE_ALL=2}

**Comment by SXRWahrheit** [comment]
Please follow the issue template by posting the file to Pastebin and providing the link.

**Comment by FlyingPikachu** [comment]
Unable to replicate in recent dev builds, so it's possibly been fixed. Feel free to request re-open with evidence to the contrary.
