### ISSUE TITLE
Task #38 for Quests v3.3.7-b483 generated an exception

### ISSUE THREAD

**Issue by iToxic9** [FlyingPikachu/Quests#515]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests v3.3.7-b483

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Every second this error pops up in the menu:
[Sun, 11. Nov 2018 17:44:11 EST WARN] [Quests] Task #38 for Quests v3.3.7-b483 generated an exception

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
That is not the full error and is insufficient to diagnose the error. Please post the entire error to reopen this issue.

You may also wish to update to the latest version of Quests, 3.4.0
