### ISSUE TITLE
Note Block Things aren't popping up after making a quest in 1.12.2

### ISSUE THREAD

**Issue by Kane16x** [FlyingPikachu/Quests#516]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.4.0.jar
(__Required__) Please describe the problem and how to replicate it. Any console errors?
No issues in the console, but here's the startup log:
https://pastebin.com/uERzcJDd
Config showing npc note is true:
https://gyazo.com/405585bca75991b9135ea7a37e6221d6
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/9XVqyDQR
^ Thats one of the quests i setup

**Comment by Kane16x** [comment]
The Note or angry_villager things aren't popping up, Are the different in 1.12.2? I've looked but I think they're the same.

**Comment by Kane16x** [comment]
it was working on previous versions but the only version that works now its the Quests3.4.0.jar one.

**Comment by FlyingPikachu** [comment]
Use this dev build once available - http://ci.ac3-servers.eu/job/Quests/496/

**Comment by Kane16x** [comment]
I have, but there still is no note block particles? Help?

**Comment by FlyingPikachu** [comment]
@Kane16x Your configuration looks fine. Any console errors?

**Comment by Kane16x** [comment]
Yea
https://gyazo.com/06e998c5dbcdecfdce1db0acca51c916
these errors just popped up after using quests 3.4.1 and 3.4.2

**Comment by Kane16x** [comment]
Im still not sure what to do.

**Comment by FlyingPikachu** [comment]
Are you using PaperSpigot?

**Comment by Kane16x** [comment]
No, just normal spigot 1.12.2

**Comment by Kane16x** [comment]
hello?

**Comment by FlyingPikachu** [comment]
@Kane16x This build should resolve the issue once available - http://ci.ac3-servers.eu/job/Quests/510/

**Comment by Kane16x** [comment]
Thank you!
