### ISSUE TITLE
could not pass BlockBreakEvent to Quests

### ISSUE THREAD

**Issue by smmmadden** [FlyingPikachu/Quests#517]
Seems to occur with every command I execute and multiple times
[latest.log](https://github.com/FlyingPikachu/Quests/files/2574386/latest.log)

PaperSpigot: 1.13.2 - Build 437
Quests: 3.4.0-b491
https://hastebin.com/ujisuvexes.cs

**Comment by FlyingPikachu** [comment]
Would you please try the latest dev build and post the new error (if upgrading doesn't resolve the issue)?

http://ci.ac3-servers.eu/job/Quests/496/

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
