### ISSUE TITLE
Enchantment books not working

### ISSUE THREAD

**Issue by StormyIceLeopard** [FlyingPikachu/Quests#520]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.4.0-b494

(__Required__) Please describe the problem and how to replicate it. Any console errors?
My friend has unearthed this issue. So I have asked him to answer this question and I am posting it for him:
I was creating a quest in the editor. I was making stage 2 and decided that I wanted the person to deliver an Enchanted Book, specifically a Sharpness III book, to the quest NPC. So in the stage 2 menu, I typed 9 (Deliver items), 1 (Add item) and then 0 (Item in hand). I finished up the rest of the item delivery (NPC & message), and then I completed stage 2 with 9 (Save). I finished up the rest of the quest, saved the quest, then reloaded Quests. It reloaded sucessfully. I was able to start the quest and execute stage 1 (Deliver 15 Iron Blocks & 20 Iron Ingots), however, when I attempted to deliver the Unbreaking III Enchanted Book, it stated that the item was not required for the quest, even though I added it through the Quests editor. In addition, the console errors showed up each time I attempted to give the NPC the book. From just the game side of things, everything looks good (Outside of the fact the book can't be delievered).

So I decided, "Okay, maybe the book won't work, so let me try an Iron Sword with the Sharpness III enchantment on it.". I went to the editor and made the change from the Sharpness III Enchanted Book to an Iron Sword with Sharpness III applied to it. I went through the process of saving the quest after making the change, saved the quest and tried to reload Quests... It wouldn't reload. In-game, it stated, "An internal error occurred while attempting to perform this command." I went back into the editor after the server was stopped and started, and the quest with the enchanted iron sword disappeared from the editor, and Quests was still unable to reload (According to the game). In the console, the errors were similar to the one mentioned when I attempted to give the NPC the Unbreaking III Enchanted Book. We were able to get Quests to work again by removing the quest causing the reload issue from the file where the Quests are saved.

Console Errors:
16:33:01 [SEVERE] IceFactions > Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
16:33:01 [INFO] IceFactions > java.lang.IllegalArgumentException: stored-enchants({DURABILITY=3}) is not a valid interface java.util.Map
16:33:01 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:215) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.buildEnchantments(CraftMetaItem.java:489) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaEnchantedBook.<init>(CraftMetaEnchantedBook.java:50) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
16:33:01 [INFO] IceFactions >     at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
16:33:01 [INFO] IceFactions >     at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
16:33:01 [INFO] IceFactions >     at java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[?:?]
16:33:01 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:180) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at jdk.internal.reflect.GeneratedMethodAccessor222.invoke(Unknown Source) ~[?:?]
16:33:01 [INFO] IceFactions >     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
16:33:01 [INFO] IceFactions >     at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
16:33:01 [INFO] IceFactions >     at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:81) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:121) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:160) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.util.ItemUtil.deserializeItemMeta(ItemUtil.java:239) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:162) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.Quests.processStages(Quests.java:2904) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.Quests.loadQuests(Quests.java:2182) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.Quests.reloadQuests(Quests.java:2011) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.Quests.adminReload(Quests.java:764) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:747) ~[?:?]
16:33:01 [INFO] IceFactions >     at me.blackvein.quests.Quests.onCommand(Quests.java:710) ~[?:?]
16:33:01 [INFO] IceFactions >     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
16:33:01 [INFO] IceFactions >     at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:33:01 [INFO] IceFactions >     at java.lang.Thread.run(Thread.java:844) [?:?]
16:33:01 [INFO] IceFactions > [Quests] Loaded language en-US. Translations via Crowdin

And when /questsadmin reload is done this occures in console, but no errors in-game:
16:50:12 [INFO] IceFactions > SmashbrosThe3rd issued server command: /questsadmin reload
16:50:12 [SEVERE] IceFactions > Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
16:50:12 [INFO] IceFactions > java.lang.IllegalArgumentException: stored-enchants({DURABILITY=3}) is not a valid interface java.util.Map
16:50:12 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:215) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.buildEnchantments(CraftMetaItem.java:489) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaEnchantedBook.<init>(CraftMetaEnchantedBook.java:50) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
16:50:12 [INFO] IceFactions >     at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
16:50:12 [INFO] IceFactions >     at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
16:50:12 [INFO] IceFactions >     at java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[?:?]
16:50:12 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:180) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at jdk.internal.reflect.GeneratedMethodAccessor222.invoke(Unknown Source) ~[?:?]
16:50:12 [INFO] IceFactions >     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
16:50:12 [INFO] IceFactions >     at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
16:50:12 [INFO] IceFactions >     at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:81) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:121) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:160) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.util.ItemUtil.deserializeItemMeta(ItemUtil.java:239) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:162) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.Quests.processStages(Quests.java:2904) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.Quests.loadQuests(Quests.java:2182) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.Quests.reloadQuests(Quests.java:2011) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.Quests.adminReload(Quests.java:764) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:747) ~[?:?]
16:50:12 [INFO] IceFactions >     at me.blackvein.quests.Quests.onCommand(Quests.java:710) ~[?:?]
16:50:12 [INFO] IceFactions >     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
16:50:12 [INFO] IceFactions >     at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [Spigot.jar:git-Spigot-2474d93-ca22de3]
16:50:12 [INFO] IceFactions >     at java.lang.Thread.run(Thread.java:844) [?:?]
16:50:12 [INFO] IceFactions > [Quests] Loaded language en-US. Translations via Crowdin

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/nnjXgHwq

**Comment by FlyingPikachu** [comment]
The commit I just pushed (and associated dev build) will quiet the error. However, it is only a first step in supporting Enchanted Books within Quests. Your quest will now accept a normal Enchanted Book (without any stored enchantments), but the intended book with Durability III will not work. I appreciate your patience as a solution draws near.

**Comment by StormyIceLeopard** [comment]
Well if you got any testing to be done, you know how to contact me.

**Comment by FlyingPikachu** [comment]
Enchanted Books should now work without issue. Use this build once available - http://ci.ac3-servers.eu/job/Quests/507/
