### ISSUE TITLE
Console Error on Reload

### ISSUE THREAD

**Issue by nexlemav** [FlyingPikachu/Quests#521]
Quests 3.4.2 build 500

Console errors while trying to reload the plugin

https://pastebin.com/rPQeyyCL
Quests.yml was a fresh install

**Comment by FlyingPikachu** [comment]
The following dev build (once available) should provide more detail in the console when the error occurs. Please give it a try and post the new output should you require further assistance.

http://ci.ac3-servers.eu/job/Quests/501/

**Comment by FlyingPikachu** [comment]
This has been resolved and should have been closed already.

Use the latest dev build - http://ci.ac3-servers.eu/job/Quests/521/
