### ISSUE TITLE
find the value Farming . if is a help not bug

### ISSUE THREAD

**Issue by svmine** [FlyingPikachu/Quests#525]
First of all this is not a bug report it just needs a little hint and needs help on the growing blocks
I have difficulty in creating planting and gardening tasks because the materials have overlapping blocks and items.
For example:
Wheat crop (59) = Wheat, Wheat (296) = Wheat
But Wheat Crop = Crops, Wheat = Wheat
So how do I find the value of Crops, where is it located?
Similar to Sugar Cane and other growing blocks
Hope someone helps me find the results for all the growing blocks below
Cocoa bean
Pumpkin
Melon
Nether worth
Carrot
Potato
Beefroot
Catus
Sorry for my bad english. I use GG translate.
Glad that someone could spend some time helping me. Thank you

**Comment by svmine** [comment]
I know the request of me below this currency, but that that that the well is the author that for the list of the list that you want to, because the link that the author has provided it that know it from long but that the website that that it is difficult me many many.
a section because the page material that has provided by it that it is not used because the chapters of minecraft. Written by the author of the plugin Quests rather than the author of the author will be know the specified but the material that will be true and exact.

**Comment by FlyingPikachu** [comment]
Bad translation. Please try again?

**Comment by comonier** [comment]
same problema here:
https://github.com/FlyingPikachu/Quests/issues/537

place block wheat seed is not working
should i try change the block name to what ?
i have planted some seeds but its not counting
https://prnt.sc/lok5t2

**Comment by FlyingPikachu** [comment]
Possibly resolved by #537

**Comment by FlyingPikachu** [comment]
Quote from @SXRWahrheit
> In 1.13, the name of crops changed to wheat. wheat is placed when right-clicking with wheat_seeds. Therefore, the place-block event catches wheat, not wheat-seeds.

https://minecraft.gamepedia.com/1.13/Flattening#Block_and_Item_IDs
