### ISSUE TITLE
Error with questadmin reload

### ISSUE THREAD

**Issue by TheOtakuJames** [FlyingPikachu/Quests#526]
Version: 3.4.2, MC version 1.13.1

Massive console spam whenever reloading the plugin from in game - /questadmin reload. mcMMO is uninstalled, if it's installed then the plugin is just "NULL". 

Error: https://pastebin.com/w9Jzt1VH

**Comment by FlyingPikachu** [comment]
What is your mcMMO version?

**Comment by TheOtakuJames** [comment]
mcMMO is uninstalled, but if I were to install it again it's 1.6.0-SNAPSHOT

That error in the pastebin is happening without mcMMO installed, which is the error that's stopping /questadmin reload

**Comment by FlyingPikachu** [comment]
Looks like you still have an mcMMO reward in your quests.yml then. The following dev build will tell you which one to change/remove, rather than showing an error:
http://ci.ac3-servers.eu/job/Quests/503/

**Comment by TheOtakuJames** [comment]
Alrighty, it shows me what to remove - thanks!
How about the issue with Quests when mcMMO is installed - it just displays "NULL" in chat, and no errors in console. Version 3.4.2 of Quests, mcMMO 1.6.0-SNAPSHOT

**Comment by FlyingPikachu** [comment]
That is probably not a bug with Quests, but rather your mcMMO config file is outdated. Unfortunately, mcMMO's config file(s) need to be regenerated for 1.13 and, if you check your server log, you'll likely see that mcMMO disabled itself after issues loading.

I'll update the plugin to skip loading mcMMO if it disabled itself, but again, that's really more of an issue with mcMMO.

**Comment by TheOtakuJames** [comment]
Perfect, thank you for that. I'll give regenning a go.
