### ISSUE TITLE
generated an exeption whilst handling conversation

### ISSUE THREAD

**Issue by Duhhero** [FlyingPikachu/Quests#527]
Version 3.4.2-b500

generated an exeption whilst handling conversation (using citizen2)

coudnt copy from the console to pastebin so i just snipping tool instead hope it help

https://media.discordapp.net/attachments/510222124237979674/512957258670276611/unknown.png

**Comment by FlyingPikachu** [comment]
I will also know what you were doing at the time this occurred. Were you typing something in chat?

**Comment by Duhhero** [comment]
At that time i currently set up quest via citizen npc. I set up starting line and finish line. Also finish set up reward and quest stage. When i save the quest the problem occur

**Comment by FlyingPikachu** [comment]
I've been trying for some time to replicate this, but to no avail. Try updating to the latest dev build and if it happens again, post the new error here.
