### ISSUE TITLE
GUI Text off-screen

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#53]
When using the GUI Displays, the text is completely off of the screen making it unreadable.

Here: http://i.imgur.com/9mzRn8E.png

**Comment by FlyingPikachu** [comment]
Try putting an "\n" in your text where you want to start a new line. If that doesn't work, please post your config.

**Comment by whoshenry** [comment]
Doesn't work. The \n just appears in the text.

Config: http://pastebin.com/Bw8Re4Mq
