### ISSUE TITLE
Unable to add custom mobs when creating an event

### ISSUE THREAD

**Issue by CurrentRiver1** [FlyingPikachu/Quests#531]
Quests Version 3.4.2

I am trying to create a custom mobs in events. Some mobs that I add are fine on their own but when I start adding armor to Zombies (for example) then I will type 15 for "Done" and nothing happens.
I also can't add Creeper's to events mob spawning either... the same error occurs. 

Not sure if this console error has anything to do with it.

[Tue, 20. Nov 2018 18:25:01 MST WARN] Task #120 for Quests v3.4.2-b500 generated an exception
[Tue, 20. Nov 2018 18:25:02 MST WARN] Task #120 for Quests v3.4.2-b500 generated an exception
[Tue, 20. Nov 2018 18:25:03 MST WARN] Task #120 for Quests v3.4.2-b500 generated an exception
[Tue, 20. Nov 2018 18:25:04 MST WARN] Task #120 for Quests v3.4.2-b500 generated an exception
[Tue, 20. Nov 2018 18:25:05 MST WARN] Task #120 for Quests v3.4.2-b500 generated an exception
[Tue, 20. Nov 2018 18:25:06 MST WARN] Task #120 for Quests v3.4.2-b500 generated an exception
[Tue, 20. Nov 2018 18:25:06 MST INFO] [Metrics] Connection timed out

![2018-11-20_20 34 34](https://user-images.githubusercontent.com/45218973/48813861-99292f80-ed06-11e8-9fad-8da00869c040.png)

**Comment by FlyingPikachu** [comment]
It could be that, when you add armor drops, you're also supposed to add the chance that they'll drop (a number from 0.0 to 1.0). However, it isn't obvious that it's required. I'll push a commit that will automatically set the drop chances to 1.0 if they haven't been set.

After I do that, I'll post a link to a dev build for you to try. Test it, and let me know whether it resolves the issue :)

**Comment by FlyingPikachu** [comment]
Please try this once available - http://ci.ac3-servers.eu/job/Quests/507/
