### ISSUE TITLE
How create a farmer quest to plant wheat seeds and havesting wheats

### ISSUE THREAD

**Issue by comonier** [FlyingPikachu/Quests#537]
Build 343 #508
Trying to create a quest were a player should to plant wheat seeds.
Trying use place block on wheat seeds, do not work
https://prnt.sc/lok5t2

before u said me to change name to crops, the plugin do not accept that block name, if you ask me to use that on place block stage. so i should use another type of option on stage edition ? and not place blocks ?

**Comment by comonier** [comment]
admin Wahrheit help me on discord
stage 1) place block wheat
stage 2) break block wheat
stage 3) delivery wheat

**Comment by FlyingPikachu** [comment]
@SXRWahrheit could you explain the workaround?

**Comment by SXRWahrheit** [comment]
In 1.13, the name of `crops` changed to `wheat`. `wheat` is placed when right-clicking with `wheat_seeds`. Therefore, the place-block event catches `wheat`, not `wheat-seeds`.

**Comment by FlyingPikachu** [comment]
@SXRWahrheit Gotcha, thanks! I'll add the following link to the Wiki, which lays out the name changes.
