### ISSUE TITLE
When i enter the mission it just jump to mission failed

### ISSUE THREAD

**Issue by Juliandilanda** [FlyingPikachu/Quests#54]
In your issue, please include:
First i have create a mission name talk to Julian in Ailly then it work but when i make an other mission in Julian and accept the mission, it just jump to mission failed i have no idea to fix about the problem
- Spigot and Quests versions (do not say "latest")
Server bukkit 1.11.2   &    Quests versions is 2.9.0
- Description of problem & console errors
it have not show 
- Pastebin an example quest from quests.yml for testing, if applicable
no
Failure to provide the first 2 bullets may result in your issue being closed!
no , the problem just about the "mission failed" peoblem

**Comment by FlyingPikachu** [comment]
Given the nature of your description, I'll definitely need you to provide the Julian quest from quests.yml before look into this further (please post it to a site like pastebin.com). Thanks!

**Comment by Juliandilanda** [comment]
Quests:
  Miner:
    Name: Stone Miner
    Ask-message: <yellow> Mine <purple> 10 <yellow> blocks of <purple> Stone <yellow> and gather the <purple> 10 pieces of <purple> Cobblestone <yellow>.
    Finish-message: <yellow> Well done. Here is your reward.
    Redo-delay: 1800
    Requirements:
      Items:
      - name-wood_pickaxe: amount-1
      Remove-items:
      - false
      Fail-requirement-message: <red> You must have a <purple> Wooden Pickaxe <red> first.
    Stages:
      Ordered:
        '1':
          Break-block-names:
          - stone
          Break-block-amounts:
          - 10
          Break-block-durability
          - 0
    Rewards
      Money: 1000
      Quest-points: 1
  Hunter:
    Name: Mob Hunter
    Ask-message: <yellow> Kill an assortment of Mobs.
    Finish-message: <yellow> Excellent. Here is a <purple> Diamond Sword <yellow>.
    Requirements:
      Quests:
      - Stone Miner
      Fail-requirement-message: <red> Complete <purple> Stone Miner <red> first.
    Stages:
      Ordered:
        '1':
          Death-event: DeathFail
          Mobs-to-kill:
          - Pig
          Mob-amounts:
          - 3
          Finish-event: GoodJob
        '2':
          Death-event: DeathFail
          Mobs-to-kill:
          - Zombie
          Mob-amounts:
          - 2
          Finish-event: GoodJob
        '3':
          Death-event: DeathFail
          Mobs-to-kill:
          - Skeleton
          Mob-amounts:
          - 1
    Rewards
      Items:
      - name-diamond_sword: amount-1
      Exp: 100
      Quest-points: 1
  CatchFish:
    Name: Catch Fish
    Ask-message: <yellow> Catch some fish!
    Finish-message: <yellow> Good job. Here is some <green> experience <yellow>.
    Requirements:
      Quests:
      - Stone Miner
      Fail-requirement-message: <red> Complete <purple> Stone Miner <red> first.
    Stages:
      Ordered:
        '1':
          Start-event: FishingStart
          Death-event: DeathFail
          Chat-events:
          - RodEvent
          Chat-event-triggers
          - rod
          Fish-to-catch: 5
    Rewards
      Exp: 250
  Custom1:
    Name: invited to sand city
    Npc-giver-id: 0
    Ask-message: young people, our destination to, after accepting the task, you go to the terminal and the "Leim" dialogue
    I wish you a pleasant journey
    Stages:
      Ordered:
        '1':
          Npc-ids-to-talk-to:
          - 1
          Objective-override: Chapter 1: Visit to Shawan City
          Do you want to be invited? Start:.
          Complete-message: ok ... it's sandy city's mind, wait a while looking for me ~
    Rewards
      Money: 1000
      Exp: 3
  Custom2:
    Name: hire to buy water
    Npc-giver-id: 1
    Ask-message: (go to the business district to buy bottles of water back after the task to accept it ~) you can help me go to the business district and "Caesar" to say hello?
    Thank you for the water ~ ~ ~ This is what you deserve
    Requirements:
      Items:
      - name-POTION: amount-1
      Remove-items:
      - true
      Quests:
      - invited sand city
      Fail-requirement-message: The task failed
    Stages:
      Ordered:
        '1':
          Npc-ids-to-talk-to:
          - 2
          Objective-override: Chapter 1: Understanding Carson
          Start-message: hey! Young man, it seems you have just come here, it seems you need a job, you can always find me oh
          Complete-message: come to me after finishing the task
    Rewards
      Items:
      - name-COAL_BLOCK: amount-4
      Money: 10
      Quest-points: 3
      Exp: 3

### this is my quests.yml

**Comment by FlyingPikachu** [comment]
The data you've provided has capitalization problems. Either your quest data is inherently faulty or (ore likely) this formatting is because you pasted here rather than a site like pastebin.com as requested.

For example, "Stages" should be "stages". This causes an error on server startup.

Please try again, using Pastebin. Thanks!

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.

**Comment by Juliandilanda** [comment]
Dear FlyingPikachu
I am so thank you to help me to fix this problem
i got fix now about the quests quetions

                                              Your dear user
