### ISSUE TITLE
Hello Error with the Effects!

### ISSUE THREAD

**Issue by mig25Zockt** [FlyingPikachu/Quests#540]
Hello! Ich habe a Problem with the  Effects on a NPC. 
Error Code: https://hastebin.com/anehulimun.css

**Comment by FlyingPikachu** [comment]
Closing as OP did follow issue instructions. Need Quests version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mig25Zockt** [comment]
What you mean?

**Comment by FlyingPikachu** [comment]
@mig25Zockt You must tell us your Quests version number, per the instructions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mig25Zockt** [comment]
Oh Okey i have the version: 3.4.3

**Comment by FlyingPikachu** [comment]
Duplicate of #516 

Use this dev build once available - http://ci.ac3-servers.eu/job/Quests/515/

**Comment by mig25Zockt** [comment]
Hello yet ist this error! Version: 3.4.4
https://hastebin.com/ekamehuqux.cs

**Comment by FlyingPikachu** [comment]
Sorry and thanks for your patience. This should do it, once available:
http://ci.ac3-servers.eu/job/Quests/521/
