### ISSUE TITLE
Please helpme. I got spam notice like this on console

### ISSUE THREAD

**Issue by asqhalnabil** [FlyingPikachu/Quests#545]
Version: 3.4.3-b508

 I got spam notice like this on console, You can check console spam error @ this link https://pastebin.com/DwAar6Mf

My quests.yml > https://pastebin.com/bEJSiCDa

Thanks For Help

**Comment by FlyingPikachu** [comment]
Already resolved in recent issues. Use http://ci.ac3-servers.eu/job/Quests/523/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
