### ISSUE TITLE
NoPermissions

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#547]
3.4.4 b515

no errors but no permissions message

![47389940_351287032364168_2574965071570534400_n](https://user-images.githubusercontent.com/43417249/49339778-f7bfa900-f636-11e8-9a6b-4aea407703dc.png)

in console: monikanovava issued server command: /tellraw monikanovava ["§aZničení §b",{"translate":"block.minecraft.diamond_ore"},"§a: 0/6"]

**Comment by FlyingPikachu** [comment]
That is the default Bukkit no permissions message.

It could be you're lacking a Quests permissions (which, as a server owner, you have to add yourself). Here is a list of all the Quests permissions and what they do - https://github.com/FlyingPikachu/Quests/blob/master/src/main/resources/plugin.yml

If you have all permissions and it still doesn't work, then it's an issue with a different plugin's perms.
