### ISSUE TITLE
Request Something

### ISSUE THREAD

**Issue by asqhalnabil** [FlyingPikachu/Quests#549]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 3.4.4-b522

(__Required__) Please describe the problem and how to replicate it. Any console errors?

No error i just want add this plugin with Placeholder please :)

**Comment by FlyingPikachu** [comment]
Quests already supports PlaceholderAPI. See https://github.com/FlyingPikachu/Quests/wiki/Translations#placeholderapi
