### ISSUE TITLE
cant set 2 items as deliver objective

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#55]
In your issue, please include:

- Spigot and Quests versions: 2.9.0

- Description of problem & console errors: cant set 2 items as a deliver objective

Basically I want to create an objective where you have to go out and mine 3 diamonds, 45 cobble stone then deliver the 3 diamond and 45 cobble stone to the npc. It wont let me set 2 items in the one delivery when i press 5 to finish. Instead is comes up with "The item list and npc list are not equal in size"

Here is a screenshot http://i.imgur.com/wZ7uKl2.png

Please fix asap, thank you

**Comment by FlyingPikachu** [comment]
It's because you need to set the NPC for the 2nd item. So there should be a list of 2 NPCs (making it the "same size" as the list of items).
