### ISSUE TITLE
/quests command not work

### ISSUE THREAD

**Issue by Lunatik934** [FlyingPikachu/Quests#553]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.4.5
(__Required__) Please describe the problem and how to replicate it. Any console errors?
/quests command not work
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
starter quests.yml

**Comment by FlyingPikachu** [comment]
What happens when you enter the command? Any errors?

**Comment by Lunatik934** [comment]
i not have any errors

**Comment by Lunatik934** [comment]
command not exist

**Comment by Lunatik934** [comment]
i am in 1.8.8

**Comment by FlyingPikachu** [comment]
Alright, that either means the plugin is not installed or it did not load properly. Could you please upload startup log? On Windows, this is located in `\logs\latest.log`

**Comment by Lunatik934** [comment]
https://pastebin.com/WP6y0ru5

**Comment by Lunatik934** [comment]
i have the commands of PermissionsEx

**Comment by Lunatik934** [comment]
/questadmin and /quest work but not /quests

**Comment by FlyingPikachu** [comment]
In that case, try running the following command (replace `yourName` with your Minecraft username):

`/pex user yourName add quests.*`

and then run

`/questadmin reload`

**Comment by Lunatik934** [comment]
it work thx
