### ISSUE TITLE
ERROR Could not pass event BlockBreakEvent to Quests v3.4.6-b526

### ISSUE THREAD

**Issue by comonier** [FlyingPikachu/Quests#556]
paper version: git-Paper-455 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
quests version: Quests-3.4.6_Build_526.jar

player cant complet second phase of quest

console error:
https://codeshare.io/2Kn93K

the error in the console occurs during the second phase of the quest, harvesting the wheats
quests.yml: "farmer quest"
https://codeshare.io/ammvAj

**Comment by comonier** [comment]
it was working i just dont know why it stop to works, maybe after i update quests build

**Comment by FlyingPikachu** [comment]
This build should resolve the issue, once available:
http://ci.ac3-servers.eu/job/Quests/528/

**Comment by comonier** [comment]
ty so muth!
