### ISSUE TITLE
Problem with daily quests

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#56]
In your issue, please include:

**- Spigot and Quests versions (do not say "latest")**
Spigot 1.11.2 (but we have ViaVersions plugin, which enables 1.12 entrance) and Quests v2.9.0
**- Description of problem & console errors**
No console errors.
We have some daily quests and the problem is, that after completing this quests players can rejoin to the server and start quests again. On our local host cooldown on this quests works good, but on server this trouble happens. We are sending you our video with such problem:
https://www.youtube.com/watch?v=4HCvZSJ_51A
**- Pastebin an example quest from quests.yml for testing, if applicable**
https://pastebin.com/W9Y6jfVM

We assume, that the problem consists in Java version, as on our local host everything goes well, so can it be so?
So, please, could you help us with that issue?

**Comment by FlyingPikachu** [comment]
What leads you to believe Java version might be the issue? Are you not using Java 8+?

Although I intend to take a closer look, try updating Quests to the latest dev build on both servers, as a similar issue was fixed recently.

**Comment by AIphaDragon** [comment]
Thank you for your response, we have updated to the latest version and it helped.
