### ISSUE TITLE
Text on GUI when starting a new line doesn't follow colour code.

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#56]
When a new line starts in the GUI, the text colour code doesn't carry over. For example, showing here, the colour of the text is yellow, but when the text goes onto the next line it reverts to green - http://prntscr.com/6irpxh

Using latest build.

Also, perhaps  &7(Completed) in brackets after the Quest name when a user has completed that quest in the GUI would be good.

**Comment by FlyingPikachu** [comment]
You are correct, you will have to start the new line with a message color. See http://dev.bukkit.org/bukkit-plugins/quests/pages/main/reference/#w-message-colors

Look at the Stone Miner quest in quests.yml for an example. Thanks!
