### ISSUE TITLE
Stage 1 of Quest <-> is not formatted properly

### ISSUE THREAD

**Issue by GuerreroCraft61** [FlyingPikachu/Quests#566]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.4.5
(__Required__) Please describe the problem and how to replicate it. Any console errors?
It don't load https://pastebin.com/w5QKcxqj
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/TzmA6ZQM

**Comment by FlyingPikachu** [comment]
Since the item in the quest you linked uses ItemFlags, which have only been addressed recently, please use the latest dev build and try again. Let us know whether that resolve the issue:

http://ci.ac3-servers.eu/job/Quests/

**Comment by GuerreroCraft61** [comment]
https://pastebin.com/m75SmvWK I remove it in the quest.yml and I try to put it, but now, I can't save it

**Comment by FlyingPikachu** [comment]
Use this dev build once available - http://ci.ac3-servers.eu/job/Quests/542/

**Comment by GuerreroCraft61** [comment]
I use the 542 and same problem https://pastebin.com/Kxm53b87
And same using 545 https://pastebin.com/HW4RdjNu

**Comment by FlyingPikachu** [comment]
@GuerreroCraft61 What version of Minecraft are you running? 1.13?

**Comment by FlyingPikachu** [comment]
@GuerreroCraft61 In your quests.yml the bold area here:

>'name-INK_SACK:amount-1:data-10:enchantment-**Proteccion** 1:displayname-§aEsencia
            de arma no comun:lore-§6§l§m   ...

Should actually be **Protection**

It seems like this is a bug when using languages other than English. I'm looking into a proper fix, but for now changing the text and restarting the server should fix the issue.

**Comment by GuerreroCraft61** [comment]
In the #546 work, but now in the 548 don't work https://pastebin.com/7e6FqHDR

**Comment by GuerreroCraft61** [comment]
And in other quests, now show that error when I reload https://pastebin.com/UTiwsACd
And I give the item to the NPC, it say that item is no required 
https://pastebin.com/nScsq6Rn

**Comment by GuerreroCraft61** [comment]
In th #546 in the console don't show any error, but same, I can't give the Item

**Comment by GuerreroCraft61** [comment]
I already update the quests, but don't work
My quests: https://pastebin.com/HCbQuLpE
Error: https://pastebin.com/huC2xrZS
Lang (I remove the 546 lang, but that file I modify it): https://pastebin.com/3XQgc2wF

**Comment by FlyingPikachu** [comment]
@GuerreroCraft61 Let's give this another try. In your _quests.yml_, change...

> 'name-INK_SACK:amount-1:data-10:enchantment-**Proteccion** 1:displayname-§aEsencia

...to...

> 'name-INK_SACK:amount-1:data-10:enchantment-**DAMAGE_ALL** 1:displayname-§aEsencia

and then use http://ci.ac3-servers.eu/job/Quests/552/

**Comment by GuerreroCraft61** [comment]
Nop, same problem `[23:07:51 ERROR]: [Quests] name-INK_SACK:amount-1:data-10:enchantment-PROTECTION_ENVIRONMENTAL 1:displayname-§aEsencia de arma no comun:lore-§6§l§m[[-=§c§l§m:=:[§r §e§lInfo del item §c§l§m]:=:§6§l§m=-]]:lore-§cTipo: §aMaterial:lore-§cRareza: §8§aNo comun:lore-§6§l§m[[-=§c§l§m:=:[--=[((-))]=--]:=:§6§l§m=-]]:meta-type-UNSPECIFIC:enchants-{PROTECTION_ENVIRONMENTAL=1}:ItemFlags-[HIDE_ENCHANTS, HIDE_ATTRIBUTES]:internal-H4sIAAAAAAAAAGWNsQrCMBiE/zEKgnTyAVwDJdSYNbT/EDCppMnQKaQ2hU5Cre9vugjiDTfcfcftAQgctG6VQ90Fp9AC8aZuc2QIHL/N5kE1cMIOTa1kaDBIq2Uwbci0z3DxC7v+jkC0dGiVvO2gkOu6zMN7Tfo5ztOclhds+ht6n3/OXEQeJ/GgJUuMVmm8UMFFSSuWNYhYsWuED3m+cQ+/AAAA inside items-to-deliver: inside Stage 1 of Quest Recuperar el Regalo is not formatted properly!`

**Comment by GuerreroCraft61** [comment]
Ok
I recomend change the format to that (I don't know how to do it, but normaly other plugins using custom item, use that format): https://pastebin.com/8xymzBQb
As CrazyCrates, MyItems, GreatKits, BlueShop,...
