### ISSUE TITLE
Incorporate CustomObjectives into the Primary Jar

### ISSUE THREAD

**Issue by frost-byte** [FlyingPikachu/Quests#567]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.4.8
(__Required__) Please describe the problem and how to replicate it. Any console errors?
We have to take an extra step to incorporate CustomObjectives into our builds, why not just
include the correct file based upon the version of your latest build in the repository? or at least create an API as another project so that I can use dependency management to work with it?

**Comment by frost-byte** [comment]
Looks like you have... Just confused by the wiki.  Going to close this.

**Comment by frost-byte** [comment]
Unfortunately if I want to just include Quests as a dependency through Maven, I am then required to include all of the dependencies for Quests on my server, even one's I don't need - Vault, mcMMO, etc.
This leads me back to my request for a QuestsAPI.

**Comment by FlyingPikachu** [comment]
You do not have to place any dependencies in your server’s /plugins folder unless you want to test their integration with Quests in-game. Just place them in a new folder, or perhaps more cleanly in your Egit /libs folder.

**Comment by frost-byte** [comment]
While I may not be a fan of the jar mechanism, in terms of managing it as a dependency, I was able to configure my plugin to register my CustomObjectives directly with Quests.
The issue I was having was caused by trying to inject with guice, which wasn't entirely necessary.
I would recommend creating a system of registering CustomObjectives directly to Quests instead of via a separate jar.

**Comment by FlyingPikachu** [comment]
I'm afraid that idea was already shot down in #564 however you're welcome look over my reasoning and add remarks there.
