### ISSUE TITLE
Quest Lore doesnt keep color in GUI

### ISSUE THREAD

**Issue by ErenBlack** [FlyingPikachu/Quests#57]
- 2.9.0

- Whenever i hover over the item i made as the GUI part of a quest, the Lore (ask message) does not keep the color all the way through. 

Here is an example screenshot of what I am trying to describe (notice the lore color changes to green):
https://preview.ibb.co/ehaNnv/2017_07_16_14_22_14.png

If you would like to test and see a live version of the issue, feel free to on my server:
AomReloaded.mcpro.co

**Comment by FlyingPikachu** [comment]
Iirc this is intentional to keep things consistent, but I hope to take a look soon.

**Comment by ErenBlack** [comment]
Alright, thanks! Hope you can get to it soon.

**Comment by FlyingPikachu** [comment]
Please give this build a try and let me know the results (you'll need to recreate the GUI item)

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.

**Comment by Alphexon** [comment]
This is still an issue in 3.3.7 build #483.
