### ISSUE TITLE
Conversations in Quests

### ISSUE THREAD

**Issue by Peda1996** [FlyingPikachu/Quests#571]
Hello,

I want to add more complex conversations, where one can choose between several answers, and the answers lead to different outcomes. 

This plugin doesn't support this kind of feature yet or?
As I am a developer myself, where, and how would be the best place / way to add this feature?

Reguards

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests.

Were you looking to create a quest that has the player respond to several prompts, or did you want NPCs to hold a complex conversation with the player (the latter being a bit beyond the scope of this plugin)?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Peda1996** [comment]
I want to hold complex conversations with the player, like in normal RPGs (Witcher etc.).

**Comment by FlyingPikachu** [comment]
Unfortunately, that's not inclusive of this plugins' goals at this time. However, you have several options:

- [CommandNPC](https://www.spigotmc.org/resources/commandnpc.40295/) to run commands when right-clicking NPCs
- [Denizen](https://www.spigotmc.org/resources/denizen.21039/) to run scripts which could be used for NPCs. It's also set up to run scripts _during_ quests
- Design a [Quest module](https://github.com/FlyingPikachu/Quests/wiki/Master-%E2%80%90-Quests-API) or external plugin which uses the [conversation API](https://bukkit.org/threads/conversations-api-q-a-i-wrote-the-conversations-api-ama.68451/) and calls methods like [takeQuest](https://github.com/FlyingPikachu/Quests/blob/3e5115d64d25345fe03204c7e61f68d813a5f2db/src/main/java/me/blackvein/quests/Quester.java#L313) as desired
- Try [BetonQuest](https://www.spigotmc.org/resources/betonquest.2117/), a different plugin (not by me) that "offers RPG-style conversations with NPCs" but hasn't been updated in over a year
