### ISSUE TITLE
Thermos server time out.

### ISSUE THREAD

**Issue by DwarfyAssassin** [FlyingPikachu/Quests#572]
This issue is about thermos and I know that this plugin is meant for Spigot but if you don't want to add thermos support that is understandable. In that case just close this issue and just say that thermos won't be supported.

Quest version: v3.5.1
Thermos version: v1.7.10-1614
LOTR mod version: v34.3

The problem is that once a player joins the player times out. This is the server log: https://pastebin.com/3Vct7VEg (Only the bottom part is interesting the rest is normal stuff)
It seems that this line causes the problem:
`[17:17:52] [Spigot Watchdog Thread/ERROR]:      me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:722)`

So that is this in the code.
```Java
@EventHandler
public void onPlayerMove(PlayerMoveEvent evt) {
    if (evt.getFrom().getBlock().equals(evt.getTo().getBlock())) {
        return;
    }
```

The only thing which I haven't tried is not using the LOTR mod so I will report back if that changes anything.

**Comment by FlyingPikachu** [comment]
I'm not opposed to supporting Thermos, but I have no interest in testing it myself.

Looking at the log, your server is running at a snail's pace. This line:
> The server is going slow. Last server tick was 34659ms ago

Says that your last tick was greater than 30 seconds ago. There should be 20 ticks _every second_. So, it wouldn't surprise me that your server crashed:

> The server has stopped responding!

I'd certainly look at your LOTR mod as the culprit first, as the reference Quests line would only cause issues if a player's movement has been improperly modified. If removing LOTR and Quests doesn't resolve the issue, and you're running on sufficient hardware, contact Thermos support.

**Comment by DwarfyAssassin** [comment]
If you want I can do some more research but I can tell you that it isn't a hardware problem nor a LOTR mod problem. It's definitely between thermos and quests. 
I tested with just thermos and quests and I wasn't able to log it. It didn't time out or anything but nothing happened it said logging in for like 15 mins but I will do some more tests later.

If you are willing to fix it if I find the cause you are a hero, well for me then.
