### ISSUE TITLE
Kill Mobs name error

### ISSUE THREAD

**Issue by GuerreroCraft61** [FlyingPikachu/Quests#573]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
#556
(__Required__) Please describe the problem and how to replicate it. Any console errors?
![image](https://user-images.githubusercontent.com/30746531/50024279-2009b900-ffe2-11e8-81d9-1e5b2a0cfab8.png)
I have translate-item in true
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/1UkyPcnG

**Comment by FlyingPikachu** [comment]
This is working as expected on a 1.13 server:

![entity](https://user-images.githubusercontent.com/2267126/50038485-6ebd5000-ffee-11e8-8c6a-2d5e8a5a54f5.png)

So, I'm thinking this issue may only be present on older server versions such 1.9.4. Would you please run the following build (once available) and report back with any console errors?

http://ci.ac3-servers.eu/job/Quests/558/

**Comment by GuerreroCraft61** [comment]
The problem is the plugin.yml https://pastebin.com/bQTnje1M
I remove the loadbefore and same error
https://i.gyazo.com/d480c0904256ab2a96644c8386464545.png

That error is when I use /questsadmin nextstage: https://pastebin.com/KGbrDXm9

I wanted to try the item-translate in items, but directly it does not let me do the mission, I've been killing and it goes wrong: https://pastebin.com/AjFgxdjg

**Comment by FlyingPikachu** [comment]
Thanks for reporting the plugin.yml issue. Latest commit resolves that problem.

Looks like I'll need to set up a 1.9.4 server to test what's wrong here. Hope to report back soon!

**Comment by FlyingPikachu** [comment]
Use http://ci.ac3-servers.eu/job/Quests/561/

**Comment by GuerreroCraft61** [comment]
The mobs error is solved, but the item error no

Error when I use /questsadmin nextstage: https://pastebin.com/KGbrDXm9

After I kill mobs one by one, and when I complete the stage 1, show that error: https://pastebin.com/AjFgxdjg (That quest is next of the kill mobs)

After, I click in the npc and show that error: https://pastebin.com/MZaspyW4

**Comment by FlyingPikachu** [comment]
That’s a different error, so please open a new issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
