### ISSUE TITLE
Quest Events Error

### ISSUE THREAD

**Issue by PlinioRasch** [FlyingPikachu/Quests#574]
I'm using the current 3.5.1 version of the plugin.

So sometimes when I type /quests events, then proceed to type the event name it gives me some console errors. Here they are... https://pastebin.com/PGWKL1K2

I've tried restarting and still the same thing, also tried to reload the plugin but nothing.

**Comment by FlyingPikachu** [comment]
Since I can't replicate the issue, I've pushed a commit which I think might resolve the issue. Please give the following build a try and report back with your results:

http://ci.ac3-servers.eu/job/Quests/562/

**Comment by FlyingPikachu** [comment]
Alright. However, it would be wise to start using that build _before_ it happens again, if it does.
