### ISSUE TITLE
Item translate problem

### ISSUE THREAD

**Issue by GuerreroCraft61** [FlyingPikachu/Quests#575]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
#561
(__Required__) Please describe the problem and how to replicate it. Any console errors?
The mobs name translate error is solved, but the item error no
Error when I use /questsadmin nextstage: https://pastebin.com/KGbrDXm9
After I kill mobs one by one, and when I complete the stage 1, show that error: https://pastebin.com/AjFgxdjg (That quest is next of the kill mobs)
After, I click in the npc and show that error: https://pastebin.com/MZaspyW4

Item-translate option cause that, I test it
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/Bk5CajJw

**Comment by FlyingPikachu** [comment]
@GuerreroCraft61 Once available, the build below should rectify the issue. Please note that some items like Wool, Beds, and anything with color variation may not work properly, but I'm still working on that. Most items will be translated and there should be no errors:

http://ci.ac3-servers.eu/job/Quests/563/

**Comment by FlyingPikachu** [comment]
The following build will also translate items with color determined by durability (like INK_SACK). Several items like wood and stone types may still have issues translating. If you experience any similar problems, please open a new issue with an example quest.

http://ci.ac3-servers.eu/job/Quests/564/

**Comment by GuerreroCraft61** [comment]
The ink sack item (black) [19:47:11 INFO]: GuerreroCraft61 issued server command: /tellraw GuerreroCraft61 ["§aEntregar §b",{"translate":"item.dyePowder.null.name"},"§a a §0§lMafioso: 0/3"]

**Comment by FlyingPikachu** [comment]
Weird, it works on my 1.9.4 test server. Will look into it shortly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FlyingPikachu** [comment]
Ended up redoing the code for showing objective, so it should work for you now. It does for me, at least!

![face2](https://user-images.githubusercontent.com/2267126/50325853-2fdb3e80-04b5-11e9-96d8-672a4fdf7a9e.png)

**Comment by FlyingPikachu** [comment]
Use this build once available - http://ci.ac3-servers.eu/job/Quests/568/

**Comment by FlyingPikachu** [comment]
Commit did not resolve issue. Still more work to do.

**Comment by FlyingPikachu** [comment]
The code for displaying objectives has been completely reworked. Everything appears OK in my tests. Use the following build once available:
http://ci.ac3-servers.eu/job/Quests/569/

![proof3](https://user-images.githubusercontent.com/2267126/50331081-73d93e00-04cb-11e9-968e-cc763d4ab875.png)

**Comment by GuerreroCraft61** [comment]
Yo can put console using tellraw? Because the player don't have that permission
https://pastebin.com/WubPL2z2 (In the user chat say he don't have permission)

**Comment by FlyingPikachu** [comment]
@GuerreroCraft61 Thanks for catching that! Use http://ci.ac3-servers.eu/job/Quests/571/ once available
