### ISSUE TITLE
Heroes Not Linking?

### ISSUE THREAD

**Issue by Foxersthe** [FlyingPikachu/Quests#576]
I'm using Quests 3.5.1, and Heroes 1.9.0 Beta 5 on a Spigot 1.13.2 server.

I plan to use Quests to give xp for Heroes classes, and I noticed a message in the console that said:
"Heroes was detected, but is not enabled! Fix Heroes to allow linkage."
Heroes is working, but how do I link it to Quests?

**Comment by FlyingPikachu** [comment]
This was an issue with the plugin.yml for Quests that was fixed in a recent dev build. Use the latest build here:
http://ci.ac3-servers.eu/job/Quests/
