### ISSUE TITLE
Bug with complete message before delay ends. v3.5.4

### ISSUE THREAD

**Issue by omatix** [FlyingPikachu/Quests#579]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
v3.5.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
There is a bug with STAGE messages. Complete message is showing up before delay timer finishes his work. The resault is: `1. Stage's objective finished.  2. Complete message showed up.  3. Delay message showed up.  4. Timer is counting. 5. New stage started up.  <- I think it's odd and complete stage message should appear after counting is finished. `

**Comment by FlyingPikachu** [comment]
Please provide an example quest via Pastebin so I may replicate the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FlyingPikachu** [comment]
After a little investigation, the order in which the messages appear is intentional. Delay is meant to postpone the completion of the stage, not the objectives.
