### ISSUE TITLE
Quest NPC won't save

### ISSUE THREAD

**Issue by xxstaten** [FlyingPikachu/Quests#58]
I'm testing out the plugin, working on making a quest... When I got to the point of saving, I had the options:

1 - yes
2 - no

when i typed 1, nothing happened, but when i typed 2, it worked... I'm unable to save and it's not saying anything I did wrong.

**Comment by FlyingPikachu** [comment]
Quests version? Console errors?Quests version? Console errors?

**Comment by xxstaten** [comment]
I figured out the problem. my quest file was broken. deleting it and letting it redownload fixed the problem. :)

**Comment by FlyingPikachu** [comment]
Cool beans!
