### ISSUE TITLE
error and not reloading

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#58]
In your issue, please include:

- Spigot and Quests versions (2.9.0

Cannot reload quests/make new quests. get an error after i make a quest with the 2.9.0 version after i make the quest then reload it:

Here is the error: https://pastebin.com/4G674TuM

**Comment by ozm8** [comment]
Now this time its saying its not a valid npc id when it clearly is: https://pastebin.com/Q6jQ3psc

my quest: https://pastebin.com/g47e4fV6

proof its the right id: blob:http://imgur.com/9f3c456b-fbb3-4704-b4d2-a7123db4bd93

**Comment by FlyingPikachu** [comment]
The reason for your first error is that at least one quest is missing a durability value. There should be an equal number of -names, -amounts, and -durability values. A bug in the Quests Editor is likely what caused the missing value. I'll push a fix for the next dev build so this doesn't happen anymore, but you'll have to add the missing -durability values yourself.

**Comment by ozm8** [comment]
ok that worked but now when i do /quest journal its says error and on the journal book, it says invalid book tag. here is the error log: https://pastebin.com/eErx8a6L

**Comment by ozm8** [comment]
yeah now when i make a new quest and go to start a quest it picks up the item https://pastebin.com/1YeEr0jp

here is the error: https://pastebin.com/rZR5pQ06

**Comment by ozm8** [comment]
I also get this when i try and edit a quest now: https://pastebin.com/1wBiuVwm

**Comment by ozm8** [comment]
ahh got it working the durability has to be 0. this plugin is a little sensitive i must say
