### ISSUE TITLE
Request: PlaceholderAPI support anywhere and everywhere

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#580]
This is a common request on the Discord and would allow for greater customization.

https://www.spigotmc.org/resources/placeholderapi.6245/

https://www.spigotmc.org/wiki/hooking-into-placeholderapi/

**Comment by FlyingPikachu** [comment]
Quests already integrates with PlaceholderAPI as outlined here: https://github.com/FlyingPikachu/Quests/wiki/Casual-%E2%80%90-Translations#placeholderapi

If someone would like to report a particular string isn’t working with it, they’re welcome to open an issue and I’ll look into it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SXRWahrheit** [comment]
Does this work outside of the translations file? The documentation has never been clear about that.

**Comment by FlyingPikachu** [comment]
Ah, no I don’t think so. Where else would it be useful?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SXRWahrheit** [comment]
Right, the request perhaps could have been clearer, but by "anywhere and everywhere" I really did mean that - in Quests and Events, not just translations.

A frequently-requested option is to be able to use them in ask-messages etc., but one could, for example, imagine using them even in objectives or requirements. We could have a conversation about when / how often they should be parsed, but I think that it is, on principle, a very good idea.

**Comment by FlyingPikachu** [comment]
That sounds fine. I'd need a list of everything to review, though, starting with ask and finish messages.

**Comment by SXRWahrheit** [comment]
I'll see what I can do this evening.

**Comment by FlyingPikachu** [comment]
Added support for ask and finish messages in 2d072b321a9c6c82d28b51ef65e350c1e9542dab

Feel free to comment with more requests as time passes. Happy Holidays!

**Comment by SXRWahrheit** [comment]
Okay, after sorting through various options a bit, here are some places PlaceholderAPI should also work:

* Quest name
* Requirements
* Rewards

**Comment by SXRWahrheit** [comment]
Unrelated - if you have time to jump on Discord this evening, I left you a message in the mod channel.

**Comment by FlyingPikachu** [comment]
Quest name shouldn’t be an issue. I’d need the specific strings they want me to target for Requirements and Rewards, though.

I’ll try to jump on, but it’s a busy time of year for me. That said, thanks for being so active.
