### ISSUE TITLE
Bug on names.

### ISSUE THREAD

**Issue by OscarMiro** [FlyingPikachu/Quests#581]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? LATEST-3.5.1

(__Required__) Please describe the problem and how to replicate it. Any console errors? Well, I basicly set a quest, called: "&7Cobble Miner &8(Level 1)". It worked alright etc. Now, when I do another quest, i want to name it to set it as a requirement but it says that "&7Cobble Miner &8(Level 1)" dosn't existt.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

https://pastebin.com/7hKB2bkY

**Comment by FlyingPikachu** [comment]
In your quests/yml

`      ordered:
        '1':
          break-block-names:
          - '4'`

'4' is not an acceptable value. It must be an item _name_, like _dirt_ or _stone_. Fix that and then see if the issue is resolved (if not, post back here with your new quests.yml via Pastebin).
