### ISSUE TITLE
Quests Location Troubles (Does not finish quest)

### ISSUE THREAD

**Issue by LoJoSho** [FlyingPikachu/Quests#587]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.5.1

(__Required__) Please describe the problem and how to replicate it. Any console errors?

Have 5 stops around map players can travel too, each block apart, and see if it ends the quest. (It spams my console)

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/5gxLqr1J

**Comment by FlyingPikachu** [comment]
Thanks for the report. Please update to the build that was released on Spigot today. If that doesn't resolve the issue, post the error generated by that build.

**Comment by FlyingPikachu** [comment]
I've tested with the latest dev build and have been unable to replicate the issue. Feel free to comment with new information if the issue persists.
