### ISSUE TITLE
Could not pass event NPCRightClickEvent to Quests v3.5.1-b${env.BUILD_NUMBER} org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#588]
Version v3.5.1

I don't know how it has appeared

quests.yml: https://pastebin.com/eYsH9zAV
log: https://pastebin.com/YpshmQ7P

Thanks for reading

**Comment by FlyingPikachu** [comment]
Thanks for the report. Please update to the build that was released on Spigot today. If that doesn't resolve the issue, post the error generated by that build.

**Comment by keodeovn** [comment]
thanks for supprorting
