### ISSUE TITLE
Cant choose spawnlocation

### ISSUE THREAD

**Issue by Superola86** [FlyingPikachu/Quests#59]
Spigot 1.12, quests 2.9.2

When i try to creat an event with mobs spawning i cant use the spawning location.
Nothing happends when right clicking and typing add.

No error logs.

**Comment by FlyingPikachu** [comment]
I assume you're speaking of the Kill Mobs stage objective

http://imgur.com/a/PV4BG

Was just able to right-click to select location in my test environment. It's possible another plugin could be blocking the event, in which case you'll want to seek help from that plugin's author or the Spigot forums.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
