### ISSUE TITLE
Item names bug

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#6]
Here is an example: I setup a quest where the player has to bring a book to the npc. if i just bring a book it does not take it. Only if I rename it (using anvil) from the (German) Buch to BOOK it works. So there must be something wrong with the item names.

**Comment by FlyingPikachu** [comment]
So you're adding the item from hand/your inventory? Is this issue similar: https://github.com/Blackvein/Quests/issues/42

**Comment by SimbaZockt** [comment]
@FlyingPikachu Loading item from hand doesnt work ;)

**Comment by FlyingPikachu** [comment]
Thanks, I saw your ticket but I'd like to confirm that ScuroK is having the same issue first.

**Comment by SimbaZockt** [comment]
No he have a other problem and i know what he means

**Comment by ScuroK** [comment]
I confirm! load from hand does nothing.

**Comment by FlyingPikachu** [comment]
Okay, try dev build #18 once it's available and let me know if that resolves the issue (no guarantee).

http://ci.ac3-servers.eu/job/Quests/

**Comment by ScuroK** [comment]
ok i test it now

**Comment by SimbaZockt** [comment]
Create quest set deliver item with Set name too: book
http://prntscr.com/63831q
http://prntscr.com/63835s
taking the quest:
http://prntscr.com/6383ef
Rightclicking the Npc with the Book doesnt work:
http://prntscr.com/6383t5
Rename the book with a Anvil to BOOK:
http://prntscr.com/638415
Works..:
http://prntscr.com/63846w

**Comment by FlyingPikachu** [comment]
Is that on the dev build? And there any console errors?

**Comment by ScuroK** [comment]
It does still not work my friend. did you know that minecraft 1.8 chanced all the item ids? does this have something to do with this bug? and load item from hand does also still not work.

**Comment by SimbaZockt** [comment]
@FlyingPikachu no Errors. 
If i rename my item: http://prntscr.com/63883s
exact like the plugin want it: http://prntscr.com/63887j
It works fine. You need to change the code that they took the item nameID and dont care about what names are the item has. 

Sorry for my bad english

**Comment by ScuroK** [comment]
load from hand does nothing:
http://prntscr.com/63882n

Wants RAW_BEEF only....:
http://prntscr.com/6388jn

**Comment by ScuroK** [comment]
Zeile 514: [01:54:38] [Server thread/WARN]: [Quests] An error occurred inserting data into the snooper database!
Zeile 513: [01:54:38] [Server thread/WARN]: [Quests] An error occurred removing old data from the snooper database!

**Comment by SimbaZockt** [comment]
@ScuroK For the first picture: Remove youre configs and recreate then they show: Item loaded. But its not :D

**Comment by ScuroK** [comment]
However: the item-names system seems to be completely broken right?

**Comment by SimbaZockt** [comment]
Looks like

**Comment by ScuroK** [comment]
i am not a dev but i guess its because of the changes in the item id/names system in 1.8.

**Comment by FlyingPikachu** [comment]
That's entirely possible. My current suspicion is it wants an ENUM value (thus the capital letters). Just need to find where.

**Comment by ScuroK** [comment]
good luck mate :)

**Comment by SimbaZockt** [comment]
Just good luck!

**Comment by ScuroK** [comment]
How is it going?

**Comment by Leescar** [comment]
Pikachu I love you for updating and putting time into this
If I could help ironing out this issue I would love to, though I can't seem to figure it out.
On the other hand I might have a lead on something that could help.

The plugin Shopkeepers which is at 1.8 currently.
https://github.com/nisovin/Shopkeepers

It uses some system to identify and store item information, lore, tags and such.
While they use a interface I feel as though the system is very similar in the fact that it accepts and stores item details and can be specific on an item for accepting trades and rewarding trades.

Much like quests it doesn't have any dependencies and uses in game interface.
Just thought might help.

**Comment by FlyingPikachu** [comment]
Fixed in Quests 2.1.6. Thanks!

@Leescar I appreciate that, however, while the plugin in your link and many others have similar interfaces, the code varies greatly. In the future, please consider making a pull request! (:

**Comment by ScuroK** [comment]
Seems to work now! Thank you!

**Comment by ScuroK** [comment]
Seems to work now! Thank you!
