### ISSUE TITLE
Unabled to Interact with Citizens2 NPCs

### ISSUE THREAD

**Issue by Formula350** [FlyingPikachu/Quests#60]
CraftBukkit 1.8 R0.1
Quests v2.3.3 (build 61)
Citizens 2.0.14 (build 1204 - last build I could remember //not// having the issue)
 -  Citizens Addon - Sentry (build 24)
 -  Citizens Addon - Depenizen (build 245)
 -  **not loaded** Citizens Addon - Denizen (build 1558 - I'm 90% certain issue remained when used)
WorldGuard 6.0.0 (build 1590)
ProtocolLib (build 83)
PacketWrapper (build.... 3? Not even sure why I'm using it, companion to ProtocolLib I believe)

Those are all the relevant plugins I can think of that I can possibly think of which could even remotely tie into the issue.

Issue being: Unable to interact with Citizen NPCs to accept quest (and turn in items). 
Config is set to allow acceptance of quests via command (somehow the cause?)

Config: http://dev.bukkit.org/paste/s0mk4h9lr2zgq8xv/
Quests: http://dev.bukkit.org/paste/xferz1ayubd9wlov/

Two strange variables I haven't been able to quite figure out... I have a Test Server which, aside from the maps (since my main server's is quite literally massive), it otherwise has basically all the same plugins or a few more. It runs on the same machine though so it is all the hardware and software, same Bukkit version, and yet the last time I attempted to turn on the Quest Effects on the main server it would error the plugin but that feature works just fine on the Test server. The erroring on main occurred back before 2.0.0Alpha, but it DID work once upon a time (I want to say it broke when switching to 1.7 in Jan of 2013). It doesn't bother me, but thought worth mentioning. The other strange thing is that new players still haven't been generating a UUID file for Quests, which ends up spamming console, but I did find a solution. Our new-player group selection room utilizes command blocks and so we just added another one that fires off the questadmin command to give the player a certain quest right away, in turn generating the file and ceasing the errors suggesting we blacklist the UUID.

**BONUS BUG:** Such a tiny thing, hope you don't mind me putting it here, given it isn't anything "game breaking". One of my admins said that for the Kill Mobs stage, you aren't able to select "Wither Skeletons", only Wither Boss.

**Comment by Formula350** [comment]
Well I seem to have figured out the issue...

I went back and forth between the various folders of the plugins listed above, noting the changes (if any). The notable ones were in the Quests config, with the items NOT on the Test Server's config being the Snoop (which I removed from it's config as a test since one of your change logs said disabled that), and then that Quester Blacklist UUID of:
- d017ee3a-cf8b-255c-891d-fb22af945b03
Now the reason I had added that was because, at one point, that UUID came up as an error. Pre-Quests 2.x, when it used the Player Names, I had to blacklist a number of NPC "bosses" that players would fight to complete quests. I figured I'd have to do the same, so when that UUID showed up (coincidentally while players were fighting one of the bosses), and the UUID converter said no suck user, naturally I assumed that it was our "The Minotaur" NPC and so I blacklisted it... Well I stuffed in the Snooper into the Test Server's quests config, reloaded things, and no issue. Dropped that UUID in, reloaded.... can't interact with NPCs now! Removed, reloaded... fixed! 

Not sure why that's happened, or what that UUID pertains to (internal mojang reference for a basic player-entity?), but that does in fact reproduce the issue... at least on my end.

Since that is solved now I can get back to nabbing the latest and greatest builds :P

While this issue is resolved, I'll leave it for you to deem Closed, in case there is some underlying issue and you'd like me to try stuff on my end.
-Formula350

**Comment by FlyingPikachu** [comment]
Interesting. Glad you were able to resolve the issue. As for the new player issue, perhaps you have 'generate-files-on-join' set to 'false'?

And for your bonus bug, I'm afraid Wither Skeleton is simply not an option in that prompt. This is because they are a variation of Skeleton (in the same sense that Red Wool is a type of Wool) and such variations aren't supported. Feel free to request that in a new ticket.
