### ISSUE TITLE
Error of ItemFlags on items loaded from hand

### ISSUE THREAD

**Issue by trungbmt** [FlyingPikachu/Quests#604]
Quests 3.5.7

No error occurred until I used /questadmin reload or restart the server.

Item: https://pastebin.com/iRCEfWuP

Console error (when /questadmin reload)
https://pastebin.com/D89wfnBW

**Comment by FlyingPikachu** [comment]
Duplicate of #569

This was fixed in c07e361ec7ed381e57aebbd2eb9c55338a611dd2 so try the latest dev build at http://ci.ac3-servers.eu/job/Quests/

**Comment by trungbmt** [comment]
item: https://pastebin.com/yp9xFcqq

**Comment by FlyingPikachu** [comment]
@trungbmt Your Diamond Sword probably shouldn't have a data value of 43. Try setting it to 0.
