### ISSUE TITLE
deliver Item NBT Tag

### ISSUE THREAD

**Issue by trungbmt** [FlyingPikachu/Quests#609]
Quests version: 3.5.9-b586
Server version: spigot 1.12.2

I encountered an error when creating "items-to-deliver" stages with items using NBT Tag Hide flag, unbreakable
Creating a successful stage but when delivering the item, the NPC does not receive it
img: https://imgur.com/a/FbVOA6N

I tried to set the data value to 0 but it still doesn't work (this I don't want, because I use custom texture packs so the data value is very important, I'm not allowed to change them)

item: https://pastebin.com/yp9xFcqq

**Comment by FlyingPikachu** [comment]
If the data/durability value isn't the issue, then it must another item attribute, as the "not a required item" message only occurs when the item in hand doesn't match the one on file _exactly_. They must be identical down to the same lore and ItemFlags.

I'll see if I can update the plugin soon to be more specific about what doesn't match.

**Comment by trungbmt** [comment]
It can't be another item, because I hold that item and load the item in hand, then reload the plugin and take quests
The item I had earlier was still in hand and delivered to npc, so it can't be different.

**Comment by trungbmt** [comment]
okay, hope it will be fixed. <3

**Comment by FlyingPikachu** [comment]
@trungbmt I've just added a feature in 90511df08fff7d1a494d1468d6427aa0bc694630 that should show the player the reason if an item doesn't match when trying to deliver it. Please update to the following build (once available) and let me know what the Quests says that the reason is:

http://ci.ac3-servers.eu/job/Quests/589/

**Comment by trungbmt** [comment]
It has shown the difference about
data
item flags
unknown
But obviously the item I delivered to npc is the item that I loaded the item in hand.
You can see video:
https://vimeo.com/309242426

**Comment by FlyingPikachu** [comment]
From your video are the following strings:

> The difference is '<data'.
> The difference is 'item flags'.
> The difference is 'unknown'.`

The first line about '<data' and the last about 'unknown' are both errors on my part which I'll fix later, so ignore that. However, the plugin thinks that your item flags do not match up. Will investigate soon.

**Comment by trungbmt** [comment]
okay, i will wait

**Comment by trungbmt** [comment]
thank you

**Comment by trungbmt** [comment]
Items: https://hastebin.com/edewipuqes.rb
I discovered that when I delivered the item with the same flag item to the npc -> they did not receive it
but I delivered the item without item flag -> then they received it

Although in items-to-deliver contains item flags, they only accept items without a item flag

**Comment by FlyingPikachu** [comment]
@trungbmt Please give http://ci.ac3-servers.eu/job/Quests/600/ a try once available and let me know if it resolves the issue.

**Comment by trungbmt** [comment]
okay, thanks you.
It has been fixed
