### ISSUE TITLE
chat error spam

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#61]
In your issue, please include:

Quests versions 2.9.2

- Description of problem & console errors
Async Chat Thread - #1/ERROR]: [Quests] currentStage was null for b6d6621e-803e-4643-a5aa-f3a662d84b06 on chat
[08:21:49] [Async Chat Thread - #1/ERROR]: [Quests] currentStage was null for b6d6621e-803e-4643-a5aa-f3a662d84b06 on chat

**Comment by FlyingPikachu** [comment]
Please post the contents of `Quests/data/b6d6621e-803e-4643-a5aa-f3a662d84b06.yml` in a Pastebin

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
