### ISSUE TITLE
gps support for deliver items

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#610]
**What does your feature do?**
GPS support for deliver item quest objectives
**How would people use it?**
Well i would like support so when you have a deliver items objective the gps works with it so players can know where the quest npc is that they need to deliver items to.

**Comment by FlyingPikachu** [comment]
Fix will be available in http://ci.ac3-servers.eu/job/Quests/593/

Note that recent commits have contained some major structural changes to the plugin which have not been tested yet, so use the linked build at your own risk (consider backing up your Quests folder first)!
