### ISSUE TITLE
./quests info permission node not working

### ISSUE THREAD

**Issue by DragaoNimhe** [FlyingPikachu/Quests#613]
**What is your Quests version / build number (do _not_ say "latest")?**
3.5.8 (dev updated version)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Currently the /quests info command is only checking to see if people have the quests.quests permission, not the quests.info permission listed on the wiki. The quests.info permission doesn't seem to do anything at all. We'd appreciate a fix for this, as we'd like our playerbase to not be able to obtain detailed info about the plugins we use.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Unrelated to quests.yml.

**Comment by DragaoNimhe** [comment]
Comment for clarity: we are on 3.5.8-b581

**Comment by FlyingPikachu** [comment]
Use http://ci.ac3-servers.eu/job/Quests/590/

**Comment by FlyingPikachu** [comment]
Use http://ci.ac3-servers.eu/job/Quests/590/

**Comment by DragaoNimhe** [comment]
Thank you so much!
