### ISSUE TITLE
/quests top requires a value when wiki suggests this is optional

### ISSUE THREAD

**Issue by DragaoNimhe** [FlyingPikachu/Quests#614]
**What is your Quests version / build number (do _not_ say "latest")?**
3.5.8 (dev updated version)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
As stated in the title, the /quests top command requires a numerical value such as /quests top 10 when typed. The wiki doesn't mention a value being required, so I believe this to be a bug. Apologies if I should have posted this as a feature request instead, but it would be great to just be able to type /quests top and have it bring up a list of the top 10 players without having to specify a value. Thanks for your time!
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by DragaoNimhe** [comment]
Comment for clarity: We are on 3.5.8-b581

**Comment by FlyingPikachu** [comment]
The usage in the Wiki is wrong. However, I will look into making a number optional.

**Comment by FlyingPikachu** [comment]
http://ci.ac3-servers.eu/job/Quests/590/
