### ISSUE TITLE
Questsadmin give <player> <quest> - 'Quest Not Found'

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#62]
When trying to give a Quest to a player when the Quest name includes spaces, I get the following message 'Quest Not Found'.

I've tried surrounding the Quest name in " and ' but no luck.

**Comment by Formula350** [comment]
Yea, I can confirm that this has been an issue for a loooong time. I've been considering making a request for a solution to allow specific selection of quests that you are wanting.

Here is the work-around I've found, but which has it's limitations (hence needing my idea). You can give a quest via questadmin if you only use 1 unique word that is in your quest. For example, we have a quest called Bronze of the Gods. If we try to type in "/questadmin give <player> Bronze of the Gods", it doesn't work. HOWEVER, if we type in "/questadmin give <player> Bronze" then it works no problem!

The limitation is if you have multiple quests with the same name. For example we have a quest chain that forks, and the player picks a path... What that means is we have zero unique words to solo out the quest, as both forks end in Part-1, Part-2, Part-3 and each part has the same phrase before it. So puttin in Part-1 would simply select one and not the other.

My suggestion is to make each quest carry with it the number that it is given in "/quests list" and that is it's unique identifier in /questadmin as well. That, or allow for tab-completing quest names, but that no doubt would also solve being able to type in the full name *shrug*
