### ISSUE TITLE
Quests not properly reading Hide Enchants ItemFlag when adding an item as a reward

### ISSUE THREAD

**Issue by frost-byte** [FlyingPikachu/Quests#626]
**What is your Quests version / build number (do _not_ say "latest")?**
3.59-b586
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Create a quest and add a reward using an item in your hand that has meta/lore using the Hide Enchants Itemflag.  When you receive the item, after completing the quest, the enchants are visible.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
This is an example of a reward that has an invalid item created when it is rewarded.
```yaml
- name-IRON_NUGGET:amount-32:enchantment-DURABILITY 1:displayname-§rIron Coins:lore-§r§6Currency:meta-type-UNSPECIFIC:enchants-{DURABILITY=1}:ItemFlags-[HIDE_ENCHANTS]
```
I must be mistaken, but I was under the impression that you had fixed this issue? Does a custom reward have to be used for something like this?

**Comment by FlyingPikachu** [comment]
I was able to replicate this on Quests 3.5.9 and the problem likely stems from how flags are being handled in ItemUtil. What is your MC server version?

**Comment by FlyingPikachu** [comment]
Fixed in http://ci.ac3-servers.eu/job/Quests/606/
