### ISSUE TITLE
Build 3.6.0 on Enable Issues

### ISSUE THREAD

**Issue by frost-byte** [FlyingPikachu/Quests#628]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.0, built by me
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Your onEnable method needs to instantiate the settings and depends fields before initializing them.
Also, when you declare your Lang instance, you construct it before the depends are initialized.
You should initialize your dependencies before constructing the lang instance.

I've made these changes locally and the plugin now loads. (Without them the pluginManager throws an NPE and unloads the plugin)

**Comment by FlyingPikachu** [comment]
Thanks for pointing that out! I haven't actually tested any 3.6.0 builds as it's a pretty major refactoring (which I probably should've made a new branch for, but I digress). I'd appreciate if you'd just submit a Pull Request, but if not I'll try to get around to fixing it soon.

**Comment by FlyingPikachu** [comment]
Use http://ci.ac3-servers.eu/job/Quests/605/
