### ISSUE TITLE
Break Block not counting

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#63]
In your issue, please include: Spigot 1.11.2 and Quests 2.9.2

Hello again. The break blocks stage is not working. This is my quest: https://pastebin.com/vQNeQm7G

and it never counts any broken blocks. When I try to change the quest to just turn in I'm getting this error:
https://pastebin.com/6tcp7MJp and my game freezes, can't get out of the editor.

**Comment by FlyingPikachu** [comment]
Duplicate of #62

**Comment by FlyingPikachu** [comment]
Fixed in http://ci.ac3-servers.eu/job/Quests/147/
