### ISSUE TITLE
/events giving 'NULL'

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#63]
I try and edit some events and I type /events and I just get NULL back in the chat.

Update: I did /quests events and that produces the Events Editor. This should be clearer on your Wiki page as a command I think, just letting you know!

**Comment by FlyingPikachu** [comment]
It looks like _Blackvein_ removed this command at some point but did not update his wiki (which I used as a reference). I have updated the plugin.yml and will update the wiki upon the next minor release. Thanks!
