### ISSUE TITLE
Quest save Error

### ISSUE THREAD

**Issue by Casb02** [FlyingPikachu/Quests#634]
Hello. 
I get an error if I want to save a quest. It says: An error occurred whil saving.

Quests version: 3.5.7
Screenshot: http://prntscr.com/m6n9mc

**Comment by FlyingPikachu** [comment]
Update to 3.5.9 and post back if the issue persists.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Casb02** [comment]
Thx!
