### ISSUE TITLE
Cannot deliver custom potions to NPC.

### ISSUE THREAD

**Issue by RednedEpic** [FlyingPikachu/Quests#635]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests Version: 3.5.7-b573
Server Version: Paper version git-Paper-1452 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
A quest with a custom-colored potion will not work. It seems to work fine with normal potions, but it appears (from my testing) when `|water:custom-color-Color:[rgb0x000]` is added to the end, it entirely bugs out. I added all these items VIA the ingame Quest Editor. 
https://pastebin.com/WH3SA1Dk

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/KnsTG7kr 
(Kill EpicBoss is my custom quest objective I made and I know there is no error there)

**Comment by FlyingPikachu** [comment]
Use http://ci.ac3-servers.eu/job/Quests/609/ once available (bearing in mind recent commits may break integration with some modules).

**Comment by RednedEpic** [comment]
Alright, thank you very much!
