### ISSUE TITLE
Show a title message when you reach a location

### ISSUE THREAD

**Issue by MrCobayo18** [FlyingPikachu/Quests#638]
Hello! Congratulations for this amazing plugin :)

I have a question. How i can set a title message when a player reach a location? 

This is my quests. I want show a message to this player when reach any location.

    stages:
      ordered:
        '1':
          locations-to-reach:
          - world 33.0 147.0 -274.0
          - world 105.0 52.0 -189.0
          - world -79.0 107.0 -367.0
          - world -105.0 43.0 -335.0
          reach-location-radii:
          - 5
          - 5
          - 5
          - 5
          reach-location-names:
          - gryffindor
          - hufflepuff
          - ravenclaw
          - slytherin
    rewards:
      money: 30
      commands:
      - give <player> diamond 5

**Comment by FlyingPikachu** [comment]
Use the Events Editor (`/quests events`) and "Set commands to execute" using something like `title <player> YourTitleMessageHere`. Then, edit your quest's stage to include the event as a "Finish Event".

**Comment by MrCobayo18** [comment]
Finish message only works when you reach all locations. I want differentes messages when you reach a specific location.

**Comment by FlyingPikachu** [comment]
@MrCobayo18 I see what you mean. To my knowledge, that's not possible at this time. However, you're welcome to open a new issue in the form of a request.

**Comment by MrCobayo18** [comment]
Ok, thanks you so much
