### ISSUE TITLE
Play event by every location reached

### ISSUE THREAD

**Issue by MrCobayo18** [FlyingPikachu/Quests#639]
**Hello! I have a Quest with 4 locations to reach, my idea is play and event when you reach one location, not only when you reach all locations.**

What does your feature do? **Option for add a event between locations to reach.**

How would people use it? **Adding a "event: x" between locations.**

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests. Currently you can have one reach-location objective per stage and just run an Event between each stage. Running Events between objectives would be cool, but frankly isn't worth the time/effort when the method I just mentioned produces the same effect.
