### ISSUE TITLE
Quest item can be removed from GUI

### ISSUE THREAD

**Issue by Ironic8b498** [FlyingPikachu/Quests#64]
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
Spigot 1.11.2  
Quests-2.9.2

- Description of problem & console errors
when you try to accept the quest it allows you to remove block from gui menu and not start, no errors. NPC has 3 other quests which work fine

- Hastebin of quest from quests.yml for testing
https://paste.md-5.net/bayugoguna.sm

**Comment by FlyingPikachu** [comment]
Caused by https://github.com/MilkBowl/VaultAPI/issues/36

Working on a fix.

**Comment by FlyingPikachu** [comment]
Fixed in http://ci.ac3-servers.eu/job/Quests/149/
