### ISSUE TITLE
Save Quests Error

### ISSUE THREAD

**Issue by trungbmt** [FlyingPikachu/Quests#641]
Version Quests: 3.6.0-b610
Console: https://hastebin.com/bemizamuho.md
Quests: https://hastebin.com/oqegoyegum.rb

i can't save quests after create it, nothing happens when i choose to save quests -> Yes
I realized the error was in rewards command
```
    rewards:
      commands:
      - lp user <player> permission set quests.6 sdo
```
Because when I delete the rewards command, I can save them without error

**Comment by FlyingPikachu** [comment]
I wasn't able to replicate this error after adding that reward to a new quest or by manually inserting it into a saved one via the config. I was able to save and edit my quests without issue and restarting Quests with `/questadmin reload` and restarting the server caused no problems.

To proceed, I'll need the exact steps you took to cause this error, in detail.

**Comment by Borc55** [comment]
Same problem, I'm running build #610 .
Error in console: https://pastebin.com/DGPdTLRt
Quest giving me trouble: https://pastebin.com/sBrVg4cZ

After a series of tests (editing file, reloading, going in editor and trying to save the quest) I found out when it allows me to save the quest.
When I remove command rewards from file and reload. Money reward seems to be okay.

**Comment by Borc55** [comment]
Steps to reproduce:
Create a test quest with one command rewards, save it, open quests.yml file, manually add another command reward, reload quests, open quest in editor, try to save, fail. Result above.
You are welcome.

**Comment by FlyingPikachu** [comment]
@Borc55 Thanks for your input. Your steps did not produce an error for me, using only the quest you provided and following your steps precisely. Did you modify anything in the editor before saving?

Also, I should note that while editing the quests.yml for reasons other than the debugging is not recommended, editing the file while the plugin running is _very_ not recommended. I'd appreciate if @trungbmt would provide the steps he followed for comparison.

**Comment by FlyingPikachu** [comment]
Although I have no way of testing it, I've pushed a potential fix. Please try the following dev build (once available):
http://ci.ac3-servers.eu/job/Quests/611/

**Comment by FlyingPikachu** [comment]
OP has chosen to continue this in a new issue #644

**Comment by FlyingPikachu** [comment]
In reference to my last comment, I'd mistakenly confused OP with another user. Re-opening.

@trungbmt Please let me know if the latest dev build resolves this issue:
http://ci.ac3-servers.eu/job/Quests/629/

**Comment by FlyingPikachu** [comment]
Thanks for your patience. The following build should resolve this issue per #655 

http://ci.ac3-servers.eu/job/Quests/634/

**Comment by trungbmt** [comment]
okay, It works very well, thank you <3
