### ISSUE TITLE
Error in console upon player quit

### ISSUE THREAD

**Issue by DragaoNimhe** [FlyingPikachu/Quests#649]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.0-b620
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When a player logs off, it creates a large error message in console.

I believe that this error also can sometimes cause quests to bug and become unable to be completed until the player quits and retakes the quest. It seems to be more likely that quests will bug if players take multiple at once, but that's just a theory.

Log of error in console: https://pastebin.com/YNREh2GU
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
N/A

**Comment by FlyingPikachu** [comment]
Fix will be soon be available here: http://ci.ac3-servers.eu/job/Quests/622/

**Comment by DragaoNimhe** [comment]
Can confirm fixed, ty very much for your quick reply and solution as usual. You're the best <3
