### ISSUE TITLE
Finish-Event not working

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#65]
I have tried to put a finish-event on one of the stages for a Quest, for example giving an item to the player. But it does not work when the player completes that stage, the only way I got it to work was to make the event a start-event at the beginning of the next stage.

I have also tried this with events that include teleporting the player, applying effects and despawning npcs, the only way it works is to make it a start-event.

**Comment by Leescar** [comment]
This is also the same for mob spawning as well

**Comment by whoshenry** [comment]
Update: I think this is only when there is more than one stage, it seems to work when a finish-event is on a Single Stage Quest, but not multiple ones.

**Comment by FlyingPikachu** [comment]
Cannot duplicate. Please post the related quest.

**Comment by FlyingPikachu** [comment]
Sorry whoshenry, could you throw that up on pastebin or something? I can't seem to get the file formatted properly with no indents.

**Comment by whoshenry** [comment]
Sure, the quests entry - http://pastebin.com/2Jmgj1EC and the events entry - http://pastebin.com/8Vgqvhdj

**Comment by FlyingPikachu** [comment]
I was able to complete the quest using the information you provided (I only changed the NPC IDs to some I had already spawned). http://i.imgur.com/QpccXLn.png

**Comment by FlyingPikachu** [comment]
Closing (tested working). If the issue persists, please open a new ticket.
