### ISSUE TITLE
[BUG]  questeditor closed

### ISSUE THREAD

**Issue by LinearBotSystems** [FlyingPikachu/Quests#65]
My setting

-Spigot 1.12 , Quests v 2.9.2, Citizen2

- When I try to create a stage with block use ( ID:379  Brewing Stand in my case)  or simply with out adding anything when I press 5 for Done the quests editor close completely.

**Comment by FlyingPikachu** [comment]
When you Set block names, what are you inputting? I was able to enter "Brewing_Stand" without any issues.

**Comment by LinearBotSystems** [comment]
It doesn't depend on block name or ID when I input the 5 for done it kicks out of the editor

**Comment by FlyingPikachu** [comment]
I'd still like to know exactly what you typed in so I can (hopefully) recreate the scenario, because the editor continues to function for me.

**Comment by LinearBotSystems** [comment]
First : Okay what I try to do is making a quest in which somebody brew with pufferfish the 'Potion of Water Breathing'. I tried a workaround but haven't any luck because because Quests seems unable to difference between different potions. Which will cause problems me int the future  because I want to give the player as reward 4x more. 

I tried the USE Block option in the beginning and I try to edit it at the moment because there seems no other way.

Here my quests:
[quests.zip](https://github.com/FlyingPikachu/Quests/files/1167606/quests.zip)

What I do is now clearing the potion and then simply go with the 4 into the USE BLOCK then with  1 entering the Brewing_Stand and then say done with the 5 which does on display nothing, the next 5 I try ends in the chat. See here : 

[2017-07-22 7](https://user-images.githubusercontent.com/25264743/28494376-cdc57e6e-6f2c-11e7-82e4-bc1080da1a61.png)

**Comment by FlyingPikachu** [comment]
@LinearBotSystems Should be fixed in latest commit- http://ci.ac3-servers.eu/job/Quests/151/

**Comment by LinearBotSystems** [comment]
Sry not really but the behavior has changed if I only enter point 1(name) and then 5  it warns me about I should enter the use amount in 2  when I have done this and enter the 5 again its kick me out again like before.

But if I'm entering the (1)name and (2)use amount in one go Minecraft crashes with an Internal NULL Pointer Exception ([22:33:54] [Server thread/INFO]: Fiercesoulking lost connection: Internal Exception: java.lang.NullPointerException)

**Comment by FlyingPikachu** [comment]
I see the new issue and will resolve it later tonight.

**Comment by FlyingPikachu** [comment]
http://ci.ac3-servers.eu/job/Quests/152/

**Comment by LinearBotSystems** [comment]
sry seems not to work either.

**Comment by LinearBotSystems** [comment]
Found it myself in CreateStagePrompt.java in line 1280 
`LinkedList<Integer> elements = (LinkedList<Integer>) context.getSessionData(pref + CK.S_USE_DURABILITY);
					for (int i = 0; i < missing; i++) {
						elements.add(0);
					}`

must be `LinkedList<Integer> elements = (LinkedList<Integer>) context.getSessionData(pref + CK.S_USE_DURABILITY);
					if (elements == null) {
						elements = new LinkedList<Integer>();
					}
					for (int i = 0; i < missing; i++) {
						elements.add(0);
					}`

The only thing I don't understand is what does durability in this context mean ?

**Comment by LinearBotSystems** [comment]
There is still one thing when I browsed the code my Oxygen Eclipse gives huge error warnings about  NPCKillListPrompt() being unreachable because it is a private internal class you might clean this up too.

**Comment by FlyingPikachu** [comment]
http://ci.ac3-servers.eu/job/Quests/153/

@LinearBotSystems Feel free to open a separate issue for your IDE warning, including the line number.
