### ISSUE TITLE
On Server start up error

### ISSUE THREAD

**Issue by CaptainAlienHD** [FlyingPikachu/Quests#653]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v3.6.0-b630
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/QYgwBwNC
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
I dont have any other file than config.yml generated with following content in it:

# See https://github.com/FlyingPikachu/Quests/wiki/Configuration
npc-effects: {}

**Comment by FlyingPikachu** [comment]
Are you using the GPS plugin? If so, which version number?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CaptainAlienHD** [comment]
Nope i dont have it

**Comment by FlyingPikachu** [comment]
It is optional! Use the following build to resolve the issue, once available:
http://ci.ac3-servers.eu/job/Quests/631/
