### ISSUE TITLE
[Feature Request] Commands to check and manipulate the quests a player has completed

### ISSUE THREAD

**Issue by PikachuEXE** [FlyingPikachu/Quests#66]
I am currently building a server with many "branches" of quests
But I find it hard to debug the quests since I cannot check and manipulate the quests a player has completed (myself and some other admin)

I think the function that can be implemented more easily is the checking one, since `/quests stats` already has such feature (but limiting to command sender himself)

**Comment by Formula350** [comment]
I also was curious about such a thing, as currently for me to do this requires me to:
-/whois the player (as we have Roleplay names and so no one has their MC name)
-Go to mcuuid.net and convert their name to UUID
-Open their Data file for that player

For me, it's annoying, but I have multiple monitors so it isn't TOO much of a task given that fact. Mainly I just hate having to convert to UUIDs now :( (Anyone know of a plugin that appends their UUID into /whois or simply offers a command like /uuid to auto-resolve it?)

To help the OP out, he **did** add a quest purge command to allow you to clear them via command, so while that doesn't give you the accuracy you're after, it can at least help you do the debugging by purging your own. After which point you would just gave to give yourself the quest(s) that are required to pick up where you left off.
