### ISSUE TITLE
[QUESTION] - Events.yml

### ISSUE THREAD

**Issue by blek-id** [FlyingPikachu/Quests#66]
Hi! I wanted to know if there's a more in-depth guide on events.yml?
All documentations found are only on the default config.
What do I do if I wanted to for example smite a player, or run a command based events?

**Comment by FlyingPikachu** [comment]
There is not, bar tutorials you may find elsewhere online.

However, I have updated the Wiki page to include a bit more information:
https://github.com/FlyingPikachu/Quests/wiki/Configuration

Thanks for your interest in Quests!
