### ISSUE TITLE
Can't add event>?

### ISSUE THREAD

**Issue by DennisFusha** [FlyingPikachu/Quests#662]
Quests 3.6.0

I just started using quests and wanted to add an event I made earlier , but when I type in 16 it just shows me the list again it doesn't give me an option to type in my event.

https://gyazo.com/b08832e890c4ad61c66602a97a0399d0

**Comment by DennisFusha** [comment]
> Thanks for your report. Any console errors?

Nope, no errors just doesn't work

**Comment by FlyingPikachu** [comment]
Just realized that the option is greyed-out. When the text is grey in color, that means it isn't available. In your case, this is because you haven't created any events yet. Use the Event Editor first by running _/quests events_ in-game.

**Comment by DennisFusha** [comment]
> Just realized that the option is greyed-out. When the text is grey in color, that means it isn't available. In your case, this is because you haven't created any events yet. Use the Event Editor first by running _/quests events_ in-game.

I made about 7 events, and it's still grey..

**Comment by FlyingPikachu** [comment]
@DennisFusha Did you reload the plugin with _/questadmin reload_? If you did and they’re still not showing up, post your server’s startup log through Pastebin.com

**Comment by FlyingPikachu** [comment]
One more thing - you must have at least one objective set to use events. In other words, you cannot have a stage with _only_ events.

If that doesn't resolve the issue, post the aforementioned log to re-open this ticket.
