### ISSUE TITLE
Feature to disable noMoreQuest:"message" for any involved NPCs / And variables for requirements in quests.yml / Extra Quest Name & GUI-ITEM if the requirements are not met

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#663]
Spigot: 1.8.8,
Quests: 3.6.0-b637

"Feature to disable noMoreQuest:"message" for any involved NPCs"
For NPCs that not giving quests their only involved with an another NPC for an delivery for example.
NPC 1 gives a quest to NPC 2 and NPC 2 makes the noMoreQuest message but the NPC not having quests set.

"And variables for requirements in quests.yml"

> example:
>     requirements:
>       items:
>       - name-DIAMOND_HELMET:amount-1
>       - name-DIAMOND_CHESTPLATE:amount-1
>       - name-DIAMOND_LEGGINGS:amount-1
>       - name-DIAMOND_BOOTS:amount-1
>       - name-DIAMOND_SWORD:amount-1
>       remove-items:
>       - false
>       - false
>       - false
>       - false
>       - false
>       quests:
>       - (0) Farmmap verstehen & benutzen! (Tutorial)
>       fail-requirement-message: §cYou need to complete >neededquest> and the Items >neededitems>

"Extra Quest Name & GUI-ITEM if the requirements are not met"

example: *Quest requirements are not met* and another icon like barrier.

**Comment by FlyingPikachu** [comment]
Thanks for your report. In the future, please open separate issues for each request.

To hide the NPC message, just set it to `noMoreQuest: ""`

For branching requirements, extra quest names & GUI items, this would fall under #454 so please feel free to contribute there.
