### ISSUE TITLE
MythicMobs objectives no longer work.

### ISSUE THREAD

**Issue by Klawdek** [FlyingPikachu/Quests#667]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Error in console and mythic mobs no objectives longer works.  I used latest version available for the mythicmobs module which is labeled 3.27 to 3.5.9 the link for 3.6.0 and above is a dead link.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/8rZuJn1r

**Comment by tiradorus** [comment]
The last version Of MMObjectives is compatible with Dev quests ... i use it with Quests 3.6.1 Dev build 644

**Comment by FlyingPikachu** [comment]
Although @tiradorus didn't set up the link correctly (clicking it takes users to the wrong page), copy and pasting it into your browser will bring OP to the right place.

Solution is to download the most recent version of the module.
