### ISSUE TITLE
 WARN Task #554 on startup

### ISSUE THREAD

**Issue by SoraShiunin** [FlyingPikachu/Quests#668]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v3.6.0-b631
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
On startup I get this error: https://pastebin.com/U1qHbqAZ
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Not applicable

**Comment by FlyingPikachu** [comment]
This was resolved in 3.6.1 - please upgrade.
