### ISSUE TITLE
Plugin crashes when entering new quest name

### ISSUE THREAD

**Issue by bsickinger** [FlyingPikachu/Quests#669]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I can type /quests editor and enter the option to create a new quest
When I enter the name of the quest in this case "TestQuest" these console errors appear:
https://pastebin.com/vG30McTP

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by bsickinger** [comment]
This is on Spigot 1.13.2

**Comment by bsickinger** [comment]
And actually, it just stops the menu from displaying, If I look up the menu options on the wiki, I can still navigate through the menu. most of the rest of the menu works as expected

**Comment by FlyingPikachu** [comment]
Thanks for using Quests. Please try the following build, once available:

http://ci.ac3-servers.eu/job/Quests/646/
