### ISSUE TITLE
Block break for Gold Ore and Coal Ore is not registered.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#67]
Spigot 1.12 (but it give the same result on 1.11.2)
Quests 2.9.4 (build 149)

The problem is that when trying to do a quest where I have to break Gold Ore or Coal Ore, it does not register and thus not being able to finish the quest. This also goes for Sugar Cane.
https://pastebin.com/hAKpajfE

**Comment by FlyingPikachu** [comment]
You have both set with a durability of 1, when the only valid durability is 0.

**Comment by OwnAgePau** [comment]
Are there even blocks where durability is needed? Because its confusing.

**Comment by FlyingPikachu** [comment]
See #68 for the answer to that question.
