### ISSUE TITLE
Console error when loading quests config

### ISSUE THREAD

**Issue by Klawdek** [FlyingPikachu/Quests#670]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Reload quests cnfig
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/nefgQr6S

**Comment by FlyingPikachu** [comment]
Use the following build once available:

http://ci.ac3-servers.eu/job/Quests/645/
