### ISSUE TITLE
adding new translations strings

### ISSUE THREAD

**Issue by waiching514** [FlyingPikachu/Quests#673]
adding new translations strings with Paeties
When Paeties plugin create a party:
"Players added to this party may perform quests together!"
delete party:
"The quest [arty was disbaned"
"you can no longer perform quests with party"

people can edit this to other lang

![image](https://user-images.githubusercontent.com/29138111/52174194-897c9b80-27cb-11e9-803e-7d237a7c4025.png)
![image](https://user-images.githubusercontent.com/29138111/52174256-3eaf5380-27cc-11e9-8bde-32c11c8f1697.png)
and also having more about Paeties strings: https://github.com/FlyingPikachu/Quests/commit/c99159993659099f9407dd4f53be55e3dbf211bb

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests. The next release on Spigot will make this possible.
