### ISSUE TITLE
console error 

### ISSUE THREAD

**Issue by djyee** [FlyingPikachu/Quests#676]
hello i setup the plugin for the first time there is no setting file(i mean its generated for the first time) and in console i got this error : 
https://pastebin.com/s601pbmE

**Comment by FlyingPikachu** [comment]
Thanks for your report. I'm unsure whether you meant to say that quests.yml was not generated, or if it was generated improperly. For now, I'll push a commit which will output a more human-readable error.

**Comment by djyee** [comment]
plugin is working fine only thing i got is that annoying error :D 
i like to see my console clean of errors :D
