### ISSUE TITLE
Question: How to get break block to also work for metadata blocks.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#68]
Spigot 1.12 (but it give the same result on 1.11.2)
Quests 2.9.4 (build 149)

The problem is that I want the player to break seperate logs, but I can't find the correct name or ID to enter in the field, when I try log:1, sprucelog, log_spruce or whatever combination it doesn't work.

My first thought is, with delivering blocks you can use "item in hand" to get the correct item/block, why not do the same for blocks and check whether it is a block. Or give an option to set the metadata (maybe a seperate line). Or maybe there is allready a way to do this, but it is unclear.

**Comment by Calski19** [comment]
I'm also having the same issue.
Log and Log_2 are accepted as ID's but I can't seem to find how to add spruce/birch

**Comment by FlyingPikachu** [comment]
It should be as simple as using the durability option.

**Comment by OwnAgePau** [comment]
"should be as simple" but then tell me how exactly it works?

**Comment by FlyingPikachu** [comment]
For future reference, you'll have better luck getting help with basic Quests functions in the discussion thread on Spigot, Wiki and tutorial videos.

In the same editor page as where you entered the block name, there is an option to enter block durability. If left empty, this will default to 0. You must manually enter another number if you would like variants such as Spruce Log.
