### ISSUE TITLE
Please fix this bug.

### ISSUE THREAD

**Issue by YxorY** [FlyingPikachu/Quests#68]
Hey,
I found a little bug.
User's and team leader's cant see the particle effect's of the NPC's.
So I hope you can fix this.

-YxorY

**Comment by FlyingPikachu** [comment]
Not enough information. Quests version? Spigot version? Configs?

Also, what is a team leader?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. If your issue persists, please open a new ticket with the requested information.
