### ISSUE TITLE
Error when there is an  npc-ids-to-talk-to: that specifies a non existent NPC

### ISSUE THREAD

**Issue by Klawdek** [FlyingPikachu/Quests#681]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I upgraded from 3.3.4 to 3.6.1.  I did a fresh install of 3.6.1 by deleting the old version and its directories.  Then I took my old quests.yml file and put it back in.,  I also edited the events.yml to add back the one event I had in there.  When I did this I tried to reload the config it throws a big error.  So I switched back to the default config that was generated when I installed and copied and pasted back in each quest until I got to the one that was causing the error.  That quest has an  npc-ids-to-talk-to: that specifies a non-existent NPC.  With the previous version 3,3,4 it was mentioned in console but it did not throw an exception and cause config not to be loaded.  I changed the objective to a mob kill and then it loaded successfully, thus proving that it was indeed the problem.
Here is the config that causes a problem:
https://pastebin.com/xqTR9Q1Q

Here is the corrected config that loads fine:
https://pastebin.com/E0n7rLVB

Here is the console error that happens with the non-existent NPC:
https://pastebin.com/VmazfsN7
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by FlyingPikachu** [comment]
This is not related to NPCs at all, but rather a custom module. Furthermore, this bug has already been fixed. Use the latest dev build available here:
http://ci.ac3-servers.eu/job/Quests/651/
