### ISSUE TITLE
Stage objectives not working in the latest version

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#683]
Quests version 3.6.2-b650

Reach Locations on rightclick not record.

and this on picture somes are missing,

https://abload.de/img/no1aekw4.png

**Comment by FlyingPikachu** [comment]
Your language file needs to be updated.

Go to _/plugins/Quests/lang/en-US_ and either copy the strings from _strings_new.yml_ into _strings.yml_, or just delete both files and let the plugin re-generate them at startup.
