### ISSUE TITLE
MythicMobs Killcounter like the normal / Better German Translation

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#685]
-------------------
the current MythicMobs killcounter is only possible with:

 Notifier msg: %c%/%s%

but pls make it possible to use %c%/%s% in Objective Name: %c%/%s%
thats would be like the normal Killcounter in /quest like 1/5 MythicMobs Zombies.

-------------------
the new german translation is realy bad examples:
German: Artikel = Items = Wrong, Blockiert = Blocks = Wrong,
Right: items = Gegenstände, Blockiert = Blöcke

i would translate German FIles for you. i am german btw .

-------------------
Thanks for the bugfixes :)

**Comment by FlyingPikachu** [comment]
Thanks for the report. I’ll look into the kill counter thing, but you must submit any German language translations on Crowdin - https://crowdin.com/project/translate-quests

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BerndiVader** [comment]
you can use %count% in the objective name

**Comment by kleinesgumi** [comment]
> Thanks for the report. I’ll look into the kill counter thing, but you must submit any German language translations on Crowdin - https://crowdin.com/project/translate-quests
> 
> Sent with [GitHawk](http://githawk.com)

that %count% is that what i need, thanks to @BerndiVader 
my current is now:                 Objective Name: 'Kill MyMobname %count%'
and thats like the normal Killcounter.
