### ISSUE TITLE
Reach Location "Rightclick for location" not work

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#686]
Quests version 3.6.3-b655

on Stageeditor and Reach location says "Right-lick on a block" but nothing happen if i do that,
no message and on 'add' says "You must select a block first".
- No language problem

**Comment by FlyingPikachu** [comment]
Thanks for your report. This will be resolved in http://ci.ac3-servers.eu/job/Quests/658/
