### ISSUE TITLE
Plugins not Linking to quests

### ISSUE THREAD

**Issue by SoraShiunin** [FlyingPikachu/Quests#687]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Start the server. Get Error that WorldGuard / PhatLoots was not linkable.
*08.02 02:20:36 [Server] INFO Enabling Quests v3.6.2-b646
08.02 02:20:36 [Server] WARN WorldGuard was detected, but is not enabled! Fix WorldGuard to allow linkage.
08.02 02:20:36 [Server] WARN PhatLoots was detected, but is not enabled! Fix PhatLoots to allow linkage.*

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Not related but also, I completely reset quests. I only have the 4 default quests.

It happened with Denized but I updated it and it fixed. Im on worldguard 7, so I can't update it more than that, I'm on version 4.2.3 with PhatLoots(the latest released, seems to work).
Note: I'm using Fawe
Startup Log: https://hastebin.com/getagibora.md

**Comment by FlyingPikachu** [comment]
I'm seeing a lot of errors in your startup log, most of which (if not all) are unrelated to Quests. I'd advise trying to fix those first as any one of them could cause problems with other plugins. You could start with updating or removing plugins/elementaleffects.jar

Next, please update to Jenkins build 654 or greater, as the previously experimental WorldGuard support was finalized in that build. If you've done this and continue to have issues, post the resulting startup log below.
