### ISSUE TITLE
When i type any command just show up the quest gui

### ISSUE THREAD

**Issue by TLeung094** [FlyingPikachu/Quests#688]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When i type any command just show up the quest gui
Does not show anything in console just show quest gui in game
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

[Quests.zip](https://github.com/FlyingPikachu/Quests/files/2843627/Quests.zip)

**Comment by FlyingPikachu** [comment]
Closing as OP did not follow issue instructions. Use Pastebin.com to post your quests.yml file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
