### ISSUE TITLE
After Delay start-event not working

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#691]
Quests version 3.6.3-b655

after the delay the start-event not get triggered.

>        .
       '1':
          npc-ids-to-talk-to:
          - 7
          start-message: '&f❝ <npc>: &7&oNun lernst du das Farmmap Item verzaubern, sprich mit dem Schmied er hilft dir.'
          delay: 1
          finish-event: shopclose
        '2':
          use-block-names:
          - BEACON
          use-block-amounts:
          - 1
          use-block-durability:
          - 0
          objective-override: §aVerzaubere das §6Trainingsschwert §amit dem §r♺ §eBuch der Haltbarkeit §5§l??? §aam §5§lZauberwürfel.
          start-event: questverzauberungsbuch
          start-message: '&f❝ <npc>: &7&oDu nimmst nun das Verzauberungsbuch rechtsklick auf den Zauberwürfel und wechselt sofort zum Trainingsschwert.'

**Comment by FlyingPikachu** [comment]
Does removing the 1-second delay cause the start-event to work again?

**Comment by kleinesgumi** [comment]
yes. if i remove the delay the start-event for the nextstage works.

**Comment by FlyingPikachu** [comment]
In the future, please use a site like Pastebin to share quests.yml

The issue here is that your `start-message` uses the <npc> tag, but you don't have an NPC start set:

![npcstart](https://user-images.githubusercontent.com/2267126/52666696-018a4600-2edd-11e9-86bb-948def1746b2.png)

All I can really do is push a commit which will show a warning in the console. Either remove the <npc> tag or set an NPC start.

**Comment by FlyingPikachu** [comment]
Warning added in 3e74d80

**Comment by kleinesgumi** [comment]
bug still there.
the start-event of the phase 2 not get triggerd after the delay:

>   custom52:
    name: Jetzt aber schnell!
    npc-giver-id: 52
    ask-message: '§7§oEine Frage der Zeit.'
    finish-message: ''
    gui-display: name-BOOK_AND_QUILL:amount-1
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 42
          start-message: '&f❝ <npc>: §7§oDer Älteste erklärt dir worum es geht, ersuche ihn. &f❞'
          complete-message: '&f❝ <npc>: §7§oin 2 Minuten geht die nächste Phase der Quest los, für die Phase hast du nur 2 Stunden Zeit! bereite dich vor. §f❞'
        '2':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 500
              data:
                Objective Name: ☛ §aErledige §c%count% §5Monster der §6Farmmap §ainnerhalb 2 Stunden.
                Conditions: NONE
                TargetConditions: NONE
                Internal Mobnames: besessener,stolzerzombie,monstersphere_mob_1,feuerskelett,feuerschütze,monstersphere_mob_1,monstersphere_mob_2,fischmensch,fisch,monstersphere3_mob_1,hexer,hexerschwein,monstersphere4_mob_1,monstersphere4_mob_2,oberzombie,steinzombie,monstersphere5_mob_1,altergolem,monstersphere6_mob_1,monstersphere6_mob_2,untoterbergarbeiter
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: 'false'
                Notifier msg: §7[§4!§7] §1%c%§7/§2%s% §bWasserzombies§7/§bLaserfisch
          start-event: jetztaberschnell
          start-message: '&f❝ <npc>: §7§oErledige 500 Monster auf der Farmmap aber das innerhalb nur 2 Stunden. &f❞'


events.yml:

>   jetztaberschnell:
    timer: 5

**Comment by FlyingPikachu** [comment]
I can’t use that quest for testing unless you use Pastebin.com

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kleinesgumi** [comment]
https://pastebin.com/cdFXdHFi
sorry.

**Comment by FlyingPikachu** [comment]
It's okay, thanks for correcting that.

Looks like Github's markup changed what I was trying to say in my earlier comment. In your start message, you're using the `<npc>` tag, but you haven't set an NPC start:

`start-message: '&f❝ <npc>: §7§oDer Älteste erklärt dir worum es geht, ersuche ihn. &f❞'`

So either set an NPC start like I showed in the picture, or remove the `<npc>` tag, and it should work.

**Comment by kleinesgumi** [comment]
i have set an start npc but still not working

**Comment by FlyingPikachu** [comment]
I don’t see one in the quest you posted, but I’ll reopen this pending further testing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FlyingPikachu** [comment]
Thanks for your patience. I see you have been using a start-npc (I did not realize it's called `npc-giver-id` in the config). The commit I've just pushed should resolve the delay issue.

Use the following build once available - http://ci.ac3-servers.eu/job/Quests/689/
