### ISSUE TITLE
Error with mcMMO requirement

### ISSUE THREAD

**Issue by x1p** [FlyingPikachu/Quests#696]
**What is your Quests version / build number (do _not_ say "latest")?**
Quest v 3.6.3-b661
mcMMO v 2.2.0 -snapshot
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Executing:
/quests editor
1 (new)
9 (requirements)
7 (mcMMO)
1 (set skills)
Console error: https://pastebin.com/JuD06AZu
In game: mcMMO requirements editor screen does not accept anything anymore

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
quest is completely default
mcMMO is completely default

**Comment by FlyingPikachu** [comment]
Quests only support mcMMO Classic at this time:
https://www.spigotmc.org/resources/official-mcmmo-classic.2445/

Support for the new mcMMO remake is planned once the project matures:
https://www.spigotmc.org/resources/official-mcmmo-overhaul.64348/
