### ISSUE TITLE
Methods of CustomObjective are Deprecation ? 

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#697]
Quest v3.6.4

Pic: https://i.imgur.com/bSvezOz.png

Thank you so much!

**Comment by keodeovn** [comment]
I saw the source, problem was solved!

**Comment by FlyingPikachu** [comment]
Glad you were able to resolve the issue. Please use the following wiki page for further guidance:
https://github.com/FlyingPikachu/Quests/wiki/Master-%E2%80%90-Quests-API
