### ISSUE TITLE
Delay for event

### ISSUE THREAD

**Issue by jajamic** [FlyingPikachu/Quests#699]
Hello,

I used the plugin "Quester" and I have to convert my 150 quests on your plugin (updated and more efficient)

I am currently blocked, I need to use a time system to trigger events. But from what I understand, there is no system on your plugin.

I am using this system to make cinematics games, currently the other plugin allows it is how the plugin offers me:

- Objective 1: successful ->
- Release: event 1 -> within 5seconds since the end of Objective 1 (/ playsound ***)
- Release: event 2 -> within 10secondsfrom the end of Objective 1 (/ npc spawn 50)
- Etc ...

Can you help me please

**Comment by FlyingPikachu** [comment]
The "time system" is called the Planner in Quests. You can access it by using _/quests editor_ and, when creating/editing a quest, selecting the "Edit Planner" option.

**Comment by jajamic** [comment]
No ! I speak for run event ! It s not the same think.

Je crois que tu es français, mon problème est que je veux que mon événement se lance plus tard, non pas la quête. J'aimerais créé un délais avant qu'il ne boot une commande.

**Comment by FlyingPikachu** [comment]
I see. Unfortunately, there is no way to delay Events themselves in Quests. The most similar option would be attach an Event to a stage objective, and then give the objective a Delay.

Google Translate:
Je ne parle pas français. Malheureusement, il n'y a aucun moyen de retarder les événements eux-mêmes dans les quêtes. L'option la plus similaire serait d'attacher un événement à un objectif d'étape, puis de lui donner un retarder.

**Comment by FlyingPikachu** [comment]
Visit our Discord for further assistance - https://discordapp.com/invite/d56CQ6e

**Comment by jajamic** [comment]
Ok Thx, but my bad I have already try that and dosen t work, I know it s hard but I can paye for create this option if you want. :'(
