### ISSUE TITLE
Quest stages doesn't finish the quest

### ISSUE THREAD

**Issue by pleiadian41** [FlyingPikachu/Quests#7]
Some of the quest stages are not finishing the quest. I have currently found these bugged stages: Talking to NPC, Delivering Items to NPC. It shows that I have successfully spoken or delivered items and the quest is supposed to finish, but instead it freezes.

**Comment by Leescar** [comment]
Attempted to reproduce with Receiving quest from npc A and talk to npc B
 Quest finishes and works like its supposed to.
can test with talk to npc A and talk to npc A again to complete if you like?

On the other hand item will not be accepted without renaming in anvil to all caps tag ie a leather chestplate to LEATHER_CHESTPLATE

**Comment by FlyingPikachu** [comment]
Fixed in Quests 2.1.6. If you still experience issues after updating, please make a open a new issue. Thanks!
