### ISSUE TITLE
Internal Error Occured

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#70]
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
git-spigot-7228328-14b597f (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
2.9.4
- Description of problem & console errors
We can't create quests as once we save a quest + do /questadmin reload, the quest doesn't save and we get this error in console. https://pastebin.com/ynK2zTPH (the error says 2.9.0 as I took the error copy before we updated, but same happens on 2.9.4)

**Comment by FlyingPikachu** [comment]
One of your quests is missing data. In your quests.yml, look for a similar situation to this:

    stages:
      ordered:
        '1':
          break-block-names:
          - stone
          - dirt
          break-block-amounts:
          - 10
          - 7
          break-block-durability:
          - 0

You'll notice how there is no second `break-block-durability` value when there should be. It's likely your configuration has a similar problem.

If you're unable to resolve this issue on your own, post your complete quests.yml file as well as the error produced with version 2.9.4. Thanks!

**Comment by Alppuccino** [comment]
Thankyou so much! Such an elaborate answer and it fixed it! Thankyou, really nice of you to give us a fix for this mate.

**Comment by Alppuccino** [comment]
Actually, sorry for reopening but if I add every hostile mob as a stage and add only one figure for mob-amounts, will it mean that each mob is optional - say they need to kill 300 hostile mobs and they kill 300 skeletons it will work the same as them killing like 150 skeletons and 150 zombies or something like that? just need clarification before I start doing it. Thankyou!

**Comment by FlyingPikachu** [comment]
I do not believe it will work like that, but the best way to find out is to try it. Seeing as that question is not related to the topic, I must close this issue. Feel free to make a new one if you need further assistance. Thanks!
