### ISSUE TITLE
Command track on Quest

### ISSUE THREAD

**Issue by Felix5566** [FlyingPikachu/Quests#703]
**What does your feature do?**
Can you add the option to track an commands they tipe in the chat.
Explain: Set your home with /sethome
(after typing /sethome) Good yob and now the next step of the quest....

**How would people use it?**
1. /quests editor
2. 1 Add new quest
3. quest name
4. 11
5. 1 Add new
--------------------
6. 25 Add new Command to Track
7. 1 Command Name
8. /sethome
-------------------

**Comment by FlyingPikachu** [comment]
The plugin is only concerned with tracking the player _while_ a quest is in-progress, which is already possible through the Event Editor (_/quests events_).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
