### ISSUE TITLE
[Request] One time Quests

### ISSUE THREAD

**Issue by MPPrison** [FlyingPikachu/Quests#71]
Hi, ive been trying to make a One Time Quest, I put no delay so I could only do it once.
I want players to be able to click him again after finishing it.
I know there's something in the en.yml for ''questAlreadyCompleted'' but that  only works for /quests take <quest>
I want the NPC to give me a message when I have already done the Quest and there's no delay on it.

**Comment by FlyingPikachu** [comment]
Just to be clear, this is requesting a message for when an NPC quest has already been completed, and not about "one time quests"?

**Comment by MPPrison** [comment]
Aha, Is there a way to make npcs with no delay clickable after they have been finished? so players know they already did the Quest.

**Comment by whoshenry** [comment]
I think this is a good idea, here's something else you can do.

If you have the GUI active for a Quest, you can have the Title of the Quest and then (Completed) after it as an easy way to signify to the player that you have completed their Quests.Then if the player clicks this it will just come up saying 'You have already completed this Quest.'

**Comment by Formula350** [comment]
I'm no coder, but would it be possible to basically copy and paste the code from the Quest Requirements where you've set it to that a player needs to have completed a previous quest, and then simply have it be a new line option during creation for a custom message **but** if no custom message is provided then it defaults to that same message from the language file "You have already completed this quest."? (or whatever it says)

Might not be as easy as I'm thinking, but I figure some code may be modular like that, with a few tweaks of course... heh
-Form

**Comment by FlyingPikachu** [comment]
@whoshenry Thank you, all help is appreciated. However, I do not have skype.

@Formula350 That's slightly overkill, but you've got the gist of it.

**Comment by FlyingPikachu** [comment]
Added in dev build 67. Needs testing as I was unable to do so thoroughly. Feedback appreciated!

http://ci.ac3-servers.eu/job/Quests/67/

**Comment by FlyingPikachu** [comment]
Closing due to lack of response. Thanks for the request!
