### ISSUE TITLE
quests editor

### ISSUE THREAD

**Issue by Gartentrulla** [FlyingPikachu/Quests#711]
**What is your Quests version / build number (do _not_ say "latest")?**
latest
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I use the german Editor an it says unknown command when I type /quests editor in the Chat. All german c ommands for quests dosen't work. I generatet all new. Now I use the old Version 3.5.1 and it works.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Sorry no, I habe nothing in my logs.
Thanks for your help, and sorry my english, I am German.
Your Gartentrulla

**Comment by FlyingPikachu** [comment]
Closing as OP did not follow issue instruction ("latest" is not an acceptable build number).
