### ISSUE TITLE
Being able to have other server operator design and create quests 

### ISSUE THREAD

**Issue by Nosneross** [FlyingPikachu/Quests#717]
Quests Addon 

**What does your feature do?**
Allow a friends Op to make and create his or hers own quests 
**How would people use it?**
on there own server when they want to op server admins its a lot easier

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests.

So long as they have the appropriate permissions, anyone can create quests. There is no need for an addon. Please see https://github.com/FlyingPikachu/Quests/wiki/1-%E2%80%90-Commands-&-Permissions

Furthermore, I do not accept requests to create addons. You should seek a developer for hire to create such things for you in the future. I suggest (but am not associate with) the folks at https://www.spigotmc.org/forums/hiring-developers.55/
