### ISSUE TITLE
npc-effects not working and Error in console

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#719]
Quests v3.6.4-b682 (Tested with every Version on Jenkins v1,v2,v3 and normal) and with old and new generated config
Server 1.8.8 Paper

> npc-effects:
>   enabled: true
>   new-quest: note
>   redo-quest: angry_villager

> [05:47:25 WARN]: [Quests] Task #121 for Quests v3.6.4-b682 generated an exception
> java.lang.NullPointerException
>         at me.blackvein.quests.particle.ParticleProvider.sendToPlayer(ParticleProvider.java:124) ~[Quests-3.6.4.jar:?]
>         at me.blackvein.quests.particle.ParticleProvider.sendToPlayer(ParticleProvider.java:99) ~[Quests-3.6.4.jar:?]
>         at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:64) ~[Quests-3.6.4.jar:?]
>         at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:44) ~[Quests-3.6.4.jar:?]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
>

**Comment by FlyingPikachu** [comment]
Fixed in 0146ce1f4163f8083c0809fb799dc1f5afbe0c3c
