### ISSUE TITLE
[Bug] Regarding delay related options for a stage...

### ISSUE THREAD

**Issue by PikachuEXE** [FlyingPikachu/Quests#72]
From original project wiki:
```
delay:: Amount of time (in milliseconds) that the player must wait after completing this Stage, before the Quest will advance to the next one
(Optional) delay-message: Message sent to the player when the delay begins 
```
There are 2 bugs:
- `delay` are seems to be actually counted in minutes
- `delay-message` is sent **after** delay ends

**Comment by MetalGearDaner** [comment]
In my server it seems to be in seconds :/

**Comment by FlyingPikachu** [comment]
This is official wiki: https://github.com/FlyingPikachu/Quests/wiki

The delay is in seconds Quests 2.3.4. I believe the delay-message behavior is intentional despite the original wiki. If you have more reason to believe otherwise, please open a new ticket.

**Comment by PikachuEXE** [comment]
I will test more about the delay.
But I guess there is no doc about `delay-message`
