### ISSUE TITLE
Some Code Errors found with Eclipse Oxygen

### ISSUE THREAD

**Issue by LinearBotSystems** [FlyingPikachu/Quests#72]
Quests 2.9.5 , Spigot is still 1.12 

Okay Eclipse Oxgen gives follow errors form the Quests sourcecode:

NPCKillListPrompt cannot be resolved to a type	CreateStagePrompt.java	/Quests-master/src/main/java/me/blackvein/quests/prompts	line 327	Java Problem

NPCKillListPrompt cannot be resolved to a type	CreateStagePrompt.java	/Quests-master/src/main/java/me/blackvein/quests/prompts	line 2253	Java Problem

Reason for this is in line 2108 in the same file 

` 	private class NpcIdsToKillPrompt extends StringPrompt {

		private class NPCKillListPrompt extends FixedSetPrompt {
		
			public NPCKillListPrompt() {
				super("1", "2", "3", "4");
			}
		`
TheNPCKillListPrompt class is inside and private there is no way to reach it from outside in any case this will certainly cause weird behavior and crashes.  I'm not sure if instead of NPCKillListPrompt  NpcIdsToKillPrompt  was meant otherwise it could get complicated I don't know what the  NpcIdsToKillPrompt constructor does which came from StringPrompt if nothing you could implement a getter and return an object from NPCKillListPrompt , if it does something you need properly an alternative constructor.

By the way the line numbers could be 1 or 2 lines of since I'm one commit behind.

**Comment by FlyingPikachu** [comment]
If I'm understanding you correctly, the issue is that the `NPCKillListPrompt` class is private? I don't see how this would create any issues. The constructor of the same name merely creates objects from the class blueprint (the objects being prompt options, in this case).

I'm still on Eclipse Luna with no immediate plans to upgrade. Perhaps this could be a false positive?

**Comment by LinearBotSystems** [comment]
I don't know I downloaded the source code again and the code is different it is no longer a inner class also the line numbers are very different so the problem is fixed.
