### ISSUE TITLE
Message devliery bug

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#720]
Quests v3.6.4-b682
Server 1.8.8 Paper

on Devliery the object message says:
"Devlier Wood Sword to NPC: 1/1" (haven't devliered yet)
before some quests it was:
"Devlier Wood Sword to NPC: 0/1"  (haven't devliered yet)

**Comment by FlyingPikachu** [comment]
This issue will be resolved in http://ci.ac3-servers.eu/job/Quests/690/

Note that this build changes the default `translate-items: false` to `translate-names: true`. No action is required on your part unless you wish to disable translation under the new setting name.
