### ISSUE TITLE
Problem with CustomObjective

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#721]
Ver 3.6.4

Hi FlyingPikachu, It's me again. Thanks for making an amazing plugin. It love it!

There're 2 CustomObjectives: 
1. Conversation: https://pastebin.com/4FKzt6ji
2. CuongHoa: https://pastebin.com/M6C7Cj21

My quest: https://pastebin.com/a93wDwMm
QuestGUI class: https://pastebin.com/wihVYuK7

How did it happen?
1. I started my quest and finished conversation stage. I used my questgui plugin. It showed my currentstage
![image](https://user-images.githubusercontent.com/29066915/53697537-b214a700-3e04-11e9-99a1-187b98a7a58e.png)

2. I was out game and rejoined server. And checked my currentstage. It didnt show currentstage. And console said: https://pastebin.com/i6vp1rNB (I tried removing my plugin and /quest but it didn't work! log: https://pastebin.com/AmHcFr9w)
![image](https://user-images.githubusercontent.com/29066915/53697539-bf319600-3e04-11e9-9249-41d2e178eddd.png)

Thanks for reading!

**Comment by FlyingPikachu** [comment]
Hello, I'm assuming this is a continuation of #710 so I'll close that issue in favor of this one.

The error you've provided tells me that your `QuestGUI.getJobToDo` method is calling `Quester.getObjectives`, but I have no way of knowing if or how your plugin is modifying the objectives. Furthermore, your error refers to line 855 of the Quester class, which (as of the most recent Jenkins build) is nothing more than a method header comment.

To start, please update to the latest build so we're on the same page. If the issue persists, post the new error along with your `getJobToDo` method - http://ci.ac3-servers.eu/job/Quests/686/

**Comment by keodeovn** [comment]
I updated the last build (Build #686 (03:18:09 04-03-2019))
New log: https://pastebin.com/4eeNteqj
Method QuestGUI.getJobToDo() is shows current objectives of player. I copy this from your command /quest. It doesn't modify anything from the objectives.
Thanks for supporting!

**Comment by FlyingPikachu** [comment]
Thanks for updating. Looks like I was referencing an older version of the class, so line 855 is correct. Here is that line for reference:

https://github.com/FlyingPikachu/Quests/blob/cc88f890936f39bbf0d9e34266b0763ffc18791b/main/src/main/java/me/blackvein/quests/Quester.java#L855

I'll be looking into this shortly.

**Comment by FlyingPikachu** [comment]
@keodeovn Please try http://ci.ac3-servers.eu/job/Quests/687/ and let me know the results.

**Comment by keodeovn** [comment]
It's worked!

**Comment by FlyingPikachu** [comment]
Great! Thanks for using Quests.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
