### ISSUE TITLE
Phatloots 1.13 update bug

### ISSUE THREAD

**Issue by CodeGod000** [FlyingPikachu/Quests#725]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The problem occurs because of an updated version of phat loots I added to my plugins folder. I'm assuming since the quest's dependency for phat loots hasn't been set to this version that this is what the problem consists of. I've been trying to fix it myself through github but I've sadly come to the decision that I can't update the maven dependencies on my own. All I think it needs though is the new version of phat loots along with some name changing in the code. The name changing is fairly simple to do (if you wanted to know). All someone needs to do is search for codisimus and replace it with articdive (the other author who took over) using control+f. Here is my server log for the error: https://pastebin.com/ssX3mPaT. Just FYI: the phatloots plugin no longer works with 1.13 anymore when downloading it from codisimus' website. Therefore, this addition would be nice for whoever wants to update their phat loots plugin to 1.13. Thank you!
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
N/A

**Comment by FlyingPikachu** [comment]
Quests only supports the official release of PhatLoots, which is unfortunately not compatible with 1.13 protocol at this time.

The "name changing" you're referring to is called _refactoring_ and, while you're right that it'd be easy to do, I will not be building against any given fork of PhatLoots as any one derivation is unlikely to gain widespread usage. Also, supporting a fork as well as the original plugin would be far too cumbersome.

As far as I can tell, you have the following options:
- Try again to create your own fork of PhatLoots and update it to 1.13.
- Create your own fork of Quests to support the desired PhatLoots fork.
- Convince the author of the desired PhatLoots fork to revert to the original package names, or fork it and change them yourself.
- Use a different fork of PhatLoots that both supports 1.13 protocol and uses the original package names.
- Support [my recent PR to the original PhatLoots](https://github.com/Codisimus/PhatLoots/pull/101) in hopes of advancing its development.

Best of luck with whatever option you choose!
