### ISSUE TITLE
Display Name Bug

### ISSUE THREAD

**Issue by MooshroomStatus** [FlyingPikachu/Quests#727]
version 3.6.3

Quests does not seem to recognize any sort of quest that has color formatting in the name. It is possible to add formatting, however, after adding formatting, it's impossible to go into the editor or take the quest ("/quests take [Quest]") that has formatting in it's name, resulting in the error "quest not found".

To further experiment on this, I removed the formatting "&6&l" from the name and the editor and take commands worked just fine.

Premade Quest:
https://pastebin.com/at1PqUsX

**Comment by FlyingPikachu** [comment]
Correct. This is because it would require users to include the associated color codes in the _/quests take [quest]_ command - codes which many users are not familiar with. And although Quests could strip color codes from names at loadtime, that would introduce problems if there were multiple quest of similar names (for example, it'd be bad if `&2MyQuest` and `&7MyQuest` would both be loaded as `MyQuest`).

As such, there are no plans to support color codes in quest names.

**Comment by MooshroomStatus** [comment]
Okay, so color coding support was removed from quests. Got that. but the same thing happens if I put a space in the name as well. if I make a quest named "Quest Test" and do /quests take Quest Test, I'll still get "Quest not found". Was support for name spacing removed as well?

**Comment by FlyingPikachu** [comment]
I’m not sure that color codes were ever supposed in names.

As for spacing I think that’s supported. Have you given it a try?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MooshroomStatus** [comment]
They were. I used to add color formatting to quests all the time in earlier versions. For example, [&7Beginner&f] First Quest . this used to work so long as I typed /quests take First Quest. 

And I have given it a try. I think the command string "/quests take" doesnt support the spacing in quest names. I think its demanding the entire name in one part of the string. As in: "/quests take First Quest" might only be accepting "/quests take First" and that's why it can't find it?

**Comment by FlyingPikachu** [comment]
Interesting. If you can determine which version removed the ability to use color, I'd be willing to take a closer look. However, there's a good chance it was removed the reasons I mentioned earlier.

Was just able to accept the default "Mob Hunter" and "Iron Miner" quests with the _/quests take_ command. I'm not sure what's stopping you from using spaces in quest names, but I'll have to ask you open a new issue with an example quest if you'd like to explore this further.
