### ISSUE TITLE
No German Language for the Editor

### ISSUE THREAD

**Issue by Gartentrulla** [FlyingPikachu/Quests#728]
I use:
version: 3.6.3-b668

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I use the german Editor an it says unknown command when I type /quests editor in the Chat. All german commands for quests dosen't work. I generatet all new. Now I use the old Version 3.5.1 and it works.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
In my logs is nohing, everything is fine
Please can you help?
Thanks a lot. sorry my english, I'm German.

Your Gartentrulla

**Comment by FlyingPikachu** [comment]
Please post the contents of your config.yml file

**Comment by FlyingPikachu** [comment]
Disregard my previous request.

Use the following build to resolve the issue:
http://ci.ac3-servers.eu/job/Quests/692/

**Comment by Gartentrulla** [comment]
Dear FlyingPikachu,
thank you very, very much for your help. Now I tried the version: 3.6.4-b692 and it works. I wrote translate-items: true
translate-subcommands: true
and it works too.

Now I have a Little other problem. In the germen translation is no part for a deliver-items only to craft. 
Maybe the translation is so diffuse that I didn't find it.

It would be very nice if you can help me again 

Thanks a lot your Gartentrulla

**Comment by FlyingPikachu** [comment]
Glad you were able to resolve the issue! And thank you for the kind Spigot review.

I believe the `deliver:` string is what you are searching for. It should be located near `craft:`
