### ISSUE TITLE
Language file for German not found

### ISSUE THREAD

**Issue by Gartentrulla** [FlyingPikachu/Quests#729]
My Server has:
spigot latest 1.13.2
**What is your Quests version / build number (do _not_ say "latest")?**
I use now:
version: 3.6.4-b692

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Thank you very much for your help, but it works only in English not in German.
In my console stands:
07.03 10:22:30 [Server] INFO [Quests] Enabling Quests v3.6.4-b692
07.03 10:22:30 [Server] ERROR [Quests] Failed loading lang files for de-De because they were not found. Using default en-US
07.03 10:22:30 [Server] INFO [Quests] If the plugin has not generated language files, ensure Quests has write permissions
07.03 10:22:30 [Server] INFO [Quests] For help, visit https://github.com/FlyingPikachu/Quests/wiki/Casual-%E2%80%90-Translations
07.03 10:22:30 [Server] INFO [Quests] Loaded language en-US. Translations via Crowdin

But the german langfile is there, both, the new and old, but both are new, because I generatet comtlitly new.
What can I do, that the german translation will be found?

This is my config:
# See https://github.com/FlyingPikachu/Quests/wiki/2-%E2%80%90-Configuration
accept-timeout: 40
allow-command-questing: true
allow-command-quests-with-npcs: false
allow-quitting: true
ask-confirmation: true
generate-files-on-join: true
ignore-locked-quests: false
kill-delay: 600
language: de-De
max-quests: 5
show-requirements: true
show-titles: false
translate-names: true
translate-subcommands: false
use-compass: false
use-gps-plugin: true
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: angry_villager

Tanks a lot and best regards from Gartentrulla

**Comment by Gartentrulla** [comment]
Now I chanced the Version to
version: 3.6.3-b668

I generatet all new and testet each ommand.
I found that if I Change :
translate-names: true
translate-subcommands: true
the language file dosen't found. But if I set this to false it works. That is not quiet correct, because I wish everything in german. So I can't use "neuladen". It works only with "reload"

Maybe it helps.
The new german translation is a little bit horrible. The last one is better
Maybe you can fix it  that "translate-names" and "translate-subcommands" can set to true.

Thanks a lot for your help.
With best regards Gartentrulla

**Comment by FlyingPikachu** [comment]
Regarding the `translate-subcommands` option, that's exactly what the for for #728 was meant to address.

The error you've posted here says that the language file at _/plugins/Quests/lang/de-De_ didn't exist. Since you say that 3.6.3-b668 was able to generate the file, try switching back to b692 now that the file exists.

If that still doesn't work, try following the "Pro-tip" directions at https://github.com/FlyingPikachu/Quests/wiki/Casual-%E2%80%90-Translations#viewing

**Comment by Gartentrulla** [comment]
Thanks very much, I will try it tomorrow, because I'm not at home today.

Regards from Gartentrulla

**Comment by Gartentrulla** [comment]
Thank you again for your immediatly answer. I found the deliver message,, but it is not near craft, it is now under NPC. If someone has the same Problem, you can help now.

Everything is now perfect and I'm very happy.
You can close this issue.

With friendly regards
 Gartentrulla from Germany, the maybe oldest Minecraftpplayer (67)
