### ISSUE TITLE
Quests Duplicating on Relog

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#73]
In your issue, please include:

git-Spigot-7228328-14b597f (MC 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Quests 2.9.4

Quests duplicate on relog
It only seems to happen on the ones with multiple stages (Supplier for tony stark, damn your coal, are you oaky? etc.)

https://pastebin.com/kbHgTzhn

**Comment by FlyingPikachu** [comment]
I am unsure what you meant by "duplicate on relog" but I was not able to produce duplicate entries in quests.yml by logging out/in, using _/questadmin reload_, or restarting my test server.

Please elaborate.

**Comment by Alppuccino** [comment]
When you log out and log in with accepted quests, the accepted quests that you have taken some of them will duplicate. It seems to be only the quests with multiple stages on them.

**Comment by FlyingPikachu** [comment]
Related to #75
