### ISSUE TITLE
Where are the placeholders of placeholderAPI?

### ISSUE THREAD

**Issue by itaquito** [FlyingPikachu/Quests#731]
Hey! 
According to this https://github.com/FlyingPikachu/Quests/wiki/Beginner-%E2%80%90-Dependencies#placeholderapi they are placeholders somewhere, but after searching them on the list of PlaceholderAPI I couldn't find them. 
Then I asked on the Discord and they suggest me opening an issue here to see if they do exist.
Do you have a list of this placeholders?

Thanks!

**Comment by FlyingPikachu** [comment]
There are no Quest-specific placeholders at this time, but you can use the built-in PAPI ones in the language files. See here for more info:
https://github.com/FlyingPikachu/Quests/wiki/Casual-%E2%80%90-Translations#placeholderapi

If you'd like to submit ideas for Quest placeholders, see #709
