### ISSUE TITLE
The planner doesn't work

### ISSUE THREAD

**Issue by Gartentrulla** [FlyingPikachu/Quests#732]
I use
3.6.4-b692
and spigot 1.13.2

Hallo,
I hope you can help me again.
I made a quest with the planner. But it always said "no more quest available".
It only wiorks one time, but not the next day.

This is the quest:
  custom31:
    name: Tagesmarke
    npc-giver-id: 261
    ask-message: Hier kannst du täglich Marken für 3 Lapisblöcke bekommen.
    finish-message: Komme Morgen wieder, heute gibt es nichts mehr
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-LAPIS_BLOCK:amount-3
          npc-delivery-ids:
          - 261
          delivery-messages:
          - Bringe mir 3 Lapisblöcke
    rewards:
      items:
      - name-LIGHT_BLUE_DYE:amount-1:enchantment-PROTECTION_ENVIRONMENTAL 1:displayname-§6Tagesmarke:meta-type-UNSPECIFIC:enchants-{PROTECTION_ENVIRONMENTAL=1}
    planner:
      start: 9:2:2019:15:9:43:Europe/Berlin
      end: 9:11:2022:4:11:52:Europe/Berlin
      repeat: 86400

I have no mistakes in the console or latest.

Is there something I made wrong or is it an issue?

Thanks for your answer.
With best regards your Gartentrulla

**Comment by FlyingPikachu** [comment]
The Planner works, it's just the repeat function that's broken. A solution is being worked on. Please direct your comments to #713 

Closing as duplicate.
