### ISSUE TITLE
[Bug] Unable to quit quests

### ISSUE THREAD

**Issue by Neoblade298** [FlyingPikachu/Quests#74]
Hi, Neo here

This was an issue in a previous Blackvein build for quests, but the /quests quit command doesn't work. allow-quitting is set to true in the config, but when I type it ingame, it only gives me the usage for the command. I have turned on debug mode and nothing shows up when I type /quests quit. Below are screenshots of what happens in-game, and a snap of the console when I type it (to prove no error is occurring).

http://gyazo.com/0fcd56f8c8c994b5101ee1917c3519f3
http://gyazo.com/382baaa3f14f2d448a87a0c030e82e80 (After typing /quests quit it only shows this message)
http://gyazo.com/4f58b3b58b9de5fc00f89c714efc6e6f (Proof that there is no error)

Thanks in advance if you get to this. Also on a lesser note, you forgot to change seconds to milliseconds on the little prompt for 'redo delay' on the ingame editor:
http://gyazo.com/85abea677a34074dc7540df45be429b5

Thanks for your work, your revitalization of quests really helped us out :p

Regards,
Neo

**Comment by Leescar** [comment]
The proper command is /quests quit questnamehere 
So for the quest in question in your screenshot it would be /quests quit QUest Name
Unless your using an older version because I get the prompt
![command prompt](https://cloud.githubusercontent.com/assets/10955493/7066818/d6374c8c-de8b-11e4-9422-968b2f88e59a.png)

**Comment by Neoblade298** [comment]
I'm using version 2.3.4, is there a newer version? And also I tried using /quests quit questnamehere and it did work, so thanks for that.

**Comment by Formula350** [comment]
Yea, we have to make that distinction to all our players as well. "I tried, but it didn't let me" to which we say "It's /questS with an S on the end".

I don't know if it's an easy thing to do but maybe FlyingPikachu can tie in the Quit 'subcommand' to work on both /quest and /quests? *shrug*
-Form

**Comment by FlyingPikachu** [comment]
I could, but then I'd be tying in every other sub-command for good measure. I wish _Blackvein_ had made the 2 commands more distinctive, but that's not something I'm looking to change.

Thanks!
