### ISSUE TITLE
Doing /quest journal makes an internal error occur and it says *Invalid book tag*

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#75]
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
Quests 2.9.4
git-Spigot-7228328-14b597f (MC 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

- Description of problem & console errors
Error 1: (when doing /quest)
https://pastebin.com/6sVZLrXR
Error 2: (taking out journal)
https://pastebin.com/cUeptHbB

- Pastebin an example quest from quests.yml for testing, if applicable
https://pastebin.com/kbHgTzhn
Failure to provide the first 2 bullets may result in your issue being closed!

**Comment by FlyingPikachu** [comment]
I have tried using _quest_  and _/quests journal_ in-game, both work just fine for me using your quests.yml

Have you accepted any quests? If so, which ones?

**Comment by Alppuccino** [comment]
I have managed to fix this temporarily by quitting the quests and re taking them, and I can't quite remember but here is a list off the top of my head:
You Guys Made Me Ink!
Are You Oaky?? (Repeatable every 1h)
Damn You're Coal (Repeatable every 1h)
Supplier For Tony Stark
B O N E L E S S

**Comment by FlyingPikachu** [comment]
Fixed in https://github.com/FlyingPikachu/Quests/commit/5d408bcba65655e74c5929a43807fb347f027583

@Alppuccino use http://ci.ac3-servers.eu/job/Quests/156/
