### ISSUE TITLE
Need help with quests

### ISSUE THREAD

**Issue by zakirish1219** [FlyingPikachu/Quests#78]
So its not exactly an issue but i would like more info on the quests requirements sections than the wiki offers. in game the editor displays more options than what the wiki shows and i want to be able to make the quests in config files so its easier as all i would do is copy paste and change names. So if you could email me with more info about setting up the quests besides what the wiki says i would greatly appreciate that. thanks.

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests! Unfortunately, I do not email privately.

For reference, I believe you are talking about this section of the Wiki - https://github.com/FlyingPikachu/Quests/wiki/Configuration#requirements

If you have questions regarding any specific settings, feel free to list them and I or another contributor should be happy to answer them. Otherwise, I will personally try to update that part of the Wiki in the near future.

**Comment by zakirish1219** [comment]
my email is zakirish1219@gmail.com   sorry for not posting.

**Comment by zakirish1219** [comment]
thank you for responding so fast. i missed it when i sent my second comment haha. anyway yes i saw that section but if you go thru the editor in game it has more options like mcmmo skills and such. that not in the wiki. and i would use the quest editor in game, but for one it stops working for me and for two i would like to be able to have it in a config file so i can copy paste it multiple times and change the settings as need be. let me know if more clarification is needed. thank you once again, and have a blessed day/night, whenever you are.

**Comment by zakirish1219** [comment]
did you get a chance to look at my last message? i guess another way of me asking is how can i add the requirement of a person having 100 skill levels in mcmmo mining for them to start a quest? i dont want to use the ingame editor. i want to strictly use the config files. how to set all that up is not in the wiki section. is there any other resource you have that i can use, or am i just out of luck? sorry to be blunt if you think i am. let me know what i can do. have a blessed day/night, whenever you are.

**Comment by FlyingPikachu** [comment]
I have updated the Wiki to include mcMMO Requirements. Using the in-game editor, it is as simple as selecting which skills you would like Quests to check for, followed by the amount of levels required. If you would prefer to configure this manually, here's an example quest for you:

https://pastebin.com/CYAme13T
