### ISSUE TITLE
Cannot edit quests after finished creating them

### ISSUE THREAD

**Issue by Arcantiz** [FlyingPikachu/Quests#78]
Hey there, when I try and edit a quest a second time and save it, it does not save.
I get this error in the console : 
09.04 21:52:20 [Server] INFO Staff: [Owner] ArcantizHD
09.04 21:51:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
09.04 21:51:55 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:704) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection$2.evaluate(PlayerConnection.java:964) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-952179b-2f50138]
09.04 21:51:55 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1040) ~[?:?]
09.04 21:51:55 [Server] INFO at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:1277) ~[?:?]
09.04 21:51:55 [Server] INFO java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.LinkedList
09.04 21:51:55 [Server] ERROR Error handling conversation prompt

**Comment by FlyingPikachu** [comment]
Is this the full error? And what is your Quests version?

**Comment by Arcantiz** [comment]
yes this is the full error and its 2.3.4

**Comment by FlyingPikachu** [comment]
I was unable to duplication this error. Would you mind uploading your quests.yml?

**Comment by Arcantiz** [comment]
http://pastebin.com/3JtMyAVa

**Comment by FlyingPikachu** [comment]
I was able to edit the "Sarkoth" quest's ask message, save it, and /questadmin reload without any errors. Could you be more specific about what steps you took?

**Comment by Arcantiz** [comment]
well it ill open the quests editor and do the things I need to change like the ask and finish message or the experience (from skillapi) or what the objective name is, ill then go to save it and when i press 1 (yes) it does nothing and gives that error.

**Comment by FlyingPikachu** [comment]
Only other suggestion I can think of (since I can't duplicate it) is to try Quests 2.4.0 and post the "new" error in its entirety.

**Comment by FlyingPikachu** [comment]
Closing as unable to duplicate. If the issue persists, please recreate the issue with a newer version of Quests.
