### ISSUE TITLE
Error spamming on console on Block break

### ISSUE THREAD

**Issue by StillSwingin** [FlyingPikachu/Quests#79]
Hi! 
It's awesome someone continues developing this plugin, thanks.

Every time someone breaks a block for a quest, this message shows on console:

21:58:14 CONSOLE: ERROR]: Could not pass event BlockBreakEvent to Quests v2.3.4
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) ~[?:?]
21:58:14 CONSOLE: Source) ~[?:1.7.0]
21:58:14 CONSOLE: Source) ~[?:1.7.0]
21:58:14 CONSOLE: ERROR]: Could not pass event BlockBreakEvent to Quests v2.3.4
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:14 CONSOLE: Source) [?:1.7.0]
21:58:15 CONSOLE: Source) ~[?:?]
21:58:15 CONSOLE: Source) ~[?:1.7.0]
21:58:15 CONSOLE: Source) ~[?:1.7.0]

**Comment by FlyingPikachu** [comment]
Sorry for the late response. Could you please post your quests.yml (preferably though something like Pastebin)?

**Comment by StillSwingin** [comment]
Here it is:
http://pastie.org/10094525

**Comment by FlyingPikachu** [comment]
I tried the quest ¿Tienes un pico? and was able to break blocks without getting any errors. Maybe another plugin is canceling the event? Are there any other errors?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. If this error persists, please open a new issue with the requested information. Thanks!
