### ISSUE TITLE
An internal error has occured when taking out journal

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#79]
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
Quests 2.9.6
git-Spigot-7228328-14b597f (MC 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
- Description of problem & console errors
https://pastebin.com/XtSnb2Gh When you try and take out the journal, it will say "An internal error has occured" and the book says *Invalid book tag* in red.

- Pastebin an example quest from quests.yml for testing, if applicable
https://pastebin.com/fXFwq9ua
Failure to provide the first 2 bullets may result in your issue being closed!

**Comment by FlyingPikachu** [comment]
To clarify, this happens when you run the _/quests journal_ command?

**Comment by Alppuccino** [comment]
Yes. Sorry I couldn't reply earlier, was away from keyboard.

**Comment by FlyingPikachu** [comment]
I was not able to replicate this just now. Which build of 2.9.6 are you using (there should be a trailing number, i.e. "2.9.6-b154")?

**Comment by FlyingPikachu** [comment]
Closing pending correction of #79. If you still experience this problem after fixing your durability, feel free to request re-open. Thanks!

**Comment by Alppuccino** [comment]
b-156
