### ISSUE TITLE
quests for npc's not working

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#8]
Hello when i assign a quest to npc and go to start the quest, it opens the gui just like it should then when i click the gui item it picks up the item instead of starting the quest. here is the error that happens:

https://pastebin.com/QQs1tB9E

**Comment by FlyingPikachu** [comment]
@ozm8 What is your Quests version? And could you provide your quests.yml (or at least the relatively quest data) for testing?

**Comment by ozm8** [comment]
well i deleted my quests.yml to test on both the latest release and on the latest dev build.. Im using 
Quests-2.8.6 and citizens: citizens-2.0.22-SNAPSHOT im on spigot 1.12

**Comment by FlyingPikachu** [comment]
@ozm8 Have you been able to replicate the error in either of those builds? If so, please post the error and quest.

**Comment by ozm8** [comment]
I think its working now for some reason you can close this for now
