### ISSUE TITLE
Break ____ quests are very inconsistent.

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#80]
In your issue, please include:

- Spigot and Quests versions (do not say "latest")
Quests 2.9.6
git-Spigot-7228328-14b597f (MC 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

- Description of problem & console errors
The quests where you need to break blocks (only usually the ones with multiple stages) are really inconsistent - the gold ore one doesn't work but the repeatable wood one works. They sometimes dont track them whatsoever - the redstone one and the ore ones are the very broken ones. If you could fix this it would be great!

- Pastebin an example quest from quests.yml for testing, if applicable
https://pastebin.com/fXFwq9ua
Failure to provide the first 2 bullets may result in your issue being closed!

**Comment by FlyingPikachu** [comment]
You have invalid block durability data. For example, your GOLD_ORE quest has a block-break-durability of 1, when the only valid value for Gold Ore would be 0. Correct this by manually editing your quests.yml -OR- setting the durability to 0 in _/quests editor_.

Personal note: Although I would like the user be notified of this problem, that's not possible as far as I can tell. May re-open pending https://www.spigotmc.org/threads/validate-block-damage.260467/
