### ISSUE TITLE
Ordering Quest

### ISSUE THREAD

**Issue by HellaMixel** [FlyingPikachu/Quests#83]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
2.9.5-b152
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I'm trying to make the quests in a specific order, do I have to do them backwards starting from the last to first or do I have to edit them some how in-game? In the pastebin the "Miner" quests is supposed to be in top of the Amateur quest. The first quests is fine. The order is supposed to be Miner-Amateur Coal Miner-Amateur Iron Miner

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/cmgY6zt4

**Comment by LinearBotSystems** [comment]
What kind of order you speaking display order ? Should be first on top and last down.
A quest order in the sense which quest should be done first you need to in add quest requirements the quest before.

**Comment by FlyingPikachu** [comment]
Closing as @LinearBotSystems appears to have answered correctly. Comment to reopen.
