### ISSUE TITLE
no more quests available

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#83]
if a npc has only one quests it shows "no more quests available"
this is misleading, please fix it

**Comment by FlyingPikachu** [comment]
If that NPC's quest is completed, then it has no more quests. I do not see how this is misleading. Please provide more information.

**Comment by seema84** [comment]
This message comes when the quests not completed. All NPCs say this on accept a Quest. 
(only in the latest dev builds)

**Comment by FlyingPikachu** [comment]
I see what you mean. Will attempt to fix that soon.
