### ISSUE TITLE
GUIs do not work on blocks? (not sure if intentional)

### ISSUE THREAD

**Issue by Neoblade298** [FlyingPikachu/Quests#84]
Basically what the title says, item GUI does not work while using 'block start'. It works just fine while using 'NPC start' however. I'm wondering if this is intentional or I'm doing something wrong. If it is the latter, I will give some more info on my configuration, but if not I'll just close the issue.

**Comment by FlyingPikachu** [comment]
This is intentional, although that could be an interesting option for the future.
