### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by ozm8** [FlyingPikachu/Quests#84]
Getting error spam in the console and the log is getting very large. here is the error:  https://pastebin.com/5frL5Akp

quests version: 2.9.5

quests config: https://pastebin.com/QBFrXjUr

**Comment by FlyingPikachu** [comment]
Try http://ci.ac3-servers.eu/job/Quests/160/ which should help, but not totally resolve the error.

Please post the new console error you get with that build.

**Comment by ozm8** [comment]
ok i think that fixed it. I got a few players to try some quests and no errors came up

**Comment by ozm8** [comment]
wait there is one small error:

[06:02:51] [Server thread/ERROR]: [Quests] currentStage was null for 79a608f5-4f1c-47d1-a25a-48432b98ba90 on quit

**Comment by FlyingPikachu** [comment]
That error can be ignored. If you'd still like to see it gone, you'll have to figure out which quest is causing it and post the quests.yml entry for testing.
