### ISSUE TITLE
Quest Delay (Request)

### ISSUE THREAD

**Issue by MPPrison** [FlyingPikachu/Quests#85]
Maybe there could be a config option to left click an NPC and it'll tell you when you can do the quest again or maybe even a timer in the GUI would be awesome!

**Comment by madtomic** [comment]
If love this feature too.

**Comment by FlyingPikachu** [comment]
After looking into this, it is possible, but the method to do this requires some looping (to check all quests), which if spammed could lag the server. And I'd rather not have Quests moderate how fast players can click, so I'm gonna have to pass. Thank you for the suggestion!
