### ISSUE TITLE
Bug: Delivering 2 items of the same type to 2 different NPC's in 1 stage will result in having to deliver to only 1 npc after a questadmin reload.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#85]
Spigot 1.12
Quests 2.9.6

The problem is as follows: I have the following delivery items: Iron Pickaxe (1), Iron Pickaxe (1), Iron Sword (1) that need to be delivered to 3 seperate people so 1 iron pickaxe to npc A, 1 iron pickaxe to npc B and the sword to npc C. After i set 3 different delivery ID's and do and questadmin reload it shows the delivery of the 2 pickaxes to be delivered BOTH to the same person so it will BOTH complete after delivering 1 pickaxe to 1 of the dudes. I want to be able to make a delivery to BOTH npc's so delivering the 2 npc's seperately.

Quest :https://pastebin.com/VFGMg84b
Note (I have set the id's to 3 seperate in the quest pastebin, but after reloading it is changed from (19, 18, 17) to (18, 18, 17) which is everything but desirable.

No errors appear.

**Comment by LinearBotSystems** [comment]
You can as a workaround add multiple stages the only down side it had is that people have to do the delivery in order also stages are meant for separating the progress so it always better. I personal would love an  OR for all the multi objections per stage so you can kills mob A or mob B or bring an item to NPC A or  NPC B and so on

**Comment by FlyingPikachu** [comment]
The issue was caused by the two Iron Pickaxe. When the plugin went to fetch the NPC for the second pickaxe, it would mistakenly grab the NPC for the first since the items are identical.

**Comment by OwnAgePau** [comment]
Well this DID not fix the problem, it now properly shows the correct npc names to deliver the pickaxes to. However it is still completed after delivering a pickaxe to either one of em.....

**Comment by FlyingPikachu** [comment]
The order in which the objectives appear in quests.yml is not the order in which they must be completed. The quester can deliver the items in whichever order they choose.

Unless you mean the quest is finishing without all objectives completed?

**Comment by OwnAgePau** [comment]
Nope I am saying that even though I have to deliver 2 pickaxes to seperate npc's it finishes after only delivering a pickaxe to 1 of them. So the 2e pickaxe doesn't need to be delivered.
