### ISSUE TITLE
quest list command not working under some circumstances

### ISSUE THREAD

**Issue by LinearBotSystems** [FlyingPikachu/Quests#86]
Version Quest 2.9.6 

I could swear somebody posted this before but anyway. The problem is that the 4 page with the /quests list command is not accessible under some circumstances reason is a faulty math in Quests.java around line 1873 the 	public void listQuests method.

`
1874	if (quests.size() < ((page * 8) - 7)) {
	player.sendMessage(ChatColor.YELLOW + Lang.get("pageNotExist"));
`
As an example I fill in some real numbers so if(22 < (4*8)- 7),=> if( 22 < 25). ( we are on the 4th page this is wrong)

The whole method seems complete full of screwed math so I overworked it completely and tested it so far I could.

Code : https://pastebin.com/6SaDx7i4

PS I tied the numbers of rows/lines to a var you can tie them to configure if you like

**Comment by FlyingPikachu** [comment]
Thanks for doing this! I rarely have enough quests loaded in my test environment to have witnessed this, so the update is certainly appreciated. I'll make sure to give you credit on the Spigot page update when the time comes.

Also, thanks for at least using Pastebin. <3
