### ISSUE TITLE
Bug: Long quests line with simple reach locations stages (10 stages) suddenly only has 6 stages after saved (no error).

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#88]
Spigot: 1.12
Quests: 2.9.7

I created a rather simple quest that had 11 stages (a city tour) moving you from one place to another, but after saving half of the stages aren't shown in the editor anymore, they are however shown in the quests.yml, but I have had this problem before and then it also got updated in the quests.yml.

Quest: https://pastebin.com/CpBeYKYX

**Comment by FlyingPikachu** [comment]
The issue was caused by every other stage being identical. Both the bug and fix for the bug were similar in nature to your last report #85
