### ISSUE TITLE
Maybe minor

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#9]
Just a little spam in console regarding npcs that were deleted BUT they were never attached to any quests:
24.06 13:12:49 [Server] INFO Quester not found for UUID "7fd97ccc-5abc-2e8d-9512-cd40f46daa8d". Consider adding them to the Quester blacklist.

and
24.06 11:41:16 [Server] INFO Quester not found for UUID "52ce8106-3cd6-24af-a79c-da886b6f34a8". Consider adding them to the Quester blacklist.

These are npcs I had attached to npcdestinations, never made quests for them but ended up having to remove them. There is also the:
24.06 13:22:45 [Server] INFO Enabling Quests v2.8.6-b132
24.06 13:22:45 [Server] WARN Could not save quests.yml to plugins/Quests/quests.yml because quests.yml already exists.
24.06 13:22:45 [Server] WARN Could not save events.yml to plugins/Quests/events.yml because events.yml already exists.
24.06 13:22:45 [Server] WARN Could not save data.yml to plugins/Quests/data.yml because data.yml already exists.

Which is minor but annoying to look at after restarts lol. Files are there since I added them but I guess it keeps trying to add its own?

**Comment by QueenKisaki** [comment]
Just had a player test out some quests and this pops up https://pastebin.com/NxhuH6sX

**Comment by FlyingPikachu** [comment]
@QueenKisaki For the "not found for UUID" stuff, it's certainly possible the UUIDs belong to NPCs, but without an error of some kind, I have no efficient way to track down the issue. I would suggest ignoring them if gameplay is unaffected.

The "Could not save" warnings are annoying, I agree. However, these warnings are a side-effect of a necessary change to get Quests working on Minecraft 1.12. So again, I'm afraid you ought to ignore them.

As for the pastebin, please open a new issue as that is unrelated to your OP. Thanks!
