### ISSUE TITLE
Stage setting sheep sheer wool color produces error

### ISSUE THREAD

**Issue by Leescar** [FlyingPikachu/Quests#9]
When I open up /quests editor
Then edit or create a new quest
go to stages
set goal
sheer sheep
set color type in any color (I tryed each color still same error) and then this error in console
http://pastebin.com/cmeBRW79

**Comment by FlyingPikachu** [comment]
Please link/upload your Quests/lang/en.yml

**Comment by Leescar** [comment]
http://pastebin.com/8ATfwWY0
Unless you wanted the file itself?
It seems to be the standard en.yml
I've tried getting the new_en.yml from the link you posted on spigot but its not working.

**Comment by FlyingPikachu** [comment]
You're good. I was thinking perhaps your file was missing certain strings (like COLOR_RED), but they're all there. I'll look into this further.

**Comment by FlyingPikachu** [comment]
I tested this and got the same result. A workaround for now is to use proper case when typing the color (for example, "Red" instead of "red").
