### ISSUE TITLE
When editing Kill mobs requirement for quests it wont let me exit unless clearing

### ISSUE THREAD

**Issue by EndslayerGaming** [FlyingPikachu/Quests#90]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 2.9.7

(__Required__) Please describe the problem and how to replicate it. Any console errors? Create a quest like normal then set the quest goal to killing any mob set everything up and you should get the error "All of your lists are not the same size!"

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_? No

**Comment by FlyingPikachu** [comment]
I was able to create and save a Kill Mob quest without issue.

Perhaps you did not include a location-radii and location-name (options 4 and 5)? Once you enter location coords (option 3) the radii and name are no longer optional.

Closing as invalid pending additional information.
