### ISSUE TITLE
The message "Quester not found for UUID" is quite spamming

### ISSUE THREAD

**Issue by PikachuEXE** [FlyingPikachu/Quests#92]
I just encounter this today.
If the file is not found for a specific player, it will keep logging this message to console (and log file)
I wonder if the continuous message is necessary

**Comment by FlyingPikachu** [comment]
I'm guessing you mean when trying to use one of the new commands. It indicates that no UUID was resolved for the name provided (lookup failed). As long as you're not spamming the command, it shouldn't be an issue.

**Comment by PikachuEXE** [comment]
I don't think it's triggered by spamming commands :(
The message is located in `Quests#getQuester`
And the method is being used by many event listeners

**Comment by FlyingPikachu** [comment]
The new commands do call getQuester() whenever a name variable is passed, but you're right, it is called elsewhere. I wouldn't know how to proceed unless you know from which event is triggering it.

**Comment by PikachuEXE** [comment]
I will close until I can find it and track down the event again
