### ISSUE TITLE
NULL quests editor issue

### ISSUE THREAD

**Issue by ReforgedGames** [FlyingPikachu/Quests#94]
When i go into quests editor on 1.8.0 version i get a NULL for all options, What is causing this and how may i fix it? 
![2015-04-22_17 33 19](https://cloud.githubusercontent.com/assets/12075543/7286959/d480942c-e915-11e4-8b59-96e7555bf3d8.png)

**Comment by FlyingPikachu** [comment]
Why are you using 1.8.0? Latest version is 2.4.0. You can download it here:
http://www.spigotmc.org/resources/quests.3711/

**Comment by ReforgedGames** [comment]
Oh, i am using 1.8.0 because i am using a plugin my server is based around, the great sword art online plugin, Is there a compatible version for 1.8 Spigot?

**Comment by ReforgedGames** [comment]
I would like to apologize, i never saw it depended on vault.

**Comment by Formula350** [comment]
If your issue was fixed by installing Vault, you should mark this thread as Closed so FlyingPikachu knows :D

**Comment by FlyingPikachu** [comment]
Closing as resolved.
