### ISSUE TITLE
Kill players stage registering deaths as kills.

### ISSUE THREAD

**Issue by Alppuccino** [FlyingPikachu/Quests#96]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.0.0-Naomi-b${env.BUILD_NUMBER}
1.12.1 git-Spigot-edd0396-20ab5d3
(__Required__) Please describe the problem and how to replicate it. Any console errors?
1.Create a quest where you need to kill a player
2. Have 2 people accept that quest.
3. Have one person kill the other with the quest accepted.
4. The quest will complete for both players, even the one that died?
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/sznWsub8

**Comment by FlyingPikachu** [comment]
Which quest from your config is affected?

**Comment by Alppuccino** [comment]
Your First Time, and that is the only one which we have been able to test

**Comment by Novy93** [comment]
In my case when i take quest to kill someone, even suicide count, got quest done.
