### ISSUE TITLE
Password-Phrases Stages not giving Items as Events

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#97]
This occurs as a finish-event, start-event or even as a reward when the Quest is complete. If the previous stage ends when the player types the correct password, the player does not receive the item set in an event or as a reward at the end of a Quest.

Error in console - http://pastebin.com/wFQ8DSNT

**Comment by FlyingPikachu** [comment]
I believe someone fixed this already, but if this is still an issue, please create a new ticket. Thanks!
