### ISSUE TITLE
Language File wont get recognised!

### ISSUE THREAD

**Issue by HrMoritz** [FlyingPikachu/Quests#97]
The plugin runs on the version 3.0.0
I translated the en language file into german in the same file (did not even change the file name). Then i restarted my server, but the plugin is still in english.

**Comment by FlyingPikachu** [comment]
@HrMoritz Could you please provide the language file? I was not able to replicate this.

**Comment by HrMoritz** [comment]
I cant upload it here. Uploaded it on Dropbox
https://www.dropbox.com/s/r3ebnvr962eo5rf/en.yml?dl=0
Thanks for your work

**Comment by HrMoritz** [comment]
Any idea?

**Comment by FlyingPikachu** [comment]
questDisplayHelp
stageEditorReachLocationRadiiPrompt
stageEditorShearAmountsPrompt

All of those have an extra quote (") on the end. Fixing those solves the issue. In the future, use a YAML parser such as the one linked below to find errors in your config

http://yaml-online-parser.appspot.com/
