### ISSUE TITLE
How can I stop [Server:Title successfully executed]

### ISSUE THREAD

**Issue by Wapstar** [FlyingPikachu/Quests#98]
Version: 3.0.0-Naomi

When the players finish a mision or take a mision they get a title on the screen but if you have op on the server you get that in chat and its hard to see what the players say. It doesn't work if you use gamerule commandBlockOutput.

**Comment by Wapstar** [comment]
Still appears

**Comment by FlyingPikachu** [comment]
Then there may be no circumvention at this time. If you like, you can disable the title feature in config.yml

**Comment by Wapstar** [comment]
What should I disable ? I don't see anything for Title, all I got is this : 

language: en
allow-command-questing: true
allow-command-quests-with-npcs: false
show-requirements: true
allow-quitting: true
use-compass: true
ignore-locked-quests: false
debug-mode: false
generate-files-on-join: true
kill-delay: 600
accept-timeout: 20
show-npc-effects: false
npc-effect: note
max-quests: 0
convert-data-on-startup: false

**Comment by FlyingPikachu** [comment]
Odd, there should be a show-titles option. See here - https://github.com/FlyingPikachu/Quests/blob/master/src/main/resources/config.yml

**Comment by Wapstar** [comment]
Hmm, it's ok if I add that there ?

**Comment by FlyingPikachu** [comment]
Should be just fine. If you have any problems just delete the config and let Quests regenerate it :)

**Comment by Wapstar** [comment]
okay

**Comment by Wapstar** [comment]
Thank you
